/**--------------------------------------------------------------------------
@file	blystnano_boards.h

@brief	Contains definitions for BLYST Nano (IMM-NRF52832-NANO) based boards

@author	Hoang Nguyen Hoan
@date	Mar. 24, 2023

@license

MIT License

Copyright (c) 2023 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BLYSTNANO_BOARDS_H__
#define __BLYSTNANO_BOARDS_H__

#define IBK_BLUEIO							1
#define IBK_BLYST_NANO						2
#define BLUEIO_TAG_EVIM						3
#define BLUEIO_ADXL_WCHRG					4
#define BLYST_NANO_DK						5
#define BLUEIO832_MINI						6

// ***** IBK-BLUEIO

// Button
#define IBK_BLUEIO_BUT1_PORT					0
#define IBK_BLUEIO_BUT1_PIN						2
#define IBK_BLUEIO_BUT1_PINOP					0

#define IBK_BLUEIO_BUT1_SENSE					IOPINSENSE_LOW_TRANSITION

#define IBK_BLUEIO_BUT2_PORT					0
#define IBK_BLUEIO_BUT2_PIN						13
#define IBK_BLUEIO_BUT2_PINOP					0

#define IBK_BLUEIO_BUT2_SENSE					IOPINSENSE_LOW_TRANSITION

#define IBK_BLUEIO_BUT_PINS_CFG			{ \
	{IBK_BLUEIO_BUT1_PORT, IBK_BLUEIO_BUT1_PIN, IBK_BLUEIO_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_BUT2_PORT, IBK_BLUEIO_BUT2_PIN, IBK_BLUEIO_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// LED
#define IBK_BLUEIO_LED1_PORT					0
#define IBK_BLUEIO_LED1_PIN						30
#define IBK_BLUEIO_LED1_PINOP					0

#define IBK_BLUEIO_LED2_PORT					0
#define IBK_BLUEIO_LED2_PIN						29
#define IBK_BLUEIO_LED2_PINOP					0

#define IBK_BLUEIO_LED3_PORT					0
#define IBK_BLUEIO_LED3_PIN						28
#define IBK_BLUEIO_LED3_PINOP					0

#define IBK_BLUEIO_LED_PINS_CFG		{ \
	{IBK_BLUEIO_LED1_PORT, IBK_BLUEIO_LED1_PIN, IBK_BLUEIO_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_LED2_PORT, IBK_BLUEIO_LED2_PIN, IBK_BLUEIO_LED2_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_LED3_PORT, IBK_BLUEIO_LED3_PIN, IBK_BLUEIO_LED3_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// UART pins
#define IBK_BLUEIO_UART_RX_PORT					0
#define IBK_BLUEIO_UART_RX_PIN					8
#define IBK_BLUEIO_UART_RX_PINOP				1
#define IBK_BLUEIO_UART_TX_PORT					0
#define IBK_BLUEIO_UART_TX_PIN					7
#define IBK_BLUEIO_UART_TX_PINOP				1
#define IBK_BLUEIO_UART_CTS_PORT				0
#define IBK_BLUEIO_UART_CTS_PIN					12
#define IBK_BLUEIO_UART_CTS_PINOP				1
#define IBK_BLUEIO_UART_RTS_PORT				0
#define IBK_BLUEIO_UART_RTS_PIN					11
#define IBK_BLUEIO_UART_RTS_PINOP				1

#define IBK_BLUEIO_UART_PINS_CFG	{ \
	{IBK_BLUEIO_UART_RX_PORT, IBK_BLUEIO_UART_RX_PIN, IBK_BLUEIO_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_TX_PORT, IBK_BLUEIO_UART_TX_PIN, IBK_BLUEIO_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_CTS_PORT, IBK_BLUEIO_UART_CTS_PIN, IBK_BLUEIO_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_RTS_PORT, IBK_BLUEIO_UART_RTS_PIN, IBK_BLUEIO_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// IBK-BLUEIO *****

// ***** IBK-BLYST-NANO

// Button
#define IBK_BLYST_NANO_BUT1_PORT				0
#define IBK_BLYST_NANO_BUT1_PIN					2
#define IBK_BLYST_NANO_BUT1_PINOP				0

#define IBK_BLYST_NANO_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define IBK_BLYST_NANO_BUT2_PORT				0
#define IBK_BLYST_NANO_BUT2_PIN					13
#define IBK_BLYST_NANO_BUT2_PINOP				0

#define IBK_BLYST_NANO_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define IBK_BLYST_NANO_BUT_PINS_CFG			{ \
	{IBK_BLYST_NANO_BUT1_PORT, IBK_BLYST_NANO_BUT1_PIN, IBK_BLYST_NANO_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_BUT2_PORT, IBK_BLYST_NANO_BUT2_PIN, IBK_BLYST_NANO_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// LED
#define IBK_BLYST_NANO_LED1_PORT				0
#define IBK_BLYST_NANO_LED1_PIN					30
#define IBK_BLYST_NANO_LED1_PINOP				0

#define IBK_BLYST_NANO_LED2_PORT				0
#define IBK_BLYST_NANO_LED2_PIN					29
#define IBK_BLYST_NANO_LED2_PINOP				0

#define IBK_BLYST_NANO_LED3_PORT				0
#define IBK_BLYST_NANO_LED3_PIN					28
#define IBK_BLYST_NANO_LED3_PINOP				0

#define IBK_BLYST_NANO_LED_PINS_CFG		{ \
	{IBK_BLYST_NANO_LED1_PORT, IBK_BLYST_NANO_LED1_PIN, IBK_BLYST_NANO_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_LED2_PORT, IBK_BLYST_NANO_LED2_PIN, IBK_BLYST_NANO_LED2_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_LED3_PORT, IBK_BLYST_NANO_LED3_PIN, IBK_BLYST_NANO_LED3_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// UART pins
#define IBK_BLYST_NANO_UART_RX_PORT				0
#define IBK_BLYST_NANO_UART_RX_PIN				8
#define IBK_BLYST_NANO_UART_RX_PINOP			0
#define IBK_BLYST_NANO_UART_TX_PORT				0
#define IBK_BLYST_NANO_UART_TX_PIN				7
#define IBK_BLYST_NANO_UART_TX_PINOP			0
#define IBK_BLYST_NANO_UART_CTS_PORT			0
#define IBK_BLYST_NANO_UART_CTS_PIN				12
#define IBK_BLYST_NANO_UART_CTS_PINOP			0
#define IBK_BLYST_NANO_UART_RTS_PORT			0
#define IBK_BLYST_NANO_UART_RTS_PIN				11
#define IBK_BLYST_NANO_UART_RTS_PINOP			0

#define IBK_BLYST_NANO_UART_PINS_CFG	{ \
	{IBK_BLYST_NANO_UART_RX_PORT, IBK_BLYST_NANO_UART_RX_PIN, IBK_BLYST_NANO_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_TX_PORT, IBK_BLYST_NANO_UART_TX_PIN, IBK_BLYST_NANO_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_CTS_PORT, IBK_BLYST_NANO_UART_CTS_PIN, IBK_BLYST_NANO_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_RTS_PORT, IBK_BLYST_NANO_UART_RTS_PIN, IBK_BLYST_NANO_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// IBK-BLYST-NANO *****

// ***** BLUEIO-TAG-EVIM

#define BLUEIO_TAG_EVIM_BUT1_PORT				0
#define BLUEIO_TAG_EVIM_BUT1_PIN				2
#define BLUEIO_TAG_EVIM_BUT1_PINOP				0

#define BLUEIO_TAG_EVIM_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_TAG_EVIM_BUT2_PORT				0
#define BLUEIO_TAG_EVIM_BUT2_PIN				13
#define BLUEIO_TAG_EVIM_BUT2_PINOP				0

#define BLUEIO_TAG_EVIM_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_TAG_EVIM_BUT_PINS_CFG			{ \
	{BLUEIO_TAG_EVIM_BUT1_PORT, BLUEIO_TAG_EVIM_BUT1_PIN, BLUEIO_TAG_EVIM_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLUEIO_TAG_EVIM_BUT2_PORT, BLUEIO_TAG_EVIM_BUT2_PIN, BLUEIO_TAG_EVIM_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_TAG_EVIM_LED1_PORT				0
#define BLUEIO_TAG_EVIM_LED1_PIN				30
#define BLUEIO_TAG_EVIM_LED1_PINOP				0

#define BLUEIO_TAG_EVIM_LED2R_PORT				0
#define BLUEIO_TAG_EVIM_LED2R_PIN				18
#define BLUEIO_TAG_EVIM_LED2R_PINOP				0

#define BLUEIO_TAG_EVIM_LED2G_PORT				0
#define BLUEIO_TAG_EVIM_LED2G_PIN				20
#define BLUEIO_TAG_EVIM_LED2G_PINOP				0

#define BLUEIO_TAG_EVIM_LED2B_PORT				0
#define BLUEIO_TAG_EVIM_LED2B_PIN				19
#define BLUEIO_TAG_EVIM_LED2B_PINOP				0

#define BLUEIO_TAG_EVIM_LED_PINS_CFG			{ \
	{BLUEIO_TAG_EVIM_LED1_PORT, BLUEIO_TAG_EVIM_LED1_PIN, BLUEIO_TAG_EVIM_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_TAG_EVIM_LED2R_PORT, BLUEIO_TAG_EVIM_LED2R_PIN, BLUEIO_TAG_EVIM_LED2R_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_TAG_EVIM_LED2G_PORT, BLUEIO_TAG_EVIM_LED2G_PIN, BLUEIO_TAG_EVIM_LED2G_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_TAG_EVIM_LED2B_PORT, BLUEIO_TAG_EVIM_LED2B_PIN, BLUEIO_TAG_EVIM_LED2B_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_TAG_EVIM_I2C0_SCL_PORT			0
#define BLUEIO_TAG_EVIM_I2C0_SCL_PIN			29
#define BLUEIO_TAG_EVIM_I2C0_SCL_PINOP			1
#define BLUEIO_TAG_EVIM_I2C0_SDA_PORT			0
#define BLUEIO_TAG_EVIM_I2C0_SDA_PIN			28
#define BLUEIO_TAG_EVIM_I2C0_SDA_PINOP			1

#define BLUEIO_TAG_EVIM_SPI2_SCK_PORT			0
#define BLUEIO_TAG_EVIM_SPI2_SCK_PIN			17
#define BLUEIO_TAG_EVIM_SPI2_SCK_PINOP			1
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PORT			0
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PIN			16
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PINOP			1
#define BLUEIO_TAG_EVIM_SPI2_MISO_PORT			0
#define BLUEIO_TAG_EVIM_SPI2_MISO_PIN			15
#define BLUEIO_TAG_EVIM_SPI2_MISO_PINOP			1

#define BLUEIO_TAG_EVIM_IMU_CS_PORT				0
#define BLUEIO_TAG_EVIM_IMU_CS_PIN				5
#define BLUEIO_TAG_EVIM_IMU_CS_PINOP			0

#define BLUEIO_TAG_EVIM_IMU_INT_PORT			0
#define BLUEIO_TAG_EVIM_IMU_INT_PIN				6
#define BLUEIO_TAG_EVIM_IMU_INT_PINOP			0

#define BLUEIO_TAG_EVIM_EEP_WP_PORT				0
#define BLUEIO_TAG_EVIM_EEP_WP_PIN				27
#define BLUEIO_TAG_EVIM_EEP_WP_PINOP			0

#define BLUEIO_TAG_EVIM_BUZZ_PORT				0
#define BLUEIO_TAG_EVIM_BUZZ_PIN				14
#define BLUEIO_TAG_EVIM_BUZZ_PINOP				0

#define BLUEIO_TAG_EVIM_FLASH_CS_PORT			0
#define BLUEIO_TAG_EVIM_FLASH_CS_PIN			26
#define BLUEIO_TAG_EVIM_FLASH_CS_PINOP			0

// BLUEIO-TAG-EVIM *****

// ***** BLUEIO-ADXL-WCHRG

#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PIN		17
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PINOP		1
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PIN		16
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PINOP	1
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PIN		15
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PINOP	1

#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PIN		5
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PPINOP		0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PORT		0
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PIN		11
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PINOP		1
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PORT		0
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PIN		12
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PINOP		1

#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PIN		20
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0

#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PORT		0
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PIN			23
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PINOP		1
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PORT		0
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PIN		24
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PINOP		1
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PORT		0
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PIN		25
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PINOP		1

#define BLUEIO_ADXL_WCHRG_FLASH_CS_PORT			0
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PIN			26
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PINOP		0

// BLUEIO-ADXL-WCHRG *****

// ***** BLYST-NANO-DK

// LED
#define BLYST_NANO_DK_LED1_PORT					0
#define BLYST_NANO_DK_LED1_PIN					30
#define BLYST_NANO_DK_LED1_PINOP				0

#define BLYST_NANO_DK_LEDR_PORT					0
#define BLYST_NANO_DK_LEDR_PIN					28
#define BLYST_NANO_DK_LEDR_PINOP				0
#define BLYST_NANO_DK_LEDG_PORT					0
#define BLYST_NANO_DK_LEDG_PIN					29
#define BLYST_NANO_DK_LEDG_PINOP				0
#define BLYST_NANO_DK_LEDB_PORT					0
#define BLYST_NANO_DK_LEDB_PIN					27
#define BLYST_NANO_DK_LEDB_PINOP				0

#define BLYST_NANO_DK_LED_PINS_CFG			{ \
	{BLYST_NANO_DK_LED1_PORT, BLYST_NANO_DK_LED1_PIN, BLYST_NANO_DK_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDR_PORT, BLYST_NANO_DK_LEDR_PIN, BLYST_NANO_DK_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDG_PORT, BLYST_NANO_DK_LEDG_PIN, BLYST_NANO_DK_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDB_PORT, BLYST_NANO_DK_LEDB_PIN, BLYST_NANO_DK_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// Button
#define BLYST_NANO_DK_BUT1_PORT					0
#define BLYST_NANO_DK_BUT1_PIN					2
#define BLYST_NANO_DK_BUT1_PINOP				0

#define BLYST_NANO_DK_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLYST_NANO_DK_BUT2_PORT					0
#define BLYST_NANO_DK_BUT2_PIN					13
#define BLYST_NANO_DK_BUT2_PINOP				0

#define BLYST_NANO_DK_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLYST_NANO_DK_BUT_PINS_CFG			{ \
	{BLYST_NANO_DK_BUT1_PORT, BLYST_NANO_DK_BUT1_PIN, BLYST_NANO_DK_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_BUT2_PORT, BLYST_NANO_DK_BUT2_PIN, BLYST_NANO_DK_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// UART pins
#define BLYST_NANO_DK_UART_RX_PORT				0
#define BLYST_NANO_DK_UART_RX_PIN				8
#define BLYST_NANO_DK_UART_RX_PINOP				1
#define BLYST_NANO_DK_UART_TX_PORT				0
#define BLYST_NANO_DK_UART_TX_PIN				7
#define BLYST_NANO_DK_UART_TX_PINOP				1
#define BLYST_NANO_DK_UART_CTS_PORT				0
#define BLYST_NANO_DK_UART_CTS_PIN				12
#define BLYST_NANO_DK_UART_CTS_PINOP			1
#define BLYST_NANO_DK_UART_RTS_PORT				0
#define BLYST_NANO_DK_UART_RTS_PIN				11
#define BLYST_NANO_DK_UART_RTS_PINOP			1

#define BLYST_NANO_DK_UART_PINS_CFG	{ \
	{BLYST_NANO_DK_UART_RX_PORT, BLYST_NANO_DK_UART_RX_PIN, BLYST_NANO_DK_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_TX_PORT, BLYST_NANO_DK_UART_TX_PIN, BLYST_NANO_DK_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_CTS_PORT, BLYST_NANO_DK_UART_CTS_PIN, BLYST_NANO_DK_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_RTS_PORT, BLYST_NANO_DK_UART_RTS_PIN, BLYST_NANO_DK_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// BLYST-NANO-DK *****

// ***** BLUEIO832-MINI

// BLUEIO832-MINI LED pins
#define BLUEIO832_MINI_LED_PORT					0
#define BLUEIO832_MINI_LED_PIN					17
#define BLUEIO832_MINI_LED_PINOP				0

#define BLUEIO832_MINI_LEDR_PORT				0
#define BLUEIO832_MINI_LEDR_PIN					18
#define BLUEIO832_MINI_LEDR_PINOP				0

#define BLUEIO832_MINI_LEDG_PORT				0
#define BLUEIO832_MINI_LEDG_PIN					16
#define BLUEIO832_MINI_LEDG_PINOP				0

#define BLUEIO832_MINI_LEDB_PORT				0
#define BLUEIO832_MINI_LEDB_PIN					17
#define BLUEIO832_MINI_LEDB_PINOP				0

#define BLUEIO832_MINI_LED_PINS_CFG		{ \
	{BLUEIO832_MINI_LEDR_PORT, BLUEIO832_MINI_LEDR_PIN, BLUEIO832_MINI_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDG_PORT, BLUEIO832_MINI_LEDG_PIN, BLUEIO832_MINI_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDB_PORT, BLUEIO832_MINI_LEDB_PIN, BLUEIO832_MINI_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// Analog input
#define BLUEIO832_MINI_A0						0	// AIN0
#define BLUEIO832_MINI_A1						1	// AIN1
#define BLUEIO832_MINI_A2						2	// AIN2
#define BLUEIO832_MINI_VIN_AIN3					3	// AIN3

// Digital I/O
#define BLUEIO832_MINI_D0_PORT					0
#define BLUEIO832_MINI_D0_PIN					12
#define BLUEIO832_MINI_D0_PINOP					0
#define BLUEIO832_MINI_D1_PORT					0
#define BLUEIO832_MINI_D1_PIN					11
#define BLUEIO832_MINI_D1_PINOP					0
#define BLUEIO832_MINI_D2_PORT					0
#define BLUEIO832_MINI_D2_PIN					8
#define BLUEIO832_MINI_D2_PINOP					0
#define BLUEIO832_MINI_D3_PORT					0
#define BLUEIO832_MINI_D3_PIN					7
#define BLUEIO832_MINI_D3_PINOP					0
#define BLUEIO832_MINI_D4_PORT					0
#define BLUEIO832_MINI_D4_PIN					6
#define BLUEIO832_MINI_D4_PINOP					0
#define BLUEIO832_MINI_D5_PORT					0
#define BLUEIO832_MINI_D5_PIN					13
#define BLUEIO832_MINI_D5_PINOP					0

// BLUEIO832-MINI *****

#endif // __BLYSTNANO_BOARDS_H__
