/**--------------------------------------------------------------------------
@file	blystnano_boards.h

@brief	Contains definitions for BLYST Nano (IMM-NRF52832-NANO) based boards

@author	Hoang Nguyen Hoan
@date	Mar. 24, 2023

@license

MIT License

Copyright (c) 2023 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BLYSTNANO_BOARDS_H__
#define __BLYSTNANO_BOARDS_H__

#include "coredev/iopincfg.h"
#include "miscdev/led.h"

#define IBK_BLUEIO							1
#define IBK_BLYST_NANO						2
#define BLUEIO_TAG_EVIM						3
#define BLUEIO_ADXL_WCHRG					4
#define BLYST_NANO_DK						5
#define BLUEIO832_MINI						6
#define BLUEPYRO_M3225						7
#define BLUEPYRO_CR24S_M3225				8
#define BLYST_MOTION						9
#define BLUEIO_THINGY						10

#include "board_blueio_tag_evim.h"
#include "board_blueio_adxl_wchrg.h"
#include "board_blueio_thingy.h"
#include "board_blyst_motion.h"
#include "board_bluepyro_m3225.h"

#define BLYSTNANO_PULSE_TRAIN_PINS	{ \
	{0, 2, 0}, {0, 3, 0}, {0, 4, 0}, {0, 5, 0}, {0, 6, 0}, {0, 7, 0}, {0, 8, 0}, \
	{0, 9, 0}, {0, 10, 0}, {0, 11, 0}, {0, 12, 0}, {0, 13, 0}, {0, 14, 0}, {0, 15, 0}, \
	{0, 16, 0}, {0, 17, 0}, {0, 18, 0}, {0, 19, 0}, {0, 20, 0}, {0, 21, 0}, {0, 22, 0}, \
	{0, 23, 0}, {0, 24, 0}, {0, 25, 0}, {0, 26, 0}, {0, 27, 0}, {0, 28, 0}, {0, 29, 0}, \
	{0, 30, 0}, {0, 31, 0} \
}

// ***** IBK-BLUEIO

// Button
#define IBK_BLUEIO_BUT1_PORT					0
#define IBK_BLUEIO_BUT1_PIN						2
#define IBK_BLUEIO_BUT1_PINOP					0

#define IBK_BLUEIO_BUT1_SENSE					IOPINSENSE_LOW_TRANSITION

#define IBK_BLUEIO_BUT2_PORT					0
#define IBK_BLUEIO_BUT2_PIN						13
#define IBK_BLUEIO_BUT2_PINOP					0

#define IBK_BLUEIO_BUT2_SENSE					IOPINSENSE_LOW_TRANSITION

#define IBK_BLUEIO_BUT_PINS_CFG			{ \
	{IBK_BLUEIO_BUT1_PORT, IBK_BLUEIO_BUT1_PIN, IBK_BLUEIO_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_BUT2_PORT, IBK_BLUEIO_BUT2_PIN, IBK_BLUEIO_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// LED
#define IBK_BLUEIO_LED1_PORT					0
#define IBK_BLUEIO_LED1_PIN						30
#define IBK_BLUEIO_LED1_PINOP					0
#define IBK_BLUEIO_LED1_LOGIC					LED_LOGIC_LOW

#define IBK_BLUEIO_LED2_PORT					0
#define IBK_BLUEIO_LED2_PIN						29
#define IBK_BLUEIO_LED2_PINOP					0
#define IBK_BLUEIO_LED2_LOGIC					LED_LOGIC_LOW

#define IBK_BLUEIO_LED3_PORT					0
#define IBK_BLUEIO_LED3_PIN						28
#define IBK_BLUEIO_LED3_PINOP					0
#define IBK_BLUEIO_LED3_LOGIC					LED_LOGIC_LOW

#define IBK_BLUEIO_LED_PINS_CFG		{ \
	{IBK_BLUEIO_LED1_PORT, IBK_BLUEIO_LED1_PIN, IBK_BLUEIO_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_LED2_PORT, IBK_BLUEIO_LED2_PIN, IBK_BLUEIO_LED2_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLUEIO_LED3_PORT, IBK_BLUEIO_LED3_PIN, IBK_BLUEIO_LED3_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// UART pins
#define IBK_BLUEIO_UART_RX_PORT					0
#define IBK_BLUEIO_UART_RX_PIN					8
#define IBK_BLUEIO_UART_RX_PINOP				1
#define IBK_BLUEIO_UART_TX_PORT					0
#define IBK_BLUEIO_UART_TX_PIN					7
#define IBK_BLUEIO_UART_TX_PINOP				1
#define IBK_BLUEIO_UART_CTS_PORT				0
#define IBK_BLUEIO_UART_CTS_PIN					12
#define IBK_BLUEIO_UART_CTS_PINOP				1
#define IBK_BLUEIO_UART_RTS_PORT				0
#define IBK_BLUEIO_UART_RTS_PIN					11
#define IBK_BLUEIO_UART_RTS_PINOP				1

#define IBK_BLUEIO_UART_PINS_CFG	{ \
	{IBK_BLUEIO_UART_RX_PORT, IBK_BLUEIO_UART_RX_PIN, IBK_BLUEIO_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_TX_PORT, IBK_BLUEIO_UART_TX_PIN, IBK_BLUEIO_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_CTS_PORT, IBK_BLUEIO_UART_CTS_PIN, IBK_BLUEIO_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLUEIO_UART_RTS_PORT, IBK_BLUEIO_UART_RTS_PIN, IBK_BLUEIO_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// IBK-BLUEIO *****

// ***** IBK-BLYST-NANO

// Button
#define IBK_BLYST_NANO_BUT1_PORT				0
#define IBK_BLYST_NANO_BUT1_PIN					2
#define IBK_BLYST_NANO_BUT1_PINOP				0

#define IBK_BLYST_NANO_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define IBK_BLYST_NANO_BUT2_PORT				0
#define IBK_BLYST_NANO_BUT2_PIN					13
#define IBK_BLYST_NANO_BUT2_PINOP				0

#define IBK_BLYST_NANO_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define IBK_BLYST_NANO_BUT_PINS_CFG			{ \
	{IBK_BLYST_NANO_BUT1_PORT, IBK_BLYST_NANO_BUT1_PIN, IBK_BLYST_NANO_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_BUT2_PORT, IBK_BLYST_NANO_BUT2_PIN, IBK_BLYST_NANO_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// LED
#define IBK_BLYST_NANO_LED1_PORT				0
#define IBK_BLYST_NANO_LED1_PIN					30
#define IBK_BLYST_NANO_LED1_PINOP				0
#define IBK_BLYST_NANO_LED1_LOGIC				LED_LOGIC_LOW


#define IBK_BLYST_NANO_LED2_PORT				0
#define IBK_BLYST_NANO_LED2_PIN					29
#define IBK_BLYST_NANO_LED2_PINOP				0
#define IBK_BLYST_NANO_LED2_LOGIC				LED_LOGIC_LOW

#define IBK_BLYST_NANO_LED3_PORT				0
#define IBK_BLYST_NANO_LED3_PIN					28
#define IBK_BLYST_NANO_LED3_PINOP				0
#define IBK_BLYST_NANO_LED3_LOGIC				LED_LOGIC_LOW

#define IBK_BLYST_NANO_LED_PINS_CFG		{ \
	{IBK_BLYST_NANO_LED1_PORT, IBK_BLYST_NANO_LED1_PIN, IBK_BLYST_NANO_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_LED2_PORT, IBK_BLYST_NANO_LED2_PIN, IBK_BLYST_NANO_LED2_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{IBK_BLYST_NANO_LED3_PORT, IBK_BLYST_NANO_LED3_PIN, IBK_BLYST_NANO_LED3_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// UART pins
#define IBK_BLYST_NANO_UART_RX_PORT				0
#define IBK_BLYST_NANO_UART_RX_PIN				8
#define IBK_BLYST_NANO_UART_RX_PINOP			0
#define IBK_BLYST_NANO_UART_TX_PORT				0
#define IBK_BLYST_NANO_UART_TX_PIN				7
#define IBK_BLYST_NANO_UART_TX_PINOP			0
#define IBK_BLYST_NANO_UART_CTS_PORT			0
#define IBK_BLYST_NANO_UART_CTS_PIN				12
#define IBK_BLYST_NANO_UART_CTS_PINOP			0
#define IBK_BLYST_NANO_UART_RTS_PORT			0
#define IBK_BLYST_NANO_UART_RTS_PIN				11
#define IBK_BLYST_NANO_UART_RTS_PINOP			0

#define IBK_BLYST_NANO_UART_PINS_CFG	{ \
	{IBK_BLYST_NANO_UART_RX_PORT, IBK_BLYST_NANO_UART_RX_PIN, IBK_BLYST_NANO_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_TX_PORT, IBK_BLYST_NANO_UART_TX_PIN, IBK_BLYST_NANO_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_CTS_PORT, IBK_BLYST_NANO_UART_CTS_PIN, IBK_BLYST_NANO_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{IBK_BLYST_NANO_UART_RTS_PORT, IBK_BLYST_NANO_UART_RTS_PIN, IBK_BLYST_NANO_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// IBK-BLYST-NANO *****


// ***** BLYST-NANO-DK

// LED
#define BLYST_NANO_DK_LED1_PORT					0
#define BLYST_NANO_DK_LED1_PIN					30
#define BLYST_NANO_DK_LED1_PINOP				0
#define BLYST_NANO_DK_LED1_LOGIC				LED_LOGIC_LOW

#define BLYST_NANO_DK_LEDR_PORT					0
#define BLYST_NANO_DK_LEDR_PIN					28
#define BLYST_NANO_DK_LEDR_PINOP				0
#define BLYST_NANO_DK_LEDR_LOGIC				LED_LOGIC_LOW
#define BLYST_NANO_DK_LEDG_PORT					0
#define BLYST_NANO_DK_LEDG_PIN					29
#define BLYST_NANO_DK_LEDG_PINOP				0
#define BLYST_NANO_DK_LEDG_LOGIC				LED_LOGIC_LOW
#define BLYST_NANO_DK_LEDB_PORT					0
#define BLYST_NANO_DK_LEDB_PIN					27
#define BLYST_NANO_DK_LEDB_PINOP				0
#define BLYST_NANO_DK_LEDB_LOGIC				LED_LOGIC_LOW

#define BLYST_NANO_DK_LED_PINS_CFG			{ \
	{BLYST_NANO_DK_LED1_PORT, BLYST_NANO_DK_LED1_PIN, BLYST_NANO_DK_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDR_PORT, BLYST_NANO_DK_LEDR_PIN, BLYST_NANO_DK_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDG_PORT, BLYST_NANO_DK_LEDG_PIN, BLYST_NANO_DK_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_LEDB_PORT, BLYST_NANO_DK_LEDB_PIN, BLYST_NANO_DK_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// Button
#define BLYST_NANO_DK_BUT1_PORT					0
#define BLYST_NANO_DK_BUT1_PIN					2
#define BLYST_NANO_DK_BUT1_PINOP				0

#define BLYST_NANO_DK_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLYST_NANO_DK_BUT2_PORT					0
#define BLYST_NANO_DK_BUT2_PIN					13
#define BLYST_NANO_DK_BUT2_PINOP				0

#define BLYST_NANO_DK_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLYST_NANO_DK_BUT_PINS_CFG			{ \
	{BLYST_NANO_DK_BUT1_PORT, BLYST_NANO_DK_BUT1_PIN, BLYST_NANO_DK_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLYST_NANO_DK_BUT2_PORT, BLYST_NANO_DK_BUT2_PIN, BLYST_NANO_DK_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// UART pins
#define BLYST_NANO_DK_UART_RX_PORT				0
#define BLYST_NANO_DK_UART_RX_PIN				8
#define BLYST_NANO_DK_UART_RX_PINOP				1
#define BLYST_NANO_DK_UART_TX_PORT				0
#define BLYST_NANO_DK_UART_TX_PIN				7
#define BLYST_NANO_DK_UART_TX_PINOP				1
#define BLYST_NANO_DK_UART_CTS_PORT				0
#define BLYST_NANO_DK_UART_CTS_PIN				12
#define BLYST_NANO_DK_UART_CTS_PINOP			1
#define BLYST_NANO_DK_UART_RTS_PORT				0
#define BLYST_NANO_DK_UART_RTS_PIN				11
#define BLYST_NANO_DK_UART_RTS_PINOP			1

#define BLYST_NANO_DK_UART_PINS_CFG	{ \
	{BLYST_NANO_DK_UART_RX_PORT, BLYST_NANO_DK_UART_RX_PIN, BLYST_NANO_DK_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_TX_PORT, BLYST_NANO_DK_UART_TX_PIN, BLYST_NANO_DK_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_CTS_PORT, BLYST_NANO_DK_UART_CTS_PIN, BLYST_NANO_DK_UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_NANO_DK_UART_RTS_PORT, BLYST_NANO_DK_UART_RTS_PIN, BLYST_NANO_DK_UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// BLYST-NANO-DK *****

// ***** BLUEIO832-MINI

// BLUEIO832-MINI LED pins
#define BLUEIO832_MINI_LEDR_PORT				0
#define BLUEIO832_MINI_LEDR_PIN					18
#define BLUEIO832_MINI_LEDR_PINOP				0
#define BLUEIO832_MINI_LEDR_LOGIC				LED_LOGIC_HIGH

#define BLUEIO832_MINI_LEDG_PORT				0
#define BLUEIO832_MINI_LEDG_PIN					16
#define BLUEIO832_MINI_LEDG_PINOP				0
#define BLUEIO832_MINI_LEDG_LOGIC				LED_LOGIC_HIGH

#define BLUEIO832_MINI_LEDB_PORT				0
#define BLUEIO832_MINI_LEDB_PIN					17
#define BLUEIO832_MINI_LEDB_PINOP				0
#define BLUEIO832_MINI_LEDB_LOGIC				LED_LOGIC_HIGH

#define BLUEIO832_MINI_LED_PINS_CFG		{ \
	{BLUEIO832_MINI_LEDR_PORT, BLUEIO832_MINI_LEDR_PIN, BLUEIO832_MINI_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDG_PORT, BLUEIO832_MINI_LEDG_PIN, BLUEIO832_MINI_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDB_PORT, BLUEIO832_MINI_LEDB_PIN, BLUEIO832_MINI_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// Analog input
#define BLUEIO832_MINI_A0						0	// AIN0
#define BLUEIO832_MINI_A1						1	// AIN1
#define BLUEIO832_MINI_A2						2	// AIN2
#define BLUEIO832_MINI_VIN_AIN3					3	// AIN3

// Digital I/O
#define BLUEIO832_MINI_D0_PORT					0
#define BLUEIO832_MINI_D0_PIN					12
#define BLUEIO832_MINI_D0_PINOP					0
#define BLUEIO832_MINI_D1_PORT					0
#define BLUEIO832_MINI_D1_PIN					11
#define BLUEIO832_MINI_D1_PINOP					0
#define BLUEIO832_MINI_D2_PORT					0
#define BLUEIO832_MINI_D2_PIN					8
#define BLUEIO832_MINI_D2_PINOP					0
#define BLUEIO832_MINI_D3_PORT					0
#define BLUEIO832_MINI_D3_PIN					7
#define BLUEIO832_MINI_D3_PINOP					0
#define BLUEIO832_MINI_D4_PORT					0
#define BLUEIO832_MINI_D4_PIN					6
#define BLUEIO832_MINI_D4_PINOP					0
#define BLUEIO832_MINI_D5_PORT					0
#define BLUEIO832_MINI_D5_PIN					13
#define BLUEIO832_MINI_D5_PINOP					0

// BLUEIO832-MINI *****


#endif // __BLYSTNANO_BOARDS_H__
