/**--------------------------------------------------------------------------
@file	board_blyst_motion.h

@brief	I/O definitions for the BLYST-MOTION board

This board uses the BLYST Nano (IMM-NRF52832-NANO) module

@author	Hoang Nguyen Hoan
@date	Mar. 24, 2023

@license

MIT License

Copyright (c) 2023 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_BLYST_MOTION_H__
#define __BOARD_BLYST_MOTION_H__


// ***** BLYST-MOTION

#define BLYST_MOTION_LED_RED_PORT				0
#define BLYST_MOTION_LED_RED_PIN				25
#define BLYST_MOTION_LED_RED_PINOP				0
#define BLYST_MOTION_LED_RED_LOGIC				LED_LOGIC_LOW

#define BLYST_MOTION_LED_GREEN_PORT				0
#define BLYST_MOTION_LED_GREEN_PIN				22
#define BLYST_MOTION_LED_GREEN_PINOP			0
#define BLYST_MOTION_LED_GREEN_LOGIC			LED_LOGIC_LOW

#define BLYST_MOTION_LED_BLUE_PORT				0
#define BLYST_MOTION_LED_BLUE_PIN				20
#define BLYST_MOTION_LED_BLUE_PINOP				0
#define BLYST_MOTION_LED_BLUE_LOGIC				LED_LOGIC_LOW

#define BLYST_MOTION_LED_PINS_CFG		{ \
	{BLYST_MOTION_LED_RED_PORT, BLYST_MOTION_LED_RED_PIN, BLYST_MOTION_LED_RED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_MOTION_LED_GREEN_PORT, BLYST_MOTION_LED_GREEN_PIN, BLYST_MOTION_LED_GREEN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_MOTION_LED_BLUE_PORT, BLYST_MOTION_LED_BLUE_PIN, BLYST_MOTION_LED_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}\
}

#define BLYST_MOTION_I2C_SDA_PORT				0
#define BLYST_MOTION_I2C_SDA_PIN				18
#define BLYST_MOTION_I2C_SDA_PINOP				1
#define BLYST_MOTION_I2C_SCL_PORT				0
#define BLYST_MOTION_I2C_SCL_PIN				17
#define BLYST_MOTION_I2C_SCL_PINOP				1

#define BLYST_MOTION_I2C_PINS_CFG	{ \
	{BLYST_MOTION_I2C_SDA_PORT, BLYST_MOTION_I2C_SDA_PIN, BLYST_MOTION_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_MOTION_I2C_SCL_PORT, BLYST_MOTION_I2C_SCL_PIN, BLYST_MOTION_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }


#define BLYST_MOTION_SPI_SCK_PORT				0
#define BLYST_MOTION_SPI_SCK_PIN				11
#define BLYST_MOTION_SPI_SCK_PINOP				1
#define BLYST_MOTION_SPI_MISO_PORT				0
#define BLYST_MOTION_SPI_MISO_PIN				13
#define BLYST_MOTION_SPI_MISO_PINOP				1
#define BLYST_MOTION_SPI_MOSI_PORT				0
#define BLYST_MOTION_SPI_MOSI_PIN				12
#define BLYST_MOTION_SPI_MOSI_PINOP				1

#define BLYST_MOTION_IMU_CS_PORT				0
#define BLYST_MOTION_IMU_CS_PIN					6
#define BLYST_MOTION_IMU_CS_PINOP				0

#define BLYST_MOTION_IMU_INT_PORT				0
#define BLYST_MOTION_IMU_INT_PIN				16
#define BLYST_MOTION_IMU_INT_PINOP				0

#define BLYST_MOTION_H3LIS331_CS_PORT			0
#define BLYST_MOTION_H3LIS331_CS_PIN			15
#define BLYST_MOTION_H3LIS331_CS_PINOP			0

#define BLYST_MOTION_FLASH_CS_PORT				0
#define BLYST_MOTION_FLASH_CS_PIN				5
#define BLYST_MOTION_FLASH_CS_PINOP				0

#define BLYST_MOTION_SPI_PINS_CFG	{\
	{BLYST_MOTION_SPI_SCK_PORT, BLYST_MOTION_SPI_SCK_PIN, BLYST_MOTION_SPI_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLYST_MOTION_SPI_MISO_PORT, BLYST_MOTION_SPI_MISO_PIN, BLYST_MOTION_SPI_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLYST_MOTION_SPI_MOSI_PORT, BLYST_MOTION_SPI_MOSI_PIN, BLYST_MOTION_SPI_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLYST_MOTION_IMU_CS_PORT, BLYST_MOTION_IMU_CS_PIN, BLYST_MOTION_IMU_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
    {BLYST_MOTION_H3LIS331_CS_PORT, BLYST_MOTION_H3LIS331_CS_PIN, BLYST_MOTION_H3LIS331_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLYST_MOTION_FLASH_CS_PORT, BLYST_MOTION_FLASH_CS_PIN, BLYST_MOTION_FLASH_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL},}	// CS


#define BLYST_MOTION_FLASH_HOLD_PORT			0
#define BLYST_MOTION_FLASH_HOLD_PIN				4
#define BLYST_MOTION_FLASH_HOLD_PINOP			0

#define BLYST_MOTION_FLASH_WP_PORT				0
#define BLYST_MOTION_FLASH_WP_PIN				29
#define BLYST_MOTION_FLASH_WP_PINOP				0

#define BLYST_MOTION_BMM350_INT_PORT			0
#define BLYST_MOTION_BMM350_INT_PIN				19
#define BLYST_MOTION_BMM350_INT_PINOP			0

#define BLYST_MOTION_UART_RX_PORT				0
#define BLYST_MOTION_UART_RX_PIN				8
#define BLYST_MOTION_UART_RX_PINOP				1
#define BLYST_MOTION_UART_TX_PORT				0
#define BLYST_MOTION_UART_TX_PIN				7
#define BLYST_MOTION_UART_TX_PINOP				1

#define BLYST_MOTION_UART_PINS_CFG	{ \
	{BLYST_MOTION_UART_RX_PORT, BLYST_MOTION_UART_RX_PIN, BLYST_MOTION_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLYST_MOTION_UART_TX_PORT, BLYST_MOTION_UART_TX_PIN, BLYST_MOTION_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}


// BLYST-MOTION *****


#endif // __BOARD_BLYST_MOTION_H__
