/**--------------------------------------------------------------------------
@file	board_tachyontrack.h

@brief	I/O definitions for the TachyonTrack board

This board uses the BLYST Nano (IMM-NRF52832-NANO) module

@author	Hoang Nguyen Hoan
@date	Sep. 9, 2025

@license

MIT License

Copyright (c) 2024 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_TACHYONTRACK_H__
#define __BOARD_TACHYONTRACK_H__


// ***** TachyonTrack

#define TACHYONTRACK_BUT1_PORT					0
#define TACHYONTRACK_BUT1_PIN					11
#define TACHYONTRACK_BUT1_PINOP					0
#define TACHYONTRACK_BUT1_SENSE					IOPINSENSE_LOW_TRANSITION

#define TACHYONTRACK_BUT2_PORT					0
#define TACHYONTRACK_BUT2_PIN					22
#define TACHYONTRACK_BUT2_PINOP					0
#define TACHYONTRACK_BUT2_SENSE					IOPINSENSE_LOW_TRANSITION

#define TACHYONTRACK_BUT_PINS_CFG		{ \
	{TACHYONTRACK_BUT1_PORT, TACHYONTRACK_BUT1_PIN, TACHYONTRACK_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_BUT2_PORT, TACHYONTRACK_BUT2_PIN, TACHYONTRACK_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define TACHYONTRACK_LED_RED_PORT				0
#define TACHYONTRACK_LED_RED_PIN				8
#define TACHYONTRACK_LED_RED_PINOP				0
#define TACHYONTRACK_LED_RED_LOGIC				LED_LOGIC_LOW

#define TACHYONTRACK_LED_GREEN_PORT				0
#define TACHYONTRACK_LED_GREEN_PIN				6
#define TACHYONTRACK_LED_GREEN_PINOP			0
#define TACHYONTRACK_LED_GREEN_LOGIC			LED_LOGIC_LOW

#define TACHYONTRACK_LED_BLUE_PORT				0
#define TACHYONTRACK_LED_BLUE_PIN				7
#define TACHYONTRACK_LED_BLUE_PINOP				0
#define TACHYONTRACK_LED_BLUE_LOGIC				LED_LOGIC_LOW

#define TACHYONTRACK_LED_PINS_CFG		{ \
	{TACHYONTRACK_LED_RED_PORT, TACHYONTRACK_LED_RED_PIN, TACHYONTRACK_LED_RED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_LED_GREEN_PORT, TACHYONTRACK_LED_GREEN_PIN, TACHYONTRACK_LED_GREEN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_LED_BLUE_PORT, TACHYONTRACK_LED_BLUE_PIN, TACHYONTRACK_LED_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}\
}

#define TACHYONTRACK_I2C_SDA_PORT				0
#define TACHYONTRACK_I2C_SDA_PIN				31
#define TACHYONTRACK_I2C_SDA_PINOP				1
#define TACHYONTRACK_I2C_SCL_PORT				0
#define TACHYONTRACK_I2C_SCL_PIN				30
#define TACHYONTRACK_I2C_SCL_PINOP				1

#define TACHYONTRACK_I2C_PINS_CFG	{ \
	{TACHYONTRACK_I2C_SDA_PORT, TACHYONTRACK_I2C_SDA_PIN, TACHYONTRACK_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_I2C_SCL_PORT, TACHYONTRACK_I2C_SCL_PIN, TACHYONTRACK_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }


#define TACHYONTRACK_SPI_SCK_PORT				0
#define TACHYONTRACK_SPI_SCK_PIN				14
#define TACHYONTRACK_SPI_SCK_PINOP				1
#define TACHYONTRACK_SPI_MISO_PORT				0
#define TACHYONTRACK_SPI_MISO_PIN				16
#define TACHYONTRACK_SPI_MISO_PINOP				1
#define TACHYONTRACK_SPI_MOSI_PORT				0
#define TACHYONTRACK_SPI_MOSI_PIN				15
#define TACHYONTRACK_SPI_MOSI_PINOP				1

#define TACHYONTRACK_IMU_CS_PORT				0
#define TACHYONTRACK_IMU_CS_PIN					13
#define TACHYONTRACK_IMU_CS_PINOP				0

#define TACHYONTRACK_IMU_INT_PORT				0
#define TACHYONTRACK_IMU_INT_PIN				12
#define TACHYONTRACK_IMU_INT_PINOP				0

#define TACHYONTRACK_H3LIS331_CS_PORT			0
#define TACHYONTRACK_H3LIS331_CS_PIN			18
#define TACHYONTRACK_H3LIS331_CS_PINOP			0

#define TACHYONTRACK_FLASH_CS_PORT				0
#define TACHYONTRACK_FLASH_CS_PIN				17
#define TACHYONTRACK_FLASH_CS_PINOP				0

#define TACHYONTRACK_SPI_PINS_CFG	{\
	{TACHYONTRACK_SPI_SCK_PORT, TACHYONTRACK_SPI_SCK_PIN, TACHYONTRACK_SPI_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_SPI_MISO_PORT, TACHYONTRACK_SPI_MISO_PIN, TACHYONTRACK_SPI_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {TACHYONTRACK_SPI_MOSI_PORT, TACHYONTRACK_SPI_MOSI_PIN, TACHYONTRACK_SPI_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {TACHYONTRACK_IMU_CS_PORT, TACHYONTRACK_IMU_CS_PIN, TACHYONTRACK_IMU_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
    {TACHYONTRACK_H3LIS331_CS_PORT, TACHYONTRACK_H3LIS331_CS_PIN, TACHYONTRACK_H3LIS331_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{TACHYONTRACK_FLASH_CS_PORT, TACHYONTRACK_FLASH_CS_PIN, TACHYONTRACK_FLASH_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL},}	// CS


#define TACHYONTRACK_MAG_INT_PORT				0
#define TACHYONTRACK_MAG_INT_PIN				20
#define TACHYONTRACK_MAG_INT_PINOP				0

#define TACHYONTRACK_UART_RX_PORT				0
#define TACHYONTRACK_UART_RX_PIN				27
#define TACHYONTRACK_UART_RX_PINOP				1
#define TACHYONTRACK_UART_TX_PORT				0
#define TACHYONTRACK_UART_TX_PIN				26
#define TACHYONTRACK_UART_TX_PINOP				1

#define TACHYONTRACK_UART_PINS_CFG	{ \
	{TACHYONTRACK_UART_RX_PORT, TACHYONTRACK_UART_RX_PIN, TACHYONTRACK_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{TACHYONTRACK_UART_TX_PORT, TACHYONTRACK_UART_TX_PIN, TACHYONTRACK_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}


// TachyonTrack *****


#endif // __BOARD_TACHYONTRACK_H__
