/**--------------------------------------------------------------------------
@file	board_beavertrack.h

@brief	I/O definitions for the BeaverTrack board

This board uses the BLYST840 (IMM-NRF52840) module

@author	Hoang Nguyen Hoan
@date	May. 20, 2025

@license

MIT License

Copyright (c) 2025 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_BEAVERTRACK_H__
#define __BOARD_BEAVERTRACK_H__

#define BEAVERTRACK_BUT_PORT					1
#define BEAVERTRACK_BUT_PIN						5
#define BEAVERTRACK_BUT_PINOP					0
#define BEAVERTRACK_BUT_SENSE					IOPINSENSE_LOW_TRANSITION

#define BEAVERTRACK_BUT_PINS {\
	{BEAVERTRACK_BUT_PORT, BEAVERTRACK_BUT_PIN, BEAVERTRACK_BUT_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define BEAVERTRACK_LED_RED_PORT				1
#define BEAVERTRACK_LED_RED_PIN					12
#define BEAVERTRACK_LED_RED_PINOP				0
#define BEAVERTRACK_LED_RED_LOGIC				LED_LOGIC_HIGH

#define BEAVERTRACK_LED_GREEN_PORT				1
#define BEAVERTRACK_LED_GREEN_PIN				10
#define BEAVERTRACK_LED_GREEN_PINOP				0
#define BEAVERTRACK_LED_GREEN_LOGIC				LED_LOGIC_HIGH

#define BEAVERTRACK_LED_BLUE_PORT				1
#define BEAVERTRACK_LED_BLUE_PIN				11
#define BEAVERTRACK_LED_BLUE_PINOP				0
#define BEAVERTRACK_LED_BLUE_LOGIC				LED_LOGIC_HIGH

#define BEAVERTRACK_LED_PINS_CFG		{ \
	{BEAVERTRACK_LED_RED_PORT, BEAVERTRACK_LED_RED_PIN, BEAVERTRACK_LED_RED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BEAVERTRACK_LED_GREEN_PORT, BEAVERTRACK_LED_GREEN_PIN, BEAVERTRACK_LED_GREEN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BEAVERTRACK_LED_BLUE_PORT, BEAVERTRACK_LED_BLUE_PIN, BEAVERTRACK_LED_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}\
}

#define BEAVERTRACK_I2C_SDA_PORT				0
#define BEAVERTRACK_I2C_SDA_PIN					15
#define BEAVERTRACK_I2C_SDA_PINOP				1
#define BEAVERTRACK_I2C_SCL_PORT				0
#define BEAVERTRACK_I2C_SCL_PIN					14
#define BEAVERTRACK_I2C_SCL_PINOP				1

#define BEAVERTRACK_I2C_PINS_CFG	{ \
	{BEAVERTRACK_I2C_SDA_PORT, BEAVERTRACK_I2C_SDA_PIN, BEAVERTRACK_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BEAVERTRACK_I2C_SCL_PORT, BEAVERTRACK_I2C_SCL_PIN, BEAVERTRACK_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }


#define BEAVERTRACK_SPI_SCK_PORT				0
#define BEAVERTRACK_SPI_SCK_PIN					20
#define BEAVERTRACK_SPI_SCK_PINOP				1
#define BEAVERTRACK_SPI_MISO_PORT				0
#define BEAVERTRACK_SPI_MISO_PIN				21
#define BEAVERTRACK_SPI_MISO_PINOP				1
#define BEAVERTRACK_SPI_MOSI_PORT				0
#define BEAVERTRACK_SPI_MOSI_PIN				23
#define BEAVERTRACK_SPI_MOSI_PINOP				1

#define BEAVERTRACK_IMU_CS_PORT					0
#define BEAVERTRACK_IMU_CS_PIN					17
#define BEAVERTRACK_IMU_CS_PINOP				0

#define BEAVERTRACK_IMU_INT_PORT				0
#define BEAVERTRACK_IMU_INT_PIN					13
#define BEAVERTRACK_IMU_INT_PINOP				0

#define BEAVERTRACK_SPI_PINS_CFG	{\
	{BEAVERTRACK_SPI_SCK_PORT, BEAVERTRACK_SPI_SCK_PIN, BEAVERTRACK_SPI_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BEAVERTRACK_SPI_MISO_PORT, BEAVERTRACK_SPI_MISO_PIN, BEAVERTRACK_SPI_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BEAVERTRACK_SPI_MOSI_PORT, BEAVERTRACK_SPI_MOSI_PIN, BEAVERTRACK_SPI_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BEAVERTRACK_IMU_CS_PORT, BEAVERTRACK_IMU_CS_PIN, BEAVERTRACK_IMU_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \



#define BEAVERTRACK_AK09940_INT_PORT			1
#define BEAVERTRACK_AK09940_INT_PIN				8
#define BEAVERTRACK_AK09940_INT_PINOP			0

#define BEAVERTRACK_UART_RX_PORT				0
#define BEAVERTRACK_UART_RX_PIN					8
#define BEAVERTRACK_UART_RX_PINOP				1
#define BEAVERTRACK_UART_TX_PORT				0
#define BEAVERTRACK_UART_TX_PIN					7
#define BEAVERTRACK_UART_TX_PINOP				1

#define BEAVERTRACK_UART_PINS_CFG	{ \
	{BEAVERTRACK_UART_RX_PORT, BEAVERTRACK_UART_RX_PIN, BEAVERTRACK_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BEAVERTRACK_UART_TX_PORT, BEAVERTRACK_UART_TX_PIN, BEAVERTRACK_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}


#endif // __BOARD_BEAVERTRACK_H__
