/**--------------------------------------------------------------------------
@file	board_blueio_thingy.h

@brief	I/O definitions for the BLUEIO-THINGY board

This board uses the BLYST Nano module

@author	Hoang Nguyen Hoan
@date	Mar. 24, 2023

@license

MIT License

Copyright (c) 2023 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_BLUEIO_THINGY_H__
#define __BOARD_BLUEIO_THINGY_H__

#include "coredev/iopincfg.h"
#include "miscdev/led.h"

// ***** BLUEIO-THINGY

#define BLUEIO_THINGY_BUT1_PORT					0
#define BLUEIO_THINGY_BUT1_PIN					8
#define BLUEIO_THINGY_BUT1_PINOP				0
#define BLUEIO_THINGY_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_THINGY_BUT2_PORT					0
#define BLUEIO_THINGY_BUT2_PIN					11
#define BLUEIO_THINGY_BUT2_PINOP				0
#define BLUEIO_THINGY_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_THINGY_BUT_PINS_CFG			{ \
	{BLUEIO_THINGY_BUT1_PORT, BLUEIO_THINGY_BUT1_PIN, BLUEIO_THINGY_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_BUT2_PORT, BLUEIO_THINGY_BUT2_PIN, BLUEIO_THINGY_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_THINGY_BUZZER_PORT				0
#define BLUEIO_THINGY_BUZZER_PIN				12
#define BLUEIO_THINGY_BUZZER_PINOP				0

#define BLUEIO_THINGY_LED1_BLUE_PORT			0
#define BLUEIO_THINGY_LED1_BLUE_PIN				24
#define BLUEIO_THINGY_LED1_BLUE_PINOP			0
#define BLUEIO_THINGY_LED1_BLUE_LOGIC			LED_LOGIC_LOW

#define BLUEIO_THINGY_LED2_RED_PORT				0
#define BLUEIO_THINGY_LED2_RED_PIN				18
#define BLUEIO_THINGY_LED2_RED_PINOP			0
#define BLUEIO_THINGY_LED2_RED_LOGIC			LED_LOGIC_LOW

#define BLUEIO_THINGY_LED2_GREEN_PORT			0
#define BLUEIO_THINGY_LED2_GREEN_PIN			20
#define BLUEIO_THINGY_LED2_GREEN_PINOP			0
#define BLUEIO_THINGY_LED2_GREEN_LOGIC			LED_LOGIC_LOW

#define BLUEIO_THINGY_LED2_BLUE_PORT			0
#define BLUEIO_THINGY_LED2_BLUE_PIN				19
#define BLUEIO_THINGY_LED2_BLUE_PINOP			0
#define BLUEIO_THINGY_LED2_BLUE_LOGIC			LED_LOGIC_LOW

#define BLUEIO_THINGY_LED_PINS_CFG		{ \
	{BLUEIO_THINGY_LED1_BLUE_PORT, BLUEIO_THINGY_LED1_BLUE_PIN, BLUEIO_THINGY_LED1_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_LED2_RED_PORT, BLUEIO_THINGY_LED2_RED_PIN, BLUEIO_THINGY_LED2_RED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_LED2_GREEN_PORT, BLUEIO_THINGY_LED2_GREEN_PIN, BLUEIO_THINGY_LED2_GREEN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_LED2_BLUE_PORT, BLUEIO_THINGY_LED2_BLUE_PIN, BLUEIO_THINGY_LED2_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// I2C0
#define BLUEIO_THINGY_I2C0_DEVNO		0
#define BLUEIO_THINGY_I2C0_SDA_PORT				0
#define BLUEIO_THINGY_I2C0_SDA_PIN				7
#define BLUEIO_THINGY_I2C0_SDA_PINOP			1
#define BLUEIO_THINGY_I2C0_SCL_PORT				0
#define BLUEIO_THINGY_I2C0_SCL_PIN				6
#define BLUEIO_THINGY_I2C0_SCL_PINOP			1

#define BLUEIO_THINGY_I2C0_PINS_CFG	{ \
	{BLUEIO_THINGY_I2C0_SDA_PORT, BLUEIO_THINGY_I2C0_SDA_PIN, BLUEIO_THINGY_I2C0_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_I2C0_SCL_PORT, BLUEIO_THINGY_I2C0_SCL_PIN, BLUEIO_THINGY_I2C0_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }

#define BLUEIO_THINGY_BMM350_INT_PORT			0
#define BLUEIO_THINGY_BMM350_INT_PIN			27
#define BLUEIO_THINGY_BMM350_INT_PINOP			0

#define BLUEIO_THINGY_IMU_INT_PORT				0
#define BLUEIO_THINGY_IMU_INT_PIN				26
#define BLUEIO_THINGY_IMU_INT_PINOP				0

// I2C1
#define BLUEIO_THINGY_I2C1_DEVNO		1
#define BLUEIO_THINGY_I2C1_SDA_PORT				0
#define BLUEIO_THINGY_I2C1_SDA_PIN				29
#define BLUEIO_THINGY_I2C1_SDA_PINOP			1
#define BLUEIO_THINGY_I2C1_SCL_PORT				0
#define BLUEIO_THINGY_I2C1_SCL_PIN				28
#define BLUEIO_THINGY_I2C1_SCL_PINOP			1

#define BLUEIO_THINGY_I2C1_PINS_CFG	{ \
	{BLUEIO_THINGY_I2C1_SDA_PORT, BLUEIO_THINGY_I2C1_SDA_PIN, BLUEIO_THINGY_I2C1_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_I2C1_SCL_PORT, BLUEIO_THINGY_I2C1_SCL_PIN, BLUEIO_THINGY_I2C1_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }

// SPI2
#define BLUEIO_THINGY_SPI2_DENO			2
#define BLUEIO_THINGY_SPI_SCK_PORT				0
#define BLUEIO_THINGY_SPI_SCK_PIN				15
#define BLUEIO_THINGY_SPI_SCK_PINOP				1
#define BLUEIO_THINGY_SPI_MISO_PORT				0
#define BLUEIO_THINGY_SPI_MISO_PIN				17
#define BLUEIO_THINGY_SPI_MISO_PINOP			1
#define BLUEIO_THINGY_SPI_MOSI_PORT				0
#define BLUEIO_THINGY_SPI_MOSI_PIN				16
#define BLUEIO_THINGY_SPI_MOSI_PINOP			1


#define BLUEIO_THINGY_FLASH_CS_PORT				0
#define BLUEIO_THINGY_FLASH_CS_PIN				25
#define BLUEIO_THINGY_FLASH_CS_PINOP			0

#define BLUEIO_THINGY_SPI_PINS_CFG	{\
	{BLUEIO_THINGY_SPI_SCK_PORT, BLUEIO_THINGY_SPI_SCK_PIN, BLUEIO_THINGY_SPI_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_SPI_MISO_PORT, BLUEIO_THINGY_SPI_MISO_PIN, BLUEIO_THINGY_SPI_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLUEIO_THINGY_SPI_MOSI_PORT, BLUEIO_THINGY_SPI_MOSI_PIN, BLUEIO_THINGY_SPI_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_THINGY_FLASH_CS_PORT, BLUEIO_THINGY_FLASH_CS_PIN, BLUEIO_THINGY_FLASH_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL},}	// CS

#define BLUEIO_THINGY_UART_RX_PORT				0
#define BLUEIO_THINGY_UART_RX_PIN				14
#define BLUEIO_THINGY_UART_RX_PINOP				1
#define BLUEIO_THINGY_UART_TX_PORT				0
#define BLUEIO_THINGY_UART_TX_PIN				13
#define BLUEIO_THINGY_UART_TX_PINOP				1

#define BLUEIO_THINGY_UART_PINS_CFG	{ \
	{BLUEIO_THINGY_UART_RX_PORT, BLUEIO_THINGY_UART_RX_PIN, BLUEIO_THINGY_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{BLUEIO_THINGY_UART_TX_PORT, BLUEIO_THINGY_UART_TX_PIN, BLUEIO_THINGY_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

// BLUEIO-THINGY *****


#endif // __BOARD_BLUEIO_THINGY_H__
