/**--------------------------------------------------------------------------
@file	board_blueio_adxl_wchrg.h

@brief	I/O definitions for BLUEIO-ADXL-WCHRG board

This board uses the BLYST Nano module

@author	Hoang Nguyen Hoan
@date	Mar. 24, 2023

@license

MIT License

Copyright (c) 2023 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_BLUEIO_ADXL_WCHRG_H__
#define __BOARD_BLUEIO_ADXL_WCHRG_H__

#include "coredev/iopincfg.h"
#include "miscdev/led.h"

// ***** BLUEIO-ADXL-WCHRG

#define BLUEIO_ADXL_WCHRG_BUT1_PORT					0
#define BLUEIO_ADXL_WCHRG_BUT1_PIN					13
#define BLUEIO_ADXL_WCHRG_BUT1_PINOP				0

#define BLUEIO_ADXL_WCHRG_BUT1_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_ADXL_WCHRG_BUT2_PORT					0
#define BLUEIO_ADXL_WCHRG_BUT2_PIN					2
#define BLUEIO_ADXL_WCHRG_BUT2_PINOP				0

#define BLUEIO_ADXL_WCHRG_BUT2_SENSE				IOPINSENSE_LOW_TRANSITION

#define BLUEIO_ADXL_WCHRG_BUT_PINS_CFG			{ \
	{BLUEIO_ADXL_WCHRG_BUT1_PORT, BLUEIO_ADXL_WCHRG_BUT1_PIN, BLUEIO_ADXL_WCHRG_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_BUT2_PORT, BLUEIO_ADXL_WCHRG_BUT2_PIN, BLUEIO_ADXL_WCHRG_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_ADXL_WCHRG_LED1_BLUE_PORT				0
#define BLUEIO_ADXL_WCHRG_LED1_BLUE_PIN					30
#define BLUEIO_ADXL_WCHRG_LED1_BLUE_PINOP				0
#define BLUEIO_ADXL_WCHRG_LED1_BLUE_LOGIC				LED_LOGIC_LOW

#define BLUEIO_ADXL_WCHRG_LED2_GREEN_PORT				0
#define BLUEIO_ADXL_WCHRG_LED2_GREEN_PIN				29
#define BLUEIO_ADXL_WCHRG_LED2_GREEN_PINOP				0
#define BLUEIO_ADXL_WCHRG_LED2_GREEN_LOGIC				LED_LOGIC_LOW

#define BLUEIO_ADXL_WCHRG_LED3_RED_PORT					0
#define BLUEIO_ADXL_WCHRG_LED3_RED_PIN					28
#define BLUEIO_ADXL_WCHRG_LED3_RED_PINOP				0
#define BLUEIO_ADXL_WCHRG_LED3_RED_LOGIC				LED_LOGIC_LOW

#define BLUEIO_ADXL_WCHRG_LED_PINS_CFG			{ \
	{BLUEIO_ADXL_WCHRG_LED1_BLUE_PORT, BLUEIO_ADXL_WCHRG_LED1_BLUE_PIN, BLUEIO_ADXL_WCHRG_LED1_BLUE_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_LED2_GREEN_PORT, BLUEIO_ADXL_WCHRG_LED2_GREEN_PIN, BLUEIO_ADXL_WCHRG_LED2_GREEN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_LED3_RED_PORT, BLUEIO_ADXL_WCHRG_LED3_RED_PIN, BLUEIO_ADXL_WCHRG_LED3_RED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_ADXL_WCHRG_I2C_DEVNO				0
#define BLUEIO_ADXL_WCHRG_I2C_SDA_PORT					0
#define BLUEIO_ADXL_WCHRG_I2C_SDA_PIN					19
#define BLUEIO_ADXL_WCHRG_I2C_SDA_PINOP					1
#define BLUEIO_ADXL_WCHRG_I2C_SCL_PORT					0
#define BLUEIO_ADXL_WCHRG_I2C_SCL_PIN					18
#define BLUEIO_ADXL_WCHRG_I2C_SCL_PINOP					1

#define BLUEIO_ADXL_WCHRG_I2C_PINS_CFG	{ \
	{BLUEIO_ADXL_WCHRG_I2C_SDA_PORT, BLUEIO_ADXL_WCHRG_I2C_SDA_PIN, BLUEIO_ADXL_WCHRG_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_I2C_SCL_PORT, BLUEIO_ADXL_WCHRG_I2C_SCL_PIN, BLUEIO_ADXL_WCHRG_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, }

#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT			0
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PIN				20
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT			0

#define BLUEIO_ADXL_WCHRG_ADXL362_SPI_DEVNO		2
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PORT				0
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PIN				17
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PINOP				1
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PORT				0
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PIN				16
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PINOP			1
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PORT				0
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PIN				15
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PINOP			1

#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PORT				0
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PIN				5
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PPINOP				0

#define BLUEIO_ADXL_WCHRG_ADXL363_SPI_PINS_CFG	{\
	{BLUEIO_ADXL_WCHRG_ADXL362_SCK_PORT, BLUEIO_ADXL_WCHRG_ADXL362_SCK_PIN, BLUEIO_ADXL_WCHRG_ADXL362_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_ADXL362_MISO_PORT, BLUEIO_ADXL_WCHRG_ADXL362_MISO_PIN, BLUEIO_ADXL_WCHRG_ADXL362_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PORT, BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PIN, BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLUEIO_ADXL_WCHRG_ADXL362_CS_PORT, BLUEIO_ADXL_WCHRG_ADXL362_CS_PIN, BLUEIO_ADXL_WCHRG_ADXL362_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT				0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN				6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP			0

#define BLUEIO_ADXL_WCHRG_FLASH_SPI_DEVNO		1
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PORT				0
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PIN					23
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PINOP				1
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PORT				0
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PIN				24
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PINOP				1
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PORT				0
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PIN				25
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PINOP				1

#define BLUEIO_ADXL_WCHRG_FLASH_CS_PORT					0
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PIN					26
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PINOP				0

#define BLUEIO_ADXL_WCHRG_FLASH_SPI_PINS_CFG	{\
	{BLUEIO_ADXL_WCHRG_FLASH_SCK_PORT, BLUEIO_ADXL_WCHRG_FLASH_SCK_PIN, BLUEIO_ADXL_WCHRG_FLASH_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO_ADXL_WCHRG_FLASH_MISO_PORT, BLUEIO_ADXL_WCHRG_FLASH_MISO_PIN, BLUEIO_ADXL_WCHRG_FLASH_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLUEIO_ADXL_WCHRG_FLASH_MOSI_PORT, BLUEIO_ADXL_WCHRG_FLASH_MOSI_PIN, BLUEIO_ADXL_WCHRG_FLASH_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
    {BLUEIO_ADXL_WCHRG_FLASH_CS_PORT, BLUEIO_ADXL_WCHRG_FLASH_CS_PIN, BLUEIO_ADXL_WCHRG_FLASH_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// BLUEIO-ADXL-WCHRG *****


#endif // __BOARD_BLUEIO_ADXL_WCHRG_H__
