/**-------------------------------------------------------------------------
@file	board_arduino_nano33ble.h

@brief	Pin map of the Arduino Nano 33 BLE and Nano 33 BLE Sense (nRF52840)

Port and pin of every signal the board routes. D and A numbers follow the
Arduino core numbering. The applications built for the stock Arduino
bootloader link with nrf52840_xxaa_bossa.ld.

@author	Hoang Nguyen Hoan
@date	Oct. 6, 2026

@license

MIT License

Copyright (c) 2026, I-SYST inc., all rights reserved

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_ARDUINO_NANO33BLE_H__
#define __BOARD_ARDUINO_NANO33BLE_H__

#include "coredev/iopincfg.h"
#include "miscdev/led.h"

// Nano header, digital
#define NANO33BLE_D0_PORT					1
#define NANO33BLE_D0_PIN					3		// Serial1 TX
#define NANO33BLE_D1_PORT					1
#define NANO33BLE_D1_PIN					10		// Serial1 RX
#define NANO33BLE_D2_PORT					1
#define NANO33BLE_D2_PIN					11
#define NANO33BLE_D3_PORT					1
#define NANO33BLE_D3_PIN					12
#define NANO33BLE_D4_PORT					1
#define NANO33BLE_D4_PIN					15
#define NANO33BLE_D5_PORT					1
#define NANO33BLE_D5_PIN					13
#define NANO33BLE_D6_PORT					1
#define NANO33BLE_D6_PIN					14
#define NANO33BLE_D7_PORT					0
#define NANO33BLE_D7_PIN					23
#define NANO33BLE_D8_PORT					0
#define NANO33BLE_D8_PIN					21
#define NANO33BLE_D9_PORT					0
#define NANO33BLE_D9_PIN					27
#define NANO33BLE_D10_PORT					1
#define NANO33BLE_D10_PIN					2		// SPI CS
#define NANO33BLE_D11_PORT					1
#define NANO33BLE_D11_PIN					1		// SPI MOSI
#define NANO33BLE_D12_PORT					1
#define NANO33BLE_D12_PIN					8		// SPI MISO
#define NANO33BLE_D13_PORT					0
#define NANO33BLE_D13_PIN					13		// SPI SCK, LED

// Nano header, analog. AIN is the SAADC input of the pin.
#define NANO33BLE_A0_PORT					0
#define NANO33BLE_A0_PIN					4
#define NANO33BLE_A0_AIN					2
#define NANO33BLE_A1_PORT					0
#define NANO33BLE_A1_PIN					5
#define NANO33BLE_A1_AIN					3
#define NANO33BLE_A2_PORT					0
#define NANO33BLE_A2_PIN					30
#define NANO33BLE_A2_AIN					6
#define NANO33BLE_A3_PORT					0
#define NANO33BLE_A3_PIN					29
#define NANO33BLE_A3_AIN					5
#define NANO33BLE_A4_PORT					0
#define NANO33BLE_A4_PIN					31		// I2C SDA
#define NANO33BLE_A4_AIN					7
#define NANO33BLE_A5_PORT					0
#define NANO33BLE_A5_PIN					2		// I2C SCL
#define NANO33BLE_A5_AIN					0
#define NANO33BLE_A6_PORT					0
#define NANO33BLE_A6_PIN					28
#define NANO33BLE_A6_AIN					4
#define NANO33BLE_A7_PORT					0
#define NANO33BLE_A7_PIN					3
#define NANO33BLE_A7_AIN					1

// LEDs. LED is the orange LED on D13, shared with SPI SCK.
#define NANO33BLE_LED_PORT					0
#define NANO33BLE_LED_PIN					13
#define NANO33BLE_LED_PINOP					0
#define NANO33BLE_LED_LOGIC					LED_LOGIC_HIGH

#define NANO33BLE_LEDR_PORT					0
#define NANO33BLE_LEDR_PIN					24
#define NANO33BLE_LEDR_PINOP				0
#define NANO33BLE_LEDR_LOGIC				LED_LOGIC_LOW

#define NANO33BLE_LEDG_PORT					0
#define NANO33BLE_LEDG_PIN					16
#define NANO33BLE_LEDG_PINOP				0
#define NANO33BLE_LEDG_LOGIC				LED_LOGIC_LOW

#define NANO33BLE_LEDB_PORT					0
#define NANO33BLE_LEDB_PIN					6
#define NANO33BLE_LEDB_PINOP				0
#define NANO33BLE_LEDB_LOGIC				LED_LOGIC_LOW

#define NANO33BLE_LED_PWR_PORT				1
#define NANO33BLE_LED_PWR_PIN				9
#define NANO33BLE_LED_PWR_PINOP				0
#define NANO33BLE_LED_PWR_LOGIC				LED_LOGIC_HIGH

#define NANO33BLE_LED_PINS_CFG	{ \
	{NANO33BLE_LED_PORT, NANO33BLE_LED_PIN, NANO33BLE_LED_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_LEDR_PORT, NANO33BLE_LEDR_PIN, NANO33BLE_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_LEDG_PORT, NANO33BLE_LEDG_PIN, NANO33BLE_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_LEDB_PORT, NANO33BLE_LEDB_PIN, NANO33BLE_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// Serial1 on D0/D1
#define NANO33BLE_UART_RX_PORT				1
#define NANO33BLE_UART_RX_PIN				10
#define NANO33BLE_UART_RX_PINOP				1
#define NANO33BLE_UART_TX_PORT				1
#define NANO33BLE_UART_TX_PIN				3
#define NANO33BLE_UART_TX_PINOP				1

#define NANO33BLE_UART_PINS_CFG	{ \
	{NANO33BLE_UART_RX_PORT, NANO33BLE_UART_RX_PIN, NANO33BLE_UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_UART_TX_PORT, NANO33BLE_UART_TX_PIN, NANO33BLE_UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// I2C on the header, A4/A5
#define NANO33BLE_I2C_SDA_PORT				0
#define NANO33BLE_I2C_SDA_PIN				31
#define NANO33BLE_I2C_SDA_PINOP				1
#define NANO33BLE_I2C_SCL_PORT				0
#define NANO33BLE_I2C_SCL_PIN				2
#define NANO33BLE_I2C_SCL_PINOP				1

#define NANO33BLE_I2C_PINS_CFG	{ \
	{NANO33BLE_I2C_SDA_PORT, NANO33BLE_I2C_SDA_PIN, NANO33BLE_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_I2C_SCL_PORT, NANO33BLE_I2C_SCL_PIN, NANO33BLE_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// On-board sensor I2C. Its pull-ups are powered by I2C_PULLUP_EN and the
// sensors by VDD_ENV_EN, both active high.
#define NANO33BLE_SENSOR_I2C_SDA_PORT		0
#define NANO33BLE_SENSOR_I2C_SDA_PIN		14
#define NANO33BLE_SENSOR_I2C_SDA_PINOP		1
#define NANO33BLE_SENSOR_I2C_SCL_PORT		0
#define NANO33BLE_SENSOR_I2C_SCL_PIN		15
#define NANO33BLE_SENSOR_I2C_SCL_PINOP		1

#define NANO33BLE_SENSOR_I2C_PINS_CFG	{ \
	{NANO33BLE_SENSOR_I2C_SDA_PORT, NANO33BLE_SENSOR_I2C_SDA_PIN, NANO33BLE_SENSOR_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_SENSOR_I2C_SCL_PORT, NANO33BLE_SENSOR_I2C_SCL_PIN, NANO33BLE_SENSOR_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#define NANO33BLE_VDD_ENV_EN_PORT			0
#define NANO33BLE_VDD_ENV_EN_PIN			22
#define NANO33BLE_VDD_ENV_EN_PINOP			0
#define NANO33BLE_I2C_PULLUP_EN_PORT		1
#define NANO33BLE_I2C_PULLUP_EN_PIN			0
#define NANO33BLE_I2C_PULLUP_EN_PINOP		0

#define NANO33BLE_SENSOR_PWR_PINS_CFG	{ \
	{NANO33BLE_VDD_ENV_EN_PORT, NANO33BLE_VDD_ENV_EN_PIN, NANO33BLE_VDD_ENV_EN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_I2C_PULLUP_EN_PORT, NANO33BLE_I2C_PULLUP_EN_PIN, NANO33BLE_I2C_PULLUP_EN_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// APDS9960 interrupt (Sense)
#define NANO33BLE_APDS_INT_PORT				0
#define NANO33BLE_APDS_INT_PIN				19
#define NANO33BLE_APDS_INT_PINOP			0

// SPI on D10-D13
#define NANO33BLE_SPI_SCK_PORT				0
#define NANO33BLE_SPI_SCK_PIN				13
#define NANO33BLE_SPI_SCK_PINOP				1
#define NANO33BLE_SPI_MISO_PORT				1
#define NANO33BLE_SPI_MISO_PIN				8
#define NANO33BLE_SPI_MISO_PINOP			1
#define NANO33BLE_SPI_MOSI_PORT				1
#define NANO33BLE_SPI_MOSI_PIN				1
#define NANO33BLE_SPI_MOSI_PINOP			1
#define NANO33BLE_SPI_CS_PORT				1
#define NANO33BLE_SPI_CS_PIN				2
#define NANO33BLE_SPI_CS_PINOP				0

#define NANO33BLE_SPI_PINS_CFG	{ \
	{NANO33BLE_SPI_SCK_PORT, NANO33BLE_SPI_SCK_PIN, NANO33BLE_SPI_SCK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_SPI_MISO_PORT, NANO33BLE_SPI_MISO_PIN, NANO33BLE_SPI_MISO_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_SPI_MOSI_PORT, NANO33BLE_SPI_MOSI_PIN, NANO33BLE_SPI_MOSI_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_SPI_CS_PORT, NANO33BLE_SPI_CS_PIN, NANO33BLE_SPI_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// PDM microphone (Sense). MIC_PWR powers the microphone, active high.
#define NANO33BLE_MIC_PWR_PORT				0
#define NANO33BLE_MIC_PWR_PIN				17
#define NANO33BLE_MIC_PWR_PINOP				0
#define NANO33BLE_PDM_CLK_PORT				0
#define NANO33BLE_PDM_CLK_PIN				26
#define NANO33BLE_PDM_CLK_PINOP				1
#define NANO33BLE_PDM_DIN_PORT				0
#define NANO33BLE_PDM_DIN_PIN				25
#define NANO33BLE_PDM_DIN_PINOP				1

#define NANO33BLE_PDM_PINS_CFG	{ \
	{NANO33BLE_PDM_CLK_PORT, NANO33BLE_PDM_CLK_PIN, NANO33BLE_PDM_CLK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{NANO33BLE_PDM_DIN_PORT, NANO33BLE_PDM_DIN_PIN, NANO33BLE_PDM_DIN_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#endif
