// 
//  Font data for FreeSerif 8pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeSerif 8pt
static const uint8_t s_FreeSerif8ptBitmaps[] = {
	// @0 '!' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  

	// @12 '"' (3 pixels wide)
	0x00, //    
	0xA0, // # #
	0xA0, // # #
	0xA0, // # #
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @24 '#' (5 pixels wide)
	0x00, //      
	0x28, //   # #
	0x48, //  #  #
	0x50, //  # # 
	0xF8, // #####
	0x50, //  # # 
	0xF8, // #####
	0x50, //  # # 
	0x50, //  # # 
	0x00, //      
	0x00, //      
	0x00, //      

	// @36 '$' (4 pixels wide)
	0x20, //   # 
	0x70, //  ###
	0xB0, // # ##
	0xA0, // # # 
	0x60, //  ## 
	0x30, //   ##
	0xB0, // # ##
	0xB0, // # ##
	0x70, //  ###
	0x20, //   # 
	0x00, //     
	0x00, //     

	// @48 '%' (8 pixels wide)
	0x00, //         
	0x64, //  ##  #  
	0xD8, // ## ##   
	0x98, // #  ##   
	0xB7, // # ## ###
	0x7D, //  ##### #
	0x29, //   # #  #
	0x2B, //   # # ##
	0x0E, //     ### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @60 '&' (8 pixels wide)
	0x00, //         
	0x18, //    ##   
	0x24, //   #  #  
	0x24, //   #  #  
	0x3B, //   ### ##
	0x32, //   ##  # 
	0xDA, // ## ## # 
	0x8C, // #   ##  
	0x73, //  ###  ##
	0x00, //         
	0x00, //         
	0x00, //         

	// @72 ''' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @84 '(' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x40, //  # 
	0x20, //   #
	0x00, //    

	// @96 ')' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x80, // #  
	0x00, //    

	// @108 '*' (4 pixels wide)
	0x00, //     
	0x40, //  #  
	0xD0, // ## #
	0x60, //  ## 
	0xD0, // ## #
	0x40, //  #  
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @120 '+' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      
	0x00, //      

	// @132 ',' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  

	// @144 '-' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @156 '.' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  

	// @168 '/' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x00, //    
	0x00, //    
	0x00, //    

	// @180 '0' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0xD8, // ## ##
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0xD8, // ## ##
	0x70, //  ### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @192 '1' (3 pixels wide)
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    

	// @204 '2' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x88, // #   #
	0x08, //     #
	0x08, //     #
	0x10, //    # 
	0x20, //   #  
	0x48, //  #  #
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @216 '3' (4 pixels wide)
	0x00, //     
	0x70, //  ###
	0x90, // #  #
	0x20, //   # 
	0x70, //  ###
	0x10, //    #
	0x10, //    #
	0x10, //    #
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @228 '4' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x10, //    # 
	0x30, //   ## 
	0x50, //  # # 
	0x90, // #  # 
	0x78, //  ####
	0x10, //    # 
	0x10, //    # 
	0x00, //      
	0x00, //      
	0x00, //      

	// @240 '5' (5 pixels wide)
	0x00, //      
	0x38, //   ###
	0x40, //  #   
	0x70, //  ### 
	0x18, //    ##
	0x08, //     #
	0x08, //     #
	0x10, //    # 
	0xE0, // ###  
	0x00, //      
	0x00, //      
	0x00, //      

	// @252 '6' (5 pixels wide)
	0x18, //    ##
	0x20, //   #  
	0x40, //  #   
	0xC0, // ##   
	0xB0, // # ## 
	0xC8, // ##  #
	0x88, // #   #
	0x88, // #   #
	0x70, //  ### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @264 '7' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x88, // #   #
	0x08, //     #
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      
	0x00, //      

	// @276 '8' (4 pixels wide)
	0x00, //     
	0x60, //  ## 
	0x90, // #  #
	0x90, // #  #
	0x60, //  ## 
	0xB0, // # ##
	0x90, // #  #
	0x90, // #  #
	0x60, //  ## 
	0x00, //     
	0x00, //     
	0x00, //     

	// @288 '9' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x78, //  ####
	0x18, //    ##
	0x10, //    # 
	0x20, //   #  
	0xC0, // ##   
	0x00, //      
	0x00, //      

	// @300 ':' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  

	// @312 ';' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x80, // # 
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x40, //  #
	0x00, //   
	0x00, //   

	// @324 '<' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x04, //      #
	0x18, //    ## 
	0x60, //  ##   
	0xC0, // ##    
	0x30, //   ##  
	0x0C, //     ##
	0x00, //       
	0x00, //       
	0x00, //       

	// @336 '=' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       

	// @348 '>' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x80, // #     
	0x60, //  ##   
	0x1C, //    ###
	0x18, //    ## 
	0x60, //  ##   
	0x80, // #     
	0x00, //       
	0x00, //       
	0x00, //       

	// @360 '?' (4 pixels wide)
	0x00, //     
	0xE0, // ### 
	0x90, // #  #
	0x10, //    #
	0x10, //    #
	0x20, //   # 
	0x40, //  #  
	0x00, //     
	0x40, //  #  
	0x00, //     
	0x00, //     
	0x00, //     

	// @372 '@' (8 pixels wide)
	0x00, //         
	0x3C, //   ####  
	0x42, //  #    # 
	0x9D, // #  ### #
	0xA5, // # #  # #
	0xA9, // # # #  #
	0xB6, // # ## ## 
	0x40, //  #      
	0x38, //   ###   
	0x00, //         
	0x00, //         
	0x00, //         

	// @384 'A' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x18, //    ##   
	0x28, //   # #   
	0x2C, //   # ##  
	0x24, //   #  #  
	0x7E, //  ###### 
	0x42, //  #    # 
	0xC7, // ##   ###
	0x00, //         
	0x00, //         
	0x00, //         

	// @396 'B' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x78, //  #### 
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @408 'C' (8 pixels wide)
	0x00, //         
	0x3D, //   #### #
	0x43, //  #    ##
	0x81, // #      #
	0x80, // #       
	0x80, // #       
	0x80, // #       
	0x41, //  #     #
	0x3E, //   ##### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @420 'D' (7 pixels wide)
	0x00, //        
	0xF8, // #####  
	0x44, //  #   # 
	0x42, //  #    #
	0x42, //  #    #
	0x42, //  #    #
	0x42, //  #    #
	0x44, //  #   # 
	0xF8, // #####  
	0x00, //        
	0x00, //        
	0x00, //        

	// @432 'E' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x42, //  #    #
	0x44, //  #   # 
	0x7C, //  ##### 
	0x44, //  #   # 
	0x40, //  #     
	0x44, //  #   # 
	0xFC, // ###### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @444 'F' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x42, //  #    #
	0x44, //  #   # 
	0x7C, //  ##### 
	0x44, //  #   # 
	0x40, //  #     
	0x40, //  #     
	0xE0, // ###    
	0x00, //        
	0x00, //        
	0x00, //        

	// @456 'G' (8 pixels wide)
	0x00, //         
	0x3A, //   ### # 
	0x46, //  #   ## 
	0x80, // #       
	0x87, // #    ###
	0x82, // #     # 
	0x82, // #     # 
	0x42, //  #    # 
	0x3C, //   ####  
	0x00, //         
	0x00, //         
	0x00, //         

	// @468 'H' (8 pixels wide)
	0x00, //         
	0xE7, // ###  ###
	0x42, //  #    # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x7E, //  ###### 
	0x42, //  #    # 
	0x42, //  #    # 
	0xE7, // ###  ###
	0x00, //         
	0x00, //         
	0x00, //         

	// @480 'I' (3 pixels wide)
	0x00, //    
	0xE0, // ###
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    

	// @492 'J' (4 pixels wide)
	0x00, //     
	0x70, //  ###
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0xC0, // ##  
	0x00, //     
	0x00, //     
	0x00, //     

	// @504 'K' (7 pixels wide)
	0x00, //        
	0xEE, // ### ###
	0x44, //  #   # 
	0x58, //  # ##  
	0x60, //  ##    
	0x50, //  # #   
	0x48, //  #  #  
	0x44, //  #   # 
	0xEE, // ### ###
	0x00, //        
	0x00, //        
	0x00, //        

	// @516 'L' (7 pixels wide)
	0x00, //        
	0xE0, // ###    
	0x40, //  #     
	0x40, //  #     
	0x40, //  #     
	0x40, //  #     
	0x40, //  #     
	0x46, //  #   ##
	0xFC, // ###### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @528 'M' (9 pixels wide)
	0x00, 0x00, //          
	0xE1, 0x80, // ###    ##
	0x63, 0x00, //  ##   ## 
	0x73, 0x00, //  ###  ## 
	0x55, 0x00, //  # # # # 
	0x55, 0x00, //  # # # # 
	0x5D, 0x00, //  # ### # 
	0x49, 0x00, //  #  #  # 
	0xEB, 0x80, // ### # ###
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @552 'N' (8 pixels wide)
	0x00, //         
	0xE7, // ###  ###
	0x62, //  ##   # 
	0x72, //  ###  # 
	0x5A, //  # ## # 
	0x4A, //  #  # # 
	0x46, //  #   ## 
	0x46, //  #   ## 
	0xE2, // ###   # 
	0x00, //         
	0x00, //         
	0x00, //         

	// @564 'O' (7 pixels wide)
	0x00, //        
	0x38, //   ###  
	0x44, //  #   # 
	0x82, // #     #
	0x82, // #     #
	0x82, // #     #
	0x82, // #     #
	0x44, //  #   # 
	0x38, //   ###  
	0x00, //        
	0x00, //        
	0x00, //        

	// @576 'P' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0x78, //  #### 
	0x40, //  #    
	0x40, //  #    
	0xE0, // ###   
	0x00, //       
	0x00, //       
	0x00, //       

	// @588 'Q' (7 pixels wide)
	0x00, //        
	0x38, //   ###  
	0x44, //  #   # 
	0x82, // #     #
	0x82, // #     #
	0x82, // #     #
	0x82, // #     #
	0x44, //  #   # 
	0x38, //   ###  
	0x08, //     #  
	0x06, //      ##
	0x00, //        

	// @600 'R' (7 pixels wide)
	0x00, //        
	0xF8, // #####  
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x78, //  ####  
	0x58, //  # ##  
	0x4C, //  #  ## 
	0xE6, // ###  ##
	0x00, //        
	0x00, //        
	0x00, //        

	// @612 'S' (4 pixels wide)
	0x00, //     
	0x70, //  ###
	0x90, // #  #
	0x80, // #   
	0x40, //  #  
	0x30, //   ##
	0x10, //    #
	0x90, // #  #
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @624 'T' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x92, // #  #  #
	0x10, //    #   
	0x10, //    #   
	0x10, //    #   
	0x10, //    #   
	0x10, //    #   
	0x38, //   ###  
	0x00, //        
	0x00, //        
	0x00, //        

	// @636 'U' (8 pixels wide)
	0x00, //         
	0xE7, // ###  ###
	0x42, //  #    # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x3C, //   ####  
	0x00, //         
	0x00, //         
	0x00, //         

	// @648 'V' (8 pixels wide)
	0x00, //         
	0xE7, // ###  ###
	0x42, //  #    # 
	0x64, //  ##  #  
	0x24, //   #  #  
	0x34, //   ## #  
	0x18, //    ##   
	0x18, //    ##   
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         

	// @660 'W' (10 pixels wide)
	0x00, 0x00, //           
	0xFC, 0xC0, // ######  ##
	0x4C, 0x40, //  #  ##   #
	0x44, 0x80, //  #   #  # 
	0x24, 0x80, //   #  #  # 
	0x2B, 0x00, //   # # ##  
	0x33, 0x00, //   ##  ##  
	0x13, 0x00, //    #  ##  
	0x10, 0x00, //    #      
	0x00, 0x00, //           
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @684 'X' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x64, //  ##  #  
	0x28, //   # #   
	0x18, //    ##   
	0x18, //    ##   
	0x24, //   #  #  
	0x46, //  #   ## 
	0xEF, // ### ####
	0x00, //         
	0x00, //         
	0x00, //         

	// @696 'Y' (7 pixels wide)
	0x00, //        
	0xE6, // ###  ##
	0x44, //  #   # 
	0x28, //   # #  
	0x38, //   ###  
	0x10, //    #   
	0x10, //    #   
	0x10, //    #   
	0x38, //   ###  
	0x00, //        
	0x00, //        
	0x00, //        

	// @708 'Z' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0x88, // #   #  
	0x08, //     #  
	0x10, //    #   
	0x20, //   #    
	0x60, //  ##    
	0x42, //  #    #
	0xFC, // ###### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @720 '[' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0xC0, // ##
	0x00, //   

	// @732 '\' (3 pixels wide)
	0x00, //    
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x00, //    
	0x00, //    
	0x00, //    

	// @744 ']' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0xC0, // ##
	0x00, //   

	// @756 '^' (5 pixels wide)
	0x00, //      
	0x20, //   #  
	0x50, //  # # 
	0x50, //  # # 
	0x88, // #   #
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @768 '_' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       

	// @780 '`' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @792 'a' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0x10, //    # 
	0x70, //  ### 
	0x90, // #  # 
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @804 'b' (5 pixels wide)
	0x00, //      
	0xC0, // ##   
	0x40, //  #   
	0x40, //  #   
	0x70, //  ### 
	0x48, //  #  #
	0x48, //  #  #
	0x48, //  #  #
	0x70, //  ### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @816 'c' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x80, // #   
	0x80, // #   
	0x80, // #   
	0x70, //  ###
	0x00, //     
	0x00, //     
	0x00, //     

	// @828 'd' (5 pixels wide)
	0x00, //      
	0x18, //    ##
	0x08, //     #
	0x08, //     #
	0x78, //  ####
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x78, //  ####
	0x00, //      
	0x00, //      
	0x00, //      

	// @840 'e' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0xF0, // ####
	0x80, // #   
	0xD0, // ## #
	0x70, //  ###
	0x00, //     
	0x00, //     
	0x00, //     

	// @852 'f' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x40, //  #  
	0x40, //  #  
	0xE0, // ### 
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @864 'g' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0x50, //  # #   
	0x50, //  # #   
	0x20, //   #    
	0x40, //  #     
	0x78, //  ####  
	0x84, // #    # 
	0xF8, // #####  

	// @876 'h' (6 pixels wide)
	0x00, //       
	0xC0, // ##    
	0x40, //  #    
	0x40, //  #    
	0x58, //  # ## 
	0x68, //  ## # 
	0x48, //  #  # 
	0x48, //  #  # 
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @888 'i' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x40, //  # 
	0x00, //    
	0x40, //  # 
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    

	// @900 'j' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x20, //   #
	0x00, //    
	0x20, //   #
	0x60, //  ##
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0xC0, // ## 

	// @912 'k' (6 pixels wide)
	0x00, //       
	0xC0, // ##    
	0x40, //  #    
	0x40, //  #    
	0x58, //  # ## 
	0x50, //  # #  
	0x60, //  ##   
	0x50, //  # #  
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @924 'l' (3 pixels wide)
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    

	// @936 'm' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0xDF, 0x00, // ## ##### 
	0x69, 0x00, //  ## #  # 
	0x49, 0x00, //  #  #  # 
	0x49, 0x00, //  #  #  # 
	0xFF, 0x80, // #########
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @960 'n' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xD8, // ## ## 
	0x68, //  ## # 
	0x48, //  #  # 
	0x48, //  #  # 
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @972 'o' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x70, //  ### 
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x70, //  ### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @984 'p' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0x48, //  #  #
	0x48, //  #  #
	0x48, //  #  #
	0x70, //  ### 
	0x40, //  #   
	0x40, //  #   
	0xE0, // ###  

	// @996 'q' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x70, //  ###  
	0x88, // #   # 
	0x88, // #   # 
	0x88, // #   # 
	0x78, //  #### 
	0x08, //     # 
	0x08, //     # 
	0x1C, //    ###

	// @1008 'r' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @1020 's' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x90, // #  #
	0x60, //  ## 
	0x90, // #  #
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @1032 't' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x40, //  # 
	0xE0, // ###
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x60, //  ##
	0x00, //    
	0x00, //    
	0x00, //    

	// @1044 'u' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xD8, // ## ## 
	0x48, //  #  # 
	0x48, //  #  # 
	0x48, //  #  # 
	0x7C, //  #####
	0x00, //       
	0x00, //       
	0x00, //       

	// @1056 'v' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xC8, // ##  #
	0x50, //  # # 
	0x50, //  # # 
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      
	0x00, //      

	// @1068 'w' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0xDA, // ## ## #
	0x52, //  # #  #
	0x5C, //  # ### 
	0x2C, //   # ## 
	0x24, //   #  # 
	0x00, //        
	0x00, //        
	0x00, //        

	// @1080 'x' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xD8, // ## ##
	0x50, //  # # 
	0x20, //   #  
	0x50, //  # # 
	0xD8, // ## ##
	0x00, //      
	0x00, //      
	0x00, //      

	// @1092 'y' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xC8, // ##  #
	0x48, //  #  #
	0x50, //  # # 
	0x30, //   ## 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xC0, // ##   

	// @1104 'z' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0xA0, // # #  
	0x20, //   #  
	0x48, //  #  #
	0xF0, // #### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @1116 '{' (3 pixels wide)
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x60, //  ##
	0x00, //    

	// @1128 '|' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  

	// @1140 '}' (3 pixels wide)
	0x00, //    
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 

	// @1152 '~' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x60, //  ##  
	0x98, // #  ##
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
};

// Character descriptors for FreeSerif 8pt
// { [Char width in bits], [Offset into freeSerif_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeSerif8ptCharDesc[] = {
	{1, s_FreeSerif8ptBitmaps + 0}, 		// !
	{3, s_FreeSerif8ptBitmaps + 12}, 		// "
	{5, s_FreeSerif8ptBitmaps + 24}, 		// #
	{4, s_FreeSerif8ptBitmaps + 36}, 		// $
	{8, s_FreeSerif8ptBitmaps + 48}, 		// %
	{8, s_FreeSerif8ptBitmaps + 60}, 		// &
	{1, s_FreeSerif8ptBitmaps + 72}, 		// '
	{3, s_FreeSerif8ptBitmaps + 84}, 		// (
	{3, s_FreeSerif8ptBitmaps + 96}, 		// )
	{4, s_FreeSerif8ptBitmaps + 108}, 		// *
	{5, s_FreeSerif8ptBitmaps + 120}, 		// +
	{1, s_FreeSerif8ptBitmaps + 132}, 		// ,
	{2, s_FreeSerif8ptBitmaps + 144}, 		// -
	{1, s_FreeSerif8ptBitmaps + 156}, 		// .
	{3, s_FreeSerif8ptBitmaps + 168}, 		// /
	{5, s_FreeSerif8ptBitmaps + 180}, 		// 0
	{3, s_FreeSerif8ptBitmaps + 192}, 		// 1
	{5, s_FreeSerif8ptBitmaps + 204}, 		// 2
	{4, s_FreeSerif8ptBitmaps + 216}, 		// 3
	{5, s_FreeSerif8ptBitmaps + 228}, 		// 4
	{5, s_FreeSerif8ptBitmaps + 240}, 		// 5
	{5, s_FreeSerif8ptBitmaps + 252}, 		// 6
	{5, s_FreeSerif8ptBitmaps + 264}, 		// 7
	{4, s_FreeSerif8ptBitmaps + 276}, 		// 8
	{5, s_FreeSerif8ptBitmaps + 288}, 		// 9
	{1, s_FreeSerif8ptBitmaps + 300}, 		// :
	{2, s_FreeSerif8ptBitmaps + 312}, 		// ;
	{6, s_FreeSerif8ptBitmaps + 324}, 		// <
	{6, s_FreeSerif8ptBitmaps + 336}, 		// =
	{6, s_FreeSerif8ptBitmaps + 348}, 		// >
	{4, s_FreeSerif8ptBitmaps + 360}, 		// ?
	{8, s_FreeSerif8ptBitmaps + 372}, 		// @
	{8, s_FreeSerif8ptBitmaps + 384}, 		// A
	{6, s_FreeSerif8ptBitmaps + 396}, 		// B
	{8, s_FreeSerif8ptBitmaps + 408}, 		// C
	{7, s_FreeSerif8ptBitmaps + 420}, 		// D
	{7, s_FreeSerif8ptBitmaps + 432}, 		// E
	{7, s_FreeSerif8ptBitmaps + 444}, 		// F
	{8, s_FreeSerif8ptBitmaps + 456}, 		// G
	{8, s_FreeSerif8ptBitmaps + 468}, 		// H
	{3, s_FreeSerif8ptBitmaps + 480}, 		// I
	{4, s_FreeSerif8ptBitmaps + 492}, 		// J
	{7, s_FreeSerif8ptBitmaps + 504}, 		// K
	{7, s_FreeSerif8ptBitmaps + 516}, 		// L
	{9, s_FreeSerif8ptBitmaps + 528}, 		// M
	{8, s_FreeSerif8ptBitmaps + 552}, 		// N
	{7, s_FreeSerif8ptBitmaps + 564}, 		// O
	{6, s_FreeSerif8ptBitmaps + 576}, 		// P
	{7, s_FreeSerif8ptBitmaps + 588}, 		// Q
	{7, s_FreeSerif8ptBitmaps + 600}, 		// R
	{4, s_FreeSerif8ptBitmaps + 612}, 		// S
	{7, s_FreeSerif8ptBitmaps + 624}, 		// T
	{8, s_FreeSerif8ptBitmaps + 636}, 		// U
	{8, s_FreeSerif8ptBitmaps + 648}, 		// V
	{10,s_FreeSerif8ptBitmaps + 660}, 		// W
	{8, s_FreeSerif8ptBitmaps + 684}, 		// X
	{7, s_FreeSerif8ptBitmaps + 696}, 		// Y
	{7, s_FreeSerif8ptBitmaps + 708}, 		// Z
	{2, s_FreeSerif8ptBitmaps + 720}, 		// [
	{3, s_FreeSerif8ptBitmaps + 732}, 		// '\'
	{2, s_FreeSerif8ptBitmaps + 744}, 		// ]
	{5, s_FreeSerif8ptBitmaps + 756}, 		// ^
	{6, s_FreeSerif8ptBitmaps + 768}, 		// _
	{1, s_FreeSerif8ptBitmaps + 780}, 		// `
	{5, s_FreeSerif8ptBitmaps + 792}, 		// a
	{5, s_FreeSerif8ptBitmaps + 804}, 		// b
	{4, s_FreeSerif8ptBitmaps + 816}, 		// c
	{5, s_FreeSerif8ptBitmaps + 828}, 		// d
	{4, s_FreeSerif8ptBitmaps + 840}, 		// e
	{4, s_FreeSerif8ptBitmaps + 852}, 		// f
	{7, s_FreeSerif8ptBitmaps + 864}, 		// g
	{6, s_FreeSerif8ptBitmaps + 876}, 		// h
	{3, s_FreeSerif8ptBitmaps + 888}, 		// i
	{3, s_FreeSerif8ptBitmaps + 900}, 		// j
	{6, s_FreeSerif8ptBitmaps + 912}, 		// k
	{3, s_FreeSerif8ptBitmaps + 924}, 		// l
	{9, s_FreeSerif8ptBitmaps + 936}, 		// m
	{6, s_FreeSerif8ptBitmaps + 960}, 		// n
	{5, s_FreeSerif8ptBitmaps + 972}, 		// o
	{5, s_FreeSerif8ptBitmaps + 984}, 		// p
	{6, s_FreeSerif8ptBitmaps + 996}, 		// q
	{4, s_FreeSerif8ptBitmaps + 1008}, 		// r
	{4, s_FreeSerif8ptBitmaps + 1020}, 		// s
	{3, s_FreeSerif8ptBitmaps + 1032}, 		// t
	{6, s_FreeSerif8ptBitmaps + 1044}, 		// u
	{5, s_FreeSerif8ptBitmaps + 1056}, 		// v
	{7, s_FreeSerif8ptBitmaps + 1068}, 		// w
	{5, s_FreeSerif8ptBitmaps + 1080}, 		// x
	{5, s_FreeSerif8ptBitmaps + 1092}, 		// y
	{5, s_FreeSerif8ptBitmaps + 1104}, 		// z
	{3, s_FreeSerif8ptBitmaps + 1116}, 		// {
	{1, s_FreeSerif8ptBitmaps + 1128}, 		// |
	{3, s_FreeSerif8ptBitmaps + 1140}, 		// }
	{5, s_FreeSerif8ptBitmaps + 1152}, 		// ~
};

// Font information for FreeSerif 8pt
const FontDesc_t iFontFreeSerif8pt = {
	0,
	10,
	12,
	{ .pCharDesc = s_FreeSerif8ptCharDesc }
};

