// 
//  Font data for FreeSerif Italic 8pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeSerif 8pt
static const uint8_t s_FreeSerifIta8ptBitmaps[] = {
	// @0 '!' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x00, //    
	0x80, // #  
	0x00, //    
	0x00, //    

	// @10 '"' (3 pixels wide)
	0x00, //    
	0xA0, // # #
	0xA0, // # #
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @20 '#' (6 pixels wide)
	0x28, //   # # 
	0x28, //   # # 
	0x7C, //  #####
	0x48, //  #  # 
	0x50, //  # #  
	0xF8, // ##### 
	0x50, //  # #  
	0xA0, // # #   
	0x00, //       
	0x00, //       

	// @30 '$' (4 pixels wide)
	0x30, //   ##
	0x50, //  # #
	0x60, //  ## 
	0x60, //  ## 
	0x30, //   ##
	0xB0, // # ##
	0xD0, // ## #
	0xE0, // ### 
	0x40, //  #  
	0x00, //     

	// @40 '%' (8 pixels wide)
	0x00, //         
	0x64, //  ##  #  
	0x98, // #  ##   
	0x9E, // #  #### 
	0xED, // ### ## #
	0x39, //   ###  #
	0x2B, //   # # ##
	0x0E, //     ### 
	0x00, //         
	0x00, //         

	// @50 '&' (7 pixels wide)
	0x00, //        
	0x0C, //     ## 
	0x14, //    # # 
	0x18, //    ##  
	0x76, //  ### ##
	0x8C, // #   ## 
	0x88, // #   #  
	0x76, //  ### ##
	0x00, //        
	0x00, //        

	// @60 ''' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @70 '(' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  

	// @80 ')' (3 pixels wide)
	0x00, //    
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x80, // #  
	0x00, //    

	// @90 '*' (4 pixels wide)
	0x00, //     
	0xD0, // ## #
	0x60, //  ## 
	0xD0, // ## #
	0x40, //  #  
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @100 '+' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @110 ',' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x40, //  #
	0x80, // # 
	0x00, //   

	// @120 '-' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @130 '.' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  

	// @140 '/' (5 pixels wide)
	0x00, //      
	0x08, //     #
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x40, //  #   
	0x40, //  #   
	0x80, // #    
	0x00, //      
	0x00, //      

	// @150 '0' (6 pixels wide)
	0x38, //   ### 
	0x64, //  ##  #
	0x44, //  #   #
	0xC4, // ##   #
	0x84, // #    #
	0x88, // #   # 
	0x98, // #  ## 
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @160 '1' (3 pixels wide)
	0x60, //  ##
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    

	// @170 '2' (5 pixels wide)
	0x30, //   ## 
	0x48, //  #  #
	0x08, //     #
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x48, //  #  #
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @180 '3' (5 pixels wide)
	0x30, //   ## 
	0x48, //  #  #
	0x10, //    # 
	0x70, //  ### 
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @190 '4' (5 pixels wide)
	0x00, //      
	0x08, //     #
	0x38, //   ###
	0x50, //  # # 
	0x90, // #  # 
	0xF8, // #####
	0x10, //    # 
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @200 '5' (6 pixels wide)
	0x00, //       
	0x1C, //    ###
	0x20, //   #   
	0x30, //   ##  
	0x08, //     # 
	0x08, //     # 
	0x10, //    #  
	0xE0, // ###   
	0x00, //       
	0x00, //       

	// @210 '6' (6 pixels wide)
	0x1C, //    ###
	0x30, //   ##  
	0x70, //  ###  
	0xC8, // ##  # 
	0x88, // #   # 
	0x88, // #   # 
	0x90, // #  #  
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @220 '7' (5 pixels wide)
	0x00, //      
	0xF8, // #####
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x40, //  #   
	0x40, //  #   
	0x80, // #    
	0x00, //      
	0x00, //      

	// @230 '8' (6 pixels wide)
	0x18, //    ## 
	0x24, //   #  #
	0x24, //   #  #
	0x18, //    ## 
	0x68, //  ## # 
	0x88, // #   # 
	0xC8, // ##  # 
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @240 '9' (5 pixels wide)
	0x70, //  ### 
	0xC8, // ##  #
	0x88, // #   #
	0x88, // #   #
	0x78, //  ####
	0x30, //   ## 
	0x60, //  ##  
	0x80, // #    
	0x00, //      
	0x00, //      

	// @250 ':' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   
	0x80, // # 
	0x00, //   
	0x00, //   

	// @260 ';' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   
	0x80, // # 
	0x80, // # 
	0x00, //   

	// @270 '<' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0xC0, // ##   
	0x80, // #    
	0x70, //  ### 
	0x08, //     #
	0x00, //      
	0x00, //      

	// @280 '=' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @290 '>' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xE0, // ###  
	0x18, //    ##
	0x18, //    ##
	0x60, //  ##  
	0x80, // #    
	0x00, //      
	0x00, //      

	// @300 '?' (3 pixels wide)
	0x00, //    
	0xE0, // ###
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x80, // #  
	0x00, //    
	0x80, // #  
	0x00, //    
	0x00, //    

	// @310 '@' (8 pixels wide)
	0x00, //         
	0x3C, //   ####  
	0x5F, //  # #####
	0xB5, // # ## # #
	0xA9, // # # #  #
	0xAB, // # # # ##
	0x76, //  ### ## 
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @320 'A' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x08, //     #  
	0x38, //   ###  
	0x28, //   # #  
	0x38, //   ###  
	0x44, //  #   # 
	0xCE, // ##  ###
	0x00, //        
	0x00, //        

	// @330 'B' (7 pixels wide)
	0x00, //        
	0x3E, //   #####
	0x22, //   #   #
	0x3C, //   #### 
	0x24, //   #  # 
	0x44, //  #   # 
	0x4C, //  #  ## 
	0xF8, // #####  
	0x00, //        
	0x00, //        

	// @340 'C' (8 pixels wide)
	0x00, //         
	0x1C, //    ###  
	0x63, //  ##   ##
	0xC0, // ##      
	0x80, // #       
	0x80, // #       
	0xC4, // ##   #  
	0x78, //  ####   
	0x00, //         
	0x00, //         

	// @350 'D' (8 pixels wide)
	0x00, //         
	0x3E, //   ##### 
	0x23, //   #   ##
	0x21, //   #    #
	0x21, //   #    #
	0x43, //  #    ##
	0x46, //  #   ## 
	0xF8, // #####   
	0x00, //         
	0x00, //         

	// @360 'E' (8 pixels wide)
	0x00, //         
	0x3F, //   ######
	0x22, //   #   # 
	0x24, //   #  #  
	0x3C, //   ####  
	0x48, //  #  #   
	0x44, //  #   #  
	0xFC, // ######  
	0x00, //         
	0x00, //         

	// @370 'F' (8 pixels wide)
	0x00, //         
	0x3F, //   ######
	0x22, //   #   # 
	0x24, //   #  #  
	0x3C, //   ####  
	0x48, //  #  #   
	0x40, //  #      
	0xE0, // ###     
	0x00, //         
	0x00, //         

	// @380 'G' (8 pixels wide)
	0x00, //         
	0x1D, //    ### #
	0x63, //  ##   ##
	0xC0, // ##      
	0x87, // #    ###
	0x82, // #     # 
	0x84, // #    #  
	0x7C, //  #####  
	0x00, //         
	0x00, //         

	// @390 'H' (8 pixels wide)
	0x00, //         
	0x33, //   ##  ##
	0x22, //   #   # 
	0x3E, //   ##### 
	0x22, //   #   # 
	0x42, //  #    # 
	0x44, //  #   #  
	0xEE, // ### ### 
	0x00, //         
	0x00, //         

	// @400 'I' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0xE0, // ### 
	0x00, //     
	0x00, //     

	// @410 'J' (5 pixels wide)
	0x00, //      
	0x18, //    ##
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @420 'K' (8 pixels wide)
	0x00, //         
	0x3F, //   ######
	0x22, //   #   # 
	0x2C, //   # ##  
	0x30, //   ##    
	0x48, //  #  #   
	0x4C, //  #  ##  
	0xEE, // ### ### 
	0x00, //         
	0x00, //         

	// @430 'L' (7 pixels wide)
	0x00, //        
	0x38, //   ###  
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x40, //  #     
	0x46, //  #   ##
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @440 'M' (10 pixels wide)
	0x00, 0x00, //           
	0x30, 0xC0, //   ##    ##
	0x33, 0x80, //   ##  ### 
	0x33, 0x00, //   ##  ##  
	0x55, 0x00, //  # # # #  
	0x59, 0x00, //  # ##  #  
	0x59, 0x00, //  # ##  #  
	0xF7, 0x00, // #### ###  
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @460 'N' (8 pixels wide)
	0x00, //         
	0x27, //   #  ###
	0x32, //   ##  # 
	0x32, //   ##  # 
	0x34, //   ## #  
	0x4C, //  #  ##  
	0x44, //  #   #  
	0xE4, // ###  #  
	0x00, //         
	0x00, //         

	// @470 'O' (7 pixels wide)
	0x00, //        
	0x1C, //    ### 
	0x62, //  ##   #
	0x42, //  #    #
	0x82, // #     #
	0x84, // #    # 
	0x8C, // #   ## 
	0x70, //  ###   
	0x00, //        
	0x00, //        

	// @480 'P' (7 pixels wide)
	0x00, //        
	0x3C, //   #### 
	0x22, //   #   #
	0x22, //   #   #
	0x3C, //   #### 
	0x40, //  #     
	0x40, //  #     
	0xE0, // ###    
	0x00, //        
	0x00, //        

	// @490 'Q' (7 pixels wide)
	0x00, //        
	0x1C, //    ### 
	0x62, //  ##   #
	0x42, //  #    #
	0x82, // #     #
	0x86, // #    ##
	0x84, // #    # 
	0x48, //  #  #  
	0x72, //  ###  #
	0xBC, // # #### 

	// @500 'R' (6 pixels wide)
	0x00, //       
	0x3C, //   ####
	0x24, //   #  #
	0x24, //   #  #
	0x38, //   ### 
	0x50, //  # #  
	0x48, //  #  # 
	0xEC, // ### ##
	0x00, //       
	0x00, //       

	// @510 'S' (6 pixels wide)
	0x00, //       
	0x38, //   ### 
	0x44, //  #   #
	0x60, //  ##   
	0x30, //   ##  
	0x88, // #   # 
	0x88, // #   # 
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @520 'T' (8 pixels wide)
	0x00, //         
	0x7F, //  #######
	0x92, // #  #  # 
	0x30, //   ##    
	0x20, //   #     
	0x20, //   #     
	0x20, //   #     
	0xF0, // ####    
	0x00, //         
	0x00, //         

	// @530 'U' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x42, //  #    # 
	0x42, //  #    # 
	0xC4, // ##   #  
	0x84, // #    #  
	0x8C, // #   ##  
	0x78, //  ####   
	0x00, //         
	0x00, //         

	// @540 'V' (7 pixels wide)
	0x00, //        
	0xE6, // ###  ##
	0x44, //  #   # 
	0x64, //  ##  # 
	0x28, //   # #  
	0x30, //   ##   
	0x30, //   ##   
	0x20, //   #    
	0x00, //        
	0x00, //        

	// @550 'W' (10 pixels wide)
	0x00, 0x00, //           
	0xEC, 0xC0, // ### ##  ##
	0x44, 0x80, //  #   #  # 
	0x5D, 0x00, //  # ### #  
	0x35, 0x00, //   ## # #  
	0x26, 0x00, //   #  ##   
	0x24, 0x00, //   #  #    
	0x04, 0x00, //      #    
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @570 'X' (8 pixels wide)
	0x00, //         
	0x77, //  ### ###
	0x24, //   #  #  
	0x18, //    ##   
	0x10, //    #    
	0x28, //   # #   
	0x48, //  #  #   
	0xCE, // ##  ### 
	0x00, //         
	0x00, //         

	// @580 'Y' (6 pixels wide)
	0x00, //       
	0xEC, // ### ##
	0x48, //  #  # 
	0x30, //   ##  
	0x20, //   #   
	0x20, //   #   
	0x20, //   #   
	0xE0, // ###   
	0x00, //       
	0x00, //       

	// @590 'Z' (7 pixels wide)
	0x00, //        
	0x3E, //   #####
	0x46, //  #   ##
	0x0C, //     ## 
	0x18, //    ##  
	0x30, //   ##   
	0x62, //  ##   #
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @600 '[' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0xE0, // ### 

	// @610 '\' (4 pixels wide)
	0x00, //     
	0x80, // #   
	0x40, //  #  
	0x40, //  #  
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x10, //    #
	0x00, //     
	0x00, //     

	// @620 ']' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x10, //    #
	0x10, //    #
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0xC0, // ##  

	// @630 '^' (4 pixels wide)
	0x00, //     
	0x20, //   # 
	0x60, //  ## 
	0x50, //  # #
	0x90, // #  #
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @640 '_' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       

	// @650 '`' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @660 'a' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x48, //  #  #
	0x90, // #  # 
	0x90, // #  # 
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @670 'b' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x40, //  #   
	0x58, //  # ##
	0x68, //  ## #
	0x48, //  #  #
	0x90, // #  # 
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @680 'c' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x40, //  #   
	0x80, // #    
	0x80, // #    
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @690 'd' (6 pixels wide)
	0x00, //       
	0x0C, //     ##
	0x08, //     # 
	0x38, //   ### 
	0x48, //  #  # 
	0x90, // #  #  
	0x90, // #  #  
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @700 'e' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x48, //  #  #
	0xB0, // # ## 
	0xC0, // ##   
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @710 'f' (7 pixels wide)
	0x06, //      ##
	0x08, //     #  
	0x10, //    #   
	0x3C, //   #### 
	0x10, //    #   
	0x10, //    #   
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0xC0, // ##     

	// @720 'g' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x48, //  #  # 
	0x48, //  #  # 
	0x30, //   ##  
	0x60, //  ##   
	0x98, // #  ## 
	0xF0, // ####  

	// @730 'h' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x20, //   #  
	0x58, //  # ##
	0x68, //  ## #
	0x48, //  #  #
	0x58, //  # ##
	0x98, // #  ##
	0x00, //      
	0x00, //      

	// @740 'i' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0xA0, // # #
	0xC0, // ## 
	0x00, //    
	0x00, //    

	// @750 'j' (5 pixels wide)
	0x00, //      
	0x08, //     #
	0x00, //      
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xC0, // ##   

	// @760 'k' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x20, //   #  
	0x58, //  # ##
	0x50, //  # # 
	0x60, //  ##  
	0xA0, // # #  
	0x98, // #  ##
	0x00, //      
	0x00, //      

	// @770 'l' (3 pixels wide)
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0xC0, // ## 
	0x00, //    
	0x00, //    

	// @780 'm' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0xDB, // ## ## ##
	0x6E, //  ## ### 
	0x4A, //  #  # # 
	0x52, //  # #  # 
	0x93, // #  #  ##
	0x00, //         
	0x00, //         

	// @790 'n' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xD8, // ## ##
	0x68, //  ## #
	0x48, //  #  #
	0x58, //  # ##
	0x98, // #  ##
	0x00, //      
	0x00, //      

	// @800 'o' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x48, //  #  #
	0x88, // #   #
	0x90, // #  # 
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @810 'p' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x2C, //   # ##
	0x34, //   ## #
	0x24, //   #  #
	0x28, //   # # 
	0x70, //  ###  
	0x40, //  #    
	0xC0, // ##    

	// @820 'q' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x48, //  #  #
	0x88, // #   #
	0xB0, // # ## 
	0xD0, // ## # 
	0x10, //    # 
	0x30, //   ## 

	// @830 'r' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x50, //  # #
	0x60, //  ## 
	0x40, //  #  
	0x40, //  #  
	0x80, // #   
	0x00, //     
	0x00, //     

	// @840 's' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x60, //  ## 
	0x50, //  # #
	0x20, //   # 
	0xA0, // # # 
	0x60, //  ## 
	0x00, //     
	0x00, //     

	// @850 't' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0xE0, // ###
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0xC0, // ## 
	0x00, //    
	0x00, //    

	// @860 'u' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xC8, // ##  #
	0x48, //  #  #
	0x70, //  ### 
	0xB0, // # ## 
	0xD8, // ## ##
	0x00, //      
	0x00, //      

	// @870 'v' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0xD0, // ## #
	0x50, //  # #
	0x60, //  ## 
	0x60, //  ## 
	0x40, //  #  
	0x00, //     
	0x00, //     

	// @880 'w' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xC2, // ##    #
	0x52, //  # #  #
	0x54, //  # # # 
	0x74, //  ### # 
	0x58, //  # ##  
	0x00, //        
	0x00, //        

	// @890 'x' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x68, //  ## #
	0x38, //   ###
	0x20, //   #  
	0x68, //  ## #
	0x90, // #  # 
	0x00, //      
	0x00, //      

	// @900 'y' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x44, //  #   #
	0x24, //   #  #
	0x28, //   # # 
	0x28, //   # # 
	0x10, //    #  
	0x20, //   #   
	0xC0, // ##    

	// @910 'z' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x78, //  ####
	0x90, // #  # 
	0x20, //   #  
	0x40, //  #   
	0xC0, // ##   
	0x30, //   ## 
	0x00, //      

	// @920 '{' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0xC0, // ## 

	// @930 '|' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  

	// @940 '}' (4 pixels wide)
	0x30, //   ##
	0x10, //    #
	0x10, //    #
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0x80, // #   

	// @950 '~' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0xC0, // ##  
	0x30, //   ##
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
};

// Character descriptors for FreeSerif 8pt
// { [Char width in bits], [Offset into freeSerif_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeSerifIta8ptCharDesc[] = {
	{3, s_FreeSerifIta8ptBitmaps + 0}, 		// !
	{3, s_FreeSerifIta8ptBitmaps + 10}, 		// "
	{6, s_FreeSerifIta8ptBitmaps + 20}, 		// #
	{4, s_FreeSerifIta8ptBitmaps + 30}, 		// $
	{8, s_FreeSerifIta8ptBitmaps + 40}, 		// %
	{7, s_FreeSerifIta8ptBitmaps + 50}, 		// &
	{1, s_FreeSerifIta8ptBitmaps + 60}, 		// '
	{3, s_FreeSerifIta8ptBitmaps + 70}, 		// (
	{3, s_FreeSerifIta8ptBitmaps + 80}, 		// )
	{4, s_FreeSerifIta8ptBitmaps + 90}, 		// *
	{5, s_FreeSerifIta8ptBitmaps + 100}, 		// +
	{2, s_FreeSerifIta8ptBitmaps + 110}, 		// ,
	{2, s_FreeSerifIta8ptBitmaps + 120}, 		// -
	{1, s_FreeSerifIta8ptBitmaps + 130}, 		// .
	{5, s_FreeSerifIta8ptBitmaps + 140}, 		// /
	{6, s_FreeSerifIta8ptBitmaps + 150}, 		// 0
	{3, s_FreeSerifIta8ptBitmaps + 160}, 		// 1
	{5, s_FreeSerifIta8ptBitmaps + 170}, 		// 2
	{5, s_FreeSerifIta8ptBitmaps + 180}, 		// 3
	{5, s_FreeSerifIta8ptBitmaps + 190}, 		// 4
	{6, s_FreeSerifIta8ptBitmaps + 200}, 		// 5
	{6, s_FreeSerifIta8ptBitmaps + 210}, 		// 6
	{5, s_FreeSerifIta8ptBitmaps + 220}, 		// 7
	{6, s_FreeSerifIta8ptBitmaps + 230}, 		// 8
	{5, s_FreeSerifIta8ptBitmaps + 240}, 		// 9
	{2, s_FreeSerifIta8ptBitmaps + 250}, 		// :
	{2, s_FreeSerifIta8ptBitmaps + 260}, 		// ;
	{5, s_FreeSerifIta8ptBitmaps + 270}, 		// <
	{5, s_FreeSerifIta8ptBitmaps + 280}, 		// =
	{5, s_FreeSerifIta8ptBitmaps + 290}, 		// >
	{3, s_FreeSerifIta8ptBitmaps + 300}, 		// ?
	{8, s_FreeSerifIta8ptBitmaps + 310}, 		// @
	{7, s_FreeSerifIta8ptBitmaps + 320}, 		// A
	{7, s_FreeSerifIta8ptBitmaps + 330}, 		// B
	{8, s_FreeSerifIta8ptBitmaps + 340}, 		// C
	{8, s_FreeSerifIta8ptBitmaps + 350}, 		// D
	{8, s_FreeSerifIta8ptBitmaps + 360}, 		// E
	{8, s_FreeSerifIta8ptBitmaps + 370}, 		// F
	{8, s_FreeSerifIta8ptBitmaps + 380}, 		// G
	{8, s_FreeSerifIta8ptBitmaps + 390}, 		// H
	{4, s_FreeSerifIta8ptBitmaps + 400}, 		// I
	{5, s_FreeSerifIta8ptBitmaps + 410}, 		// J
	{8, s_FreeSerifIta8ptBitmaps + 420}, 		// K
	{7, s_FreeSerifIta8ptBitmaps + 430}, 		// L
	{10,s_FreeSerifIta8ptBitmaps +  440}, 		// M
	{8, s_FreeSerifIta8ptBitmaps + 460}, 		// N
	{7, s_FreeSerifIta8ptBitmaps + 470}, 		// O
	{7, s_FreeSerifIta8ptBitmaps + 480}, 		// P
	{7, s_FreeSerifIta8ptBitmaps + 490}, 		// Q
	{6, s_FreeSerifIta8ptBitmaps + 500}, 		// R
	{6, s_FreeSerifIta8ptBitmaps + 510}, 		// S
	{8, s_FreeSerifIta8ptBitmaps + 520}, 		// T
	{8, s_FreeSerifIta8ptBitmaps + 530}, 		// U
	{7, s_FreeSerifIta8ptBitmaps + 540}, 		// V
	{10,s_FreeSerifIta8ptBitmaps +  550}, 		// W
	{8, s_FreeSerifIta8ptBitmaps + 570}, 		// X
	{6, s_FreeSerifIta8ptBitmaps + 580}, 		// Y
	{7, s_FreeSerifIta8ptBitmaps + 590}, 		// Z
	{4, s_FreeSerifIta8ptBitmaps + 600}, 		// [
	{4, s_FreeSerifIta8ptBitmaps + 610}, 		// '\'
	{4, s_FreeSerifIta8ptBitmaps + 620}, 		// ]
	{4, s_FreeSerifIta8ptBitmaps + 630}, 		// ^
	{6, s_FreeSerifIta8ptBitmaps + 640}, 		// _
	{1, s_FreeSerifIta8ptBitmaps + 650}, 		// `
	{5, s_FreeSerifIta8ptBitmaps + 660}, 		// a
	{5, s_FreeSerifIta8ptBitmaps + 670}, 		// b
	{5, s_FreeSerifIta8ptBitmaps + 680}, 		// c
	{6, s_FreeSerifIta8ptBitmaps + 690}, 		// d
	{5, s_FreeSerifIta8ptBitmaps + 700}, 		// e
	{7, s_FreeSerifIta8ptBitmaps + 710}, 		// f
	{6, s_FreeSerifIta8ptBitmaps + 720}, 		// g
	{5, s_FreeSerifIta8ptBitmaps + 730}, 		// h
	{3, s_FreeSerifIta8ptBitmaps + 740}, 		// i
	{5, s_FreeSerifIta8ptBitmaps + 750}, 		// j
	{5, s_FreeSerifIta8ptBitmaps + 760}, 		// k
	{3, s_FreeSerifIta8ptBitmaps + 770}, 		// l
	{8, s_FreeSerifIta8ptBitmaps + 780}, 		// m
	{5, s_FreeSerifIta8ptBitmaps + 790}, 		// n
	{5, s_FreeSerifIta8ptBitmaps + 800}, 		// o
	{6, s_FreeSerifIta8ptBitmaps + 810}, 		// p
	{5, s_FreeSerifIta8ptBitmaps + 820}, 		// q
	{4, s_FreeSerifIta8ptBitmaps + 830}, 		// r
	{4, s_FreeSerifIta8ptBitmaps + 840}, 		// s
	{3, s_FreeSerifIta8ptBitmaps + 850}, 		// t
	{5, s_FreeSerifIta8ptBitmaps + 860}, 		// u
	{4, s_FreeSerifIta8ptBitmaps + 870}, 		// v
	{7, s_FreeSerifIta8ptBitmaps + 880}, 		// w
	{5, s_FreeSerifIta8ptBitmaps + 890}, 		// x
	{6, s_FreeSerifIta8ptBitmaps + 900}, 		// y
	{5, s_FreeSerifIta8ptBitmaps + 910}, 		// z
	{3, s_FreeSerifIta8ptBitmaps + 920}, 		// {
	{1, s_FreeSerifIta8ptBitmaps + 930}, 		// |
	{4, s_FreeSerifIta8ptBitmaps + 940}, 		// }
	{4, s_FreeSerifIta8ptBitmaps + 950}, 		// ~
};

// Font information for FreeSerif 8pt
const FontDesc_t iFontFreeSerifIta8pt = {
	0,
	10,
	10,
	{ .pCharDesc = s_FreeSerifIta8ptCharDesc }
};

