// 
//  Font data for FreeSerif Bold 8pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeSerif 8pt
static const uint8_t s_FreeSerifBold8ptBitmaps[] = {
	// @0 '!' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   

	// @11 '"' (5 pixels wide)
	0x00, //      
	0xD8, // ## ##
	0xD8, // ## ##
	0x80, // #    
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @22 '#' (6 pixels wide)
	0x00, //       
	0x28, //   # # 
	0x28, //   # # 
	0xFC, // ######
	0x50, //  # #  
	0x50, //  # #  
	0xF8, // ##### 
	0x50, //  # #  
	0x50, //  # #  
	0x00, //       
	0x00, //       

	// @33 '$' (6 pixels wide)
	0x00, //       
	0x20, //   #   
	0xF8, // ##### 
	0xA8, // # # # 
	0xE0, // ###   
	0x38, //   ### 
	0xAC, // # # ##
	0xAC, // # # ##
	0x78, //  #### 
	0x20, //   #   
	0x00, //       

	// @44 '%' (9 pixels wide)
	0x00, 0x00, //          
	0x70, 0x00, //  ###     
	0xEE, 0x00, // ### ###  
	0xCC, 0x00, // ##  ##   
	0xDB, 0x80, // ## ## ###
	0x76, 0x80, //  ### ## #
	0x1E, 0x80, //    #### #
	0x16, 0x80, //    # ## #
	0x23, 0x00, //   #   ## 
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @66 '&' (9 pixels wide)
	0x00, 0x00, //          
	0x1C, 0x00, //    ###   
	0x36, 0x00, //   ## ##  
	0x34, 0x00, //   ## #   
	0x19, 0x80, //    ##  ##
	0x3D, 0x00, //   #### # 
	0xCF, 0x00, // ##  #### 
	0xE7, 0x00, // ###  ### 
	0x7B, 0x80, //  #### ###
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @88 ''' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @99 '(' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x40, //  # 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #

	// @110 ')' (3 pixels wide)
	0x00, //    
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0x80, // #  

	// @121 '*' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0xF8, // #####
	0x60, //  ##  
	0xF0, // #### 
	0x60, //  ##  
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @132 '+' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @143 ',' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x80, // # 

	// @154 '-' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @165 '.' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   

	// @176 '/' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x00, //    
	0x00, //    

	// @187 '0' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x50, //  # # 
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD0, // ## # 
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @198 '1' (4 pixels wide)
	0x00, //     
	0x20, //   # 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @209 '2' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x98, // #  ##
	0x18, //    ##
	0x18, //    ##
	0x30, //   ## 
	0x20, //   #  
	0x40, //  #   
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @220 '3' (6 pixels wide)
	0x00, //       
	0x3C, //   ####
	0x4C, //  #  ##
	0x08, //     # 
	0x18, //    ## 
	0x0C, //     ##
	0x0C, //     ##
	0x08, //     # 
	0xF0, // ####  
	0x00, //       
	0x00, //       

	// @231 '4' (5 pixels wide)
	0x00, //      
	0x10, //    # 
	0x30, //   ## 
	0xF0, // #### 
	0xB0, // # ## 
	0xB0, // # ## 
	0xF8, // #####
	0x30, //   ## 
	0x30, //   ## 
	0x00, //      
	0x00, //      

	// @242 '5' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x40, //  #   
	0x40, //  #   
	0x70, //  ### 
	0x38, //   ###
	0x08, //     #
	0x08, //     #
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @253 '6' (6 pixels wide)
	0x00, //       
	0x0C, //     ##
	0x30, //   ##  
	0x60, //  ##   
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       

	// @264 '7' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x88, // #   #
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @275 '8' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x70, //  ###  
	0x5C, //  # ###
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       

	// @286 '9' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0x78, //  ####
	0x30, //   ## 
	0x70, //  ### 
	0xC0, // ##   
	0x00, //      
	0x00, //      

	// @297 ':' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   

	// @308 ';' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x80, // # 

	// @319 '<' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x04, //      #
	0x18, //    ## 
	0x60, //  ##   
	0xC0, // ##    
	0x30, //   ##  
	0x0C, //     ##
	0x00, //       
	0x00, //       

	// @330 '=' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @341 '>' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xC0, // ##    
	0x30, //   ##  
	0x0C, //     ##
	0x18, //    ## 
	0x60, //  ##   
	0x80, // #     
	0x00, //       
	0x00, //       

	// @352 '?' (4 pixels wide)
	0x00, //     
	0xE0, // ### 
	0xB0, // # ##
	0x30, //   ##
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0x00, //     
	0xC0, // ##  
	0x00, //     
	0x00, //     

	// @363 '@' (8 pixels wide)
	0x00, //         
	0x3C, //   ####  
	0x62, //  ##   # 
	0xCB, // ##  # ##
	0xDD, // ## ### #
	0xD5, // ## # # #
	0xDE, // ## #### 
	0x60, //  ##     
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @374 'A' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x18, //    ##   
	0x18, //    ##   
	0x2C, //   # ##  
	0x4C, //  #  ##  
	0x7C, //  #####  
	0x46, //  #   ## 
	0xCF, // ##  ####
	0x00, //         
	0x00, //         

	// @385 'B' (7 pixels wide)
	0x00, //        
	0xFC, // ###### 
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x7C, //  ##### 
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x66, //  ##  ##
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @396 'C' (8 pixels wide)
	0x00, //         
	0x39, //   ###  #
	0x67, //  ##  ###
	0xC1, // ##     #
	0xC0, // ##      
	0xC0, // ##      
	0xC0, // ##      
	0x63, //  ##   ##
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @407 'D' (8 pixels wide)
	0x00, //         
	0xFC, // ######  
	0x66, //  ##  ## 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x66, //  ##  ## 
	0xFC, // ######  
	0x00, //         
	0x00, //         

	// @418 'E' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x62, //  ##   #
	0x64, //  ##  # 
	0x7C, //  ##### 
	0x64, //  ##  # 
	0x60, //  ##    
	0x62, //  ##   #
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @429 'F' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x62, //  ##   #
	0x64, //  ##  # 
	0x7C, //  ##### 
	0x64, //  ##  # 
	0x60, //  ##    
	0x60, //  ##    
	0xF0, // ####   
	0x00, //        
	0x00, //        

	// @440 'G' (9 pixels wide)
	0x00, 0x00, //          
	0x3D, 0x00, //   #### # 
	0x63, 0x00, //  ##   ## 
	0xC1, 0x00, // ##     # 
	0xC0, 0x00, // ##       
	0xC7, 0x80, // ##   ####
	0xC3, 0x00, // ##    ## 
	0x63, 0x00, //  ##   ## 
	0x3E, 0x00, //   #####  
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @462 'H' (9 pixels wide)
	0x00, 0x00, //          
	0xF7, 0x80, // #### ####
	0x63, 0x00, //  ##   ## 
	0x63, 0x00, //  ##   ## 
	0x7F, 0x00, //  ####### 
	0x63, 0x00, //  ##   ## 
	0x63, 0x00, //  ##   ## 
	0x63, 0x00, //  ##   ## 
	0xF7, 0x80, // #### ####
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @484 'I' (4 pixels wide)
	0x00, //     
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @495 'J' (6 pixels wide)
	0x00, //       
	0x3C, //   ####
	0x18, //    ## 
	0x18, //    ## 
	0x18, //    ## 
	0x18, //    ## 
	0x18, //    ## 
	0x18, //    ## 
	0xD8, // ## ## 
	0xF0, // ####  
	0x00, //       

	// @506 'K' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x62, //  ##   # 
	0x6C, //  ## ##  
	0x78, //  ####   
	0x6C, //  ## ##  
	0x66, //  ##  ## 
	0x67, //  ##  ###
	0xF7, // #### ###
	0x00, //         
	0x00, //         

	// @517 'L' (7 pixels wide)
	0x00, //        
	0xF0, // ####   
	0x60, //  ##    
	0x60, //  ##    
	0x60, //  ##    
	0x60, //  ##    
	0x60, //  ##    
	0x62, //  ##   #
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @528 'M' (11 pixels wide)
	0x00, 0x00, //            
	0xF0, 0xE0, // ####    ###
	0x71, 0xC0, //  ###   ### 
	0x71, 0xC0, //  ###   ### 
	0x5A, 0xC0, //  # ## # ## 
	0x5A, 0xC0, //  # ## # ## 
	0x4C, 0xC0, //  #  ##  ## 
	0x4C, 0xC0, //  #  ##  ## 
	0xE1, 0xE0, // ###    ####
	0x00, 0x00, //            
	0x00, 0x00, //            

	// @550 'N' (8 pixels wide)
	0x00, //         
	0xE7, // ###  ###
	0x72, //  ###  # 
	0x72, //  ###  # 
	0x5A, //  # ## # 
	0x4E, //  #  ### 
	0x46, //  #   ## 
	0x42, //  #    # 
	0xE0, // ###     
	0x00, //         
	0x00, //         

	// @561 'O' (8 pixels wide)
	0x00, //         
	0x3C, //   ####  
	0x66, //  ##  ## 
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0x66, //  ##  ## 
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @572 'P' (7 pixels wide)
	0x00, //        
	0xFC, // ###### 
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x7C, //  ##### 
	0x60, //  ##    
	0x60, //  ##    
	0xF0, // ####   
	0x00, //        
	0x00, //        

	// @583 'Q' (8 pixels wide)
	0x00, //         
	0x3C, //   ####  
	0x66, //  ##  ## 
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0x42, //  #    # 
	0x3C, //   ####  
	0x1C, //    ###  
	0x0F, //     ####

	// @594 'R' (8 pixels wide)
	0x00, //         
	0xFC, // ######  
	0x66, //  ##  ## 
	0x66, //  ##  ## 
	0x66, //  ##  ## 
	0x78, //  ####   
	0x6C, //  ## ##  
	0x6E, //  ## ### 
	0xF7, // #### ###
	0x00, //         
	0x00, //         

	// @605 'S' (6 pixels wide)
	0x00, //       
	0x74, //  ### #
	0xCC, // ##  ##
	0xC0, // ##    
	0x70, //  ###  
	0x3C, //   ####
	0x0C, //     ##
	0x8C, // #   ##
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @616 'T' (8 pixels wide)
	0x00, //         
	0xFF, // ########
	0x99, // #  ##  #
	0x18, //    ##   
	0x18, //    ##   
	0x18, //    ##   
	0x18, //    ##   
	0x18, //    ##   
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @627 'U' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @638 'V' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x62, //  ##   # 
	0x64, //  ##  #  
	0x34, //   ## #  
	0x34, //   ## #  
	0x18, //    ##   
	0x18, //    ##   
	0x10, //    #    
	0x00, //         
	0x00, //         

	// @649 'W' (10 pixels wide)
	0x00, 0x00, //           
	0xEE, 0xC0, // ### ### ##
	0xCC, 0x80, // ##  ##  # 
	0x44, 0x80, //  #   #  # 
	0x6E, 0x80, //  ## ### # 
	0x77, 0x00, //  ### ###  
	0x33, 0x00, //   ##  ##  
	0x33, 0x00, //   ##  ##  
	0x20, 0x00, //   #       
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @671 'X' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x64, //  ##  #  
	0x38, //   ###   
	0x18, //    ##   
	0x18, //    ##   
	0x2C, //   # ##  
	0x46, //  #   ## 
	0xEF, // ### ####
	0x00, //         
	0x00, //         

	// @682 'Y' (8 pixels wide)
	0x00, //         
	0xF7, // #### ###
	0x62, //  ##   # 
	0x34, //   ## #  
	0x34, //   ## #  
	0x18, //    ##   
	0x18, //    ##   
	0x18, //    ##   
	0x3C, //   ####  
	0x00, //         
	0x00, //         

	// @693 'Z' (7 pixels wide)
	0x00, //        
	0xFC, // ###### 
	0x88, // #   #  
	0x18, //    ##  
	0x30, //   ##   
	0x20, //   #    
	0x62, //  ##   #
	0xC4, // ##   # 
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @704 '[' (3 pixels wide)
	0x00, //    
	0xE0, // ###
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xE0, // ###

	// @715 '\' (3 pixels wide)
	0x00, //    
	0x80, // #  
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x00, //    
	0x00, //    

	// @726 ']' (3 pixels wide)
	0x00, //    
	0xE0, // ###
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0xE0, // ###

	// @737 '^' (4 pixels wide)
	0x00, //     
	0x20, //   # 
	0x60, //  ## 
	0x50, //  # #
	0x90, // #  #
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @748 '_' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######

	// @759 '`' (2 pixels wide)
	0x00, //   
	0x80, // # 
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @770 'a' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0xD8, // ## ##
	0x38, //   ###
	0xD8, // ## ##
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @781 'b' (6 pixels wide)
	0x00, //       
	0xE0, // ###   
	0x60, //  ##   
	0x60, //  ##   
	0x78, //  #### 
	0x6C, //  ## ##
	0x6C, //  ## ##
	0x6C, //  ## ##
	0x58, //  # ## 
	0x00, //       
	0x00, //       

	// @792 'c' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x78, //  ####
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @803 'd' (7 pixels wide)
	0x00, //        
	0x1C, //    ### 
	0x0C, //     ## 
	0x0C, //     ## 
	0x7C, //  ##### 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0x7E, //  ######
	0x00, //        
	0x00, //        

	// @814 'e' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x70, //  ### 
	0xF8, // #####
	0xC0, // ##   
	0xC8, // ##  #
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @825 'f' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @836 'g' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x60, //  ##  
	0xD8, // ## ##
	0x78, //  ####
	0xC0, // ##   
	0xF8, // #####
	0x88, // #   #
	0x70, //  ### 

	// @847 'h' (7 pixels wide)
	0x00, //        
	0xE0, // ###    
	0x60, //  ##    
	0x60, //  ##    
	0x7C, //  ##### 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @858 'i' (4 pixels wide)
	0x00, //     
	0x60, //  ## 
	0x00, //     
	0x00, //     
	0xE0, // ### 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @869 'j' (4 pixels wide)
	0x00, //     
	0x30, //   ##
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0xE0, // ### 

	// @880 'k' (7 pixels wide)
	0x00, //        
	0xE0, // ###    
	0x60, //  ##    
	0x60, //  ##    
	0x6C, //  ## ## 
	0x68, //  ## #  
	0x78, //  ####  
	0x6C, //  ## ## 
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @891 'l' (4 pixels wide)
	0x00, //     
	0xE0, // ### 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @902 'm' (10 pixels wide)
	0x00, 0x00, //           
	0x00, 0x00, //           
	0x00, 0x00, //           
	0x00, 0x00, //           
	0xFB, 0x80, // ##### ### 
	0x6D, 0x80, //  ## ## ## 
	0x6D, 0x80, //  ## ## ## 
	0x6D, 0x80, //  ## ## ## 
	0xFF, 0xC0, // ##########
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @924 'n' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0xFC, // ###### 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @935 'o' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       

	// @946 'p' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xF8, // ##### 
	0x6C, //  ## ##
	0x6C, //  ## ##
	0x6C, //  ## ##
	0x78, //  #### 
	0x60, //  ##   
	0xF0, // ####  

	// @957 'q' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x74, //  ### # 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0x7C, //  ##### 
	0x0C, //     ## 
	0x1E, //    ####

	// @968 'r' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x60, //  ##  
	0x60, //  ##  
	0x60, //  ##  
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @979 's' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x90, // #  #
	0xF0, // ####
	0x90, // #  #
	0xE0, // ### 
	0x00, //     
	0x00, //     

	// @990 't' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x20, //   # 
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x70, //  ###
	0x00, //     
	0x00, //     

	// @1001 'u' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0xFC, // ###### 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x7E, //  ######
	0x00, //        
	0x00, //        

	// @1012 'v' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xE8, // ### #
	0x48, //  #  #
	0x70, //  ### 
	0x30, //   ## 
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @1023 'w' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0xFF, // ########
	0x4A, //  #  # # 
	0x7E, //  ###### 
	0x24, //   #  #  
	0x24, //   #  #  
	0x00, //         
	0x00, //         

	// @1034 'x' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x70, //  ### 
	0x30, //   ## 
	0x58, //  # ##
	0xD8, // ## ##
	0x00, //      
	0x00, //      

	// @1045 'y' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xE8, // ### #
	0x68, //  ## #
	0x30, //   ## 
	0x30, //   ## 
	0x20, //   #  
	0x20, //   #  
	0xC0, // ##   

	// @1056 'z' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x90, // #  # 
	0x30, //   ## 
	0x68, //  ## #
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @1067 '{' (4 pixels wide)
	0x30, //   ##
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xC0, // ##  
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x30, //   ##

	// @1078 '|' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  

	// @1089 '}' (4 pixels wide)
	0xC0, // ##  
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x30, //   ##
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xC0, // ##  

	// @1100 '~' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0xC0, // ##  
	0x30, //   ##
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
};

// Character descriptors for FreeSerif 8pt
// { [Char width in bits], [Offset into freeSerif_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeSerifBold8ptCharDesc[] = {
	{2, s_FreeSerifBold8ptBitmaps + 0}, 		// !
	{5, s_FreeSerifBold8ptBitmaps + 11}, 		// "
	{6, s_FreeSerifBold8ptBitmaps + 22}, 		// #
	{6, s_FreeSerifBold8ptBitmaps + 33}, 		// $
	{9, s_FreeSerifBold8ptBitmaps + 44}, 		// %
	{9, s_FreeSerifBold8ptBitmaps + 66}, 		// &
	{2, s_FreeSerifBold8ptBitmaps + 88}, 		// '
	{3, s_FreeSerifBold8ptBitmaps + 99}, 		// (
	{3, s_FreeSerifBold8ptBitmaps + 110}, 		// )
	{5, s_FreeSerifBold8ptBitmaps + 121}, 		// *
	{5, s_FreeSerifBold8ptBitmaps + 132}, 		// +
	{2, s_FreeSerifBold8ptBitmaps + 143}, 		// ,
	{2, s_FreeSerifBold8ptBitmaps + 154}, 		// -
	{2, s_FreeSerifBold8ptBitmaps + 165}, 		// .
	{3, s_FreeSerifBold8ptBitmaps + 176}, 		// /
	{5, s_FreeSerifBold8ptBitmaps + 187}, 		// 0
	{4, s_FreeSerifBold8ptBitmaps + 198}, 		// 1
	{5, s_FreeSerifBold8ptBitmaps + 209}, 		// 2
	{6, s_FreeSerifBold8ptBitmaps + 220}, 		// 3
	{5, s_FreeSerifBold8ptBitmaps + 231}, 		// 4
	{5, s_FreeSerifBold8ptBitmaps + 242}, 		// 5
	{6, s_FreeSerifBold8ptBitmaps + 253}, 		// 6
	{5, s_FreeSerifBold8ptBitmaps + 264}, 		// 7
	{6, s_FreeSerifBold8ptBitmaps + 275}, 		// 8
	{5, s_FreeSerifBold8ptBitmaps + 286}, 		// 9
	{2, s_FreeSerifBold8ptBitmaps + 297}, 		// :
	{2, s_FreeSerifBold8ptBitmaps + 308}, 		// ;
	{6, s_FreeSerifBold8ptBitmaps + 319}, 		// <
	{6, s_FreeSerifBold8ptBitmaps + 330}, 		// =
	{6, s_FreeSerifBold8ptBitmaps + 341}, 		// >
	{4, s_FreeSerifBold8ptBitmaps + 352}, 		// ?
	{8, s_FreeSerifBold8ptBitmaps + 363}, 		// @
	{8, s_FreeSerifBold8ptBitmaps + 374}, 		// A
	{7, s_FreeSerifBold8ptBitmaps + 385}, 		// B
	{8, s_FreeSerifBold8ptBitmaps + 396}, 		// C
	{8, s_FreeSerifBold8ptBitmaps + 407}, 		// D
	{7, s_FreeSerifBold8ptBitmaps + 418}, 		// E
	{7, s_FreeSerifBold8ptBitmaps + 429}, 		// F
	{9, s_FreeSerifBold8ptBitmaps + 440}, 		// G
	{9, s_FreeSerifBold8ptBitmaps + 462}, 		// H
	{4, s_FreeSerifBold8ptBitmaps + 484}, 		// I
	{6, s_FreeSerifBold8ptBitmaps + 495}, 		// J
	{8, s_FreeSerifBold8ptBitmaps + 506}, 		// K
	{7, s_FreeSerifBold8ptBitmaps + 517}, 		// L
	{11,s_FreeSerifBold8ptBitmaps +  528}, 		// M
	{8, s_FreeSerifBold8ptBitmaps + 550}, 		// N
	{8, s_FreeSerifBold8ptBitmaps + 561}, 		// O
	{7, s_FreeSerifBold8ptBitmaps + 572}, 		// P
	{8, s_FreeSerifBold8ptBitmaps + 583}, 		// Q
	{8, s_FreeSerifBold8ptBitmaps + 594}, 		// R
	{6, s_FreeSerifBold8ptBitmaps + 605}, 		// S
	{8, s_FreeSerifBold8ptBitmaps + 616}, 		// T
	{8, s_FreeSerifBold8ptBitmaps + 627}, 		// U
	{8, s_FreeSerifBold8ptBitmaps + 638}, 		// V
	{10,s_FreeSerifBold8ptBitmaps +  649}, 		// W
	{8, s_FreeSerifBold8ptBitmaps + 671}, 		// X
	{8, s_FreeSerifBold8ptBitmaps + 682}, 		// Y
	{7, s_FreeSerifBold8ptBitmaps + 693}, 		// Z
	{3, s_FreeSerifBold8ptBitmaps + 704}, 		// [
	{3, s_FreeSerifBold8ptBitmaps + 715}, 		// '\'
	{3, s_FreeSerifBold8ptBitmaps + 726}, 		// ]
	{4, s_FreeSerifBold8ptBitmaps + 737}, 		// ^
	{6, s_FreeSerifBold8ptBitmaps + 748}, 		// _
	{2, s_FreeSerifBold8ptBitmaps + 759}, 		// `
	{5, s_FreeSerifBold8ptBitmaps + 770}, 		// a
	{6, s_FreeSerifBold8ptBitmaps + 781}, 		// b
	{5, s_FreeSerifBold8ptBitmaps + 792}, 		// c
	{7, s_FreeSerifBold8ptBitmaps + 803}, 		// d
	{5, s_FreeSerifBold8ptBitmaps + 814}, 		// e
	{4, s_FreeSerifBold8ptBitmaps + 825}, 		// f
	{5, s_FreeSerifBold8ptBitmaps + 836}, 		// g
	{7, s_FreeSerifBold8ptBitmaps + 847}, 		// h
	{4, s_FreeSerifBold8ptBitmaps + 858}, 		// i
	{4, s_FreeSerifBold8ptBitmaps + 869}, 		// j
	{7, s_FreeSerifBold8ptBitmaps + 880}, 		// k
	{4, s_FreeSerifBold8ptBitmaps + 891}, 		// l
	{10,s_FreeSerifBold8ptBitmaps +  902}, 		// m
	{7, s_FreeSerifBold8ptBitmaps + 924}, 		// n
	{6, s_FreeSerifBold8ptBitmaps + 935}, 		// o
	{6, s_FreeSerifBold8ptBitmaps + 946}, 		// p
	{7, s_FreeSerifBold8ptBitmaps + 957}, 		// q
	{5, s_FreeSerifBold8ptBitmaps + 968}, 		// r
	{4, s_FreeSerifBold8ptBitmaps + 979}, 		// s
	{4, s_FreeSerifBold8ptBitmaps + 990}, 		// t
	{7, s_FreeSerifBold8ptBitmaps + 1001}, 		// u
	{5, s_FreeSerifBold8ptBitmaps + 1012}, 		// v
	{8, s_FreeSerifBold8ptBitmaps + 1023}, 		// w
	{5, s_FreeSerifBold8ptBitmaps + 1034}, 		// x
	{5, s_FreeSerifBold8ptBitmaps + 1045}, 		// y
	{5, s_FreeSerifBold8ptBitmaps + 1056}, 		// z
	{4, s_FreeSerifBold8ptBitmaps + 1067}, 		// {
	{1, s_FreeSerifBold8ptBitmaps + 1078}, 		// |
	{4, s_FreeSerifBold8ptBitmaps + 1089}, 		// }
	{4, s_FreeSerifBold8ptBitmaps + 1100}, 		// ~
};

// Font information for FreeSerif 8pt
const FontDesc_t iFontFreeSerifBold8pt = {
	FONT_TYPE_VAR_WIDTH,
	11,
	11,
	{ .pCharDesc = s_FreeSerifBold8ptCharDesc }
};

