/**-------------------------------------------------------------------------
@file	board.h

@brief	Board specific definitions

This file contains all I/O definitions for a specific board for the
application firmware.  This files should be located in each project and
modified to suit the need for the application use case.

@author	Hoang Nguyen Hoan
@date	Nov. 16, 2016

@license

Copyright (c) 2016, I-SYST inc., all rights reserved

Permission to use, copy, modify, and distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright
notice and this permission notice appear in all copies, and none of the
names : I-SYST or its contributors may be used to endorse or
promote products derived from this software without specific prior written
permission.

For info or contributing contact : hnhoan at i-syst dot com

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

----------------------------------------------------------------------------*/

#ifndef __BOARD_H__
#define __BOARD_H__

#include "blystnano_boards.h"

// Uncomment this to set custom board oscillator
// Default library setting is :
// #define MCU_OSC	{{OSC_TYPE_XTAL, 32000000, 20}, {OSC_TYPE_XTAL, 32768, 20}, false}

//#define NORDIC_DK

#ifdef NORDIC_DK
// Nordic DK PCA10040 board

#define BUT1_PORT			0
#define BUT1_PIN			13
#define BUT2_PORT			0
#define BUT2_PIN			14

#define BUT1_PORT			0
#define BUT1_PIN			13
#define BUT2_PORT			0
#define BUT2_PIN			14

#define LED1_PORT			BLUEPYRO_CR24S_M3225_LED1_PORT
#define LED1_PIN			BLUEPYRO_CR24S_M3225_LED1_PIN
#define LED1_ACTIVE			BLUEPYRO_CR24S_M3225_LED1_ACTIVE
#define LED2_PORT			BLUEPYRO_CR24S_M3225_LED2R_PORT
#define LED2_PIN			BLUEPYRO_CR24S_M3225_LED2R_PIN
#define LED2_ACTIVE			BLUEPYRO_CR24S_M3225_LED2R_ACTIVE
#define LED3_PORT			BLUEPYRO_CR24S_M3225_LED2G_PORT
#define LED3_PIN			BLUEPYRO_CR24S_M3225_LED2G_PIN
#define LED3_ACTIVE			BLUEPYRO_CR24S_M3225_LED2G_ACTIVE
#define LED4_PORT			BLUEPYRO_CR24S_M3225_LED2B_PORT
#define LED4_PIN			BLUEPYRO_CR24S_M3225_LED2B_PIN
#define LED4_ACTIVE			BLUEPYRO_CR24S_M3225_LED2B_ACTIVE

#define UART_RX_PORT		0
#define UART_RX_PIN			8
#define UART_RX_PINOP		1	//
#define UART_TX_PORT		0
#define UART_TX_PIN			6//7
#define UART_TX_PINOP		0
#define UART_CTS_PORT		0
#define UART_CTS_PIN		7//12
#define UART_CTS_PINOP		0
#define UART_RTS_PORT		0
#define UART_RTS_PIN		5//11
#define UART_RTS_PINOP		0

#else
// BLYST-NANO-DK board
#define BUT1_PORT			BLYST_NANO_DK_BUT1_PORT
#define BUT1_PIN			BLYST_NANO_DK_BUT1_PIN
#define BUT2_PORT			BLYST_NANO_DK_BUT2_PORT
#define BUT2_PIN			BLYST_NANO_DK_BUT2_PIN


#define LED1_PORT			BLYST_NANO_DK_LEDR_PORT
#define LED1_PIN			BLYST_NANO_DK_LEDR_PIN
#define LED1_ACTIVE			BLYST_NANO_DK_LEDR_LOGIC
#define LED2_PORT			BLYST_NANO_DK_LEDG_PORT
#define LED2_PIN			BLYST_NANO_DK_LEDG_PIN
#define LED2_ACTIVE			BLYST_NANO_DK_LEDG_LOGIC
#define LED3_PORT			BLYST_NANO_DK_LEDB_PORT
#define LED3_PIN			BLYST_NANO_DK_LEDB_PIN
#define LED3_ACTIVE			BLYST_NANO_DK_LEDB_LOGIC

#define CONNECT_LED_PORT	BLYST_NANO_DK_LED1_PORT
#define CONNECT_LED_PIN		BLYST_NANO_DK_LED1_PIN
#define CONNECT_LED_LOGIC	BLYST_NANO_DK_LED1_LOGIC

#define UART_RX_PORT		BLYST_NANO_DK_UART_RX_PORT
#define UART_RX_PIN			BLYST_NANO_DK_UART_RX_PIN
#define UART_RX_PINOP		BLYST_NANO_DK_UART_RX_PINOP
#define UART_TX_PORT		BLYST_NANO_DK_UART_TX_PORT
#define UART_TX_PIN			BLYST_NANO_DK_UART_TX_PIN
#define UART_TX_PINOP		BLYST_NANO_DK_UART_TX_PINOP
#define UART_CTS_PORT		BLYST_NANO_DK_UART_CTS_PORT
#define UART_CTS_PIN		BLYST_NANO_DK_UART_CTS_PIN
#define UART_CTS_PINOP		BLYST_NANO_DK_UART_CTS_PINOP
#define UART_RTS_PORT		BLYST_NANO_DK_UART_RTS_PORT
#define UART_RTS_PIN		BLYST_NANO_DK_UART_RTS_PIN
#define UART_RTS_PINOP		BLYST_NANO_DK_UART_RTS_PINOP


#endif

#define BUTTON_PINS		{ \
	{BUT1_PORT, BUT1_PIN, BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BUT2_PORT, BUT2_PIN, BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

#define LED_PINS	{ \
	{LED1_PORT, LED1_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{LED2_PORT, LED2_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{LED3_PORT, LED3_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

#define UART_PINS			{ \
	{UART_RX_PORT, UART_RX_PIN, UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{UART_TX_PORT, UART_TX_PIN, UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{UART_CTS_PORT, UART_CTS_PIN, UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},\
	{UART_RTS_PORT, UART_RTS_PIN, UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},}

#endif // __BOARD_H__

