// 
//  Font data for FreeMono 8pt
// https://savannah.gnu.org/projects/freefont/
// 
// Font bitmap generated by
// http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeMono 8pt
static const uint8_t s_FreeMonoBold8ptBitmaps[] = {
	// @0 '!' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  

	// @10 '"' (3 pixels wide)
	0x00, //    
	0x00, //    
	0xA0, // # #
	0xA0, // # #
	0xA0, // # #
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @20 '#' (5 pixels wide)
	0x00, //      
	0x50, //  # # 
	0x50, //  # # 
	0xF8, // #####
	0x50, //  # # 
	0xF8, // #####
	0x50, //  # # 
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @30 '$' (5 pixels wide)
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xD0, // ## # 
	0xF0, // #### 
	0x88, // #   #
	0x70, //  ### 
	0x20, //   #  
	0x20, //   #  
	0x00, //      

	// @40 '%' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x90, // #  # 
	0x60, //  ##  
	0x38, //   ###
	0xD8, // ## ##
	0x28, //   # #
	0x18, //    ##
	0x00, //      
	0x00, //      

	// @50 '&' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x70, //  ### 
	0x40, //  #   
	0x40, //  #   
	0xE8, // ### #
	0xB0, // # ## 
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @60 ''' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @70 '(' (2 pixels wide)
	0x00, //   
	0x40, //  #
	0x40, //  #
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x40, //  #
	0x40, //  #

	// @80 ')' (2 pixels wide)
	0x00, //   
	0x80, // # 
	0x80, // # 
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x80, // # 
	0x80, // # 

	// @90 '*' (5 pixels wide)
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x70, //  ### 
	0x50, //  # # 
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @100 '+' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @110 ',' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x80, // # 
	0x80, // # 

	// @120 '-' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       

	// @130 '.' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  

	// @140 '/' (5 pixels wide)
	0x08, //     #
	0x10, //    # 
	0x10, //    # 
	0x30, //   ## 
	0x20, //   #  
	0x60, //  ##  
	0x40, //  #   
	0xC0, // ##   
	0x80, // #    
	0x00, //      

	// @150 '0' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x88, // #   #
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @160 '1' (4 pixels wide)
	0x00, //     
	0x60, //  ## 
	0xE0, // ### 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x70, //  ###
	0x00, //     
	0x00, //     

	// @170 '2' (4 pixels wide)
	0x00, //     
	0x60, //  ## 
	0x90, // #  #
	0x10, //    #
	0x30, //   ##
	0x20, //   # 
	0x40, //  #  
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @180 '3' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x08, //     #
	0x08, //     #
	0x30, //   ## 
	0x08, //     #
	0x08, //     #
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @190 '4' (5 pixels wide)
	0x00, //      
	0x30, //   ## 
	0x30, //   ## 
	0x50, //  # # 
	0xD0, // ## # 
	0xF8, // #####
	0x10, //    # 
	0x38, //   ###
	0x00, //      
	0x00, //      

	// @200 '5' (5 pixels wide)
	0x00, //      
	0xF0, // #### 
	0x80, // #    
	0xF0, // #### 
	0x88, // #   #
	0x08, //     #
	0x08, //     #
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @210 '6' (5 pixels wide)
	0x00, //      
	0x38, //   ###
	0x60, //  ##  
	0x40, //  #   
	0xB0, // # ## 
	0xC8, // ##  #
	0x48, //  #  #
	0x70, //  ### 
	0x00, //      
	0x00, //      

	// @220 '7' (5 pixels wide)
	0x00, //      
	0xF8, // #####
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      

	// @230 '8' (4 pixels wide)
	0x00, //     
	0x60, //  ## 
	0x90, // #  #
	0x90, // #  #
	0x60, //  ## 
	0x90, // #  #
	0x90, // #  #
	0x60, //  ## 
	0x00, //     
	0x00, //     

	// @240 '9' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x90, // #  # 
	0x98, // #  ##
	0x78, //  ####
	0x10, //    # 
	0x30, //   ## 
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @250 ':' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  

	// @260 ';' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x80, // # 
	0x80, // # 

	// @270 '<' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x08, //     #
	0x38, //   ###
	0xE0, // ###  
	0x60, //  ##  
	0x18, //    ##
	0x00, //      
	0x00, //      
	0x00, //      

	// @280 '=' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       

	// @290 '>' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0xC0, // ##  
	0x30, //   ##
	0x30, //   ##
	0xC0, // ##  
	0x00, //     
	0x00, //     
	0x00, //     

	// @300 '?' (5 pixels wide)
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0x88, // #   #
	0x18, //    ##
	0x20, //   #  
	0x00, //      
	0x40, //  #   
	0x00, //      
	0x00, //      

	// @310 '@' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x90, // #  # 
	0x90, // #  # 
	0xB0, // # ## 
	0xD0, // ## # 
	0xF8, // #####
	0x80, // #    
	0x90, // #  # 
	0x70, //  ### 

	// @320 'A' (7 pixels wide)
	0x00, //        
	0x70, //  ###   
	0x28, //   # #  
	0x28, //   # #  
	0x28, //   # #  
	0x7C, //  ##### 
	0x44, //  #   # 
	0xEE, // ### ###
	0x00, //        
	0x00, //        

	// @330 'B' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x78, //  #### 
	0x44, //  #   #
	0x44, //  #   #
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @340 'C' (6 pixels wide)
	0x00, //       
	0x7C, //  #####
	0xC4, // ##   #
	0x80, // #     
	0x80, // #     
	0x80, // #     
	0xC0, // ##    
	0x7C, //  #####
	0x00, //       
	0x00, //       

	// @350 'D' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0x4C, //  #  ##
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @360 'E' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x44, //  #   #
	0x50, //  # #  
	0x70, //  ###  
	0x50, //  # #  
	0x44, //  #   #
	0xFC, // ######
	0x00, //       
	0x00, //       

	// @370 'F' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x44, //  #   #
	0x50, //  # #  
	0x70, //  ###  
	0x50, //  # #  
	0x40, //  #    
	0xE0, // ###   
	0x00, //       
	0x00, //       

	// @380 'G' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0xC4, // ##   # 
	0x80, // #      
	0x80, // #      
	0x8E, // #   ###
	0xC4, // ##   # 
	0x7C, //  ##### 
	0x00, //        
	0x00, //        

	// @390 'H' (8 pixels wide)
	0x00, //         
	0x66, //  ##  ## 
	0x22, //   #   # 
	0x22, //   #   # 
	0x3E, //   ##### 
	0x22, //   #   # 
	0x22, //   #   # 
	0xE7, // ###  ###
	0x00, //         
	0x00, //         

	// @400 'I' (3 pixels wide)
	0x00, //    
	0xE0, // ###
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xE0, // ###
	0x00, //    
	0x00, //    

	// @410 'J' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x90, // #  # 
	0x90, // #  # 
	0xE0, // ###  
	0x00, //      
	0x00, //      

	// @420 'K' (7 pixels wide)
	0x00, //        
	0xEC, // ### ## 
	0x48, //  #  #  
	0x70, //  ###   
	0x70, //  ###   
	0x48, //  #  #  
	0x48, //  #  #  
	0xE6, // ###  ##
	0x00, //        
	0x00, //        

	// @430 'L' (5 pixels wide)
	0x00, //      
	0xE0, // ###  
	0x40, //  #   
	0x40, //  #   
	0x40, //  #   
	0x48, //  #  #
	0x48, //  #  #
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @440 'M' (8 pixels wide)
	0x00, //         
	0xC3, // ##    ##
	0x66, //  ##  ## 
	0x66, //  ##  ## 
	0x7E, //  ###### 
	0x5A, //  # ## # 
	0x5A, //  # ## # 
	0xE7, // ###  ###
	0x00, //         
	0x00, //         

	// @450 'N' (7 pixels wide)
	0x00, //        
	0xCE, // ##  ###
	0x64, //  ##  # 
	0x74, //  ### # 
	0x54, //  # # # 
	0x5C, //  # ### 
	0x4C, //  #  ## 
	0xE4, // ###  # 
	0x00, //        
	0x00, //        

	// @460 'O' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0x4C, //  #  ##
	0x84, // #    #
	0x84, // #    #
	0x84, // #    #
	0x48, //  #  # 
	0x78, //  #### 
	0x00, //       
	0x00, //       

	// @470 'P' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x78, //  #### 
	0x40, //  #    
	0x40, //  #    
	0xE0, // ###   
	0x00, //       
	0x00, //       

	// @480 'Q' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0x48, //  #  # 
	0x84, // #    #
	0x84, // #    #
	0x84, // #    #
	0xC8, // ##  # 
	0x78, //  #### 
	0x64, //  ##  #
	0x7C, //  #####

	// @490 'R' (6 pixels wide)
	0x00, //       
	0xF0, // ####  
	0x48, //  #  # 
	0x48, //  #  # 
	0x70, //  ###  
	0x58, //  # ## 
	0x48, //  #  # 
	0xEC, // ### ##
	0x00, //       
	0x00, //       

	// @500 'S' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x88, // #   #
	0x80, // #    
	0xE0, // ###  
	0x18, //    ##
	0x88, // #   #
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @510 'T' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x94, // #  # #
	0x94, // #  # #
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x38, //   ### 
	0x00, //       
	0x00, //       

	// @520 'U' (7 pixels wide)
	0x00, //        
	0xEE, // ### ###
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x38, //   ###  
	0x00, //        
	0x00, //        

	// @530 'V' (7 pixels wide)
	0x00, //        
	0xEE, // ### ###
	0x44, //  #   # 
	0x6C, //  ## ## 
	0x28, //   # #  
	0x28, //   # #  
	0x38, //   ###  
	0x10, //    #   
	0x00, //        
	0x00, //        

	// @540 'W' (7 pixels wide)
	0x00, //        
	0xEE, // ### ###
	0xC4, // ##   # 
	0x54, //  # # # 
	0x74, //  ### # 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x6C, //  ## ## 
	0x00, //        
	0x00, //        

	// @550 'X' (6 pixels wide)
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x78, //  #### 
	0x30, //   ##  
	0x78, //  #### 
	0x48, //  #  # 
	0xCC, // ##  ##
	0x00, //       
	0x00, //       

	// @560 'Y' (6 pixels wide)
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x28, //   # # 
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x38, //   ### 
	0x00, //       
	0x00, //       

	// @570 'Z' (5 pixels wide)
	0x00, //      
	0xF0, // #### 
	0x90, // #  # 
	0xA0, // # #  
	0x20, //   #  
	0x48, //  #  #
	0x88, // #   #
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @580 '[' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0xC0, // ##

	// @590 '\' (5 pixels wide)
	0x80, // #    
	0x80, // #    
	0x40, //  #   
	0x40, //  #   
	0x20, //   #  
	0x20, //   #  
	0x30, //   ## 
	0x10, //    # 
	0x18, //    ##
	0x00, //      

	// @600 ']' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0xC0, // ##

	// @610 '^' (5 pixels wide)
	0x20, //   #  
	0x60, //  ##  
	0xD0, // ## # 
	0x98, // #  ##
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @620 '_' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0xFE, // #######

	// @630 '`' (2 pixels wide)
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @640 'a' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0x08, //     # 
	0x78, //  #### 
	0x88, // #   # 
	0xFC, // ######
	0x00, //       
	0x00, //       

	// @650 'b' (6 pixels wide)
	0x00, //       
	0xC0, // ##    
	0x40, //  #    
	0x78, //  #### 
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @660 'c' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x78, //  ####
	0x88, // #   #
	0x80, // #    
	0x88, // #   #
	0x78, //  ####
	0x00, //      
	0x00, //      

	// @670 'd' (7 pixels wide)
	0x00, //        
	0x0C, //     ## 
	0x04, //      # 
	0x7C, //  ##### 
	0xC4, // ##   # 
	0x84, // #    # 
	0x84, // #    # 
	0x7E, //  ######
	0x00, //        
	0x00, //        

	// @680 'e' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0x44, //  #   #
	0xFC, // ######
	0x40, //  #    
	0x7C, //  #####
	0x00, //       
	0x00, //       

	// @690 'f' (5 pixels wide)
	0x00, //      
	0x78, //  ####
	0x40, //  #   
	0xF0, // #### 
	0x40, //  #   
	0x40, //  #   
	0x40, //  #   
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @700 'g' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0x84, // #    # 
	0x84, // #    # 
	0xCC, // ##  ## 
	0x7C, //  ##### 
	0x04, //      # 
	0x38, //   ###  

	// @710 'h' (7 pixels wide)
	0x00, //        
	0xC0, // ##     
	0x40, //  #     
	0x7C, //  ##### 
	0x64, //  ##  # 
	0x44, //  #   # 
	0x44, //  #   # 
	0xC6, // ##   ##
	0x00, //        
	0x00, //        

	// @720 'i' (5 pixels wide)
	0x00, //      
	0x20, //   #  
	0x00, //      
	0x60, //  ##  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @730 'j' (4 pixels wide)
	0x00, //     
	0x20, //   # 
	0x00, //     
	0xF0, // ####
	0x10, //    #
	0x10, //    #
	0x10, //    #
	0x10, //    #
	0x10, //    #
	0xE0, // ### 

	// @740 'k' (7 pixels wide)
	0x00, //        
	0xC0, // ##     
	0x40, //  #     
	0x4C, //  #  ## 
	0x78, //  ####  
	0x70, //  ###   
	0x58, //  # ##  
	0xCE, // ##  ###
	0x00, //        
	0x00, //        

	// @750 'l' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @760 'm' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xFE, // #######
	0x4A, //  #  # #
	0x4A, //  #  # #
	0x4A, //  #  # #
	0xCA, // ##  # #
	0x00, //        
	0x00, //        

	// @770 'n' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0xCC, // ##  ##
	0x00, //       
	0x00, //       

	// @780 'o' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0x84, // #    #
	0x84, // #    #
	0x84, // #    #
	0x78, //  #### 
	0x00, //       
	0x00, //       

	// @790 'p' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xF8, // ##### 
	0x44, //  #   #
	0x44, //  #   #
	0x44, //  #   #
	0x78, //  #### 
	0x40, //  #    
	0xE0, // ###   

	// @800 'q' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0xC4, // ##   # 
	0x84, // #    # 
	0xC4, // ##   # 
	0x7C, //  ##### 
	0x04, //      # 
	0x0E, //     ###

	// @810 'r' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x60, //  ##  
	0x40, //  #   
	0x40, //  #   
	0xF0, // #### 
	0x00, //      
	0x00, //      

	// @820 's' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x78, //  ####
	0xE0, // ###  
	0x78, //  ####
	0x38, //   ###
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @830 't' (5 pixels wide)
	0x00, //      
	0x40, //  #   
	0x40, //  #   
	0xF0, // #### 
	0x40, //  #   
	0x40, //  #   
	0x48, //  #  #
	0x78, //  ####
	0x00, //      
	0x00, //      

	// @840 'u' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xCC, // ##  ## 
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x3E, //   #####
	0x00, //        
	0x00, //        

	// @850 'v' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xEE, // ### ###
	0x44, //  #   # 
	0x28, //   # #  
	0x38, //   ###  
	0x10, //    #   
	0x00, //        
	0x00, //        

	// @860 'w' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x74, //  ### #
	0x74, //  ### #
	0x78, //  #### 
	0x48, //  #  # 
	0x00, //       
	0x00, //       

	// @870 'x' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x78, //  #### 
	0x30, //   ##  
	0x48, //  #  # 
	0xCC, // ##  ##
	0x00, //       
	0x00, //       

	// @880 'y' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x48, //  #  # 
	0x70, //  ###  
	0x30, //   ##  
	0x20, //   #   
	0xE0, // ###   

	// @890 'z' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0xF0, // ####
	0x20, //   # 
	0x40, //  #  
	0xC0, // ##  
	0xF0, // ####
	0x00, //     
	0x00, //     

	// @900 '{' (3 pixels wide)
	0x00, //    
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x60, //  ##

	// @910 '|' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #

	// @920 '}' (3 pixels wide)
	0x00, //    
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0xC0, // ## 

	// @930 '~' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xE8, // ### #
	0xB0, // # ## 
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
};

// Character descriptors for FreeMono 8pt
// { [Char width in bits], [Offset into freeMono_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeMonoBold8ptCharDesc[] = {
	{1, s_FreeMonoBold8ptBitmaps + 0}, 		// !
	{3, s_FreeMonoBold8ptBitmaps + 10}, 		// "
	{5, s_FreeMonoBold8ptBitmaps + 20}, 		// #
	{5, s_FreeMonoBold8ptBitmaps + 30}, 		// $
	{5, s_FreeMonoBold8ptBitmaps + 40}, 		// %
	{5, s_FreeMonoBold8ptBitmaps + 50}, 		// &
	{1, s_FreeMonoBold8ptBitmaps + 60}, 		// '
	{2, s_FreeMonoBold8ptBitmaps + 70}, 		// (
	{2, s_FreeMonoBold8ptBitmaps + 80}, 		// )
	{5, s_FreeMonoBold8ptBitmaps + 90}, 		// *
	{5, s_FreeMonoBold8ptBitmaps + 100}, 		// +
	{2, s_FreeMonoBold8ptBitmaps + 110}, 		// ,
	{6, s_FreeMonoBold8ptBitmaps + 120}, 		// -
	{1, s_FreeMonoBold8ptBitmaps + 130}, 		// .
	{5, s_FreeMonoBold8ptBitmaps + 140}, 		// /
	{5, s_FreeMonoBold8ptBitmaps + 150}, 		// 0
	{4, s_FreeMonoBold8ptBitmaps + 160}, 		// 1
	{4, s_FreeMonoBold8ptBitmaps + 170}, 		// 2
	{5, s_FreeMonoBold8ptBitmaps + 180}, 		// 3
	{5, s_FreeMonoBold8ptBitmaps + 190}, 		// 4
	{5, s_FreeMonoBold8ptBitmaps + 200}, 		// 5
	{5, s_FreeMonoBold8ptBitmaps + 210}, 		// 6
	{5, s_FreeMonoBold8ptBitmaps + 220}, 		// 7
	{4, s_FreeMonoBold8ptBitmaps + 230}, 		// 8
	{5, s_FreeMonoBold8ptBitmaps + 240}, 		// 9
	{1, s_FreeMonoBold8ptBitmaps + 250}, 		// :
	{2, s_FreeMonoBold8ptBitmaps + 260}, 		// ;
	{5, s_FreeMonoBold8ptBitmaps + 270}, 		// <
	{6, s_FreeMonoBold8ptBitmaps + 280}, 		// =
	{4, s_FreeMonoBold8ptBitmaps + 290}, 		// >
	{5, s_FreeMonoBold8ptBitmaps + 300}, 		// ?
	{5, s_FreeMonoBold8ptBitmaps + 310}, 		// @
	{7, s_FreeMonoBold8ptBitmaps + 320}, 		// A
	{6, s_FreeMonoBold8ptBitmaps + 330}, 		// B
	{6, s_FreeMonoBold8ptBitmaps + 340}, 		// C
	{6, s_FreeMonoBold8ptBitmaps + 350}, 		// D
	{6, s_FreeMonoBold8ptBitmaps + 360}, 		// E
	{6, s_FreeMonoBold8ptBitmaps + 370}, 		// F
	{7, s_FreeMonoBold8ptBitmaps + 380}, 		// G
	{8, s_FreeMonoBold8ptBitmaps + 390}, 		// H
	{3, s_FreeMonoBold8ptBitmaps + 400}, 		// I
	{5, s_FreeMonoBold8ptBitmaps + 410}, 		// J
	{7, s_FreeMonoBold8ptBitmaps + 420}, 		// K
	{5, s_FreeMonoBold8ptBitmaps + 430}, 		// L
	{8, s_FreeMonoBold8ptBitmaps + 440}, 		// M
	{7, s_FreeMonoBold8ptBitmaps + 450}, 		// N
	{6, s_FreeMonoBold8ptBitmaps + 460}, 		// O
	{6, s_FreeMonoBold8ptBitmaps + 470}, 		// P
	{6, s_FreeMonoBold8ptBitmaps + 480}, 		// Q
	{6, s_FreeMonoBold8ptBitmaps + 490}, 		// R
	{5, s_FreeMonoBold8ptBitmaps + 500}, 		// S
	{6, s_FreeMonoBold8ptBitmaps + 510}, 		// T
	{7, s_FreeMonoBold8ptBitmaps + 520}, 		// U
	{7, s_FreeMonoBold8ptBitmaps + 530}, 		// V
	{7, s_FreeMonoBold8ptBitmaps + 540}, 		// W
	{6, s_FreeMonoBold8ptBitmaps + 550}, 		// X
	{6, s_FreeMonoBold8ptBitmaps + 560}, 		// Y
	{5, s_FreeMonoBold8ptBitmaps + 570}, 		// Z
	{2, s_FreeMonoBold8ptBitmaps + 580}, 		// [
	{5, s_FreeMonoBold8ptBitmaps + 590}, 		// '\'
	{2, s_FreeMonoBold8ptBitmaps + 600}, 		// ]
	{5, s_FreeMonoBold8ptBitmaps + 610}, 		// ^
	{7, s_FreeMonoBold8ptBitmaps + 620}, 		// _
	{2, s_FreeMonoBold8ptBitmaps + 630}, 		// `
	{6, s_FreeMonoBold8ptBitmaps + 640}, 		// a
	{6, s_FreeMonoBold8ptBitmaps + 650}, 		// b
	{5, s_FreeMonoBold8ptBitmaps + 660}, 		// c
	{7, s_FreeMonoBold8ptBitmaps + 670}, 		// d
	{6, s_FreeMonoBold8ptBitmaps + 680}, 		// e
	{5, s_FreeMonoBold8ptBitmaps + 690}, 		// f
	{7, s_FreeMonoBold8ptBitmaps + 700}, 		// g
	{7, s_FreeMonoBold8ptBitmaps + 710}, 		// h
	{5, s_FreeMonoBold8ptBitmaps + 720}, 		// i
	{4, s_FreeMonoBold8ptBitmaps + 730}, 		// j
	{7, s_FreeMonoBold8ptBitmaps + 740}, 		// k
	{5, s_FreeMonoBold8ptBitmaps + 750}, 		// l
	{7, s_FreeMonoBold8ptBitmaps + 760}, 		// m
	{6, s_FreeMonoBold8ptBitmaps + 770}, 		// n
	{6, s_FreeMonoBold8ptBitmaps + 780}, 		// o
	{6, s_FreeMonoBold8ptBitmaps + 790}, 		// p
	{7, s_FreeMonoBold8ptBitmaps + 800}, 		// q
	{5, s_FreeMonoBold8ptBitmaps + 810}, 		// r
	{5, s_FreeMonoBold8ptBitmaps + 820}, 		// s
	{5, s_FreeMonoBold8ptBitmaps + 830}, 		// t
	{7, s_FreeMonoBold8ptBitmaps + 840}, 		// u
	{7, s_FreeMonoBold8ptBitmaps + 850}, 		// v
	{6, s_FreeMonoBold8ptBitmaps + 860}, 		// w
	{6, s_FreeMonoBold8ptBitmaps + 870}, 		// x
	{6, s_FreeMonoBold8ptBitmaps + 880}, 		// y
	{4, s_FreeMonoBold8ptBitmaps + 890}, 		// z
	{3, s_FreeMonoBold8ptBitmaps + 900}, 		// {
	{1, s_FreeMonoBold8ptBitmaps + 910}, 		// |
	{3, s_FreeMonoBold8ptBitmaps + 920}, 		// }
	{5, s_FreeMonoBold8ptBitmaps + 930}, 		// ~
};

// Font information for FreeMono 8pt
const FontDesc_t iFontFreeMonoBold8pt = {
	0,
	8,
	10,
	{.pCharDesc = s_FreeMonoBold8ptCharDesc }
};

