// Minimal stand-ins for the nrfxlib HCI command entry points that
// bt_hci_ctlr_sdc.cpp dispatches to. Only the names and shapes matter here:
// the parameter blocks are opaque because the file casts a void pointer into
// each of them and never reads a field.
#ifndef __SDC_HCI_CMD_STUB_H__
#define __SDC_HCI_CMD_STUB_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct { uint8_t Opaque; } sdc_hci_cmd_stub_param_t;

uint8_t sdc_hci_cmd_cb_reset(void);
uint8_t sdc_hci_cmd_le_clear_periodic_adv_list(void);
uint8_t sdc_hci_cmd_le_periodic_adv_create_sync_cancel(void);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_read_max_data_length_return_t;
uint8_t sdc_hci_cmd_le_read_max_data_length(sdc_hci_cmd_le_read_max_data_length_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_read_periodic_adv_list_size_return_t;
uint8_t sdc_hci_cmd_le_read_periodic_adv_list_size(sdc_hci_cmd_le_read_periodic_adv_list_size_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_cb_set_event_mask_t;
uint8_t sdc_hci_cmd_cb_set_event_mask(const sdc_hci_cmd_cb_set_event_mask_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_cb_set_event_mask_page_2_t;
uint8_t sdc_hci_cmd_cb_set_event_mask_page_2(const sdc_hci_cmd_cb_set_event_mask_page_2_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_lc_disconnect_t;
uint8_t sdc_hci_cmd_lc_disconnect(const sdc_hci_cmd_lc_disconnect_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_add_device_to_periodic_adv_list_t;
uint8_t sdc_hci_cmd_le_add_device_to_periodic_adv_list(const sdc_hci_cmd_le_add_device_to_periodic_adv_list_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_create_conn_t;
uint8_t sdc_hci_cmd_le_create_conn(const sdc_hci_cmd_le_create_conn_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_enable_encryption_t;
uint8_t sdc_hci_cmd_le_enable_encryption(const sdc_hci_cmd_le_enable_encryption_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_periodic_adv_create_sync_t;
uint8_t sdc_hci_cmd_le_periodic_adv_create_sync(const sdc_hci_cmd_le_periodic_adv_create_sync_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_periodic_adv_terminate_sync_t;
uint8_t sdc_hci_cmd_le_periodic_adv_terminate_sync(const sdc_hci_cmd_le_periodic_adv_terminate_sync_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_remove_device_from_periodic_adv_list_t;
uint8_t sdc_hci_cmd_le_remove_device_from_periodic_adv_list(const sdc_hci_cmd_le_remove_device_from_periodic_adv_list_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_adv_set_random_address_t;
uint8_t sdc_hci_cmd_le_set_adv_set_random_address(const sdc_hci_cmd_le_set_adv_set_random_address_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_event_mask_t;
uint8_t sdc_hci_cmd_le_set_event_mask(const sdc_hci_cmd_le_set_event_mask_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_data_t;
uint8_t sdc_hci_cmd_le_set_ext_adv_data(const sdc_hci_cmd_le_set_ext_adv_data_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_enable_t;
uint8_t sdc_hci_cmd_le_set_ext_adv_enable(const sdc_hci_cmd_le_set_ext_adv_enable_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_scan_enable_t;
uint8_t sdc_hci_cmd_le_set_ext_scan_enable(const sdc_hci_cmd_le_set_ext_scan_enable_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_scan_params_t;
uint8_t sdc_hci_cmd_le_set_ext_scan_params(const sdc_hci_cmd_le_set_ext_scan_params_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_scan_response_data_t;
uint8_t sdc_hci_cmd_le_set_ext_scan_response_data(const sdc_hci_cmd_le_set_ext_scan_response_data_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_host_feature_t;
uint8_t sdc_hci_cmd_le_set_host_feature(const sdc_hci_cmd_le_set_host_feature_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_data_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_data(const sdc_hci_cmd_le_set_periodic_adv_data_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_enable_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_enable(const sdc_hci_cmd_le_set_periodic_adv_enable_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_params_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_params(const sdc_hci_cmd_le_set_periodic_adv_params_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_receive_enable_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_receive_enable(const sdc_hci_cmd_le_set_periodic_adv_receive_enable_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_phy_t;
uint8_t sdc_hci_cmd_le_set_phy(const sdc_hci_cmd_le_set_phy_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_random_address_t;
uint8_t sdc_hci_cmd_le_set_random_address(const sdc_hci_cmd_le_set_random_address_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_write_suggested_default_data_length_t;
uint8_t sdc_hci_cmd_le_write_suggested_default_data_length(const sdc_hci_cmd_le_write_suggested_default_data_length_t *p_params);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_encrypt_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_encrypt_return_t;
uint8_t sdc_hci_cmd_le_encrypt(const sdc_hci_cmd_le_encrypt_t *p_params, sdc_hci_cmd_le_encrypt_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_long_term_key_request_negative_reply_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_long_term_key_request_negative_reply_return_t;
uint8_t sdc_hci_cmd_le_long_term_key_request_negative_reply(const sdc_hci_cmd_le_long_term_key_request_negative_reply_t *p_params, sdc_hci_cmd_le_long_term_key_request_negative_reply_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_long_term_key_request_reply_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_long_term_key_request_reply_return_t;
uint8_t sdc_hci_cmd_le_long_term_key_request_reply(const sdc_hci_cmd_le_long_term_key_request_reply_t *p_params, sdc_hci_cmd_le_long_term_key_request_reply_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_read_phy_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_read_phy_return_t;
uint8_t sdc_hci_cmd_le_read_phy(const sdc_hci_cmd_le_read_phy_t *p_params, sdc_hci_cmd_le_read_phy_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_data_length_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_data_length_return_t;
uint8_t sdc_hci_cmd_le_set_data_length(const sdc_hci_cmd_le_set_data_length_t *p_params, sdc_hci_cmd_le_set_data_length_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_params_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_params_return_t;
uint8_t sdc_hci_cmd_le_set_ext_adv_params(const sdc_hci_cmd_le_set_ext_adv_params_t *p_params, sdc_hci_cmd_le_set_ext_adv_params_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_params_v2_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_ext_adv_params_v2_return_t;
uint8_t sdc_hci_cmd_le_set_ext_adv_params_v2(const sdc_hci_cmd_le_set_ext_adv_params_v2_t *p_params, sdc_hci_cmd_le_set_ext_adv_params_v2_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_params_v2_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_params_v2_return_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_params_v2(const sdc_hci_cmd_le_set_periodic_adv_params_v2_t *p_params, sdc_hci_cmd_le_set_periodic_adv_params_v2_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_response_data_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_response_data_return_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_response_data(const sdc_hci_cmd_le_set_periodic_adv_response_data_t *p_params, sdc_hci_cmd_le_set_periodic_adv_response_data_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_subevent_data_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_adv_subevent_data_return_t;
uint8_t sdc_hci_cmd_le_set_periodic_adv_subevent_data(const sdc_hci_cmd_le_set_periodic_adv_subevent_data_t *p_params, sdc_hci_cmd_le_set_periodic_adv_subevent_data_return_t *p_return);
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_sync_subevent_t;
typedef sdc_hci_cmd_stub_param_t sdc_hci_cmd_le_set_periodic_sync_subevent_return_t;
uint8_t sdc_hci_cmd_le_set_periodic_sync_subevent(const sdc_hci_cmd_le_set_periodic_sync_subevent_t *p_params, sdc_hci_cmd_le_set_periodic_sync_subevent_return_t *p_return);

#ifdef __cplusplus
}
#endif



#ifdef __cplusplus
// Which command entry point the dispatcher last reached, and how many it made.
extern const char *g_SdcHciCmdLast;
extern int g_SdcHciCmdCount;
extern uint8_t g_SdcHciCmdStatus;
void SdcHciCmdStubReset(void);
#endif
#endif // __SDC_HCI_CMD_STUB_H__
