// 
//  Font data for FreeMono Italic 10pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeMono 10pt
static const uint8_t s_FreeMonoIta10ptBitmaps[] = {
	// @0 '!' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x00, //    
	0x00, //    
	0x80, // #  
	0x00, //    
	0x00, //    

	// @11 '"' (4 pixels wide)
	0x00, //     
	0x90, // #  #
	0x90, // #  #
	0x90, // #  #
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @22 '#' (6 pixels wide)
	0x00, //       
	0x38, //   ### 
	0x28, //   # # 
	0x7C, //  #####
	0x30, //   ##  
	0x50, //  # #  
	0xF8, // ##### 
	0x60, //  ##   
	0x60, //  ##   
	0x00, //       
	0x00, //       

	// @33 '$' (6 pixels wide)
	0x00, //       
	0x3C, //   ####
	0x44, //  #   #
	0x40, //  #    
	0x70, //  ###  
	0x08, //     # 
	0x88, // #   # 
	0x70, //  ###  
	0x20, //   #   
	0x00, //       
	0x00, //       

	// @44 '%' (6 pixels wide)
	0x38, //   ### 
	0x48, //  #  # 
	0x48, //  #  # 
	0x30, //   ##  
	0x0C, //     ##
	0x78, //  #### 
	0xA4, // # #  #
	0x24, //   #  #
	0x38, //   ### 
	0x00, //       
	0x00, //       

	// @55 '&' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x40, //  #   
	0x40, //  #   
	0xA8, // # # #
	0xB0, // # ## 
	0xA0, // # #  
	0xD0, // ## # 
	0x00, //      
	0x00, //      

	// @66 ''' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @77 '(' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x00, //    

	// @88 ')' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x00, //    

	// @99 '*' (5 pixels wide)
	0x20, //   #  
	0x20, //   #  
	0xA8, // # # #
	0xF0, // #### 
	0x60, //  ##  
	0xA0, // # #  
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @110 '+' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x10, //    #  
	0x10, //    #  
	0xFC, // ######
	0x20, //   #   
	0x20, //   #   
	0x00, //       
	0x00, //       
	0x00, //       

	// @121 ',' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x40, //  # 
	0x80, // #  
	0x80, // #  

	// @132 '-' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       

	// @143 '.' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  

	// @154 '/' (7 pixels wide)
	0x00, //        
	0x02, //       #
	0x04, //      # 
	0x08, //     #  
	0x10, //    #   
	0x10, //    #   
	0x20, //   #    
	0x40, //  #     
	0x40, //  #     
	0x80, // #      
	0x00, //        

	// @165 '0' (6 pixels wide)
	0x38, //   ### 
	0x64, //  ##  #
	0x44, //  #   #
	0x84, // #    #
	0x84, // #    #
	0x84, // #    #
	0x88, // #   # 
	0x88, // #   # 
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @176 '1' (5 pixels wide)
	0x00, //      
	0x10, //    # 
	0x70, //  ### 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @187 '2' (6 pixels wide)
	0x18, //    ## 
	0x24, //   #  #
	0x04, //      #
	0x04, //      #
	0x18, //    ## 
	0x20, //   #   
	0x40, //  #    
	0x80, // #     
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @198 '3' (7 pixels wide)
	0x1C, //    ### 
	0x02, //       #
	0x02, //       #
	0x04, //      # 
	0x08, //     #  
	0x04, //      # 
	0x04, //      # 
	0x88, // #   #  
	0x70, //  ###   
	0x00, //        
	0x00, //        

	// @209 '4' (5 pixels wide)
	0x18, //    ##
	0x28, //   # #
	0x28, //   # #
	0x48, //  #  #
	0x90, // #  # 
	0x90, // #  # 
	0xF8, // #####
	0x10, //    # 
	0x38, //   ###
	0x00, //      
	0x00, //      

	// @220 '5' (6 pixels wide)
	0x3C, //   ####
	0x40, //  #    
	0x40, //  #    
	0x78, //  #### 
	0x04, //      #
	0x04, //      #
	0x04, //      #
	0x08, //     # 
	0xF0, // ####  
	0x00, //       
	0x00, //       

	// @231 '6' (7 pixels wide)
	0x0E, //     ###
	0x30, //   ##   
	0x60, //  ##    
	0x40, //  #     
	0xB8, // # ###  
	0xC4, // ##   # 
	0x84, // #    # 
	0x8C, // #   ## 
	0x70, //  ###   
	0x00, //        
	0x00, //        

	// @242 '7' (5 pixels wide)
	0xF8, // #####
	0x08, //     #
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x40, //  #   
	0x40, //  #   
	0x00, //      
	0x00, //      
	0x00, //      

	// @253 '8' (6 pixels wide)
	0x38, //   ### 
	0x64, //  ##  #
	0x44, //  #   #
	0x48, //  #  # 
	0x30, //   ##  
	0x48, //  #  # 
	0x88, // #   # 
	0x98, // #  ## 
	0x70, //  ###  
	0x00, //       
	0x00, //       

	// @264 '9' (6 pixels wide)
	0x38, //   ### 
	0x24, //   #  #
	0x44, //  #   #
	0x44, //  #   #
	0x4C, //  #  ##
	0x3C, //   ####
	0x08, //     # 
	0x10, //    #  
	0xE0, // ###   
	0x00, //       
	0x00, //       

	// @275 ':' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x80, // # 
	0x00, //   
	0x00, //   

	// @286 ';' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x10, //    #
	0x00, //     
	0x00, //     
	0x00, //     
	0x20, //   # 
	0x60, //  ## 
	0x40, //  #  
	0x80, // #   

	// @297 '<' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x04, //      #
	0x18, //    ## 
	0x60, //  ##   
	0x80, // #     
	0x60, //  ##   
	0x10, //    #  
	0x00, //       
	0x00, //       
	0x00, //       

	// @308 '=' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0x00, //        
	0xFE, // #######
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        

	// @319 '>' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x80, // #    
	0x60, //  ##  
	0x10, //    # 
	0x08, //     #
	0x30, //   ## 
	0xC0, // ##   
	0x00, //      
	0x00, //      
	0x00, //      

	// @330 '?' (5 pixels wide)
	0x00, //      
	0x70, //  ### 
	0x88, // #   #
	0x08, //     #
	0x30, //   ## 
	0x40, //  #   
	0x00, //      
	0x00, //      
	0x80, // #    
	0x00, //      
	0x00, //      

	// @341 '@' (6 pixels wide)
	0x18, //    ## 
	0x24, //   #  #
	0x44, //  #   #
	0x58, //  # ## 
	0xA8, // # # # 
	0xA8, // # # # 
	0xB8, // # ### 
	0x80, // #     
	0x80, // #     
	0x70, //  ###  
	0x00, //       

	// @352 'A' (7 pixels wide)
	0x00, //        
	0x38, //   ###  
	0x08, //     #  
	0x38, //   ###  
	0x24, //   #  # 
	0x44, //  #   # 
	0x7C, //  ##### 
	0x84, // #    # 
	0xCE, // ##  ###
	0x00, //        
	0x00, //        

	// @363 'B' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0x62, //  ##   #
	0x42, //  #    #
	0x7C, //  ##### 
	0x42, //  #    #
	0x42, //  #    #
	0x46, //  #   ##
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @374 'C' (7 pixels wide)
	0x00, //        
	0x1C, //    ### 
	0x22, //   #   #
	0x42, //  #    #
	0x40, //  #     
	0x40, //  #     
	0x80, // #      
	0x80, // #      
	0x70, //  ###   
	0x00, //        
	0x00, //        

	// @385 'D' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0x46, //  #   ##
	0x42, //  #    #
	0x42, //  #    #
	0x42, //  #    #
	0x44, //  #   # 
	0x4C, //  #  ## 
	0xF8, // #####  
	0x00, //        
	0x00, //        

	// @396 'E' (7 pixels wide)
	0x00, //        
	0x7E, //  ######
	0x62, //  ##   #
	0x48, //  #  #  
	0x78, //  ####  
	0x48, //  #  #  
	0x40, //  #     
	0x44, //  #   # 
	0xFC, // ###### 
	0x00, //        
	0x00, //        

	// @407 'F' (8 pixels wide)
	0x00, //         
	0x7F, //  #######
	0x62, //  ##   # 
	0x48, //  #  #   
	0x78, //  ####   
	0x48, //  #  #   
	0x40, //  #      
	0x40, //  #      
	0xF0, // ####    
	0x00, //         
	0x00, //         

	// @418 'G' (7 pixels wide)
	0x00, //        
	0x1E, //    ####
	0x62, //  ##   #
	0x40, //  #     
	0x80, // #      
	0x8C, // #   ## 
	0x82, // #     #
	0xC6, // ##   ##
	0x7C, //  ##### 
	0x00, //        
	0x00, //        

	// @429 'H' (7 pixels wide)
	0x00, //        
	0x76, //  ### ##
	0x22, //   #   #
	0x44, //  #   # 
	0x7C, //  ##### 
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0xEE, // ### ###
	0x00, //        
	0x00, //        

	// @440 'I' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x10, //    #  
	0x20, //   #   
	0x20, //   #   
	0x20, //   #   
	0x20, //   #   
	0x20, //   #   
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @451 'J' (9 pixels wide)
	0x00, 0x00, //          
	0x0F, 0x80, //     #####
	0x02, 0x00, //       #  
	0x02, 0x00, //       #  
	0x04, 0x00, //      #   
	0x04, 0x00, //      #   
	0x44, 0x00, //  #   #   
	0x8C, 0x00, // #   ##   
	0x78, 0x00, //  ####    
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @473 'K' (8 pixels wide)
	0x00, //         
	0x73, //  ###  ##
	0x62, //  ##   # 
	0x4C, //  #  ##  
	0x50, //  # #    
	0x68, //  ## #   
	0x48, //  #  #   
	0x44, //  #   #  
	0xE6, // ###  ## 
	0x00, //         
	0x00, //         

	// @484 'L' (7 pixels wide)
	0x00, //        
	0x78, //  ####  
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x22, //   #   #
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @495 'M' (9 pixels wide)
	0x00, 0x00, //          
	0x71, 0x80, //  ###   ##
	0x31, 0x00, //   ##   # 
	0x37, 0x00, //   ## ### 
	0x2D, 0x00, //   # ## # 
	0x49, 0x00, //  #  #  # 
	0x49, 0x00, //  #  #  # 
	0x41, 0x00, //  #     # 
	0xE7, 0x00, // ###  ### 
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @517 'N' (8 pixels wide)
	0x00, //         
	0x47, //  #   ###
	0x62, //  ##   # 
	0x62, //  ##   # 
	0x52, //  # #  # 
	0x54, //  # # #  
	0x54, //  # # #  
	0x8C, // #   ##  
	0xE4, // ###  #  
	0x00, //         
	0x00, //         

	// @528 'O' (7 pixels wide)
	0x00, //        
	0x3C, //   #### 
	0x66, //  ##  ##
	0x42, //  #    #
	0x82, // #     #
	0x82, // #     #
	0x84, // #    # 
	0xCC, // ##  ## 
	0x78, //  ####  
	0x00, //        
	0x00, //        

	// @539 'P' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0x62, //  ##   #
	0x42, //  #    #
	0x46, //  #   ##
	0x7C, //  ##### 
	0x40, //  #     
	0x40, //  #     
	0xF0, // ####   
	0x00, //        
	0x00, //        

	// @550 'Q' (7 pixels wide)
	0x00, //        
	0x3C, //   #### 
	0x66, //  ##  ##
	0x42, //  #    #
	0x82, // #     #
	0x82, // #     #
	0x84, // #    # 
	0xCC, // ##  ## 
	0x78, //  ####  
	0x74, //  ### # 
	0x48, //  #  #  

	// @561 'R' (7 pixels wide)
	0x00, //        
	0x7C, //  ##### 
	0x62, //  ##   #
	0x42, //  #    #
	0x44, //  #   # 
	0x78, //  ####  
	0x48, //  #  #  
	0x44, //  #   # 
	0xE2, // ###   #
	0x00, //        
	0x00, //        

	// @572 'S' (6 pixels wide)
	0x00, //       
	0x3C, //   ####
	0x44, //  #   #
	0x44, //  #   #
	0x40, //  #    
	0x38, //   ### 
	0x88, // #   # 
	0x88, // #   # 
	0xF0, // ####  
	0x00, //       
	0x00, //       

	// @583 'T' (7 pixels wide)
	0x00, //        
	0xFE, // #######
	0x92, // #  #  #
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0xF0, // ####   
	0x00, //        
	0x00, //        

	// @594 'U' (7 pixels wide)
	0x00, //        
	0xEE, // ### ###
	0x44, //  #   # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x84, // #    # 
	0x88, // #   #  
	0x88, // #   #  
	0x70, //  ###   
	0x00, //        
	0x00, //        

	// @605 'V' (7 pixels wide)
	0x00, //        
	0xE6, // ###  ##
	0x84, // #    # 
	0x88, // #   #  
	0x88, // #   #  
	0x50, //  # #   
	0x50, //  # #   
	0x60, //  ##    
	0x60, //  ##    
	0x00, //        
	0x00, //        

	// @616 'W' (8 pixels wide)
	0x00, //         
	0xE3, // ###   ##
	0x41, //  #     #
	0x4A, //  #  # # 
	0x4A, //  #  # # 
	0x7A, //  #### # 
	0x6C, //  ## ##  
	0x4C, //  #  ##  
	0x4C, //  #  ##  
	0x00, //         
	0x00, //         

	// @627 'X' (8 pixels wide)
	0x00, //         
	0x67, //  ##  ###
	0x24, //   #  #  
	0x28, //   # #   
	0x10, //    #    
	0x30, //   ##    
	0x48, //  #  #   
	0x84, // #    #  
	0xCC, // ##  ##  
	0x00, //         
	0x00, //         

	// @638 'Y' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0x44, //  #   # 
	0x48, //  #  #  
	0x30, //   ##   
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0xF0, // ####   
	0x00, //        
	0x00, //        

	// @649 'Z' (6 pixels wide)
	0x00, //       
	0x7C, //  #####
	0x48, //  #  # 
	0x10, //    #  
	0x20, //   #   
	0x40, //  #    
	0x80, // #     
	0x88, // #   # 
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @660 '[' (4 pixels wide)
	0x30, //   ##
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x80, // #   
	0x80, // #   
	0xC0, // ##  

	// @671 '\' (3 pixels wide)
	0x80, // #  
	0x80, // #  
	0xC0, // ## 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x20, //   #
	0x00, //    

	// @682 ']' (4 pixels wide)
	0x30, //   ##
	0x10, //    #
	0x10, //    #
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0xC0, // ##  

	// @693 '^' (5 pixels wide)
	0x00, //      
	0x10, //    # 
	0x28, //   # #
	0xC0, // ##   
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @704 '_' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0x00, //         
	0xFF, // ########

	// @715 '`' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @726 'a' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x3C, //   #### 
	0x04, //      # 
	0x74, //  ### # 
	0x8C, // #   ## 
	0x88, // #   #  
	0xFE, // #######
	0x00, //        
	0x00, //        

	// @737 'b' (8 pixels wide)
	0x60, //  ##     
	0x20, //   #     
	0x20, //   #     
	0x2E, //   # ### 
	0x31, //   ##   #
	0x21, //   #    #
	0x41, //  #     #
	0x22, //   #   # 
	0xDC, // ## ###  
	0x00, //         
	0x00, //         

	// @748 'c' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x3A, //   ### #
	0x44, //  #   # 
	0x80, // #      
	0x80, // #      
	0x80, // #      
	0x78, //  ####  
	0x00, //        
	0x00, //        

	// @759 'd' (7 pixels wide)
	0x06, //      ##
	0x02, //       #
	0x02, //       #
	0x3A, //   ### #
	0x46, //  #   ##
	0x84, // #    # 
	0x84, // #    # 
	0x84, // #    # 
	0x7E, //  ######
	0x00, //        
	0x00, //        

	// @770 'e' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x3C, //   #### 
	0x42, //  #    #
	0xFE, // #######
	0x80, // #      
	0xC0, // ##     
	0x7C, //  ##### 
	0x00, //        
	0x00, //        

	// @781 'f' (8 pixels wide)
	0x07, //      ###
	0x08, //     #   
	0x10, //    #    
	0x3E, //   ##### 
	0x10, //    #    
	0x10, //    #    
	0x20, //   #     
	0x20, //   #     
	0xFC, // ######  
	0x00, //         
	0x00, //         

	// @792 'g' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x3B, //   ### ##
	0x44, //  #   #  
	0x84, // #    #  
	0x84, // #    #  
	0x8C, // #   ##  
	0x74, //  ### #  
	0x08, //     #   
	0x70, //  ###    

	// @803 'h' (8 pixels wide)
	0x60, //  ##     
	0x20, //   #     
	0x40, //  #      
	0x5C, //  # ###  
	0x62, //  ##   # 
	0x42, //  #    # 
	0x42, //  #    # 
	0x44, //  #   #  
	0xE7, // ###  ###
	0x00, //         
	0x00, //         

	// @814 'i' (6 pixels wide)
	0x00, //       
	0x08, //     # 
	0x00, //       
	0x70, //  ###  
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0xFC, // ######
	0x00, //       
	0x00, //       

	// @825 'j' (6 pixels wide)
	0x00, //       
	0x04, //      #
	0x00, //       
	0x3C, //   ####
	0x04, //      #
	0x04, //      #
	0x04, //      #
	0x08, //     # 
	0x08, //     # 
	0x08, //     # 
	0xF0, // ####  

	// @836 'k' (7 pixels wide)
	0x60, //  ##    
	0x20, //   #    
	0x20, //   #    
	0x2E, //   # ###
	0x48, //  #  #  
	0x70, //  ###   
	0x50, //  # #   
	0x48, //  #  #  
	0xCC, // ##  ## 
	0x00, //        
	0x00, //        

	// @847 'l' (6 pixels wide)
	0x38, //   ### 
	0x08, //     # 
	0x18, //    ## 
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0xFC, // ######
	0x00, //       
	0x00, //       

	// @858 'm' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x7B, //  #### ##
	0x25, //   #  # #
	0x49, //  #  #  #
	0x49, //  #  #  #
	0x49, //  #  #  #
	0xEF, // ### ####
	0x00, //         
	0x00, //         

	// @869 'n' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xDC, // ## ### 
	0x62, //  ##   #
	0x42, //  #    #
	0x42, //  #    #
	0x44, //  #   # 
	0xE6, // ###  ##
	0x00, //        
	0x00, //        

	// @880 'o' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x3C, //   #### 
	0x42, //  #    #
	0x82, // #     #
	0x82, // #     #
	0xC4, // ##   # 
	0x78, //  ####  
	0x00, //        
	0x00, //        

	// @891 'p' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x6E, //  ## ### 
	0x31, //   ##   #
	0x41, //  #     #
	0x41, //  #     #
	0x62, //  ##   # 
	0x5C, //  # ###  
	0x40, //  #      
	0xF0, // ####    

	// @902 'q' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0x3B, //   ### ##
	0x44, //  #   #  
	0x84, // #    #  
	0x84, // #    #  
	0xC4, // ##   #  
	0x7C, //  #####  
	0x04, //      #  
	0x1E, //    #### 

	// @913 'r' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x66, //  ##  ##
	0x38, //   ###  
	0x20, //   #    
	0x20, //   #    
	0x20, //   #    
	0xF8, // #####  
	0x00, //        
	0x00, //        

	// @924 's' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x44, //  #   #
	0x60, //  ##   
	0x1C, //    ###
	0x84, // #    #
	0xF8, // ##### 
	0x00, //       
	0x00, //       

	// @935 't' (5 pixels wide)
	0x00, //      
	0x20, //   #  
	0x20, //   #  
	0xF8, // #####
	0x20, //   #  
	0x60, //  ##  
	0x40, //  #   
	0x40, //  #   
	0x78, //  ####
	0x00, //      
	0x00, //      

	// @946 'u' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0xEE, // ### ###
	0x24, //   #  # 
	0x44, //  #   # 
	0x44, //  #   # 
	0x4C, //  #  ## 
	0x7C, //  ##### 
	0x00, //        
	0x00, //        

	// @957 'v' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0xE7, // ###  ###
	0x44, //  #   #  
	0x44, //  #   #  
	0x28, //   # #   
	0x30, //   ##    
	0x30, //   ##    
	0x00, //         
	0x00, //         

	// @968 'w' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0xE3, // ###   ##
	0x42, //  #    # 
	0x5A, //  # ## # 
	0x6C, //  ## ##  
	0x6C, //  ## ##  
	0x48, //  #  #   
	0x00, //         
	0x00, //         

	// @979 'x' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x66, //  ##  ##
	0x24, //   #  # 
	0x18, //    ##  
	0x30, //   ##   
	0x48, //  #  #  
	0xCC, // ##  ## 
	0x00, //        
	0x00, //        

	// @990 'y' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x33, 0x80, //   ##  ###
	0x21, 0x00, //   #    # 
	0x12, 0x00, //    #  #  
	0x14, 0x00, //    # #   
	0x18, 0x00, //    ##    
	0x10, 0x00, //    #     
	0x20, 0x00, //   #      
	0xF0, 0x00, // ####     

	// @1012 'z' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x90, // #  # 
	0x20, //   #  
	0x40, //  #   
	0x80, // #    
	0xF8, // #####
	0x00, //      
	0x00, //      

	// @1023 '{' (5 pixels wide)
	0x08, //     #
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xE0, // ###  
	0x20, //   #  
	0x40, //  #   
	0x40, //  #   
	0x40, //  #   
	0x60, //  ##  

	// @1034 '|' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 

	// @1045 '}' (6 pixels wide)
	0x18, //    ## 
	0x08, //     # 
	0x10, //    #  
	0x10, //    #  
	0x10, //    #  
	0x0C, //     ##
	0x30, //   ##  
	0x20, //   #   
	0x20, //   #   
	0x40, //  #    
	0xC0, // ##    

	// @1056 '~' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x40, //  #   
	0xB8, // # ###
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
};

// Character descriptors for FreeMono 10pt
// { [Char width in bits], [Offset into freeMono_10ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeMonoIta10ptCharDesc[] = {
	{3, s_FreeMonoIta10ptBitmaps + 0}, 			// !
	{4, s_FreeMonoIta10ptBitmaps + 11}, 		// "
	{6, s_FreeMonoIta10ptBitmaps + 22}, 		// #
	{6, s_FreeMonoIta10ptBitmaps + 33}, 		// $
	{6, s_FreeMonoIta10ptBitmaps + 44}, 		// %
	{5, s_FreeMonoIta10ptBitmaps + 55}, 		// &
	{1, s_FreeMonoIta10ptBitmaps + 66}, 		// '
	{3, s_FreeMonoIta10ptBitmaps + 77}, 		// (
	{3, s_FreeMonoIta10ptBitmaps + 88}, 		// )
	{5, s_FreeMonoIta10ptBitmaps + 99}, 		// *
	{6, s_FreeMonoIta10ptBitmaps + 110}, 		// +
	{3, s_FreeMonoIta10ptBitmaps + 121}, 		// ,
	{6, s_FreeMonoIta10ptBitmaps + 132}, 		// -
	{1, s_FreeMonoIta10ptBitmaps + 143}, 		// .
	{7, s_FreeMonoIta10ptBitmaps + 154}, 		// /
	{6, s_FreeMonoIta10ptBitmaps + 165}, 		// 0
	{5, s_FreeMonoIta10ptBitmaps + 176}, 		// 1
	{6, s_FreeMonoIta10ptBitmaps + 187}, 		// 2
	{7, s_FreeMonoIta10ptBitmaps + 198}, 		// 3
	{5, s_FreeMonoIta10ptBitmaps + 209}, 		// 4
	{6, s_FreeMonoIta10ptBitmaps + 220}, 		// 5
	{7, s_FreeMonoIta10ptBitmaps + 231}, 		// 6
	{5, s_FreeMonoIta10ptBitmaps + 242}, 		// 7
	{6, s_FreeMonoIta10ptBitmaps + 253}, 		// 8
	{6, s_FreeMonoIta10ptBitmaps + 264}, 		// 9
	{2, s_FreeMonoIta10ptBitmaps + 275}, 		// :
	{4, s_FreeMonoIta10ptBitmaps + 286}, 		// ;
	{6, s_FreeMonoIta10ptBitmaps + 297}, 		// <
	{7, s_FreeMonoIta10ptBitmaps + 308}, 		// =
	{5, s_FreeMonoIta10ptBitmaps + 319}, 		// >
	{5, s_FreeMonoIta10ptBitmaps + 330}, 		// ?
	{6, s_FreeMonoIta10ptBitmaps + 341}, 		// @
	{7, s_FreeMonoIta10ptBitmaps + 352}, 		// A
	{7, s_FreeMonoIta10ptBitmaps + 363}, 		// B
	{7, s_FreeMonoIta10ptBitmaps + 374}, 		// C
	{7, s_FreeMonoIta10ptBitmaps + 385}, 		// D
	{7, s_FreeMonoIta10ptBitmaps + 396}, 		// E
	{8, s_FreeMonoIta10ptBitmaps + 407}, 		// F
	{7, s_FreeMonoIta10ptBitmaps + 418}, 		// G
	{7, s_FreeMonoIta10ptBitmaps + 429}, 		// H
	{6, s_FreeMonoIta10ptBitmaps + 440}, 		// I
	{9, s_FreeMonoIta10ptBitmaps + 451}, 		// J
	{8, s_FreeMonoIta10ptBitmaps + 473}, 		// K
	{7, s_FreeMonoIta10ptBitmaps + 484}, 		// L
	{9, s_FreeMonoIta10ptBitmaps + 495}, 		// M
	{8, s_FreeMonoIta10ptBitmaps + 517}, 		// N
	{7, s_FreeMonoIta10ptBitmaps + 528}, 		// O
	{7, s_FreeMonoIta10ptBitmaps + 539}, 		// P
	{7, s_FreeMonoIta10ptBitmaps + 550}, 		// Q
	{7, s_FreeMonoIta10ptBitmaps + 561}, 		// R
	{6, s_FreeMonoIta10ptBitmaps + 572}, 		// S
	{7, s_FreeMonoIta10ptBitmaps + 583}, 		// T
	{7, s_FreeMonoIta10ptBitmaps + 594}, 		// U
	{7, s_FreeMonoIta10ptBitmaps + 605}, 		// V
	{8, s_FreeMonoIta10ptBitmaps + 616}, 		// W
	{8, s_FreeMonoIta10ptBitmaps + 627}, 		// X
	{7, s_FreeMonoIta10ptBitmaps + 638}, 		// Y
	{6, s_FreeMonoIta10ptBitmaps + 649}, 		// Z
	{4, s_FreeMonoIta10ptBitmaps + 660}, 		// [
	{3, s_FreeMonoIta10ptBitmaps + 671}, 		// '\'
	{4, s_FreeMonoIta10ptBitmaps + 682}, 		// ]
	{5, s_FreeMonoIta10ptBitmaps + 693}, 		// ^
	{8, s_FreeMonoIta10ptBitmaps + 704}, 		// _
	{1, s_FreeMonoIta10ptBitmaps + 715}, 		// `
	{7, s_FreeMonoIta10ptBitmaps + 726}, 		// a
	{8, s_FreeMonoIta10ptBitmaps + 737}, 		// b
	{7, s_FreeMonoIta10ptBitmaps + 748}, 		// c
	{7, s_FreeMonoIta10ptBitmaps + 759}, 		// d
	{7, s_FreeMonoIta10ptBitmaps + 770}, 		// e
	{8, s_FreeMonoIta10ptBitmaps + 781}, 		// f
	{8, s_FreeMonoIta10ptBitmaps + 792}, 		// g
	{8, s_FreeMonoIta10ptBitmaps + 803}, 		// h
	{6, s_FreeMonoIta10ptBitmaps + 814}, 		// i
	{6, s_FreeMonoIta10ptBitmaps + 825}, 		// j
	{7, s_FreeMonoIta10ptBitmaps + 836}, 		// k
	{6, s_FreeMonoIta10ptBitmaps + 847}, 		// l
	{8, s_FreeMonoIta10ptBitmaps + 858}, 		// m
	{7, s_FreeMonoIta10ptBitmaps + 869}, 		// n
	{7, s_FreeMonoIta10ptBitmaps + 880}, 		// o
	{8, s_FreeMonoIta10ptBitmaps + 891}, 		// p
	{8, s_FreeMonoIta10ptBitmaps + 902}, 		// q
	{7, s_FreeMonoIta10ptBitmaps + 913}, 		// r
	{6, s_FreeMonoIta10ptBitmaps + 924}, 		// s
	{5, s_FreeMonoIta10ptBitmaps + 935}, 		// t
	{7, s_FreeMonoIta10ptBitmaps + 946}, 		// u
	{8, s_FreeMonoIta10ptBitmaps + 957}, 		// v
	{8, s_FreeMonoIta10ptBitmaps + 968}, 		// w
	{7, s_FreeMonoIta10ptBitmaps + 979}, 		// x
	{9, s_FreeMonoIta10ptBitmaps + 990}, 		// y
	{5, s_FreeMonoIta10ptBitmaps + 1012}, 		// z
	{5, s_FreeMonoIta10ptBitmaps + 1023}, 		// {
	{2, s_FreeMonoIta10ptBitmaps + 1034}, 		// |
	{6, s_FreeMonoIta10ptBitmaps + 1045}, 		// }
	{5, s_FreeMonoIta10ptBitmaps + 1056}, 		// ~
};

// Font information for FreeMono 10pt
const FontDesc_t iFontFreeMonoIta10pt = {
	FONT_TYPE_VAR_WIDTH,
	9,
	11,
	{.pCharDesc = s_FreeMonoIta10ptCharDesc }
};

