// 
//  Font data for FreeSans 8pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeSans 8pt
static const uint8_t s_FreeSansBold8ptBitmaps[] = {
	// @0 '!' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @12 '"' (4 pixels wide)
	0x00, //     
	0xF0, // ####
	0xF0, // ####
	0xF0, // ####
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @24 '#' (6 pixels wide)
	0x00, //       
	0x28, //   # # 
	0x28, //   # # 
	0xFC, // ######
	0x48, //  #  # 
	0x58, //  # ## 
	0xFC, // ######
	0x50, //  # #  
	0x50, //  # #  
	0x00, //       
	0x00, //       
	0x00, //       

	// @36 '$' (6 pixels wide)
	0x10, //    #  
	0x78, //  #### 
	0xDC, // ## ###
	0xD0, // ## #  
	0x70, //  ###  
	0x1C, //    ###
	0x1C, //    ###
	0xDC, // ## ###
	0x78, //  #### 
	0x10, //    #  
	0x00, //       
	0x00, //       

	// @48 '%' (9 pixels wide)
	0x00, 0x00, //          
	0x62, 0x00, //  ##   #  
	0x94, 0x00, // #  # #   
	0x94, 0x00, // #  # #   
	0x68, 0x00, //  ## #    
	0x0B, 0x00, //     # ## 
	0x14, 0x80, //    # #  #
	0x14, 0x80, //    # #  #
	0x23, 0x00, //   #   ## 
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @72 '&' (7 pixels wide)
	0x00, //        
	0x30, //   ##   
	0x78, //  ####  
	0x78, //  ####  
	0x20, //   #    
	0x76, //  ### ##
	0xDE, // ## ####
	0xCC, // ##  ## 
	0x7E, //  ######
	0x00, //        
	0x00, //        
	0x00, //        

	// @84 ''' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @96 '(' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x60, //  ##
	0x40, //  # 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0x40, //  # 
	0x60, //  ##
	0x20, //   #
	0x00, //    

	// @108 ')' (3 pixels wide)
	0x00, //    
	0x80, // #  
	0xC0, // ## 
	0x40, //  # 
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x40, //  # 
	0xC0, // ## 
	0x80, // #  
	0x00, //    

	// @120 '*' (3 pixels wide)
	0x00, //    
	0x40, //  # 
	0xE0, // ###
	0x40, //  # 
	0xA0, // # #
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @132 '+' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x60, //  ## 
	0x60, //  ## 
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x00, //     
	0x00, //     
	0x00, //     

	// @144 ',' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x80, // # 
	0x00, //   

	// @156 '-' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @168 '.' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @180 '/' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x00, //    
	0x00, //    
	0x00, //    

	// @192 '0' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @204 '1' (3 pixels wide)
	0x00, //    
	0x20, //   #
	0xE0, // ###
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x00, //    
	0x00, //    
	0x00, //    

	// @216 '2' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0x0C, //     ##
	0x0C, //     ##
	0x18, //    ## 
	0x30, //   ##  
	0x60, //  ##   
	0x7C, //  #####
	0x00, //       
	0x00, //       
	0x00, //       

	// @228 '3' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0x0C, //     ##
	0x18, //    ## 
	0x0C, //     ##
	0x0C, //     ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @240 '4' (5 pixels wide)
	0x00, //      
	0x30, //   ## 
	0x30, //   ## 
	0xF0, // #### 
	0xB0, // # ## 
	0xB0, // # ## 
	0xF8, // #####
	0x30, //   ## 
	0x30, //   ## 
	0x00, //      
	0x00, //      
	0x00, //      

	// @252 '5' (6 pixels wide)
	0x00, //       
	0x7C, //  #####
	0x40, //  #    
	0x40, //  #    
	0x78, //  #### 
	0x4C, //  #  ##
	0x0C, //     ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @264 '6' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0x4C, //  #  ##
	0xC0, // ##    
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @276 '7' (5 pixels wide)
	0x00, //      
	0xF8, // #####
	0x18, //    ##
	0x10, //    # 
	0x30, //   ## 
	0x30, //   ## 
	0x60, //  ##  
	0x60, //  ##  
	0x60, //  ##  
	0x00, //      
	0x00, //      
	0x00, //      

	// @288 '8' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @300 '9' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x7C, //  #####
	0x0C, //     ##
	0xC8, // ##  # 
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @312 ':' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @324 ';' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x40, //  #
	0x80, // # 
	0x00, //   

	// @336 '<' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x0C, //     ##
	0x70, //  ###  
	0xC0, // ##    
	0x38, //   ### 
	0x0C, //     ##
	0x00, //       
	0x00, //       
	0x00, //       

	// @348 '=' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x00, //      
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @360 '>' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xE0, // ###   
	0x38, //   ### 
	0x0C, //     ##
	0x78, //  #### 
	0xC0, // ##    
	0x00, //       
	0x00, //       
	0x00, //       

	// @372 '?' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0x0C, //     ##
	0x0C, //     ##
	0x18, //    ## 
	0x30, //   ##  
	0x00, //       
	0x30, //   ##  
	0x00, //       
	0x00, //       
	0x00, //       

	// @384 '@' (10 pixels wide)
	0x00, 0x00, //           
	0x0F, 0x00, //     ####  
	0x30, 0x80, //   ##    # 
	0x67, 0x40, //  ##  ### #
	0xC9, 0x40, // ##  #  # #
	0xD9, 0x40, // ## ##  # #
	0xD9, 0x40, // ## ##  # #
	0xCF, 0x80, // ##  ##### 
	0x60, 0x00, //  ##       
	0x30, 0x00, //   ##      
	0x1F, 0x00, //    #####  
	0x00, 0x00, //           

	// @408 'A' (7 pixels wide)
	0x00, //        
	0x18, //    ##  
	0x38, //   ###  
	0x3C, //   #### 
	0x2C, //   # ## 
	0x64, //  ##  # 
	0x7E, //  ######
	0x46, //  #   ##
	0xC2, // ##    #
	0x00, //        
	0x00, //        
	0x00, //        

	// @420 'B' (7 pixels wide)
	0x00, //        
	0xFC, // ###### 
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xFC, // ###### 
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xFC, // ###### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @432 'C' (8 pixels wide)
	0x00, //         
	0x3E, //   ##### 
	0x63, //  ##   ##
	0xC0, // ##      
	0xC0, // ##      
	0xC0, // ##      
	0xC0, // ##      
	0x63, //  ##   ##
	0x3E, //   ##### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @444 'D' (7 pixels wide)
	0x00, //        
	0xF8, // #####  
	0xCC, // ##  ## 
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xCC, // ##  ## 
	0xF8, // #####  
	0x00, //        
	0x00, //        
	0x00, //        

	// @456 'E' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0xC0, // ##    
	0xC0, // ##    
	0xC0, // ##    
	0xF8, // ##### 
	0xC0, // ##    
	0xC0, // ##    
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @468 'F' (5 pixels wide)
	0x00, //      
	0xF8, // #####
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xF8, // #####
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0x00, //      
	0x00, //      
	0x00, //      

	// @480 'G' (8 pixels wide)
	0x00, //         
	0x3E, //   ##### 
	0x63, //  ##   ##
	0xC0, // ##      
	0xC0, // ##      
	0xC7, // ##   ###
	0xC3, // ##    ##
	0x63, //  ##   ##
	0x3D, //   #### #
	0x00, //         
	0x00, //         
	0x00, //         

	// @492 'H' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xFE, // #######
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x00, //        
	0x00, //        
	0x00, //        

	// @504 'I' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @516 'J' (6 pixels wide)
	0x00, //       
	0x0C, //     ##
	0x0C, //     ##
	0x0C, //     ##
	0x0C, //     ##
	0x0C, //     ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @528 'K' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0xCC, // ##  ## 
	0xD8, // ## ##  
	0xF0, // ####   
	0xF8, // #####  
	0xC8, // ##  #  
	0xCC, // ##  ## 
	0xC6, // ##   ##
	0x00, //        
	0x00, //        
	0x00, //        

	// @540 'L' (5 pixels wide)
	0x00, //      
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xC0, // ##   
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @552 'M' (8 pixels wide)
	0x00, //         
	0xC7, // ##   ###
	0xE7, // ###  ###
	0xE7, // ###  ###
	0xE7, // ###  ###
	0xEB, // ### # ##
	0xFB, // ##### ##
	0xDB, // ## ## ##
	0xDB, // ## ## ##
	0x00, //         
	0x00, //         
	0x00, //         

	// @564 'N' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0xE6, // ###  ##
	0xE6, // ###  ##
	0xD6, // ## # ##
	0xD6, // ## # ##
	0xCE, // ##  ###
	0xCE, // ##  ###
	0xC6, // ##   ##
	0x00, //        
	0x00, //        
	0x00, //        

	// @576 'O' (9 pixels wide)
	0x00, 0x00, //          
	0x3E, 0x00, //   #####  
	0x63, 0x00, //  ##   ## 
	0xC1, 0x80, // ##     ##
	0xC1, 0x80, // ##     ##
	0xC1, 0x80, // ##     ##
	0xC1, 0x80, // ##     ##
	0x63, 0x00, //  ##   ## 
	0x3E, 0x00, //   #####  
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @600 'P' (6 pixels wide)
	0x00, //       
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xF8, // ##### 
	0xC0, // ##    
	0xC0, // ##    
	0xC0, // ##    
	0x00, //       
	0x00, //       
	0x00, //       

	// @612 'Q' (9 pixels wide)
	0x00, 0x00, //          
	0x3E, 0x00, //   #####  
	0x63, 0x00, //  ##   ## 
	0xC1, 0x80, // ##     ##
	0xC1, 0x80, // ##     ##
	0xC1, 0x80, // ##     ##
	0xC5, 0x80, // ##   # ##
	0x67, 0x00, //  ##  ### 
	0x3F, 0x80, //   #######
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @636 'R' (7 pixels wide)
	0x00, //        
	0xFC, // ###### 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0xF0, // ####   
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0xCE, // ##  ###
	0x00, //        
	0x00, //        
	0x00, //        

	// @648 'S' (6 pixels wide)
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xC0, // ##    
	0xF0, // ####  
	0x3C, //   ####
	0x0C, //     ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @660 'T' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x00, //       
	0x00, //       
	0x00, //       

	// @672 'U' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x7C, //  ##### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @684 'V' (7 pixels wide)
	0x00, //        
	0xC6, // ##   ##
	0x46, //  #   ##
	0x64, //  ##  # 
	0x6C, //  ## ## 
	0x2C, //   # ## 
	0x28, //   # #  
	0x38, //   ###  
	0x18, //    ##  
	0x00, //        
	0x00, //        
	0x00, //        

	// @696 'W' (10 pixels wide)
	0x00, 0x00, //           
	0xCC, 0xC0, // ##  ##  ##
	0x4C, 0xC0, //  #  ##  ##
	0x4E, 0xC0, //  #  ### ##
	0x6A, 0x80, //  ## # # # 
	0x6A, 0x80, //  ## # # # 
	0x33, 0x80, //   ##  ### 
	0x33, 0x80, //   ##  ### 
	0x31, 0x00, //   ##   #  
	0x00, 0x00, //           
	0x00, 0x00, //           
	0x00, 0x00, //           

	// @720 'X' (6 pixels wide)
	0x00, //       
	0xCC, // ##  ##
	0xD8, // ## ## 
	0x78, //  #### 
	0x70, //  ###  
	0x70, //  ###  
	0x78, //  #### 
	0xD8, // ## ## 
	0x8C, // #   ##
	0x00, //       
	0x00, //       
	0x00, //       

	// @732 'Y' (6 pixels wide)
	0x00, //       
	0x8C, // #   ##
	0xCC, // ##  ##
	0x58, //  # ## 
	0x78, //  #### 
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x00, //       
	0x00, //       
	0x00, //       

	// @744 'Z' (6 pixels wide)
	0x00, //       
	0xFC, // ######
	0x0C, //     ##
	0x18, //    ## 
	0x18, //    ## 
	0x30, //   ##  
	0x60, //  ##   
	0x60, //  ##   
	0xFC, // ######
	0x00, //       
	0x00, //       
	0x00, //       

	// @756 '[' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   

	// @768 '\' (3 pixels wide)
	0x00, //    
	0x80, // #  
	0x80, // #  
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x20, //   #
	0x20, //   #
	0x00, //    
	0x00, //    
	0x00, //    

	// @780 ']' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   

	// @792 '^' (5 pixels wide)
	0x00, //      
	0x60, //  ##  
	0x60, //  ##  
	0x70, //  ### 
	0x90, // #  # 
	0x98, // #  ##
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @804 '_' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       

	// @816 '`' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @828 'a' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0x3C, //   ####
	0xEC, // ### ##
	0xCC, // ##  ##
	0x7C, //  #####
	0x00, //       
	0x00, //       
	0x00, //       

	// @840 'b' (6 pixels wide)
	0x00, //       
	0xC0, // ##    
	0xC0, // ##    
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @852 'c' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0xC0, // ##    
	0xC0, // ##    
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @864 'd' (7 pixels wide)
	0x00, //        
	0x06, //      ##
	0x06, //      ##
	0x7E, //  ######
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x7E, //  ######
	0x00, //        
	0x00, //        
	0x00, //        

	// @876 'e' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x70, //  ###  
	0xC8, // ##  # 
	0xF8, // ##### 
	0xC0, // ##    
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @888 'f' (4 pixels wide)
	0x00, //     
	0x70, //  ###
	0x60, //  ## 
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x00, //     
	0x00, //     
	0x00, //     

	// @900 'g' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x7E, //  ######
	0x06, //      ##
	0xC6, // ##   ##
	0x7C, //  ##### 

	// @912 'h' (5 pixels wide)
	0x00, //      
	0xC0, // ##   
	0xC0, // ##   
	0xF0, // #### 
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0x00, //      
	0x00, //      
	0x00, //      

	// @924 'i' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @936 'j' (3 pixels wide)
	0x00, //    
	0x60, //  ##
	0x00, //    
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0xE0, // ###

	// @948 'k' (6 pixels wide)
	0x00, //       
	0xC0, // ##    
	0xC0, // ##    
	0xC8, // ##  # 
	0xD0, // ## #  
	0xF0, // ####  
	0xD0, // ## #  
	0xD8, // ## ## 
	0xCC, // ##  ##
	0x00, //       
	0x00, //       
	0x00, //       

	// @960 'l' (2 pixels wide)
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @972 'm' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0xFF, 0x00, // ######## 
	0xD9, 0x80, // ## ##  ##
	0xD9, 0x80, // ## ##  ##
	0xD9, 0x80, // ## ##  ##
	0xD9, 0x80, // ## ##  ##
	0xD9, 0x80, // ## ##  ##
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @996 'n' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xF0, // #### 
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0x00, //      
	0x00, //      
	0x00, //      

	// @1008 'o' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x7C, //  ##### 
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x7C, //  ##### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @1020 'p' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xF8, // ##### 
	0xC0, // ##    
	0xC0, // ##    
	0xC0, // ##    

	// @1032 'q' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0xC6, // ##   ##
	0x7E, //  ######
	0x06, //      ##
	0x06, //      ##
	0x06, //      ##

	// @1044 'r' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0xF0, // ####
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0x00, //     
	0x00, //     
	0x00, //     

	// @1056 's' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x70, //  ### 
	0xD8, // ## ##
	0xE0, // ###  
	0x78, //  ####
	0xD8, // ## ##
	0x70, //  ### 
	0x00, //      
	0x00, //      
	0x00, //      

	// @1068 't' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x60, //  ## 
	0xF0, // ####
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x70, //  ###
	0x00, //     
	0x00, //     
	0x00, //     

	// @1080 'u' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0xD8, // ## ##
	0x78, //  ####
	0x00, //      
	0x00, //      
	0x00, //      

	// @1092 'v' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x48, //  #  # 
	0x78, //  #### 
	0x30, //   ##  
	0x30, //   ##  
	0x00, //       
	0x00, //       
	0x00, //       

	// @1104 'w' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x00, //         
	0xD9, // ## ##  #
	0x59, //  # ##  #
	0x5F, //  # #####
	0x56, //  # # ## 
	0x76, //  ### ## 
	0x26, //   #  ## 
	0x00, //         
	0x00, //         
	0x00, //         

	// @1116 'x' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x4C, //  #  ##
	0x78, //  #### 
	0x30, //   ##  
	0x30, //   ##  
	0x78, //  #### 
	0xCC, // ##  ##
	0x00, //       
	0x00, //       
	0x00, //       

	// @1128 'y' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x48, //  #  # 
	0x78, //  #### 
	0x38, //   ### 
	0x30, //   ##  
	0x30, //   ##  
	0x30, //   ##  
	0x60, //  ##   

	// @1140 'z' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x78, //  ####
	0x18, //    ##
	0x30, //   ## 
	0x60, //  ##  
	0x60, //  ##  
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @1152 '{' (4 pixels wide)
	0x00, //     
	0x70, //  ###
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x80, // #   
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x70, //  ###
	0x00, //     

	// @1164 '|' (1 pixels wide)
	0x00, //  
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x80, // #
	0x00, //  

	// @1176 '}' (4 pixels wide)
	0x00, //     
	0xE0, // ### 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x10, //    #
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xE0, // ### 
	0x00, //     

	// @1188 '~' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0xE8, // ### #
	0xB8, // # ###
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
};

// Character descriptors for FreeSans 8pt
// { [Char width in bits], [Offset into freeSans_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeSansBold8ptCharDesc[] = {
	{2, s_FreeSansBold8ptBitmaps + 0}, 		// !
	{4, s_FreeSansBold8ptBitmaps + 12}, 		// "
	{6, s_FreeSansBold8ptBitmaps + 24}, 		// #
	{6, s_FreeSansBold8ptBitmaps + 36}, 		// $
	{9, s_FreeSansBold8ptBitmaps + 48}, 		// %
	{7, s_FreeSansBold8ptBitmaps + 72}, 		// &
	{2, s_FreeSansBold8ptBitmaps + 84}, 		// '
	{3, s_FreeSansBold8ptBitmaps + 96}, 		// (
	{3, s_FreeSansBold8ptBitmaps + 108}, 		// )
	{3, s_FreeSansBold8ptBitmaps + 120}, 		// *
	{4, s_FreeSansBold8ptBitmaps + 132}, 		// +
	{2, s_FreeSansBold8ptBitmaps + 144}, 		// ,
	{3, s_FreeSansBold8ptBitmaps + 156}, 		// -
	{2, s_FreeSansBold8ptBitmaps + 168}, 		// .
	{3, s_FreeSansBold8ptBitmaps + 180}, 		// /
	{6, s_FreeSansBold8ptBitmaps + 192}, 		// 0
	{3, s_FreeSansBold8ptBitmaps + 204}, 		// 1
	{6, s_FreeSansBold8ptBitmaps + 216}, 		// 2
	{6, s_FreeSansBold8ptBitmaps + 228}, 		// 3
	{5, s_FreeSansBold8ptBitmaps + 240}, 		// 4
	{6, s_FreeSansBold8ptBitmaps + 252}, 		// 5
	{6, s_FreeSansBold8ptBitmaps + 264}, 		// 6
	{5, s_FreeSansBold8ptBitmaps + 276}, 		// 7
	{6, s_FreeSansBold8ptBitmaps + 288}, 		// 8
	{6, s_FreeSansBold8ptBitmaps + 300}, 		// 9
	{2, s_FreeSansBold8ptBitmaps + 312}, 		// :
	{2, s_FreeSansBold8ptBitmaps + 324}, 		// ;
	{6, s_FreeSansBold8ptBitmaps + 336}, 		// <
	{5, s_FreeSansBold8ptBitmaps + 348}, 		// =
	{6, s_FreeSansBold8ptBitmaps + 360}, 		// >
	{6, s_FreeSansBold8ptBitmaps + 372}, 		// ?
	{10,s_FreeSansBold8ptBitmaps + 384}, 		// @
	{7, s_FreeSansBold8ptBitmaps + 408}, 		// A
	{7, s_FreeSansBold8ptBitmaps + 420}, 		// B
	{8, s_FreeSansBold8ptBitmaps + 432}, 		// C
	{7, s_FreeSansBold8ptBitmaps + 444}, 		// D
	{6, s_FreeSansBold8ptBitmaps + 456}, 		// E
	{5, s_FreeSansBold8ptBitmaps + 468}, 		// F
	{8, s_FreeSansBold8ptBitmaps + 480}, 		// G
	{7, s_FreeSansBold8ptBitmaps + 492}, 		// H
	{2, s_FreeSansBold8ptBitmaps + 504}, 		// I
	{6, s_FreeSansBold8ptBitmaps + 516}, 		// J
	{7, s_FreeSansBold8ptBitmaps + 528}, 		// K
	{5, s_FreeSansBold8ptBitmaps + 540}, 		// L
	{8, s_FreeSansBold8ptBitmaps + 552}, 		// M
	{7, s_FreeSansBold8ptBitmaps + 564}, 		// N
	{9, s_FreeSansBold8ptBitmaps + 576}, 		// O
	{6, s_FreeSansBold8ptBitmaps + 600}, 		// P
	{9, s_FreeSansBold8ptBitmaps + 612}, 		// Q
	{7, s_FreeSansBold8ptBitmaps + 636}, 		// R
	{6, s_FreeSansBold8ptBitmaps + 648}, 		// S
	{6, s_FreeSansBold8ptBitmaps + 660}, 		// T
	{7, s_FreeSansBold8ptBitmaps + 672}, 		// U
	{7, s_FreeSansBold8ptBitmaps + 684}, 		// V
	{10,s_FreeSansBold8ptBitmaps + 696}, 		// W
	{6, s_FreeSansBold8ptBitmaps + 720}, 		// X
	{6, s_FreeSansBold8ptBitmaps + 732}, 		// Y
	{6, s_FreeSansBold8ptBitmaps + 744}, 		// Z
	{2, s_FreeSansBold8ptBitmaps + 756}, 		// [
	{3, s_FreeSansBold8ptBitmaps + 768}, 		// '\'
	{2, s_FreeSansBold8ptBitmaps + 780}, 		// ]
	{5, s_FreeSansBold8ptBitmaps + 792}, 		// ^
	{6, s_FreeSansBold8ptBitmaps + 804}, 		// _
	{1, s_FreeSansBold8ptBitmaps + 816}, 		// `
	{6, s_FreeSansBold8ptBitmaps + 828}, 		// a
	{6, s_FreeSansBold8ptBitmaps + 840}, 		// b
	{6, s_FreeSansBold8ptBitmaps + 852}, 		// c
	{7, s_FreeSansBold8ptBitmaps + 864}, 		// d
	{6, s_FreeSansBold8ptBitmaps + 876}, 		// e
	{4, s_FreeSansBold8ptBitmaps + 888}, 		// f
	{7, s_FreeSansBold8ptBitmaps + 900}, 		// g
	{5, s_FreeSansBold8ptBitmaps + 912}, 		// h
	{2, s_FreeSansBold8ptBitmaps + 924}, 		// i
	{3, s_FreeSansBold8ptBitmaps + 936}, 		// j
	{6, s_FreeSansBold8ptBitmaps + 948}, 		// k
	{2, s_FreeSansBold8ptBitmaps + 960}, 		// l
	{9, s_FreeSansBold8ptBitmaps + 972}, 		// m
	{5, s_FreeSansBold8ptBitmaps + 996}, 		// n
	{7, s_FreeSansBold8ptBitmaps + 1008}, 		// o
	{6, s_FreeSansBold8ptBitmaps + 1020}, 		// p
	{7, s_FreeSansBold8ptBitmaps + 1032}, 		// q
	{4, s_FreeSansBold8ptBitmaps + 1044}, 		// r
	{5, s_FreeSansBold8ptBitmaps + 1056}, 		// s
	{4, s_FreeSansBold8ptBitmaps + 1068}, 		// t
	{5, s_FreeSansBold8ptBitmaps + 1080}, 		// u
	{6, s_FreeSansBold8ptBitmaps + 1092}, 		// v
	{8, s_FreeSansBold8ptBitmaps + 1104}, 		// w
	{6, s_FreeSansBold8ptBitmaps + 1116}, 		// x
	{6, s_FreeSansBold8ptBitmaps + 1128}, 		// y
	{5, s_FreeSansBold8ptBitmaps + 1140}, 		// z
	{4, s_FreeSansBold8ptBitmaps + 1152}, 		// {
	{1, s_FreeSansBold8ptBitmaps + 1164}, 		// |
	{4, s_FreeSansBold8ptBitmaps + 1176}, 		// }
	{5, s_FreeSansBold8ptBitmaps + 1188}, 		// ~
};

// Font information for FreeSans 8pt
const FontDesc_t iFontFreeSansBold8pt = {
	0,
	10,
	12,
	{.pCharDesc = s_FreeSansBold8ptCharDesc }
};

