// 
//  Font data for FreeSans 8pt
// 	https://savannah.gnu.org/projects/freefont/
// 
// 	Font bitmap generated by
// 	http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator

#include "display/ifont.h"

// Character bitmaps for FreeSans 8pt
static const uint8_t s_FreeSansBoldIta8ptBitmaps[] = {
	// @0 '!' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0x00, //    
	0xC0, // ## 
	0x00, //    
	0x00, //    
	0x00, //    

	// @13 '"' (5 pixels wide)
	0x00, //      
	0x00, //      
	0xD8, // ## ##
	0xD8, // ## ##
	0x90, // #  # 
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      

	// @26 '#' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x34, //   ## #
	0x28, //   # # 
	0xFC, // ######
	0x48, //  #  # 
	0x50, //  # #  
	0xF8, // ##### 
	0xB0, // # ##  
	0xA0, // # #   
	0x00, //       
	0x00, //       
	0x00, //       

	// @39 '$' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x7C, //  #####
	0x7C, //  #####
	0x70, //  ###  
	0x38, //   ### 
	0x38, //   ### 
	0xF8, // ##### 
	0xF0, // ####  
	0x40, //  #    
	0x00, //       
	0x00, //       

	// @52 '%' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x71, 0x00, //  ###   # 
	0x92, 0x00, // #  #  #  
	0x94, 0x00, // #  # #   
	0xE8, 0x00, // ### #    
	0x0B, 0x80, //     # ###
	0x14, 0x80, //    # #  #
	0x24, 0x80, //   #  #  #
	0x47, 0x00, //  #   ### 
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @78 '&' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x1C, //    ###  
	0x3C, //   ####  
	0x38, //   ###   
	0x10, //    #    
	0x7B, //  #### ##
	0xCE, // ##  ### 
	0xCC, // ##  ##  
	0x7E, //  ###### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @91 ''' (2 pixels wide)
	0x00, //   
	0x00, //   
	0xC0, // ##
	0xC0, // ##
	0x80, // # 
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   

	// @104 '(' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x10, //    #
	0x30, //   ##
	0x20, //   # 
	0x60, //  ## 
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0x40, //  #  
	0x00, //     

	// @117 ')' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x20, //   # 
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0x30, //   ##
	0x60, //  ## 
	0x40, //  #  
	0xC0, // ##  
	0x80, // #   
	0x00, //     

	// @130 '*' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x40, //  # 
	0xE0, // ###
	0x40, //  # 
	0x80, // #  
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @143 '+' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x10, //    # 
	0x30, //   ## 
	0xF8, // #####
	0x20, //   #  
	0x20, //   #  
	0x00, //      
	0x00, //      
	0x00, //      

	// @156 ',' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x40, //  #
	0xC0, // ##
	0x40, //  #
	0x80, // # 
	0x00, //   

	// @169 '-' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0xE0, // ###
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    

	// @182 '.' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @195 '/' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x10, //    #
	0x10, //    #
	0x20, //   # 
	0x20, //   # 
	0x40, //  #  
	0x40, //  #  
	0x80, // #   
	0x80, // #   
	0x00, //     
	0x00, //     
	0x00, //     

	// @208 '0' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x6C, //  ## ##
	0x4C, //  #  ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xC8, // ##  # 
	0xD8, // ## ## 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @221 '1' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x10, //    #
	0x30, //   ##
	0xE0, // ### 
	0x20, //   # 
	0x60, //  ## 
	0x60, //  ## 
	0x40, //  #  
	0x40, //  #  
	0x00, //     
	0x00, //     
	0x00, //     

	// @234 '2' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x6C, //  ## ##
	0x0C, //     ##
	0x0C, //     ##
	0x18, //    ## 
	0x30, //   ##  
	0x60, //  ##   
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @247 '3' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x6C, //  ## ##
	0x0C, //     ##
	0x18, //    ## 
	0x0C, //     ##
	0x0C, //     ##
	0xCC, // ##  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @260 '4' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x18, //    ##
	0x18, //    ##
	0x28, //   # #
	0x58, //  # ##
	0x98, // #  ##
	0xF8, // #####
	0x10, //    # 
	0x30, //   ## 
	0x00, //      
	0x00, //      
	0x00, //      

	// @273 '5' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x20, //   #   
	0x78, //  #### 
	0x4C, //  #  ##
	0x0C, //     ##
	0xC8, // ##  # 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @286 '6' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x64, //  ##  #
	0x60, //  ##   
	0xF8, // ##### 
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xC8, // ##  # 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @299 '7' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0xF8, // #####
	0x18, //    ##
	0x30, //   ## 
	0x60, //  ##  
	0x40, //  #   
	0xC0, // ##   
	0x80, // #    
	0x00, //      
	0x00, //      
	0x00, //      

	// @312 '8' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x3C, //   #### 
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x38, //   ###  
	0x4C, //  #  ## 
	0xCC, // ##  ## 
	0xCC, // ##  ## 
	0x78, //  ####  
	0x00, //        
	0x00, //        
	0x00, //        

	// @325 '9' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x1C, //    ### 
	0x26, //   #  ##
	0x66, //  ##  ##
	0x66, //  ##  ##
	0x3E, //   #####
	0x0C, //     ## 
	0xCC, // ##  ## 
	0x78, //  ####  
	0x00, //        
	0x00, //        
	0x00, //        

	// @338 ':' (2 pixels wide)
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   
	0xC0, // ##
	0x00, //   
	0x00, //   
	0x00, //   

	// @351 ';' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x00, //    
	0x00, //    
	0x40, //  # 
	0xC0, // ## 
	0x40, //  # 
	0x80, // #  
	0x00, //    

	// @364 '<' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x0C, //     ##
	0x70, //  ###  
	0xC0, // ##    
	0x78, //  #### 
	0x08, //     # 
	0x00, //       
	0x00, //       
	0x00, //       

	// @377 '=' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x00, //       
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       

	// @390 '>' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x40, //  #    
	0x78, //  #### 
	0x0C, //     ##
	0x38, //   ### 
	0xC0, // ##    
	0x00, //       
	0x00, //       
	0x00, //       

	// @403 '?' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x78, //  #### 
	0xCC, // ##  ##
	0x0C, //     ##
	0x18, //    ## 
	0x30, //   ##  
	0x60, //  ##   
	0x00, //       
	0x60, //  ##   
	0x00, //       
	0x00, //       
	0x00, //       

	// @416 '@' (10 pixels wide)
	0x00, 0x00, //           
	0x00, 0x00, //           
	0x0F, 0x80, //     ##### 
	0x38, 0xC0, //   ###   ##
	0x6F, 0x40, //  ## #### #
	0x7B, 0x40, //  #### ## #
	0xF2, 0x40, // ####  #  #
	0xF2, 0x80, // ####  # # 
	0xDF, 0x00, // ## #####  
	0xC0, 0x00, // ##        
	0x62, 0x00, //  ##   #   
	0x3E, 0x00, //   #####   
	0x00, 0x00, //           

	// @442 'A' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x0E, //     ### 
	0x0E, //     ### 
	0x1E, //    #### 
	0x16, //    # ## 
	0x26, //   #  ## 
	0x7F, //  #######
	0x43, //  #    ##
	0xC3, // ##    ##
	0x00, //         
	0x00, //         
	0x00, //         

	// @455 'B' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x7E, //  ###### 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x42, //  #    # 
	0x7C, //  #####  
	0xC6, // ##   ## 
	0xC6, // ##   ## 
	0xFC, // ######  
	0x00, //         
	0x00, //         
	0x00, //         

	// @468 'C' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x1E, //    #### 
	0x63, //  ##   ##
	0x60, //  ##     
	0xC0, // ##      
	0xC0, // ##      
	0xC0, // ##      
	0xC6, // ##   ## 
	0x7C, //  #####  
	0x00, //         
	0x00, //         
	0x00, //         

	// @481 'D' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x7E, //  ###### 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x43, //  #    ##
	0x43, //  #    ##
	0xC6, // ##   ## 
	0xC6, // ##   ## 
	0xF8, // #####   
	0x00, //         
	0x00, //         
	0x00, //         

	// @494 'E' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0x60, //  ##    
	0x60, //  ##    
	0x40, //  #     
	0x7C, //  ##### 
	0xC0, // ##     
	0xC0, // ##     
	0xFC, // ###### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @507 'F' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x7E, //  ######
	0x60, //  ##    
	0x60, //  ##    
	0x40, //  #     
	0x7C, //  ##### 
	0xC0, // ##     
	0xC0, // ##     
	0xC0, // ##     
	0x00, //        
	0x00, //        
	0x00, //        

	// @520 'G' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x3C, //   ####  
	0x62, //  ##   # 
	0x40, //  #      
	0xC0, // ##      
	0xC7, // ##   ###
	0xC3, // ##    ##
	0xE6, // ###  ## 
	0x7E, //  ###### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @533 'H' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x62, //  ##   # 
	0x7E, //  ###### 
	0x46, //  #   ## 
	0xC6, // ##   ## 
	0xC6, // ##   ## 
	0x84, // #    #  
	0x00, //         
	0x00, //         
	0x00, //         

	// @546 'I' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0x00, //    
	0x00, //    
	0x00, //    

	// @559 'J' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x0C, //     ##
	0x0C, //     ##
	0x0C, //     ##
	0x08, //     # 
	0x18, //    ## 
	0xD8, // ## ## 
	0xD8, // ## ## 
	0xF0, // ####  
	0x00, //       
	0x00, //       
	0x00, //       

	// @572 'K' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x63, //  ##   ##
	0x66, //  ##  ## 
	0x68, //  ## #   
	0x70, //  ###    
	0x78, //  ####   
	0xC8, // ##  #   
	0xCC, // ##  ##  
	0xC6, // ##   ## 
	0x00, //         
	0x00, //         
	0x00, //         

	// @585 'L' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x60, //  ##  
	0x60, //  ##  
	0x60, //  ##  
	0x40, //  #   
	0x40, //  #   
	0xC0, // ##   
	0xC0, // ##   
	0xF8, // #####
	0x00, //      
	0x00, //      
	0x00, //      

	// @598 'M' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x31, 0x80, //   ##   ##
	0x71, 0x80, //  ###   ##
	0x73, 0x80, //  ###  ###
	0x5D, 0x00, //  # ### # 
	0x5D, 0x00, //  # ### # 
	0xDD, 0x00, // ## ### # 
	0xDB, 0x00, // ## ## ## 
	0x9B, 0x00, // #  ## ## 
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @624 'N' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x63, //  ##   ##
	0x73, //  ###  ##
	0x52, //  # #  # 
	0x52, //  # #  # 
	0x5E, //  # #### 
	0xCE, // ##  ### 
	0xCE, // ##  ### 
	0x8C, // #   ##  
	0x00, //         
	0x00, //         
	0x00, //         

	// @637 'O' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x1E, //    #### 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xC6, // ##   ## 
	0xC6, // ##   ## 
	0x78, //  ####   
	0x00, //         
	0x00, //         
	0x00, //         

	// @650 'P' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x7E, //  ###### 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x42, //  #    # 
	0x7C, //  #####  
	0xC0, // ##      
	0xC0, // ##      
	0xC0, // ##      
	0x00, //         
	0x00, //         
	0x00, //         

	// @663 'Q' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x1E, //    #### 
	0x63, //  ##   ##
	0x63, //  ##   ##
	0xC3, // ##    ##
	0xC3, // ##    ##
	0xCE, // ##  ### 
	0xCE, // ##  ### 
	0x7E, //  ###### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @676 'R' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x7F, 0x80, //  ########
	0x61, 0x80, //  ##    ##
	0x61, 0x00, //  ##    # 
	0x7E, 0x00, //  ######  
	0x46, 0x00, //  #   ##  
	0xC6, 0x00, // ##   ##  
	0xC6, 0x00, // ##   ##  
	0xC6, 0x00, // ##   ##  
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @702 'S' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x3C, //   #### 
	0x66, //  ##  ##
	0x60, //  ##    
	0x78, //  ####  
	0x1E, //    ####
	0x06, //      ##
	0xC6, // ##   ##
	0x7C, //  ##### 
	0x00, //        
	0x00, //        
	0x00, //        

	// @715 'T' (6 pixels wide)
	0x00, //       
	0x00, //       
	0xFC, // ######
	0x30, //   ##  
	0x20, //   #   
	0x20, //   #   
	0x60, //  ##   
	0x60, //  ##   
	0x60, //  ##   
	0x40, //  #    
	0x00, //       
	0x00, //       
	0x00, //       

	// @728 'U' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x63, //  ##   ##
	0x63, //  ##   ##
	0x62, //  ##   # 
	0x42, //  #    # 
	0xC6, // ##   ## 
	0xC6, // ##   ## 
	0xC4, // ##   #  
	0x78, //  ####   
	0x00, //         
	0x00, //         
	0x00, //         

	// @741 'V' (7 pixels wide)
	0x00, //        
	0x00, //        
	0xC6, // ##   ##
	0xCC, // ##  ## 
	0xC8, // ##  #  
	0xD8, // ## ##  
	0x50, //  # #   
	0x70, //  ###   
	0x60, //  ##    
	0x60, //  ##    
	0x00, //        
	0x00, //        
	0x00, //        

	// @754 'W' (11 pixels wide)
	0x00, 0x00, //            
	0x00, 0x00, //            
	0xCE, 0x60, // ##  ###  ##
	0xCE, 0x40, // ##  ###  # 
	0xDE, 0xC0, // ## #### ## 
	0xD6, 0xC0, // ## # ## ## 
	0xD6, 0x80, // ## # ## #  
	0xE7, 0x80, // ###  ####  
	0x67, 0x00, //  ##  ###   
	0x67, 0x00, //  ##  ###   
	0x00, 0x00, //            
	0x00, 0x00, //            
	0x00, 0x00, //            

	// @780 'X' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x62, //  ##   #
	0x36, //   ## ##
	0x3C, //   #### 
	0x38, //   ###  
	0x38, //   ###  
	0x78, //  ####  
	0x4C, //  #  ## 
	0xCC, // ##  ## 
	0x00, //        
	0x00, //        
	0x00, //        

	// @793 'Y' (6 pixels wide)
	0x00, //       
	0x00, //       
	0xC4, // ##   #
	0xCC, // ##  ##
	0x58, //  # ## 
	0x70, //  ###  
	0x70, //  ###  
	0x60, //  ##   
	0x60, //  ##   
	0x60, //  ##   
	0x00, //       
	0x00, //       
	0x00, //       

	// @806 'Z' (8 pixels wide)
	0x00, //         
	0x00, //         
	0x3F, //   ######
	0x06, //      ## 
	0x04, //      #  
	0x0C, //     ##  
	0x18, //    ##   
	0x30, //   ##    
	0x60, //  ##     
	0xFE, // ####### 
	0x00, //         
	0x00, //         
	0x00, //         

	// @819 '[' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x18, //    ##
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x40, //  #   
	0x40, //  #   
	0x40, //  #   
	0x40, //  #   
	0xE0, // ###  
	0x00, //      

	// @832 '\' (2 pixels wide)
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x80, // # 
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x40, //  #
	0x00, //   
	0x00, //   
	0x00, //   

	// @845 ']' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x38, //   ###
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x10, //    # 
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0x20, //   #  
	0xC0, // ##   
	0x00, //      

	// @858 '^' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x30, //   ##
	0x70, //  ###
	0x50, //  # #
	0x90, // #  #
	0x90, // #  #
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     

	// @871 '_' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0xFE, // #######
	0x00, //        

	// @884 '`' (1 pixels wide)
	0x00, //  
	0x00, //  
	0x80, // #
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  
	0x00, //  

	// @897 'a' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x4C, //  #  ##
	0x38, //   ### 
	0xC8, // ##  # 
	0xD8, // ## ## 
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @910 'b' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x60, //  ##   
	0x60, //  ##   
	0x58, //  # ## 
	0x6C, //  ## ##
	0x8C, // #   ##
	0x8C, // #   ##
	0x98, // #  ## 
	0xF0, // ####  
	0x00, //       
	0x00, //       
	0x00, //       

	// @923 'c' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x6C, //  ## ##
	0xC0, // ##    
	0xC0, // ##    
	0xC8, // ##  # 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @936 'd' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x06, //      ##
	0x04, //      # 
	0x34, //   ## # 
	0x6C, //  ## ## 
	0xC4, // ##   # 
	0xC4, // ##   # 
	0xC8, // ##  #  
	0x78, //  ####  
	0x00, //        
	0x00, //        
	0x00, //        

	// @949 'e' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x4C, //  #  ##
	0xFC, // ######
	0xC0, // ##    
	0xC8, // ##  # 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @962 'f' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x30, //   ##
	0x60, //  ## 
	0xF0, // ####
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0xC0, // ##  
	0xC0, // ##  
	0x00, //     
	0x00, //     
	0x00, //     

	// @975 'g' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x34, //   ## #
	0x6C, //  ## ##
	0xC4, // ##   #
	0xC8, // ##  # 
	0xC8, // ##  # 
	0x78, //  #### 
	0x18, //    ## 
	0x90, // #  #  
	0xF0, // ####  

	// @988 'h' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x60, //  ##   
	0x60, //  ##   
	0x5C, //  # ###
	0x6C, //  ## ##
	0xC8, // ##  # 
	0xC8, // ##  # 
	0xC8, // ##  # 
	0x98, // #  ## 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1001 'i' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x00, //    
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0x00, //    
	0x00, //    
	0x00, //    

	// @1014 'j' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x30, //   ##
	0x00, //     
	0x20, //   # 
	0x20, //   # 
	0x20, //   # 
	0x60, //  ## 
	0x60, //  ## 
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0x80, // #   

	// @1027 'k' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x60, //  ##   
	0x60, //  ##   
	0x4C, //  #  ##
	0x50, //  # #  
	0xF0, // ####  
	0xF0, // ####  
	0xD0, // ## #  
	0x98, // #  ## 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1040 'l' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x60, //  ##
	0x60, //  ##
	0x60, //  ##
	0x40, //  # 
	0x40, //  # 
	0xC0, // ## 
	0xC0, // ## 
	0xC0, // ## 
	0x00, //    
	0x00, //    
	0x00, //    

	// @1053 'm' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x5B, 0x80, //  # ## ###
	0x6D, 0x80, //  ## ## ##
	0xC9, 0x80, // ##  #  ##
	0xC9, 0x80, // ##  #  ##
	0xD9, 0x00, // ## ##  # 
	0x99, 0x00, // #  ##  # 
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @1079 'n' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x7C, //  #####
	0x4C, //  #  ##
	0xC8, // ##  # 
	0xC8, // ##  # 
	0xC8, // ##  # 
	0x98, // #  ## 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1092 'o' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x38, //   ### 
	0x6C, //  ## ##
	0xCC, // ##  ##
	0xCC, // ##  ##
	0xD8, // ## ## 
	0x70, //  ###  
	0x00, //       
	0x00, //       
	0x00, //       

	// @1105 'p' (7 pixels wide)
	0x00, //        
	0x00, //        
	0x00, //        
	0x00, //        
	0x2C, //   # ## 
	0x36, //   ## ##
	0x46, //  #   ##
	0x46, //  #   ##
	0x4C, //  #  ## 
	0x78, //  ####  
	0x40, //  #     
	0xC0, // ##     
	0xC0, // ##     

	// @1118 'q' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x34, //   ## #
	0x6C, //  ## ##
	0xC4, // ##   #
	0xC4, // ##   #
	0xC8, // ##  # 
	0x78, //  #### 
	0x18, //    ## 
	0x18, //    ## 
	0x18, //    ## 

	// @1131 'r' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x40, //  #  
	0xC0, // ##  
	0xC0, // ##  
	0xC0, // ##  
	0x80, // #   
	0x00, //     
	0x00, //     
	0x00, //     

	// @1144 's' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x7C, //  #####
	0xCC, // ##  ##
	0xE0, // ###   
	0x3C, //   ####
	0x4C, //  #  ##
	0x78, //  #### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1157 't' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x00, //     
	0x60, //  ## 
	0xF0, // ####
	0x40, //  #  
	0x40, //  #  
	0x40, //  #  
	0xC0, // ##  
	0xE0, // ### 
	0x00, //     
	0x00, //     
	0x00, //     

	// @1170 'u' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x44, //  #   #
	0x4C, //  #  ##
	0xCC, // ##  ##
	0xC8, // ##  # 
	0xC8, // ##  # 
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1183 'v' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x58, //  # ## 
	0x50, //  # #  
	0x70, //  ###  
	0x60, //  ##   
	0x00, //       
	0x00, //       
	0x00, //       

	// @1196 'w' (9 pixels wide)
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          
	0xDC, 0x80, // ## ###  #
	0xDD, 0x80, // ## ### ##
	0xDD, 0x00, // ## ### # 
	0xEF, 0x00, // ### #### 
	0xEE, 0x00, // ### ###  
	0xEE, 0x00, // ### ###  
	0x00, 0x00, //          
	0x00, 0x00, //          
	0x00, 0x00, //          

	// @1222 'x' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x6C, //  ## ##
	0x78, //  #### 
	0x30, //   ##  
	0x70, //  ###  
	0xD0, // ## #  
	0x98, // #  ## 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1235 'y' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0xCC, // ##  ##
	0x48, //  #  # 
	0x58, //  # ## 
	0x50, //  # #  
	0x50, //  # #  
	0x60, //  ##   
	0x60, //  ##   
	0x40, //  #    
	0xC0, // ##    

	// @1248 'z' (6 pixels wide)
	0x00, //       
	0x00, //       
	0x00, //       
	0x00, //       
	0x3C, //   ####
	0x0C, //     ##
	0x18, //    ## 
	0x30, //   ##  
	0x60, //  ##   
	0xF8, // ##### 
	0x00, //       
	0x00, //       
	0x00, //       

	// @1261 '{' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x30, //   ##
	0x20, //   # 
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0xE0, // ### 
	0x40, //  #  
	0xC0, // ##  
	0xC0, // ##  
	0xE0, // ### 
	0x00, //     

	// @1274 '|' (3 pixels wide)
	0x00, //    
	0x00, //    
	0x20, //   #
	0x20, //   #
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x40, //  # 
	0x80, // #  
	0x80, // #  
	0x80, // #  
	0x00, //    

	// @1287 '}' (4 pixels wide)
	0x00, //     
	0x00, //     
	0x70, //  ###
	0x30, //   ##
	0x30, //   ##
	0x20, //   # 
	0x70, //  ###
	0x60, //  ## 
	0x60, //  ## 
	0x60, //  ## 
	0x40, //  #  
	0xC0, // ##  
	0x00, //     

	// @1300 '~' (5 pixels wide)
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x68, //  ## #
	0x98, // #  ##
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
	0x00, //      
};

// Character descriptors for FreeSans 8pt
// { [Char width in bits], [Offset into freeSans_8ptCharBitmaps in bytes] }
static const CharDesc_t s_FreeSansBoldIta8ptCharDesc[] = {
	{3, s_FreeSansBoldIta8ptBitmaps + 0}, 			// !
	{5, s_FreeSansBoldIta8ptBitmaps + 13}, 			// "
	{6, s_FreeSansBoldIta8ptBitmaps + 26}, 			// #
	{6, s_FreeSansBoldIta8ptBitmaps + 39}, 			// $
	{9, s_FreeSansBoldIta8ptBitmaps + 52}, 			// %
	{8, s_FreeSansBoldIta8ptBitmaps + 78}, 			// &
	{2, s_FreeSansBoldIta8ptBitmaps + 91}, 			// '
	{4, s_FreeSansBoldIta8ptBitmaps + 104}, 		// (
	{4, s_FreeSansBoldIta8ptBitmaps + 117}, 		// )
	{3, s_FreeSansBoldIta8ptBitmaps + 130}, 		// *
	{5, s_FreeSansBoldIta8ptBitmaps + 143}, 		// +
	{2, s_FreeSansBoldIta8ptBitmaps + 156}, 		// ,
	{3, s_FreeSansBoldIta8ptBitmaps + 169}, 		// -
	{2, s_FreeSansBoldIta8ptBitmaps + 182}, 		// .
	{4, s_FreeSansBoldIta8ptBitmaps + 195}, 		// /
	{6, s_FreeSansBoldIta8ptBitmaps + 208}, 		// 0
	{4, s_FreeSansBoldIta8ptBitmaps + 221}, 		// 1
	{6, s_FreeSansBoldIta8ptBitmaps + 234}, 		// 2
	{6, s_FreeSansBoldIta8ptBitmaps + 247}, 		// 3
	{5, s_FreeSansBoldIta8ptBitmaps + 260}, 		// 4
	{6, s_FreeSansBoldIta8ptBitmaps + 273}, 		// 5
	{6, s_FreeSansBoldIta8ptBitmaps + 286}, 		// 6
	{5, s_FreeSansBoldIta8ptBitmaps + 299}, 		// 7
	{7, s_FreeSansBoldIta8ptBitmaps + 312}, 		// 8
	{7, s_FreeSansBoldIta8ptBitmaps + 325}, 		// 9
	{2, s_FreeSansBoldIta8ptBitmaps + 338}, 		// :
	{3, s_FreeSansBoldIta8ptBitmaps + 351}, 		// ;
	{6, s_FreeSansBoldIta8ptBitmaps + 364}, 		// <
	{6, s_FreeSansBoldIta8ptBitmaps + 377}, 		// =
	{6, s_FreeSansBoldIta8ptBitmaps + 390}, 		// >
	{6, s_FreeSansBoldIta8ptBitmaps + 403}, 		// ?
	{10,s_FreeSansBoldIta8ptBitmaps + 416}, 		// @
	{8, s_FreeSansBoldIta8ptBitmaps + 442}, 		// A
	{8, s_FreeSansBoldIta8ptBitmaps + 455}, 		// B
	{8, s_FreeSansBoldIta8ptBitmaps + 468}, 		// C
	{8, s_FreeSansBoldIta8ptBitmaps + 481}, 		// D
	{7, s_FreeSansBoldIta8ptBitmaps + 494}, 		// E
	{7, s_FreeSansBoldIta8ptBitmaps + 507}, 		// F
	{8, s_FreeSansBoldIta8ptBitmaps + 520}, 		// G
	{8, s_FreeSansBoldIta8ptBitmaps + 533}, 		// H
	{3, s_FreeSansBoldIta8ptBitmaps + 546}, 		// I
	{6, s_FreeSansBoldIta8ptBitmaps + 559}, 		// J
	{8, s_FreeSansBoldIta8ptBitmaps + 572}, 		// K
	{5, s_FreeSansBoldIta8ptBitmaps + 585}, 		// L
	{9, s_FreeSansBoldIta8ptBitmaps + 598}, 		// M
	{8, s_FreeSansBoldIta8ptBitmaps + 624}, 		// N
	{8, s_FreeSansBoldIta8ptBitmaps + 637}, 		// O
	{8, s_FreeSansBoldIta8ptBitmaps + 650}, 		// P
	{8, s_FreeSansBoldIta8ptBitmaps + 663}, 		// Q
	{9, s_FreeSansBoldIta8ptBitmaps + 676}, 		// R
	{7, s_FreeSansBoldIta8ptBitmaps + 702}, 		// S
	{6, s_FreeSansBoldIta8ptBitmaps + 715}, 		// T
	{8, s_FreeSansBoldIta8ptBitmaps + 728}, 		// U
	{7, s_FreeSansBoldIta8ptBitmaps + 741}, 		// V
	{11,s_FreeSansBoldIta8ptBitmaps + 754}, 		// W
	{7, s_FreeSansBoldIta8ptBitmaps + 780}, 		// X
	{6, s_FreeSansBoldIta8ptBitmaps + 793}, 		// Y
	{8, s_FreeSansBoldIta8ptBitmaps + 806}, 		// Z
	{5, s_FreeSansBoldIta8ptBitmaps + 819}, 		// [
	{2, s_FreeSansBoldIta8ptBitmaps + 832}, 		// '\'
	{5, s_FreeSansBoldIta8ptBitmaps + 845}, 		// ]
	{4, s_FreeSansBoldIta8ptBitmaps + 858}, 		// ^
	{7, s_FreeSansBoldIta8ptBitmaps + 871}, 		// _
	{1, s_FreeSansBoldIta8ptBitmaps + 884}, 		// `
	{6, s_FreeSansBoldIta8ptBitmaps + 897}, 		// a
	{6, s_FreeSansBoldIta8ptBitmaps + 910}, 		// b
	{6, s_FreeSansBoldIta8ptBitmaps + 923}, 		// c
	{7, s_FreeSansBoldIta8ptBitmaps + 936}, 		// d
	{6, s_FreeSansBoldIta8ptBitmaps + 949}, 		// e
	{4, s_FreeSansBoldIta8ptBitmaps + 962}, 		// f
	{6, s_FreeSansBoldIta8ptBitmaps + 975}, 		// g
	{6, s_FreeSansBoldIta8ptBitmaps + 988}, 		// h
	{3, s_FreeSansBoldIta8ptBitmaps + 1001}, 		// i
	{4, s_FreeSansBoldIta8ptBitmaps + 1014}, 		// j
	{6, s_FreeSansBoldIta8ptBitmaps + 1027}, 		// k
	{3, s_FreeSansBoldIta8ptBitmaps + 1040}, 		// l
	{9, s_FreeSansBoldIta8ptBitmaps + 1053}, 		// m
	{6, s_FreeSansBoldIta8ptBitmaps + 1079}, 		// n
	{6, s_FreeSansBoldIta8ptBitmaps + 1092}, 		// o
	{7, s_FreeSansBoldIta8ptBitmaps + 1105}, 		// p
	{6, s_FreeSansBoldIta8ptBitmaps + 1118}, 		// q
	{4, s_FreeSansBoldIta8ptBitmaps + 1131}, 		// r
	{6, s_FreeSansBoldIta8ptBitmaps + 1144}, 		// s
	{4, s_FreeSansBoldIta8ptBitmaps + 1157}, 		// t
	{6, s_FreeSansBoldIta8ptBitmaps + 1170}, 		// u
	{6, s_FreeSansBoldIta8ptBitmaps + 1183}, 		// v
	{9, s_FreeSansBoldIta8ptBitmaps + 1196}, 		// w
	{6, s_FreeSansBoldIta8ptBitmaps + 1222}, 		// x
	{6, s_FreeSansBoldIta8ptBitmaps + 1235}, 		// y
	{6, s_FreeSansBoldIta8ptBitmaps + 1248}, 		// z
	{4, s_FreeSansBoldIta8ptBitmaps + 1261}, 		// {
	{3, s_FreeSansBoldIta8ptBitmaps + 1274}, 		// |
	{4, s_FreeSansBoldIta8ptBitmaps + 1287}, 		// }
	{5, s_FreeSansBoldIta8ptBitmaps + 1300}, 		// ~
};

// Font information for FreeSans 8pt
const FontDesc_t iFontFreeSansBoldIta8pt = {
	0,
	11,
	13,
	{.pCharDesc = s_FreeSansBoldIta8ptCharDesc }
};
