/**-------------------------------------------------------------------------
@file	esp32c2.h

@brief	ESP32-C2 chip-specific definition.

Single-core 32-bit RISC-V at up to 120 MHz, Wi-Fi 4 (2.4 GHz) + BLE 5,
21 GPIOs, 32 CPU interrupts.  Cost-optimized budget chip (formerly
ESP8684).  Uses the older SYSTEM block (no PCR) for peripheral
clock-gating, same as C3.

Defines the chip-specific ESP32C2_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32c2/register/soc/reg_base.h
   components/soc/esp32c2/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32C2_H__
#define __ESP32C2_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32C2_UART0_BASE                  0x60000000UL
#define ESP32C2_SPI1_BASE                   0x60002000UL    //!< MSPI flash 1
#define ESP32C2_SPI0_BASE                   0x60003000UL    //!< MSPI flash 0
#define ESP32C2_GPIO_BASE                   0x60004000UL
#define ESP32C2_FE2_BASE                    0x60005000UL    //!< Front-end 2 (radio)
#define ESP32C2_FE_BASE                     0x60006000UL    //!< Front-end (radio)
#define ESP32C2_RTC_CNTL_BASE               0x60008000UL    //!< RTC control
#define ESP32C2_EFUSE_BASE                  0x60008800UL
#define ESP32C2_IOMUX_BASE                  0x60009000UL
#define ESP32C2_RTC_I2C_BASE                0x6000E000UL
#define ESP32C2_UART1_BASE                  0x60010000UL
#define ESP32C2_I2C_BASE                    0x60013000UL
#define ESP32C2_LEDC_BASE                   0x60019000UL
#define ESP32C2_NRX_BASE                    0x6001CC00UL    //!< Radio NRX
#define ESP32C2_BB_BASE                     0x6001D000UL    //!< Radio baseband
#define ESP32C2_TIMG0_BASE                  0x6001F000UL    //!< Timer group 0 (only one on C2)
#define ESP32C2_SYSTIMER_BASE               0x60023000UL
#define ESP32C2_SPI2_BASE                   0x60024000UL    //!< GP-SPI2
#define ESP32C2_SYSCON_BASE                 0x60026000UL
#define ESP32C2_APB_SARADC_BASE             0x60040000UL
#define ESP32C2_WDEVLE_BASE                 0x60045000UL
#define ESP32C2_ETM_BIT_BASE                0x6004B000UL
#define ESP32C2_BLE_TIMER_BASE              0x6004B800UL
#define ESP32C2_BLE_SEC_BASE                0x6004C000UL
#define ESP32C2_COEX_BIT_BASE               0x6004C400UL
#define ESP32C2_MODEM_CLKRST_BASE           0x6004D800UL
#define ESP32C2_I2C_MST_BASE                0x6004E800UL    //!< I2C analog master
#define ESP32C2_XTS_AES_BASE                0x600CC000UL
#define ESP32C2_AES_XTS_BASE                ESP32C2_XTS_AES_BASE

#define ESP32C2_SHA_BASE                    0x6003B000UL
#define ESP32C2_ECC_MULT_BASE               0x6003E000UL
#define ESP32C2_ECC_BASE                    ESP32C2_ECC_MULT_BASE
#define ESP32C2_GDMA_BASE                   0x6003F000UL

#define ESP32C2_SYSTEM_BASE                 0x600C0000UL    //!< SYSTEM (peripheral clock-gating)
#define ESP32C2_SENSITIVE_BASE              0x600C1000UL
#define ESP32C2_INTMTX_BASE                 0x600C2000UL
#define ESP32C2_EXTMEM_BASE                 0x600C4000UL    //!< CACHE_CONFIG
#define ESP32C2_MMU_TABLE_BASE              0x600C5000UL
#define ESP32C2_ASSIST_DEBUG_BASE           0x600CE000UL
#define ESP32C2_DEDICATED_GPIO_BASE         0x600CF000UL
#define ESP32C2_WORLD_CTRL_BASE             0x600D0000UL

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32C2_CPU_CORE_COUNT              1U
#define ESP32C2_CPU_INTERRUPT_COUNT         32U
#define ESP32C2_UART_COUNT                  2U
#define ESP32C2_HP_UART_COUNT               2U
#define ESP32C2_LP_UART_COUNT               0U
#define ESP32C2_SPI_MEM_COUNT               2U
#define ESP32C2_GP_SPI_COUNT                1U
#define ESP32C2_I2C_COUNT                   1U
#define ESP32C2_HP_I2C_COUNT                1U
#define ESP32C2_LP_I2C_COUNT                0U
#define ESP32C2_I2S_COUNT                   0U      //!< No I2S on C2
#define ESP32C2_TWAI_COUNT                  0U      //!< No TWAI on C2
#define ESP32C2_RMT_COUNT                   0U      //!< No RMT on C2
#define ESP32C2_LEDC_COUNT                  1U
#define ESP32C2_TIMER_GROUP_COUNT           1U      //!< Only one timer group
#define ESP32C2_TIMER_PER_GROUP_COUNT       1U
#define ESP32C2_TIMER_COUNT                 1U
#define ESP32C2_SYSTIMER_COUNT              1U
#define ESP32C2_SYSTIMER_COUNTER_COUNT      2U
#define ESP32C2_SYSTIMER_ALARM_COUNT        3U
#define ESP32C2_GDMA_COUNT                  1U
#define ESP32C2_GDMA_PAIR_COUNT             1U
#define ESP32C2_GDMA_TX_CHANNEL_COUNT       1U
#define ESP32C2_GDMA_RX_CHANNEL_COUNT       1U
#define ESP32C2_GPIO_PORT_COUNT             1U
#define ESP32C2_GPIO_PIN_COUNT              21U
#define ESP32C2_GPIO_PIN_MAX                20U
#define ESP32C2_GPIO_PIN_REG_COUNT          21U
#define ESP32C2_GPIO_FUNC_IN_COUNT          128U
#define ESP32C2_GPIO_FUNC_OUT_COUNT         21U
#define ESP32C2_GPIO_FUNC_OUT_REG_COUNT     21U
#define ESP32C2_ADC_COUNT                   1U
#define ESP32C2_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32C2_USB_SERIAL_JTAG_COUNT       0U      //!< No USB serial-JTAG on C2
#define ESP32C2_SHA_COUNT                   1U
#define ESP32C2_ECC_COUNT                   1U
#define ESP32C2_EFUSE_COUNT                 1U
#define ESP32C2_INTMTX_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32C2_*
 *
 * Every ESP32C2_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32C2_UART0_BASE
#define ESP32_SPI1_BASE                         ESP32C2_SPI1_BASE
#define ESP32_SPI0_BASE                         ESP32C2_SPI0_BASE
#define ESP32_GPIO_BASE                         ESP32C2_GPIO_BASE
#define ESP32_FE2_BASE                          ESP32C2_FE2_BASE
#define ESP32_FE_BASE                           ESP32C2_FE_BASE
#define ESP32_RTC_CNTL_BASE                     ESP32C2_RTC_CNTL_BASE
#define ESP32_EFUSE_BASE                        ESP32C2_EFUSE_BASE
#define ESP32_IOMUX_BASE                        ESP32C2_IOMUX_BASE
#define ESP32_RTC_I2C_BASE                      ESP32C2_RTC_I2C_BASE
#define ESP32_UART1_BASE                        ESP32C2_UART1_BASE
#define ESP32_I2C_BASE                          ESP32C2_I2C_BASE
#define ESP32_LEDC_BASE                         ESP32C2_LEDC_BASE
#define ESP32_NRX_BASE                          ESP32C2_NRX_BASE
#define ESP32_BB_BASE                           ESP32C2_BB_BASE
#define ESP32_TIMG0_BASE                        ESP32C2_TIMG0_BASE
#define ESP32_SYSTIMER_BASE                     ESP32C2_SYSTIMER_BASE
#define ESP32_SPI2_BASE                         ESP32C2_SPI2_BASE
#define ESP32_SYSCON_BASE                       ESP32C2_SYSCON_BASE
#define ESP32_APB_SARADC_BASE                   ESP32C2_APB_SARADC_BASE
#define ESP32_WDEVLE_BASE                       ESP32C2_WDEVLE_BASE
#define ESP32_ETM_BIT_BASE                      ESP32C2_ETM_BIT_BASE
#define ESP32_BLE_TIMER_BASE                    ESP32C2_BLE_TIMER_BASE
#define ESP32_BLE_SEC_BASE                      ESP32C2_BLE_SEC_BASE
#define ESP32_COEX_BIT_BASE                     ESP32C2_COEX_BIT_BASE
#define ESP32_MODEM_CLKRST_BASE                 ESP32C2_MODEM_CLKRST_BASE
#define ESP32_I2C_MST_BASE                      ESP32C2_I2C_MST_BASE
#define ESP32_XTS_AES_BASE                      ESP32C2_XTS_AES_BASE
#define ESP32_AES_XTS_BASE                      ESP32C2_AES_XTS_BASE
#define ESP32_SHA_BASE                          ESP32C2_SHA_BASE
#define ESP32_ECC_MULT_BASE                     ESP32C2_ECC_MULT_BASE
#define ESP32_ECC_BASE                          ESP32C2_ECC_BASE
#define ESP32_GDMA_BASE                         ESP32C2_GDMA_BASE
#define ESP32_SYSTEM_BASE                       ESP32C2_SYSTEM_BASE
#define ESP32_SENSITIVE_BASE                    ESP32C2_SENSITIVE_BASE
#define ESP32_INTMTX_BASE                       ESP32C2_INTMTX_BASE
#define ESP32_EXTMEM_BASE                       ESP32C2_EXTMEM_BASE
#define ESP32_MMU_TABLE_BASE                    ESP32C2_MMU_TABLE_BASE
#define ESP32_ASSIST_DEBUG_BASE                 ESP32C2_ASSIST_DEBUG_BASE
#define ESP32_DEDICATED_GPIO_BASE               ESP32C2_DEDICATED_GPIO_BASE
#define ESP32_WORLD_CTRL_BASE                   ESP32C2_WORLD_CTRL_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32C2_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32C2_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32C2_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32C2_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32C2_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32C2_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32C2_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32C2_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32C2_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32C2_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32C2_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32C2_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32C2_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32C2_LEDC_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32C2_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32C2_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32C2_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32C2_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32C2_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32C2_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32C2_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32C2_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32C2_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32C2_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32C2_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32C2_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32C2_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32C2_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32C2_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32C2_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32C2_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32C2_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32C2_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32C2_USB_SERIAL_JTAG_COUNT
#define ESP32_SHA_COUNT                         ESP32C2_SHA_COUNT
#define ESP32_ECC_COUNT                         ESP32C2_ECC_COUNT
#define ESP32_EFUSE_COUNT                       ESP32C2_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32C2_INTMTX_COUNT

#endif // __ESP32C2_H__
