/**-------------------------------------------------------------------------
@file	esp32c5.h

@brief	ESP32-C5 chip-specific definition.

Single-core 32-bit RISC-V, HP up to 240 MHz + LP RISC-V at 40-48 MHz.
Dual-band Wi-Fi 6 (2.4 + 5 GHz) + BLE 5 + 802.15.4 (Thread/Zigbee/Matter).
29 GPIOs, PCR-based peripheral clock-gating, dedicated INTMTX + INTPRI.

Defines the chip-specific ESP32C5_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32c5/register/soc/reg_base.h
   components/soc/esp32c5/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026 (consolidation)

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32C5_H__
#define __ESP32C5_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32C5_UART0_BASE                  0x60000000UL
#define ESP32C5_UART1_BASE                  0x60001000UL
#define ESP32C5_SPIMEM0_BASE                0x60002000UL
#define ESP32C5_SPIMEM1_BASE                0x60003000UL
#define ESP32C5_I2C_BASE                    0x60004000UL
#define ESP32C5_UHCI_BASE                   0x60005000UL
#define ESP32C5_RMT_BASE                    0x60006000UL
#define ESP32C5_LEDC_BASE                   0x60007000UL
#define ESP32C5_TIMG0_BASE                  0x60008000UL
#define ESP32C5_TIMG1_BASE                  0x60009000UL
#define ESP32C5_SYSTIMER_BASE               0x6000A000UL
#define ESP32C5_TWAI0_BASE                  0x6000B000UL
#define ESP32C5_I2S_BASE                    0x6000C000UL
#define ESP32C5_TWAI1_BASE                  0x6000D000UL
#define ESP32C5_SAR_ADC_BASE                0x6000E000UL
#define ESP32C5_USB_SERIAL_JTAG_BASE               0x6000F000UL
#define ESP32C5_INTMTX_BASE                 0x60010000UL
#define ESP32C5_PCNT_BASE                   0x60012000UL
#define ESP32C5_SOC_ETM_BASE                0x60013000UL
#define ESP32C5_MCPWM_BASE                  0x60014000UL
#define ESP32C5_PARL_IO_BASE                0x60015000UL
#define ESP32C5_SDIO_HINF_BASE              0x60016000UL
#define ESP32C5_SDIO_SLC_BASE               0x60017000UL
#define ESP32C5_SDIO_SLCHOST_BASE           0x60018000UL
#define ESP32C5_PVT_MONITOR_BASE            0x60019000UL
#define ESP32C5_PSRAM_MEM_MONITOR_BASE      0x6001A000UL

#define ESP32C5_GDMA_BASE                   0x60080000UL    //!< AHB GDMA controller
#define ESP32C5_AHB_DMA_BASE                ESP32C5_GDMA_BASE
#define ESP32C5_GP_SPI2_BASE                0x60081000UL
#define ESP32C5_SPI2_BASE                   ESP32C5_GP_SPI2_BASE
#define ESP32C5_BITSCRAMBLER_BASE           0x60082000UL
#define ESP32C5_KEYMNG_BASE                 0x60087000UL
#define ESP32C5_AES_BASE                    0x60088000UL
#define ESP32C5_SHA_BASE                    0x60089000UL
#define ESP32C5_RSA_BASE                    0x6008A000UL
#define ESP32C5_ECC_BASE                    0x6008B000UL
#define ESP32C5_ECC_MULT_BASE               ESP32C5_ECC_BASE
#define ESP32C5_RSA_DS_BASE                 0x6008C000UL
#define ESP32C5_DS_BASE                     ESP32C5_RSA_DS_BASE
#define ESP32C5_HMAC_BASE                   0x6008D000UL
#define ESP32C5_ECDSA_BASE                  0x6008E000UL

#define ESP32C5_IOMUX_BASE                  0x60090000UL
#define ESP32C5_GPIO_BASE                   0x60091000UL
#define ESP32C5_GPIO_EXT_BASE               0x60091E00UL
#define ESP32C5_MEM_MONITOR_BASE            0x60092000UL
#define ESP32C5_PAU_BASE                    0x60093000UL
#define ESP32C5_HP_SYSREG_BASE              0x60095000UL
#define ESP32C5_PCR_BASE                    0x60096000UL
#define ESP32C5_TEE_BASE                    0x60098000UL
#define ESP32C5_HP_APM_BASE                 0x60099000UL
#define ESP32C5_LP_APM0_BASE                0x60099800UL
#define ESP32C5_CPU_APM_BASE                0x6009A000UL
#define ESP32C5_MISC_BASE                   0x6009F000UL
#define ESP32C5_MODEM0_BASE                 0x600A0000UL
#define ESP32C5_IEEE802154_BASE             0x600A3000UL
#define ESP32C5_MODEM1_BASE                 0x600AC000UL
#define ESP32C5_MODEM_PWR0_BASE             0x600AD000UL
#define ESP32C5_MODEM_PWR1_BASE             0x600AF000UL
#define ESP32C5_I2C_ANA_MST_BASE            0x600AF800UL

#define ESP32C5_PMU_BASE                    0x600B0000UL
#define ESP32C5_LP_CLKRST_BASE              0x600B0400UL
#define ESP32C5_LP_TIMER_BASE               0x600B0C00UL
#define ESP32C5_RTC_TIMER_BASE              ESP32C5_LP_TIMER_BASE
#define ESP32C5_LP_AON_BASE                 0x600B1000UL
#define ESP32C5_LP_UART_BASE                0x600B1400UL
#define ESP32C5_LP_I2C_BASE                 0x600B1800UL
#define ESP32C5_LP_WDT_BASE                 0x600B1C00UL
#define ESP32C5_RTC_WDT_BASE                ESP32C5_LP_WDT_BASE
#define ESP32C5_LP_I2C_ANA_MST_BASE         0x600B2400UL
#define ESP32C5_LPPERI_BASE                 0x600B2800UL
#define ESP32C5_LP_ANA_BASE                 0x600B2C00UL
#define ESP32C5_HUK_BASE                    0x600B3000UL
#define ESP32C5_LP_TEE_BASE                 0x600B3400UL
#define ESP32C5_LP_APM_BASE                 0x600B3800UL
#define ESP32C5_LP_IOMUX_BASE               0x600B4000UL
#define ESP32C5_LP_GPIO_BASE                0x600B4400UL
#define ESP32C5_EFUSE_BASE                  0x600B4800UL
#define ESP32C5_OTP_DEBUG_BASE              0x600B4D00UL

#define ESP32C5_TRACE_BASE                  0x600C0000UL
#define ESP32C5_BUS_MONITOR_BASE            0x600C2000UL
#define ESP32C5_INTPRI_BASE                 0x600C5000UL
#define ESP32C5_CACHE_BASE                  0x600C8000UL

#define ESP32C5_CLINT_M_BASE                0x20000000UL    //!< RISC-V CLINT machine-mode

/* CPU interrupt numbers used by ROM / IDF startup conventions. */
#define ESP32C5_ETS_MAX_INUM                31U
#define ESP32C5_ETS_SLC_INUM                1U
#define ESP32C5_ETS_UART0_INUM              5U
#define ESP32C5_ETS_UART1_INUM              5U
#define ESP32C5_ETS_SPI2_INUM               1U
#define ESP32C5_ETS_GPIO_INUM               4U
#define ESP32C5_ETS_INVALID_INUM            0U

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32C5_CPU_CORE_COUNT              1U
#define ESP32C5_CPU_INTERRUPT_COUNT         32U
#define ESP32C5_UART_COUNT                  3U      //!< 2 HP + 1 LP
#define ESP32C5_HP_UART_COUNT               2U
#define ESP32C5_LP_UART_COUNT               1U
#define ESP32C5_SPI_MEM_COUNT               2U
#define ESP32C5_GP_SPI_COUNT                1U
#define ESP32C5_I2C_COUNT                   2U      //!< 1 HP + 1 LP
#define ESP32C5_HP_I2C_COUNT                1U
#define ESP32C5_LP_I2C_COUNT                1U
#define ESP32C5_I2S_COUNT                   1U
#define ESP32C5_TWAI_COUNT                  2U
#define ESP32C5_RMT_COUNT                   1U
#define ESP32C5_LEDC_COUNT                  1U
#define ESP32C5_PCNT_COUNT                  1U
#define ESP32C5_ETM_COUNT                   1U
#define ESP32C5_MCPWM_COUNT                 1U
#define ESP32C5_PARL_IO_COUNT               1U
#define ESP32C5_TIMER_GROUP_COUNT           2U
#define ESP32C5_TIMER_PER_GROUP_COUNT       1U
#define ESP32C5_TIMER_COUNT                 2U
#define ESP32C5_SYSTIMER_COUNT              1U
#define ESP32C5_SYSTIMER_COUNTER_COUNT      2U
#define ESP32C5_SYSTIMER_ALARM_COUNT        3U
#define ESP32C5_GDMA_COUNT                  1U
#define ESP32C5_GDMA_PAIR_COUNT             3U
#define ESP32C5_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32C5_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32C5_GPIO_PORT_COUNT             1U
#define ESP32C5_GPIO_PIN_COUNT              29U
#define ESP32C5_GPIO_PIN_MAX                28U
#define ESP32C5_GPIO_PIN_REG_COUNT          33U
#define ESP32C5_GPIO_FUNC_IN_COUNT          256U
#define ESP32C5_GPIO_FUNC_OUT_COUNT         29U
#define ESP32C5_GPIO_FUNC_OUT_REG_COUNT     33U
#define ESP32C5_ADC_COUNT                   1U
#define ESP32C5_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32C5_UHCI_COUNT                  1U
#define ESP32C5_USB_SERIAL_JTAG_COUNT       1U
#define ESP32C5_AES_COUNT                   1U
#define ESP32C5_SHA_COUNT                   1U
#define ESP32C5_RSA_COUNT                   1U
#define ESP32C5_RSA_DS_COUNT                1U
#define ESP32C5_HMAC_COUNT                  1U
#define ESP32C5_ECC_COUNT                   1U
#define ESP32C5_ECDSA_COUNT                 1U
#define ESP32C5_KEYMNG_COUNT                1U
#define ESP32C5_HUK_COUNT                   1U
#define ESP32C5_EFUSE_COUNT                 1U
#define ESP32C5_INTMTX_COUNT                1U
#define ESP32C5_INTPRI_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32C5_*
 *
 * Every ESP32C5_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32C5_UART0_BASE
#define ESP32_UART1_BASE                        ESP32C5_UART1_BASE
#define ESP32_SPIMEM0_BASE                      ESP32C5_SPIMEM0_BASE
#define ESP32_SPIMEM1_BASE                      ESP32C5_SPIMEM1_BASE
#define ESP32_I2C_BASE                          ESP32C5_I2C_BASE
#define ESP32_UHCI_BASE                         ESP32C5_UHCI_BASE
#define ESP32_RMT_BASE                          ESP32C5_RMT_BASE
#define ESP32_LEDC_BASE                         ESP32C5_LEDC_BASE
#define ESP32_TIMG0_BASE                        ESP32C5_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32C5_TIMG1_BASE
#define ESP32_SYSTIMER_BASE                     ESP32C5_SYSTIMER_BASE
#define ESP32_TWAI0_BASE                        ESP32C5_TWAI0_BASE
#define ESP32_I2S_BASE                          ESP32C5_I2S_BASE
#define ESP32_TWAI1_BASE                        ESP32C5_TWAI1_BASE
#define ESP32_SAR_ADC_BASE                      ESP32C5_SAR_ADC_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32C5_USB_SERIAL_JTAG_BASE
#define ESP32_INTMTX_BASE                       ESP32C5_INTMTX_BASE
#define ESP32_PCNT_BASE                         ESP32C5_PCNT_BASE
#define ESP32_SOC_ETM_BASE                      ESP32C5_SOC_ETM_BASE
#define ESP32_MCPWM_BASE                        ESP32C5_MCPWM_BASE
#define ESP32_PARL_IO_BASE                      ESP32C5_PARL_IO_BASE
#define ESP32_SDIO_HINF_BASE                    ESP32C5_SDIO_HINF_BASE
#define ESP32_SDIO_SLC_BASE                     ESP32C5_SDIO_SLC_BASE
#define ESP32_SDIO_SLCHOST_BASE                 ESP32C5_SDIO_SLCHOST_BASE
#define ESP32_PVT_MONITOR_BASE                  ESP32C5_PVT_MONITOR_BASE
#define ESP32_PSRAM_MEM_MONITOR_BASE            ESP32C5_PSRAM_MEM_MONITOR_BASE
#define ESP32_GDMA_BASE                         ESP32C5_GDMA_BASE
#define ESP32_AHB_DMA_BASE                      ESP32C5_AHB_DMA_BASE
#define ESP32_GP_SPI2_BASE                      ESP32C5_GP_SPI2_BASE
#define ESP32_SPI2_BASE                         ESP32C5_SPI2_BASE
#define ESP32_BITSCRAMBLER_BASE                 ESP32C5_BITSCRAMBLER_BASE
#define ESP32_KEYMNG_BASE                       ESP32C5_KEYMNG_BASE
#define ESP32_AES_BASE                          ESP32C5_AES_BASE
#define ESP32_SHA_BASE                          ESP32C5_SHA_BASE
#define ESP32_RSA_BASE                          ESP32C5_RSA_BASE
#define ESP32_ECC_BASE                          ESP32C5_ECC_BASE
#define ESP32_ECC_MULT_BASE                     ESP32C5_ECC_MULT_BASE
#define ESP32_RSA_DS_BASE                       ESP32C5_RSA_DS_BASE
#define ESP32_DS_BASE                           ESP32C5_DS_BASE
#define ESP32_HMAC_BASE                         ESP32C5_HMAC_BASE
#define ESP32_ECDSA_BASE                        ESP32C5_ECDSA_BASE
#define ESP32_IOMUX_BASE                        ESP32C5_IOMUX_BASE
#define ESP32_GPIO_BASE                         ESP32C5_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32C5_GPIO_EXT_BASE
#define ESP32_MEM_MONITOR_BASE                  ESP32C5_MEM_MONITOR_BASE
#define ESP32_PAU_BASE                          ESP32C5_PAU_BASE
#define ESP32_HP_SYSREG_BASE                    ESP32C5_HP_SYSREG_BASE
#define ESP32_PCR_BASE                          ESP32C5_PCR_BASE
#define ESP32_TEE_BASE                          ESP32C5_TEE_BASE
#define ESP32_HP_APM_BASE                       ESP32C5_HP_APM_BASE
#define ESP32_LP_APM0_BASE                      ESP32C5_LP_APM0_BASE
#define ESP32_CPU_APM_BASE                      ESP32C5_CPU_APM_BASE
#define ESP32_MISC_BASE                         ESP32C5_MISC_BASE
#define ESP32_MODEM0_BASE                       ESP32C5_MODEM0_BASE
#define ESP32_IEEE802154_BASE                   ESP32C5_IEEE802154_BASE
#define ESP32_MODEM1_BASE                       ESP32C5_MODEM1_BASE
#define ESP32_MODEM_PWR0_BASE                   ESP32C5_MODEM_PWR0_BASE
#define ESP32_MODEM_PWR1_BASE                   ESP32C5_MODEM_PWR1_BASE
#define ESP32_I2C_ANA_MST_BASE                  ESP32C5_I2C_ANA_MST_BASE
#define ESP32_PMU_BASE                          ESP32C5_PMU_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32C5_LP_CLKRST_BASE
#define ESP32_LP_TIMER_BASE                     ESP32C5_LP_TIMER_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32C5_RTC_TIMER_BASE
#define ESP32_LP_AON_BASE                       ESP32C5_LP_AON_BASE
#define ESP32_LP_UART_BASE                      ESP32C5_LP_UART_BASE
#define ESP32_LP_I2C_BASE                       ESP32C5_LP_I2C_BASE
#define ESP32_LP_WDT_BASE                       ESP32C5_LP_WDT_BASE
#define ESP32_RTC_WDT_BASE                      ESP32C5_RTC_WDT_BASE
#define ESP32_LP_I2C_ANA_MST_BASE               ESP32C5_LP_I2C_ANA_MST_BASE
#define ESP32_LPPERI_BASE                       ESP32C5_LPPERI_BASE
#define ESP32_LP_ANA_BASE                       ESP32C5_LP_ANA_BASE
#define ESP32_HUK_BASE                          ESP32C5_HUK_BASE
#define ESP32_LP_TEE_BASE                       ESP32C5_LP_TEE_BASE
#define ESP32_LP_APM_BASE                       ESP32C5_LP_APM_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32C5_LP_IOMUX_BASE
#define ESP32_LP_GPIO_BASE                      ESP32C5_LP_GPIO_BASE
#define ESP32_EFUSE_BASE                        ESP32C5_EFUSE_BASE
#define ESP32_OTP_DEBUG_BASE                    ESP32C5_OTP_DEBUG_BASE
#define ESP32_TRACE_BASE                        ESP32C5_TRACE_BASE
#define ESP32_BUS_MONITOR_BASE                  ESP32C5_BUS_MONITOR_BASE
#define ESP32_INTPRI_BASE                       ESP32C5_INTPRI_BASE
#define ESP32_CACHE_BASE                        ESP32C5_CACHE_BASE
#define ESP32_CLINT_M_BASE                      ESP32C5_CLINT_M_BASE
#define ESP32_ETS_MAX_INUM                      ESP32C5_ETS_MAX_INUM
#define ESP32_ETS_SLC_INUM                      ESP32C5_ETS_SLC_INUM
#define ESP32_ETS_UART0_INUM                    ESP32C5_ETS_UART0_INUM
#define ESP32_ETS_UART1_INUM                    ESP32C5_ETS_UART1_INUM
#define ESP32_ETS_SPI2_INUM                     ESP32C5_ETS_SPI2_INUM
#define ESP32_ETS_GPIO_INUM                     ESP32C5_ETS_GPIO_INUM
#define ESP32_ETS_INVALID_INUM                  ESP32C5_ETS_INVALID_INUM
#define ESP32_CPU_CORE_COUNT                    ESP32C5_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32C5_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32C5_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32C5_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32C5_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32C5_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32C5_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32C5_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32C5_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32C5_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32C5_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32C5_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32C5_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32C5_LEDC_COUNT
#define ESP32_PCNT_COUNT                        ESP32C5_PCNT_COUNT
#define ESP32_ETM_COUNT                         ESP32C5_ETM_COUNT
#define ESP32_MCPWM_COUNT                       ESP32C5_MCPWM_COUNT
#define ESP32_PARL_IO_COUNT                     ESP32C5_PARL_IO_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32C5_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32C5_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32C5_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32C5_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32C5_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32C5_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32C5_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32C5_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32C5_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32C5_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32C5_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32C5_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32C5_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32C5_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32C5_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32C5_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32C5_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32C5_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32C5_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32C5_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32C5_USB_SERIAL_JTAG_COUNT
#define ESP32_AES_COUNT                         ESP32C5_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32C5_SHA_COUNT
#define ESP32_RSA_COUNT                         ESP32C5_RSA_COUNT
#define ESP32_RSA_DS_COUNT                      ESP32C5_RSA_DS_COUNT
#define ESP32_HMAC_COUNT                        ESP32C5_HMAC_COUNT
#define ESP32_ECC_COUNT                         ESP32C5_ECC_COUNT
#define ESP32_ECDSA_COUNT                       ESP32C5_ECDSA_COUNT
#define ESP32_KEYMNG_COUNT                      ESP32C5_KEYMNG_COUNT
#define ESP32_HUK_COUNT                         ESP32C5_HUK_COUNT
#define ESP32_EFUSE_COUNT                       ESP32C5_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32C5_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32C5_INTPRI_COUNT

#endif // __ESP32C5_H__
