/**-------------------------------------------------------------------------
@file	esp32c3.h

@brief	ESP32-C3 chip-specific definition.

Single-core 32-bit RISC-V at up to 160 MHz, Wi-Fi 4 (2.4 GHz) + BLE 5,
22 GPIOs, 32 CPU interrupts via the older SYSTEM/INTMTX block (no separate
INTPRI register).  Peripheral clock-gating goes through SYSTEM (not PCR).

Defines the chip-specific ESP32C3_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32c3/register/soc/reg_base.h
   components/soc/esp32c3/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026 (consolidation)

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32C3_H__
#define __ESP32C3_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32C3_UART0_BASE                  0x60000000UL    //!< UART0
#define ESP32C3_SPI1_BASE                   0x60002000UL    //!< MSPI flash 1
#define ESP32C3_SPI0_BASE                   0x60003000UL    //!< MSPI flash 0
#define ESP32C3_GPIO_BASE                   0x60004000UL
#define ESP32C3_LP_MGNT_BASE                0x60008000UL
#define ESP32C3_IOMUX_BASE                  0x60009000UL
#define ESP32C3_UART1_BASE                  0x60010000UL    //!< UART1
#define ESP32C3_I2C_BASE                    0x60013000UL
#define ESP32C3_UHCI0_BASE                  0x60014000UL
#define ESP32C3_RMT_BASE                    0x60016000UL    //!< Remote control
#define ESP32C3_LEDC_BASE                   0x60019000UL    //!< LED PWM controller
#define ESP32C3_EFUSE_BASE                  0x6001A000UL
#define ESP32C3_TIMG0_BASE                  0x6001F000UL    //!< Timer group 0
#define ESP32C3_TIMG1_BASE                  0x60020000UL    //!< Timer group 1
#define ESP32C3_SYSTIMER_BASE               0x60023000UL    //!< System timer
#define ESP32C3_SPI2_BASE                   0x60024000UL    //!< GP-SPI2
#define ESP32C3_SYSCON_BASE                 0x60026000UL
#define ESP32C3_TWAI_BASE                   0x6002B000UL    //!< Two-wire Automotive Interface
#define ESP32C3_I2S_BASE                    0x6002D000UL
#define ESP32C3_AES_BASE                    0x6003A000UL
#define ESP32C3_SHA_BASE                    0x6003B000UL
#define ESP32C3_RSA_BASE                    0x6003C000UL
#define ESP32C3_RSA_DS_BASE                 0x6003D000UL
#define ESP32C3_HMAC_BASE                   0x6003E000UL
#define ESP32C3_GDMA_BASE                   0x6003F000UL
#define ESP32C3_ADC_BASE                    0x60040000UL    //!< Successive approximation ADC
#define ESP32C3_USB_SERIAL_JTAG_BASE        0x60043000UL
#define ESP32C3_SYSTEM_BASE                 0x600C0000UL    //!< SYSTEM (peripheral clock-gating)
#define ESP32C3_PMS_BASE                    0x600C1000UL
#define ESP32C3_INTMTX_BASE                 0x600C2000UL    //!< Interrupt matrix
#define ESP32C3_XTS_AES_BASE                0x600CC000UL    //!< External memory encryption
#define ESP32C3_ASSIST_DEBUG_BASE           0x600CE000UL
#define ESP32C3_WORLD_CTRL_BASE             0x600D0000UL

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32C3_CPU_CORE_COUNT              1U
#define ESP32C3_CPU_INTERRUPT_COUNT         32U
#define ESP32C3_UART_COUNT                  2U
#define ESP32C3_HP_UART_COUNT               2U
#define ESP32C3_LP_UART_COUNT               0U
#define ESP32C3_SPI_MEM_COUNT               2U      //!< SPI0/SPI1 memory controllers
#define ESP32C3_GP_SPI_COUNT                1U      //!< GP-SPI2
#define ESP32C3_I2C_COUNT                   1U
#define ESP32C3_HP_I2C_COUNT                1U
#define ESP32C3_LP_I2C_COUNT                0U
#define ESP32C3_I2S_COUNT                   1U
#define ESP32C3_TWAI_COUNT                  1U
#define ESP32C3_RMT_COUNT                   1U
#define ESP32C3_LEDC_COUNT                  1U
#define ESP32C3_TIMER_GROUP_COUNT           2U
#define ESP32C3_TIMER_PER_GROUP_COUNT       1U
#define ESP32C3_TIMER_COUNT                 2U
#define ESP32C3_SYSTIMER_COUNT              1U
#define ESP32C3_SYSTIMER_COUNTER_COUNT      2U
#define ESP32C3_SYSTIMER_ALARM_COUNT        3U
#define ESP32C3_GDMA_COUNT                  1U
#define ESP32C3_GDMA_PAIR_COUNT             3U
#define ESP32C3_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32C3_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32C3_GPIO_PORT_COUNT             1U
#define ESP32C3_GPIO_PIN_COUNT              22U
#define ESP32C3_GPIO_PIN_MAX                21U
#define ESP32C3_GPIO_PIN_REG_COUNT          22U
#define ESP32C3_GPIO_FUNC_IN_COUNT          128U
#define ESP32C3_GPIO_FUNC_OUT_COUNT         22U
#define ESP32C3_GPIO_FUNC_OUT_REG_COUNT     22U
#define ESP32C3_ADC_COUNT                   2U
#define ESP32C3_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32C3_UHCI_COUNT                  1U
#define ESP32C3_USB_SERIAL_JTAG_COUNT       1U
#define ESP32C3_AES_COUNT                   1U
#define ESP32C3_SHA_COUNT                   1U
#define ESP32C3_RSA_COUNT                   1U
#define ESP32C3_RSA_DS_COUNT                1U
#define ESP32C3_HMAC_COUNT                  1U
#define ESP32C3_EFUSE_COUNT                 1U
#define ESP32C3_INTMTX_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *
 * Set the variant prefix and capability flags; esp32xx_aliases.h (pulled in
 * by esp32xx.h) emits the chip-agnostic ESP32_* aliases.
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32C3_*
 *
 * Every ESP32C3_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32C3_UART0_BASE
#define ESP32_SPI1_BASE                         ESP32C3_SPI1_BASE
#define ESP32_SPI0_BASE                         ESP32C3_SPI0_BASE
#define ESP32_GPIO_BASE                         ESP32C3_GPIO_BASE
#define ESP32_LP_MGNT_BASE                      ESP32C3_LP_MGNT_BASE
#define ESP32_IOMUX_BASE                        ESP32C3_IOMUX_BASE
#define ESP32_UART1_BASE                        ESP32C3_UART1_BASE
#define ESP32_I2C_BASE                          ESP32C3_I2C_BASE
#define ESP32_UHCI0_BASE                        ESP32C3_UHCI0_BASE
#define ESP32_RMT_BASE                          ESP32C3_RMT_BASE
#define ESP32_LEDC_BASE                         ESP32C3_LEDC_BASE
#define ESP32_EFUSE_BASE                        ESP32C3_EFUSE_BASE
#define ESP32_TIMG0_BASE                        ESP32C3_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32C3_TIMG1_BASE
#define ESP32_SYSTIMER_BASE                     ESP32C3_SYSTIMER_BASE
#define ESP32_SPI2_BASE                         ESP32C3_SPI2_BASE
#define ESP32_SYSCON_BASE                       ESP32C3_SYSCON_BASE
#define ESP32_TWAI_BASE                         ESP32C3_TWAI_BASE
#define ESP32_I2S_BASE                          ESP32C3_I2S_BASE
#define ESP32_AES_BASE                          ESP32C3_AES_BASE
#define ESP32_SHA_BASE                          ESP32C3_SHA_BASE
#define ESP32_RSA_BASE                          ESP32C3_RSA_BASE
#define ESP32_RSA_DS_BASE                       ESP32C3_RSA_DS_BASE
#define ESP32_HMAC_BASE                         ESP32C3_HMAC_BASE
#define ESP32_GDMA_BASE                         ESP32C3_GDMA_BASE
#define ESP32_ADC_BASE                          ESP32C3_ADC_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32C3_USB_SERIAL_JTAG_BASE
#define ESP32_SYSTEM_BASE                       ESP32C3_SYSTEM_BASE
#define ESP32_PMS_BASE                          ESP32C3_PMS_BASE
#define ESP32_INTMTX_BASE                       ESP32C3_INTMTX_BASE
#define ESP32_XTS_AES_BASE                      ESP32C3_XTS_AES_BASE
#define ESP32_ASSIST_DEBUG_BASE                 ESP32C3_ASSIST_DEBUG_BASE
#define ESP32_WORLD_CTRL_BASE                   ESP32C3_WORLD_CTRL_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32C3_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32C3_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32C3_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32C3_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32C3_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32C3_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32C3_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32C3_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32C3_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32C3_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32C3_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32C3_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32C3_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32C3_LEDC_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32C3_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32C3_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32C3_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32C3_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32C3_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32C3_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32C3_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32C3_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32C3_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32C3_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32C3_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32C3_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32C3_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32C3_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32C3_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32C3_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32C3_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32C3_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32C3_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32C3_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32C3_USB_SERIAL_JTAG_COUNT
#define ESP32_AES_COUNT                         ESP32C3_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32C3_SHA_COUNT
#define ESP32_RSA_COUNT                         ESP32C3_RSA_COUNT
#define ESP32_RSA_DS_COUNT                      ESP32C3_RSA_DS_COUNT
#define ESP32_HMAC_COUNT                        ESP32C3_HMAC_COUNT
#define ESP32_EFUSE_COUNT                       ESP32C3_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32C3_INTMTX_COUNT

#endif // __ESP32C3_H__
