/**-------------------------------------------------------------------------
@file	esp32c6.h

@brief	ESP32-C6 chip-specific definition.

HP RISC-V at 160 MHz + LP RISC-V at 20 MHz, Wi-Fi 6 (2.4 GHz) + BLE 5.3 +
802.15.4 (Thread/Zigbee/Matter), 31 GPIOs, PCR-based peripheral clock-
gating, dedicated INTMTX + INTPRI.

Defines the chip-specific ESP32C6_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32c6/register/soc/reg_base.h
   components/soc/esp32c6/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026 (consolidation)

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32C6_H__
#define __ESP32C6_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32C6_UART0_BASE                  0x60000000UL
#define ESP32C6_UART1_BASE                  0x60001000UL
#define ESP32C6_SPI0_BASE                   0x60002000UL    //!< MSPI0 (alias: SPIMEM0)
#define ESP32C6_SPI1_BASE                   0x60003000UL    //!< MSPI1 (alias: SPIMEM1)
#define ESP32C6_SPIMEM0_BASE                ESP32C6_SPI0_BASE
#define ESP32C6_SPIMEM1_BASE                ESP32C6_SPI1_BASE
#define ESP32C6_XTS_AES_BASE                0x60002000UL    //!< Shares MSPI0 window
#define ESP32C6_I2C_BASE                    0x60004000UL
#define ESP32C6_UHCI_BASE                   0x60005000UL
#define ESP32C6_RMT_BASE                    0x60006000UL
#define ESP32C6_LEDC_BASE                   0x60007000UL
#define ESP32C6_TIMG0_BASE                  0x60008000UL
#define ESP32C6_TIMG1_BASE                  0x60009000UL
#define ESP32C6_SYSTIMER_BASE               0x6000A000UL
#define ESP32C6_TWAI0_BASE                  0x6000B000UL
#define ESP32C6_I2S_BASE                    0x6000C000UL
#define ESP32C6_TWAI1_BASE                  0x6000D000UL
#define ESP32C6_SAR_ADC_BASE                0x6000E000UL
#define ESP32C6_USB_SERIAL_JTAG_BASE               0x6000F000UL
#define ESP32C6_INTMTX_BASE                 0x60010000UL
#define ESP32C6_ATOMIC_BASE                 0x60011000UL    //!< Atomic ops emulator
#define ESP32C6_PCNT_BASE                   0x60012000UL
#define ESP32C6_SOC_ETM_BASE                0x60013000UL
#define ESP32C6_MCPWM_BASE                  0x60014000UL
#define ESP32C6_PARL_IO_BASE                0x60015000UL
#define ESP32C6_SDIO_HINF_BASE              0x60016000UL
#define ESP32C6_SDIO_SLC_BASE               0x60017000UL
#define ESP32C6_SDIO_SLCHOST_BASE           0x60018000UL
#define ESP32C6_PVT_MONITOR_BASE            0x60019000UL
#define ESP32C6_GDMA_BASE                   0x60080000UL
#define ESP32C6_GP_SPI2_BASE                0x60081000UL
#define ESP32C6_SPI2_BASE                   ESP32C6_GP_SPI2_BASE
#define ESP32C6_AES_BASE                    0x60088000UL
#define ESP32C6_SHA_BASE                    0x60089000UL
#define ESP32C6_RSA_BASE                    0x6008A000UL
#define ESP32C6_ECC_BASE                    0x6008B000UL
#define ESP32C6_RSA_DS_BASE                 0x6008C000UL
#define ESP32C6_HMAC_BASE                   0x6008D000UL
#define ESP32C6_IOMUX_BASE                  0x60090000UL
#define ESP32C6_GPIO_MATRIX_BASE            0x60091000UL
#define ESP32C6_GPIO_BASE                   ESP32C6_GPIO_MATRIX_BASE
#define ESP32C6_GPIO_EXT_BASE               0x60091F00UL
#define ESP32C6_MEM_MONITOR_BASE            0x60092000UL
#define ESP32C6_HP_SYSREG_BASE              0x60095000UL
#define ESP32C6_PCR_BASE                    0x60096000UL
#define ESP32C6_TEE_BASE                    0x60098000UL
#define ESP32C6_HP_APM_BASE                 0x60099000UL
#define ESP32C6_PMU_BASE                    0x600B0000UL
#define ESP32C6_LP_CLKRST_BASE              0x600B0400UL
#define ESP32C6_EFUSE_BASE                  0x600B0800UL
#define ESP32C6_RTC_TIMER_BASE              0x600B0C00UL
#define ESP32C6_LP_TIMER_BASE               ESP32C6_RTC_TIMER_BASE
#define ESP32C6_LP_AON_BASE                 0x600B1000UL    //!< Low-power Always-on Register
#define ESP32C6_LP_AON_BASE_PERI_BASE       0x600B2C00UL    //!< Low-power Analog Peripheral (alias kept for source compatibility)
#define ESP32C6_LP_UART_BASE                0x600B1400UL
#define ESP32C6_LP_I2C_BASE                 0x600B1800UL
#define ESP32C6_RTC_WDT_BASE                0x600B1C00UL
#define ESP32C6_LP_WDT_BASE                 ESP32C6_RTC_WDT_BASE
#define ESP32C6_LP_IOMUX_BASE               0x600B2000UL
#define ESP32C6_I2C_ANA_MST_BASE            0x600B2400UL
#define ESP32C6_LPPERI_BASE                 0x600B2800UL
#define ESP32C6_LP_ANA_BASE                 0x600B2C00UL
#define ESP32C6_LP_GPIO_BASE                ESP32C6_LP_IOMUX_BASE   //!< C6 alias: LP IO_MUX is the LP GPIO block
#define ESP32C6_LP_TEE_BASE                 0x600B3400UL
#define ESP32C6_LP_APM_BASE                 0x600B3800UL
#define ESP32C6_TRACE_BASE                  0x600C0000UL
#define ESP32C6_ASSIST_DEBUG_BASE           0x600C2000UL
#define ESP32C6_INTPRI_BASE                 0x600C5000UL

#define ESP32C6_CLINT_M_BASE                0x20001800UL    //!< RISC-V CLINT machine-mode
#define ESP32C6_PLIC_MX_BASE                0x20001000UL    //!< RISC-V PLIC machine-mode external
#define ESP32C6_PLIC_UX_BASE                0x20001400UL    //!< RISC-V PLIC user-mode external

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32C6_CPU_CORE_COUNT              1U      //!< 1 HP core (LP core is separate, controlled by LPPERI)
#define ESP32C6_CPU_INTERRUPT_COUNT         32U
#define ESP32C6_UART_COUNT                  3U      //!< 2 HP + 1 LP
#define ESP32C6_HP_UART_COUNT               2U
#define ESP32C6_LP_UART_COUNT               1U
#define ESP32C6_SPI_MEM_COUNT               2U      //!< SPIMEM0 / SPIMEM1
#define ESP32C6_GP_SPI_COUNT                1U      //!< GP-SPI2
#define ESP32C6_I2C_COUNT                   2U
#define ESP32C6_HP_I2C_COUNT                1U
#define ESP32C6_LP_I2C_COUNT                1U
#define ESP32C6_I2S_COUNT                   1U
#define ESP32C6_TWAI_COUNT                  2U
#define ESP32C6_RMT_COUNT                   1U
#define ESP32C6_LEDC_COUNT                  1U
#define ESP32C6_PCNT_COUNT                  1U
#define ESP32C6_ETM_COUNT                   1U
#define ESP32C6_MCPWM_COUNT                 1U
#define ESP32C6_PARL_IO_COUNT               1U
#define ESP32C6_TIMER_GROUP_COUNT           2U
#define ESP32C6_TIMER_PER_GROUP_COUNT       1U
#define ESP32C6_TIMER_COUNT                 2U
#define ESP32C6_SYSTIMER_COUNT              1U
#define ESP32C6_SYSTIMER_COUNTER_COUNT      2U
#define ESP32C6_SYSTIMER_ALARM_COUNT        3U
#define ESP32C6_GDMA_COUNT                  1U
#define ESP32C6_GDMA_PAIR_COUNT             3U
#define ESP32C6_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32C6_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32C6_GPIO_PORT_COUNT             1U
#define ESP32C6_GPIO_PIN_COUNT              31U
#define ESP32C6_GPIO_PIN_MAX                30U
#define ESP32C6_GPIO_PIN_REG_COUNT          31U
#define ESP32C6_GPIO_FUNC_IN_COUNT          128U
#define ESP32C6_GPIO_FUNC_OUT_COUNT         31U
#define ESP32C6_GPIO_FUNC_OUT_REG_COUNT     31U
#define ESP32C6_ADC_COUNT                   1U
#define ESP32C6_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32C6_UHCI_COUNT                  1U
#define ESP32C6_USB_SERIAL_JTAG_COUNT       1U
#define ESP32C6_AES_COUNT                   1U
#define ESP32C6_SHA_COUNT                   1U
#define ESP32C6_RSA_COUNT                   1U
#define ESP32C6_RSA_DS_COUNT                1U
#define ESP32C6_HMAC_COUNT                  1U
#define ESP32C6_ECC_COUNT                   1U
#define ESP32C6_EFUSE_COUNT                 1U
#define ESP32C6_INTMTX_COUNT                1U
#define ESP32C6_INTPRI_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32C6_*
 *
 * Every ESP32C6_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32C6_UART0_BASE
#define ESP32_UART1_BASE                        ESP32C6_UART1_BASE
#define ESP32_SPI0_BASE                         ESP32C6_SPI0_BASE
#define ESP32_SPI1_BASE                         ESP32C6_SPI1_BASE
#define ESP32_SPIMEM0_BASE                      ESP32C6_SPIMEM0_BASE
#define ESP32_SPIMEM1_BASE                      ESP32C6_SPIMEM1_BASE
#define ESP32_XTS_AES_BASE                      ESP32C6_XTS_AES_BASE
#define ESP32_I2C_BASE                          ESP32C6_I2C_BASE
#define ESP32_UHCI_BASE                         ESP32C6_UHCI_BASE
#define ESP32_RMT_BASE                          ESP32C6_RMT_BASE
#define ESP32_LEDC_BASE                         ESP32C6_LEDC_BASE
#define ESP32_TIMG0_BASE                        ESP32C6_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32C6_TIMG1_BASE
#define ESP32_SYSTIMER_BASE                     ESP32C6_SYSTIMER_BASE
#define ESP32_TWAI0_BASE                        ESP32C6_TWAI0_BASE
#define ESP32_I2S_BASE                          ESP32C6_I2S_BASE
#define ESP32_TWAI1_BASE                        ESP32C6_TWAI1_BASE
#define ESP32_SAR_ADC_BASE                      ESP32C6_SAR_ADC_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32C6_USB_SERIAL_JTAG_BASE
#define ESP32_INTMTX_BASE                       ESP32C6_INTMTX_BASE
#define ESP32_ATOMIC_BASE                       ESP32C6_ATOMIC_BASE
#define ESP32_PCNT_BASE                         ESP32C6_PCNT_BASE
#define ESP32_SOC_ETM_BASE                      ESP32C6_SOC_ETM_BASE
#define ESP32_MCPWM_BASE                        ESP32C6_MCPWM_BASE
#define ESP32_PARL_IO_BASE                      ESP32C6_PARL_IO_BASE
#define ESP32_SDIO_HINF_BASE                    ESP32C6_SDIO_HINF_BASE
#define ESP32_SDIO_SLC_BASE                     ESP32C6_SDIO_SLC_BASE
#define ESP32_SDIO_SLCHOST_BASE                 ESP32C6_SDIO_SLCHOST_BASE
#define ESP32_PVT_MONITOR_BASE                  ESP32C6_PVT_MONITOR_BASE
#define ESP32_GDMA_BASE                         ESP32C6_GDMA_BASE
#define ESP32_GP_SPI2_BASE                      ESP32C6_GP_SPI2_BASE
#define ESP32_SPI2_BASE                         ESP32C6_SPI2_BASE
#define ESP32_AES_BASE                          ESP32C6_AES_BASE
#define ESP32_SHA_BASE                          ESP32C6_SHA_BASE
#define ESP32_RSA_BASE                          ESP32C6_RSA_BASE
#define ESP32_ECC_BASE                          ESP32C6_ECC_BASE
#define ESP32_RSA_DS_BASE                       ESP32C6_RSA_DS_BASE
#define ESP32_HMAC_BASE                         ESP32C6_HMAC_BASE
#define ESP32_IOMUX_BASE                        ESP32C6_IOMUX_BASE
#define ESP32_GPIO_MATRIX_BASE                  ESP32C6_GPIO_MATRIX_BASE
#define ESP32_GPIO_BASE                         ESP32C6_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32C6_GPIO_EXT_BASE
#define ESP32_MEM_MONITOR_BASE                  ESP32C6_MEM_MONITOR_BASE
#define ESP32_HP_SYSREG_BASE                    ESP32C6_HP_SYSREG_BASE
#define ESP32_PCR_BASE                          ESP32C6_PCR_BASE
#define ESP32_TEE_BASE                          ESP32C6_TEE_BASE
#define ESP32_HP_APM_BASE                       ESP32C6_HP_APM_BASE
#define ESP32_PMU_BASE                          ESP32C6_PMU_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32C6_LP_CLKRST_BASE
#define ESP32_EFUSE_BASE                        ESP32C6_EFUSE_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32C6_RTC_TIMER_BASE
#define ESP32_LP_TIMER_BASE                     ESP32C6_LP_TIMER_BASE
#define ESP32_LP_AON_BASE                       ESP32C6_LP_AON_BASE
#define ESP32_LP_AON_BASE_PERI_BASE             ESP32C6_LP_AON_BASE_PERI_BASE
#define ESP32_LP_UART_BASE                      ESP32C6_LP_UART_BASE
#define ESP32_LP_I2C_BASE                       ESP32C6_LP_I2C_BASE
#define ESP32_RTC_WDT_BASE                      ESP32C6_RTC_WDT_BASE
#define ESP32_LP_WDT_BASE                       ESP32C6_LP_WDT_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32C6_LP_IOMUX_BASE
#define ESP32_I2C_ANA_MST_BASE                  ESP32C6_I2C_ANA_MST_BASE
#define ESP32_LPPERI_BASE                       ESP32C6_LPPERI_BASE
#define ESP32_LP_ANA_BASE                       ESP32C6_LP_ANA_BASE
#define ESP32_LP_GPIO_BASE                      ESP32C6_LP_GPIO_BASE
#define ESP32_LP_TEE_BASE                       ESP32C6_LP_TEE_BASE
#define ESP32_LP_APM_BASE                       ESP32C6_LP_APM_BASE
#define ESP32_TRACE_BASE                        ESP32C6_TRACE_BASE
#define ESP32_ASSIST_DEBUG_BASE                 ESP32C6_ASSIST_DEBUG_BASE
#define ESP32_INTPRI_BASE                       ESP32C6_INTPRI_BASE
#define ESP32_CLINT_M_BASE                      ESP32C6_CLINT_M_BASE
#define ESP32_PLIC_MX_BASE                      ESP32C6_PLIC_MX_BASE
#define ESP32_PLIC_UX_BASE                      ESP32C6_PLIC_UX_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32C6_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32C6_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32C6_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32C6_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32C6_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32C6_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32C6_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32C6_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32C6_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32C6_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32C6_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32C6_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32C6_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32C6_LEDC_COUNT
#define ESP32_PCNT_COUNT                        ESP32C6_PCNT_COUNT
#define ESP32_ETM_COUNT                         ESP32C6_ETM_COUNT
#define ESP32_MCPWM_COUNT                       ESP32C6_MCPWM_COUNT
#define ESP32_PARL_IO_COUNT                     ESP32C6_PARL_IO_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32C6_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32C6_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32C6_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32C6_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32C6_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32C6_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32C6_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32C6_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32C6_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32C6_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32C6_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32C6_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32C6_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32C6_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32C6_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32C6_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32C6_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32C6_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32C6_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32C6_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32C6_USB_SERIAL_JTAG_COUNT
#define ESP32_AES_COUNT                         ESP32C6_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32C6_SHA_COUNT
#define ESP32_RSA_COUNT                         ESP32C6_RSA_COUNT
#define ESP32_RSA_DS_COUNT                      ESP32C6_RSA_DS_COUNT
#define ESP32_HMAC_COUNT                        ESP32C6_HMAC_COUNT
#define ESP32_ECC_COUNT                         ESP32C6_ECC_COUNT
#define ESP32_EFUSE_COUNT                       ESP32C6_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32C6_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32C6_INTPRI_COUNT

#endif // __ESP32C6_H__
