/**-------------------------------------------------------------------------
@file	esp32h2.h

@brief	ESP32-H2 chip-specific definition.

Single-core 32-bit RISC-V at up to 96 MHz, BLE 5 + 802.15.4 (Thread /
Zigbee / Matter), no Wi-Fi.  28 GPIOs.  Uses PCR for peripheral
clock-gating, dedicated INTMTX + INTPRI.

Designed as a low-power 802.15.4 endpoint chip; typically paired with a
Wi-Fi host like C6 or C5 for Matter bridges.

Defines the chip-specific ESP32H2_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32h2/register/soc/reg_base.h
   components/soc/esp32h2/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32H2_H__
#define __ESP32H2_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32H2_UART0_BASE                  0x60000000UL
#define ESP32H2_UART1_BASE                  0x60001000UL
#define ESP32H2_SPI0_BASE                   0x60002000UL    //!< MSPI 0
#define ESP32H2_SPI1_BASE                   0x60003000UL    //!< MSPI 1
#define ESP32H2_SPIMEM0_BASE                ESP32H2_SPI0_BASE
#define ESP32H2_SPIMEM1_BASE                ESP32H2_SPI1_BASE
#define ESP32H2_I2C0_BASE                   0x60004000UL    //!< I2C bus 0
#define ESP32H2_I2C1_BASE                   0x60005000UL    //!< I2C bus 1
#define ESP32H2_I2C_BASE                    ESP32H2_I2C0_BASE
#define ESP32H2_UHCI_BASE                   0x60006000UL
#define ESP32H2_RMT_BASE                    0x60007000UL
#define ESP32H2_LEDC_BASE                   0x60008000UL
#define ESP32H2_TIMG0_BASE                  0x60009000UL
#define ESP32H2_TIMG1_BASE                  0x6000A000UL
#define ESP32H2_SYSTIMER_BASE               0x6000B000UL
#define ESP32H2_TWAI_BASE                   0x6000C000UL
#define ESP32H2_I2S_BASE                    0x6000D000UL
#define ESP32H2_APB_SARADC_BASE             0x6000E000UL
#define ESP32H2_USB_SERIAL_JTAG_BASE        0x6000F000UL
#define ESP32H2_INTMTX_BASE                 0x60010000UL
#define ESP32H2_PCNT_BASE                   0x60012000UL
#define ESP32H2_SOC_ETM_BASE                0x60013000UL
#define ESP32H2_MCPWM_BASE                  0x60014000UL
#define ESP32H2_PARL_IO_BASE                0x60015000UL
#define ESP32H2_PVT_MONITOR_BASE            0x60019000UL

#define ESP32H2_GDMA_BASE                   0x60080000UL
#define ESP32H2_GP_SPI2_BASE                0x60081000UL
#define ESP32H2_SPI2_BASE                   ESP32H2_GP_SPI2_BASE
#define ESP32H2_AES_BASE                    0x60088000UL
#define ESP32H2_SHA_BASE                    0x60089000UL
#define ESP32H2_RSA_BASE                    0x6008A000UL
#define ESP32H2_ECC_MULT_BASE               0x6008B000UL
#define ESP32H2_ECC_BASE                    ESP32H2_ECC_MULT_BASE
#define ESP32H2_RSA_DS_BASE                 0x6008C000UL
#define ESP32H2_DS_BASE                     ESP32H2_RSA_DS_BASE
#define ESP32H2_HMAC_BASE                   0x6008D000UL
#define ESP32H2_ECDSA_BASE                  0x6008E000UL

#define ESP32H2_IOMUX_BASE                  0x60090000UL
#define ESP32H2_GPIO_BASE                   0x60091000UL
#define ESP32H2_GPIO_EXT_BASE               0x60091F00UL
#define ESP32H2_MEM_MONITOR_BASE            0x60092000UL
#define ESP32H2_PAU_BASE                    0x60093000UL
#define ESP32H2_HP_SYSREG_BASE              0x60095000UL
#define ESP32H2_PCR_BASE                    0x60096000UL
#define ESP32H2_TEE_BASE                    0x60098000UL
#define ESP32H2_HP_APM_BASE                 0x60099000UL
#define ESP32H2_LP_APM0_BASE                0x60099800UL
#define ESP32H2_MISC_BASE                   0x6009F000UL

#define ESP32H2_PMU_BASE                    0x600B0000UL
#define ESP32H2_LP_CLKRST_BASE              0x600B0400UL
#define ESP32H2_EFUSE_BASE                  0x600B0800UL
#define ESP32H2_LP_TIMER_BASE               0x600B0C00UL
#define ESP32H2_RTC_TIMER_BASE              ESP32H2_LP_TIMER_BASE
#define ESP32H2_LP_AON_BASE                 0x600B1000UL
#define ESP32H2_LP_WDT_BASE                 0x600B1C00UL
#define ESP32H2_RTC_WDT_BASE                ESP32H2_LP_WDT_BASE
#define ESP32H2_LP_IO_BASE                  0x600B2000UL
#define ESP32H2_LP_IOMUX_BASE               ESP32H2_LP_IO_BASE
#define ESP32H2_LP_GPIO_BASE                ESP32H2_LP_IO_BASE
#define ESP32H2_LP_ANALOG_PERI_BASE         0x600B2C00UL
#define ESP32H2_LP_APM_BASE                 0x600B3800UL
#define ESP32H2_LPPERI_BASE                 0x600B2800UL
#define ESP32H2_OTP_DEBUG_BASE              0x600B3C00UL

#define ESP32H2_TRACE_BASE                  0x600C0000UL
#define ESP32H2_ASSIST_DEBUG_BASE           0x600C2000UL
#define ESP32H2_INTPRI_BASE                 0x600C5000UL
#define ESP32H2_CACHE_BASE                  0x600C8000UL

#define ESP32H2_CLINT_M_BASE                0x20000000UL    //!< RISC-V CLINT machine-mode

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32H2_CPU_CORE_COUNT              1U
#define ESP32H2_CPU_INTERRUPT_COUNT         32U
#define ESP32H2_UART_COUNT                  2U      //!< 2 HP, no LP
#define ESP32H2_HP_UART_COUNT               2U
#define ESP32H2_LP_UART_COUNT               0U
#define ESP32H2_SPI_MEM_COUNT               2U
#define ESP32H2_GP_SPI_COUNT                1U
#define ESP32H2_I2C_COUNT                   2U
#define ESP32H2_HP_I2C_COUNT                2U
#define ESP32H2_LP_I2C_COUNT                0U
#define ESP32H2_I2S_COUNT                   1U
#define ESP32H2_TWAI_COUNT                  1U
#define ESP32H2_RMT_COUNT                   1U
#define ESP32H2_LEDC_COUNT                  1U
#define ESP32H2_PCNT_COUNT                  1U
#define ESP32H2_ETM_COUNT                   1U
#define ESP32H2_MCPWM_COUNT                 1U
#define ESP32H2_PARL_IO_COUNT               1U
#define ESP32H2_TIMER_GROUP_COUNT           2U
#define ESP32H2_TIMER_PER_GROUP_COUNT       1U
#define ESP32H2_TIMER_COUNT                 2U
#define ESP32H2_SYSTIMER_COUNT              1U
#define ESP32H2_SYSTIMER_COUNTER_COUNT      2U
#define ESP32H2_SYSTIMER_ALARM_COUNT        3U
#define ESP32H2_GDMA_COUNT                  1U
#define ESP32H2_GDMA_PAIR_COUNT             3U
#define ESP32H2_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32H2_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32H2_GPIO_PORT_COUNT             1U
#define ESP32H2_GPIO_PIN_COUNT              28U
#define ESP32H2_GPIO_PIN_MAX                27U
#define ESP32H2_GPIO_PIN_REG_COUNT          28U
#define ESP32H2_GPIO_FUNC_IN_COUNT          128U
#define ESP32H2_GPIO_FUNC_OUT_COUNT         28U
#define ESP32H2_GPIO_FUNC_OUT_REG_COUNT     28U
#define ESP32H2_ADC_COUNT                   1U
#define ESP32H2_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32H2_UHCI_COUNT                  1U
#define ESP32H2_USB_SERIAL_JTAG_COUNT       1U
#define ESP32H2_AES_COUNT                   1U
#define ESP32H2_SHA_COUNT                   1U
#define ESP32H2_RSA_COUNT                   1U
#define ESP32H2_RSA_DS_COUNT                1U
#define ESP32H2_HMAC_COUNT                  1U
#define ESP32H2_ECC_COUNT                   1U
#define ESP32H2_ECDSA_COUNT                 1U
#define ESP32H2_EFUSE_COUNT                 1U
#define ESP32H2_INTMTX_COUNT                1U
#define ESP32H2_INTPRI_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32H2_*
 *
 * Every ESP32H2_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32H2_UART0_BASE
#define ESP32_UART1_BASE                        ESP32H2_UART1_BASE
#define ESP32_SPI0_BASE                         ESP32H2_SPI0_BASE
#define ESP32_SPI1_BASE                         ESP32H2_SPI1_BASE
#define ESP32_SPIMEM0_BASE                      ESP32H2_SPIMEM0_BASE
#define ESP32_SPIMEM1_BASE                      ESP32H2_SPIMEM1_BASE
#define ESP32_I2C0_BASE                         ESP32H2_I2C0_BASE
#define ESP32_I2C1_BASE                         ESP32H2_I2C1_BASE
#define ESP32_I2C_BASE                          ESP32H2_I2C_BASE
#define ESP32_UHCI_BASE                         ESP32H2_UHCI_BASE
#define ESP32_RMT_BASE                          ESP32H2_RMT_BASE
#define ESP32_LEDC_BASE                         ESP32H2_LEDC_BASE
#define ESP32_TIMG0_BASE                        ESP32H2_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32H2_TIMG1_BASE
#define ESP32_SYSTIMER_BASE                     ESP32H2_SYSTIMER_BASE
#define ESP32_TWAI_BASE                         ESP32H2_TWAI_BASE
#define ESP32_I2S_BASE                          ESP32H2_I2S_BASE
#define ESP32_APB_SARADC_BASE                   ESP32H2_APB_SARADC_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32H2_USB_SERIAL_JTAG_BASE
#define ESP32_INTMTX_BASE                       ESP32H2_INTMTX_BASE
#define ESP32_PCNT_BASE                         ESP32H2_PCNT_BASE
#define ESP32_SOC_ETM_BASE                      ESP32H2_SOC_ETM_BASE
#define ESP32_MCPWM_BASE                        ESP32H2_MCPWM_BASE
#define ESP32_PARL_IO_BASE                      ESP32H2_PARL_IO_BASE
#define ESP32_PVT_MONITOR_BASE                  ESP32H2_PVT_MONITOR_BASE
#define ESP32_GDMA_BASE                         ESP32H2_GDMA_BASE
#define ESP32_GP_SPI2_BASE                      ESP32H2_GP_SPI2_BASE
#define ESP32_SPI2_BASE                         ESP32H2_SPI2_BASE
#define ESP32_AES_BASE                          ESP32H2_AES_BASE
#define ESP32_SHA_BASE                          ESP32H2_SHA_BASE
#define ESP32_RSA_BASE                          ESP32H2_RSA_BASE
#define ESP32_ECC_MULT_BASE                     ESP32H2_ECC_MULT_BASE
#define ESP32_ECC_BASE                          ESP32H2_ECC_BASE
#define ESP32_RSA_DS_BASE                       ESP32H2_RSA_DS_BASE
#define ESP32_DS_BASE                           ESP32H2_DS_BASE
#define ESP32_HMAC_BASE                         ESP32H2_HMAC_BASE
#define ESP32_ECDSA_BASE                        ESP32H2_ECDSA_BASE
#define ESP32_IOMUX_BASE                        ESP32H2_IOMUX_BASE
#define ESP32_GPIO_BASE                         ESP32H2_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32H2_GPIO_EXT_BASE
#define ESP32_MEM_MONITOR_BASE                  ESP32H2_MEM_MONITOR_BASE
#define ESP32_PAU_BASE                          ESP32H2_PAU_BASE
#define ESP32_HP_SYSREG_BASE                    ESP32H2_HP_SYSREG_BASE
#define ESP32_PCR_BASE                          ESP32H2_PCR_BASE
#define ESP32_TEE_BASE                          ESP32H2_TEE_BASE
#define ESP32_HP_APM_BASE                       ESP32H2_HP_APM_BASE
#define ESP32_LP_APM0_BASE                      ESP32H2_LP_APM0_BASE
#define ESP32_MISC_BASE                         ESP32H2_MISC_BASE
#define ESP32_PMU_BASE                          ESP32H2_PMU_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32H2_LP_CLKRST_BASE
#define ESP32_EFUSE_BASE                        ESP32H2_EFUSE_BASE
#define ESP32_LP_TIMER_BASE                     ESP32H2_LP_TIMER_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32H2_RTC_TIMER_BASE
#define ESP32_LP_AON_BASE                       ESP32H2_LP_AON_BASE
#define ESP32_LP_WDT_BASE                       ESP32H2_LP_WDT_BASE
#define ESP32_RTC_WDT_BASE                      ESP32H2_RTC_WDT_BASE
#define ESP32_LP_IO_BASE                        ESP32H2_LP_IO_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32H2_LP_IOMUX_BASE
#define ESP32_LP_GPIO_BASE                      ESP32H2_LP_GPIO_BASE
#define ESP32_LP_ANALOG_PERI_BASE               ESP32H2_LP_ANALOG_PERI_BASE
#define ESP32_LP_APM_BASE                       ESP32H2_LP_APM_BASE
#define ESP32_LPPERI_BASE                       ESP32H2_LPPERI_BASE
#define ESP32_OTP_DEBUG_BASE                    ESP32H2_OTP_DEBUG_BASE
#define ESP32_TRACE_BASE                        ESP32H2_TRACE_BASE
#define ESP32_ASSIST_DEBUG_BASE                 ESP32H2_ASSIST_DEBUG_BASE
#define ESP32_INTPRI_BASE                       ESP32H2_INTPRI_BASE
#define ESP32_CACHE_BASE                        ESP32H2_CACHE_BASE
#define ESP32_CLINT_M_BASE                      ESP32H2_CLINT_M_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32H2_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32H2_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32H2_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32H2_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32H2_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32H2_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32H2_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32H2_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32H2_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32H2_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32H2_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32H2_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32H2_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32H2_LEDC_COUNT
#define ESP32_PCNT_COUNT                        ESP32H2_PCNT_COUNT
#define ESP32_ETM_COUNT                         ESP32H2_ETM_COUNT
#define ESP32_MCPWM_COUNT                       ESP32H2_MCPWM_COUNT
#define ESP32_PARL_IO_COUNT                     ESP32H2_PARL_IO_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32H2_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32H2_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32H2_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32H2_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32H2_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32H2_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32H2_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32H2_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32H2_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32H2_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32H2_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32H2_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32H2_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32H2_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32H2_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32H2_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32H2_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32H2_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32H2_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32H2_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32H2_USB_SERIAL_JTAG_COUNT
#define ESP32_AES_COUNT                         ESP32H2_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32H2_SHA_COUNT
#define ESP32_RSA_COUNT                         ESP32H2_RSA_COUNT
#define ESP32_RSA_DS_COUNT                      ESP32H2_RSA_DS_COUNT
#define ESP32_HMAC_COUNT                        ESP32H2_HMAC_COUNT
#define ESP32_ECC_COUNT                         ESP32H2_ECC_COUNT
#define ESP32_ECDSA_COUNT                       ESP32H2_ECDSA_COUNT
#define ESP32_EFUSE_COUNT                       ESP32H2_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32H2_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32H2_INTPRI_COUNT

#endif // __ESP32H2_H__
