/**-------------------------------------------------------------------------
@file	esp32p4.h

@brief	ESP32-P4 chip-specific definition.

Dual-core 32-bit RISC-V HP (up to 400 MHz, single-precision FPU, AI
extensions) plus an LP RISC-V core.  No on-chip wireless.  High-end
multimedia / AIoT chip with MIPI-CSI/DSI camera+display, H.264 encoder,
JPEG codec, USB 2.0 HS OTG, EMAC, PSRAM controller, DDR PHY.

55 GPIOs, 6 UARTs (5 HP + 1 LP), 3 I2C, 3 SPI, 3 TWAI.  Uses PCR for
peripheral clock-gating; peripherals split across two HP buses
(HPPERIPH0 = 0x50000000, HPPERIPH1 = 0x500C0000) plus LP buses.

Defines the chip-specific ESP32P4_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32p4/register/hw_ver3/soc/reg_base.h
   components/soc/esp32p4/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32P4_H__
#define __ESP32P4_H__

/*===========================================================================
 * Bus base addresses
 *
 * P4 splits peripherals across multiple buses:
 *   HPCPUTCP    @ 0x3FF00000  Tightly-coupled HP-CPU registers (trace, cache)
 *   HPPERIPH0   @ 0x50000000  Crypto, GDMA, USB, multimedia (H.264, JPEG)
 *   HPPERIPH1   @ 0x500C0000  UARTs, timers, GPIO, I2C, SPI
 *   LPAON       @ 0x50110000  LP always-on (PMU, EFUSE, LP_AON)
 *   LPPERIPH    @ 0x50120000  LP peripherals
 *==========================================================================*/
#define ESP32P4_HPCPUTCP_BASE               0x3FF00000UL
#define ESP32P4_HPPERIPH0_BASE              0x50000000UL
#define ESP32P4_HPPERIPH1_BASE              0x500C0000UL
#define ESP32P4_LPAON_BASE                  0x50110000UL
#define ESP32P4_LPPERIPH_BASE               0x50120000UL

/*===========================================================================
 * HP CPU TCP peripherals (trace, cache, monitors)
 *==========================================================================*/
#define ESP32P4_TRACE0_BASE                 (ESP32P4_HPCPUTCP_BASE + 0x4000UL)
#define ESP32P4_TRACE1_BASE                 (ESP32P4_HPCPUTCP_BASE + 0x5000UL)
#define ESP32P4_TRACE_BASE                  ESP32P4_TRACE0_BASE
#define ESP32P4_CPU_BUS_MON_BASE            (ESP32P4_HPCPUTCP_BASE + 0x6000UL)
#define ESP32P4_L2MEM_MON_BASE              (ESP32P4_HPCPUTCP_BASE + 0xE000UL)
#define ESP32P4_TCM_MON_BASE                (ESP32P4_HPCPUTCP_BASE + 0xF000UL)
#define ESP32P4_CACHE_BASE                  (ESP32P4_HPCPUTCP_BASE + 0x10000UL)

/*===========================================================================
 * HP peripheral bus 0 (HPPERIPH0)
 *
 * Crypto, multimedia, DMA, USB, EMAC.
 *==========================================================================*/
#define ESP32P4_USB2_BASE                   (ESP32P4_HPPERIPH0_BASE + 0x00000UL)
#define ESP32P4_USB11_BASE                  (ESP32P4_HPPERIPH0_BASE + 0x40000UL)
#define ESP32P4_USB_OTG_BASE                ESP32P4_USB2_BASE
#define ESP32P4_USB_WRAP_BASE               (ESP32P4_HPPERIPH0_BASE + 0x80000UL)
#define ESP32P4_GDMA_BASE                   (ESP32P4_HPPERIPH0_BASE + 0x81000UL)
#define ESP32P4_REGDMA_BASE                 (ESP32P4_HPPERIPH0_BASE + 0x82000UL)
#define ESP32P4_SDMMC_BASE                  (ESP32P4_HPPERIPH0_BASE + 0x83000UL)
#define ESP32P4_H264_CORE_BASE              (ESP32P4_HPPERIPH0_BASE + 0x84000UL)
#define ESP32P4_AHB_DMA_BASE                (ESP32P4_HPPERIPH0_BASE + 0x85000UL)
#define ESP32P4_JPEG_BASE                   (ESP32P4_HPPERIPH0_BASE + 0x86000UL)
#define ESP32P4_PPA_BASE                    (ESP32P4_HPPERIPH0_BASE + 0x87000UL)
#define ESP32P4_DMA2D_BASE                  (ESP32P4_HPPERIPH0_BASE + 0x88000UL)
#define ESP32P4_KEYMNG_BASE                 (ESP32P4_HPPERIPH0_BASE + 0x89000UL)
#define ESP32P4_AXI_DMA_BASE                (ESP32P4_HPPERIPH0_BASE + 0x8A000UL)
#define ESP32P4_FLASH_SPI0_BASE             (ESP32P4_HPPERIPH0_BASE + 0x8C000UL)
#define ESP32P4_SPIMEM0_BASE                ESP32P4_FLASH_SPI0_BASE
#define ESP32P4_FLASH_SPI1_BASE             (ESP32P4_HPPERIPH0_BASE + 0x8D000UL)
#define ESP32P4_SPIMEM1_BASE                ESP32P4_FLASH_SPI1_BASE
#define ESP32P4_PSRAM_MSPI0_BASE            (ESP32P4_HPPERIPH0_BASE + 0x8E000UL)
#define ESP32P4_PSRAM_MSPI1_BASE            (ESP32P4_HPPERIPH0_BASE + 0x8F000UL)
#define ESP32P4_CRYPTO_BASE                 (ESP32P4_HPPERIPH0_BASE + 0x90000UL)
#define ESP32P4_EMAC_BASE                   (ESP32P4_HPPERIPH0_BASE + 0x98000UL)
#define ESP32P4_USBPHY_BASE                 (ESP32P4_HPPERIPH0_BASE + 0x9C000UL)
#define ESP32P4_DDRPHY_BASE                 (ESP32P4_HPPERIPH0_BASE + 0x9D000UL)
#define ESP32P4_PVT_BASE                    (ESP32P4_HPPERIPH0_BASE + 0x9E000UL)
#define ESP32P4_CSI_HOST_BASE               (ESP32P4_HPPERIPH0_BASE + 0x9F000UL)   //!< MIPI-CSI host
#define ESP32P4_CSI_BRG_BASE                (ESP32P4_HPPERIPH0_BASE + 0x9F800UL)
#define ESP32P4_DSI_HOST_BASE               (ESP32P4_HPPERIPH0_BASE + 0xA0000UL)   //!< MIPI-DSI host
#define ESP32P4_DSI_BRG_BASE                (ESP32P4_HPPERIPH0_BASE + 0xA0800UL)
#define ESP32P4_ISP_BASE                    (ESP32P4_HPPERIPH0_BASE + 0xA1000UL)   //!< Image signal processor
#define ESP32P4_RMT_BASE                    (ESP32P4_HPPERIPH0_BASE + 0xA2000UL)
#define ESP32P4_BITSCRAMBLER_BASE           (ESP32P4_HPPERIPH0_BASE + 0xA3000UL)
#define ESP32P4_AXI_ICM_BASE                (ESP32P4_HPPERIPH0_BASE + 0xA4000UL)

/*===========================================================================
 * HP peripheral bus 1 (HPPERIPH1)
 *
 * Timers, UARTs, GPIO, I2C, SPI -- "the usual suspects".
 *==========================================================================*/
#define ESP32P4_MCPWM0_BASE                 (ESP32P4_HPPERIPH1_BASE + 0x0000UL)
#define ESP32P4_MCPWM_BASE                  ESP32P4_MCPWM0_BASE
#define ESP32P4_MCPWM1_BASE                 (ESP32P4_HPPERIPH1_BASE + 0x1000UL)
#define ESP32P4_TIMG0_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x2000UL)
#define ESP32P4_TIMG1_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x3000UL)
#define ESP32P4_I2C0_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x4000UL)
#define ESP32P4_I2C_BASE                    ESP32P4_I2C0_BASE
#define ESP32P4_I2C1_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x5000UL)
#define ESP32P4_I2S0_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x6000UL)
#define ESP32P4_I2S_BASE                    ESP32P4_I2S0_BASE
#define ESP32P4_I2S1_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x7000UL)
#define ESP32P4_I2S2_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x8000UL)
#define ESP32P4_PCNT_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x9000UL)
#define ESP32P4_UART0_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xA000UL)
#define ESP32P4_UART1_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xB000UL)
#define ESP32P4_UART2_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xC000UL)
#define ESP32P4_UART3_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xD000UL)
#define ESP32P4_UART4_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xE000UL)
#define ESP32P4_PARIO_BASE                  (ESP32P4_HPPERIPH1_BASE + 0xF000UL)
#define ESP32P4_PARL_IO_BASE                ESP32P4_PARIO_BASE
#define ESP32P4_SPI2_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x10000UL)
#define ESP32P4_GP_SPI2_BASE                ESP32P4_SPI2_BASE
#define ESP32P4_SPI3_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x11000UL)
#define ESP32P4_GP_SPI3_BASE                ESP32P4_SPI3_BASE
#define ESP32P4_USB2JTAG_BASE               (ESP32P4_HPPERIPH1_BASE + 0x12000UL)
#define ESP32P4_USB_SERIAL_JTAG_BASE        ESP32P4_USB2JTAG_BASE
#define ESP32P4_LEDC_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x13000UL)
#define ESP32P4_SOC_ETM_BASE                (ESP32P4_HPPERIPH1_BASE + 0x15000UL)
#define ESP32P4_INTR_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x16000UL)
#define ESP32P4_INTMTX_BASE                 ESP32P4_INTR_BASE
#define ESP32P4_TWAI0_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x17000UL)
#define ESP32P4_TWAI_BASE                   ESP32P4_TWAI0_BASE
#define ESP32P4_TWAI1_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x18000UL)
#define ESP32P4_TWAI2_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x19000UL)
#define ESP32P4_I3C_MST_BASE                (ESP32P4_HPPERIPH1_BASE + 0x1A000UL)
#define ESP32P4_I3C_SLV_BASE                (ESP32P4_HPPERIPH1_BASE + 0x1B000UL)
#define ESP32P4_LCDCAM_BASE                 (ESP32P4_HPPERIPH1_BASE + 0x1C000UL)
#define ESP32P4_ADC_BASE                    (ESP32P4_HPPERIPH1_BASE + 0x1E000UL)
#define ESP32P4_SAR_ADC_BASE                ESP32P4_ADC_BASE
#define ESP32P4_UHCI_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x1F000UL)
#define ESP32P4_GPIO_BASE                   (ESP32P4_HPPERIPH1_BASE + 0x20000UL)
#define ESP32P4_GPIO_EXT_BASE               (ESP32P4_HPPERIPH1_BASE + 0x20F00UL)
#define ESP32P4_IOMUX_BASE                  (ESP32P4_HPPERIPH1_BASE + 0x21000UL)
#define ESP32P4_SYSTIMER_BASE               (ESP32P4_HPPERIPH1_BASE + 0x22000UL)
#define ESP32P4_HP_SYS_CLKRST_BASE          (ESP32P4_HPPERIPH1_BASE + 0x26000UL)    //!< Peripheral clock & reset (P4's equivalent of PCR)

/*===========================================================================
 * LP / always-on
 *==========================================================================*/
#define ESP32P4_PMU_BASE                    (ESP32P4_LPAON_BASE + 0x0000UL)
#define ESP32P4_LP_CLKRST_BASE              (ESP32P4_LPAON_BASE + 0x0400UL)
#define ESP32P4_EFUSE_BASE                  (ESP32P4_LPAON_BASE + 0x0800UL)
#define ESP32P4_LP_TIMER_BASE               (ESP32P4_LPAON_BASE + 0x0C00UL)
#define ESP32P4_RTC_TIMER_BASE              ESP32P4_LP_TIMER_BASE
#define ESP32P4_LP_AON_BASE                 (ESP32P4_LPAON_BASE + 0x1000UL)
#define ESP32P4_LP_WDT_BASE                 (ESP32P4_LPAON_BASE + 0x1C00UL)
#define ESP32P4_RTC_WDT_BASE                ESP32P4_LP_WDT_BASE
#define ESP32P4_LP_IOMUX_BASE               (ESP32P4_LPAON_BASE + 0x4000UL)
#define ESP32P4_LP_GPIO_BASE                (ESP32P4_LPAON_BASE + 0x4400UL)

#define ESP32P4_LP_UART_BASE                (ESP32P4_LPPERIPH_BASE + 0x0000UL)
#define ESP32P4_LP_I2C_BASE                 (ESP32P4_LPPERIPH_BASE + 0x1000UL)
#define ESP32P4_LP_I2S_BASE                 (ESP32P4_LPPERIPH_BASE + 0x2000UL)
#define ESP32P4_LPPERI_BASE                 ESP32P4_LPPERIPH_BASE

#define ESP32P4_INTPRI_BASE                 ESP32P4_INTR_BASE   //!< P4 folds INTPRI into INTR block
#define ESP32P4_CLINT_M_BASE                0x20000000UL

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32P4_CPU_CORE_COUNT              2U      //!< 2 HP RISC-V cores at 400 MHz
#define ESP32P4_CPU_INTERRUPT_COUNT         32U
#define ESP32P4_UART_COUNT                  6U      //!< 5 HP + 1 LP
#define ESP32P4_HP_UART_COUNT               5U
#define ESP32P4_LP_UART_COUNT               1U
#define ESP32P4_SPI_MEM_COUNT               2U
#define ESP32P4_GP_SPI_COUNT                2U      //!< SPI2 + SPI3
#define ESP32P4_I2C_COUNT                   3U      //!< 2 HP + 1 LP
#define ESP32P4_HP_I2C_COUNT                2U
#define ESP32P4_LP_I2C_COUNT                1U
#define ESP32P4_I2S_COUNT                   3U
#define ESP32P4_TWAI_COUNT                  3U
#define ESP32P4_RMT_COUNT                   1U
#define ESP32P4_LEDC_COUNT                  1U
#define ESP32P4_PCNT_COUNT                  1U
#define ESP32P4_ETM_COUNT                   1U
#define ESP32P4_MCPWM_COUNT                 2U
#define ESP32P4_PARL_IO_COUNT               1U
#define ESP32P4_TIMER_GROUP_COUNT           2U
#define ESP32P4_TIMER_PER_GROUP_COUNT       1U
#define ESP32P4_TIMER_COUNT                 2U
#define ESP32P4_SYSTIMER_COUNT              1U
#define ESP32P4_SYSTIMER_COUNTER_COUNT      2U
#define ESP32P4_SYSTIMER_ALARM_COUNT        3U
#define ESP32P4_GDMA_COUNT                  1U
#define ESP32P4_GDMA_PAIR_COUNT             3U
#define ESP32P4_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32P4_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32P4_GPIO_PORT_COUNT             1U
#define ESP32P4_GPIO_PIN_COUNT              55U
#define ESP32P4_GPIO_PIN_MAX                54U
#define ESP32P4_GPIO_PIN_REG_COUNT          55U
#define ESP32P4_GPIO_FUNC_IN_COUNT          256U
#define ESP32P4_GPIO_FUNC_OUT_COUNT         55U
#define ESP32P4_GPIO_FUNC_OUT_REG_COUNT     55U
#define ESP32P4_ADC_COUNT                   2U
#define ESP32P4_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32P4_UHCI_COUNT                  1U
#define ESP32P4_USB_SERIAL_JTAG_COUNT       1U
#define ESP32P4_USB_OTG_COUNT               1U      //!< USB 2.0 HS OTG
#define ESP32P4_AES_COUNT                   1U
#define ESP32P4_SHA_COUNT                   1U
#define ESP32P4_HMAC_COUNT                  1U
#define ESP32P4_ECC_COUNT                   1U
#define ESP32P4_ECDSA_COUNT                 1U
#define ESP32P4_KEYMNG_COUNT                1U
#define ESP32P4_EFUSE_COUNT                 1U
#define ESP32P4_INTMTX_COUNT                2U      //!< One per core
#define ESP32P4_INTPRI_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32P4_*
 *
 * Every ESP32P4_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_HPCPUTCP_BASE                     ESP32P4_HPCPUTCP_BASE
#define ESP32_HPPERIPH0_BASE                    ESP32P4_HPPERIPH0_BASE
#define ESP32_HPPERIPH1_BASE                    ESP32P4_HPPERIPH1_BASE
#define ESP32_LPAON_BASE                        ESP32P4_LPAON_BASE
#define ESP32_LPPERIPH_BASE                     ESP32P4_LPPERIPH_BASE
#define ESP32_TRACE0_BASE                       ESP32P4_TRACE0_BASE
#define ESP32_TRACE1_BASE                       ESP32P4_TRACE1_BASE
#define ESP32_TRACE_BASE                        ESP32P4_TRACE_BASE
#define ESP32_CPU_BUS_MON_BASE                  ESP32P4_CPU_BUS_MON_BASE
#define ESP32_L2MEM_MON_BASE                    ESP32P4_L2MEM_MON_BASE
#define ESP32_TCM_MON_BASE                      ESP32P4_TCM_MON_BASE
#define ESP32_CACHE_BASE                        ESP32P4_CACHE_BASE
#define ESP32_USB2_BASE                         ESP32P4_USB2_BASE
#define ESP32_USB11_BASE                        ESP32P4_USB11_BASE
#define ESP32_USB_OTG_BASE                      ESP32P4_USB_OTG_BASE
#define ESP32_USB_WRAP_BASE                     ESP32P4_USB_WRAP_BASE
#define ESP32_GDMA_BASE                         ESP32P4_GDMA_BASE
#define ESP32_REGDMA_BASE                       ESP32P4_REGDMA_BASE
#define ESP32_SDMMC_BASE                        ESP32P4_SDMMC_BASE
#define ESP32_H264_CORE_BASE                    ESP32P4_H264_CORE_BASE
#define ESP32_AHB_DMA_BASE                      ESP32P4_AHB_DMA_BASE
#define ESP32_JPEG_BASE                         ESP32P4_JPEG_BASE
#define ESP32_PPA_BASE                          ESP32P4_PPA_BASE
#define ESP32_DMA2D_BASE                        ESP32P4_DMA2D_BASE
#define ESP32_KEYMNG_BASE                       ESP32P4_KEYMNG_BASE
#define ESP32_AXI_DMA_BASE                      ESP32P4_AXI_DMA_BASE
#define ESP32_FLASH_SPI0_BASE                   ESP32P4_FLASH_SPI0_BASE
#define ESP32_SPIMEM0_BASE                      ESP32P4_SPIMEM0_BASE
#define ESP32_FLASH_SPI1_BASE                   ESP32P4_FLASH_SPI1_BASE
#define ESP32_SPIMEM1_BASE                      ESP32P4_SPIMEM1_BASE
#define ESP32_PSRAM_MSPI0_BASE                  ESP32P4_PSRAM_MSPI0_BASE
#define ESP32_PSRAM_MSPI1_BASE                  ESP32P4_PSRAM_MSPI1_BASE
#define ESP32_CRYPTO_BASE                       ESP32P4_CRYPTO_BASE
#define ESP32_EMAC_BASE                         ESP32P4_EMAC_BASE
#define ESP32_USBPHY_BASE                       ESP32P4_USBPHY_BASE
#define ESP32_DDRPHY_BASE                       ESP32P4_DDRPHY_BASE
#define ESP32_PVT_BASE                          ESP32P4_PVT_BASE
#define ESP32_CSI_HOST_BASE                     ESP32P4_CSI_HOST_BASE
#define ESP32_CSI_BRG_BASE                      ESP32P4_CSI_BRG_BASE
#define ESP32_DSI_HOST_BASE                     ESP32P4_DSI_HOST_BASE
#define ESP32_DSI_BRG_BASE                      ESP32P4_DSI_BRG_BASE
#define ESP32_ISP_BASE                          ESP32P4_ISP_BASE
#define ESP32_RMT_BASE                          ESP32P4_RMT_BASE
#define ESP32_BITSCRAMBLER_BASE                 ESP32P4_BITSCRAMBLER_BASE
#define ESP32_AXI_ICM_BASE                      ESP32P4_AXI_ICM_BASE
#define ESP32_MCPWM0_BASE                       ESP32P4_MCPWM0_BASE
#define ESP32_MCPWM_BASE                        ESP32P4_MCPWM_BASE
#define ESP32_MCPWM1_BASE                       ESP32P4_MCPWM1_BASE
#define ESP32_TIMG0_BASE                        ESP32P4_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32P4_TIMG1_BASE
#define ESP32_I2C0_BASE                         ESP32P4_I2C0_BASE
#define ESP32_I2C_BASE                          ESP32P4_I2C_BASE
#define ESP32_I2C1_BASE                         ESP32P4_I2C1_BASE
#define ESP32_I2S0_BASE                         ESP32P4_I2S0_BASE
#define ESP32_I2S_BASE                          ESP32P4_I2S_BASE
#define ESP32_I2S1_BASE                         ESP32P4_I2S1_BASE
#define ESP32_I2S2_BASE                         ESP32P4_I2S2_BASE
#define ESP32_PCNT_BASE                         ESP32P4_PCNT_BASE
#define ESP32_UART0_BASE                        ESP32P4_UART0_BASE
#define ESP32_UART1_BASE                        ESP32P4_UART1_BASE
#define ESP32_UART2_BASE                        ESP32P4_UART2_BASE
#define ESP32_UART3_BASE                        ESP32P4_UART3_BASE
#define ESP32_UART4_BASE                        ESP32P4_UART4_BASE
#define ESP32_PARIO_BASE                        ESP32P4_PARIO_BASE
#define ESP32_PARL_IO_BASE                      ESP32P4_PARL_IO_BASE
#define ESP32_SPI2_BASE                         ESP32P4_SPI2_BASE
#define ESP32_GP_SPI2_BASE                      ESP32P4_GP_SPI2_BASE
#define ESP32_SPI3_BASE                         ESP32P4_SPI3_BASE
#define ESP32_GP_SPI3_BASE                      ESP32P4_GP_SPI3_BASE
#define ESP32_USB2JTAG_BASE                     ESP32P4_USB2JTAG_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32P4_USB_SERIAL_JTAG_BASE
#define ESP32_LEDC_BASE                         ESP32P4_LEDC_BASE
#define ESP32_SOC_ETM_BASE                      ESP32P4_SOC_ETM_BASE
#define ESP32_INTR_BASE                         ESP32P4_INTR_BASE
#define ESP32_INTMTX_BASE                       ESP32P4_INTMTX_BASE
#define ESP32_TWAI0_BASE                        ESP32P4_TWAI0_BASE
#define ESP32_TWAI_BASE                         ESP32P4_TWAI_BASE
#define ESP32_TWAI1_BASE                        ESP32P4_TWAI1_BASE
#define ESP32_TWAI2_BASE                        ESP32P4_TWAI2_BASE
#define ESP32_I3C_MST_BASE                      ESP32P4_I3C_MST_BASE
#define ESP32_I3C_SLV_BASE                      ESP32P4_I3C_SLV_BASE
#define ESP32_LCDCAM_BASE                       ESP32P4_LCDCAM_BASE
#define ESP32_ADC_BASE                          ESP32P4_ADC_BASE
#define ESP32_SAR_ADC_BASE                      ESP32P4_SAR_ADC_BASE
#define ESP32_UHCI_BASE                         ESP32P4_UHCI_BASE
#define ESP32_GPIO_BASE                         ESP32P4_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32P4_GPIO_EXT_BASE
#define ESP32_IOMUX_BASE                        ESP32P4_IOMUX_BASE
#define ESP32_SYSTIMER_BASE                     ESP32P4_SYSTIMER_BASE
#define ESP32_HP_SYS_CLKRST_BASE                ESP32P4_HP_SYS_CLKRST_BASE
#define ESP32_PMU_BASE                          ESP32P4_PMU_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32P4_LP_CLKRST_BASE
#define ESP32_EFUSE_BASE                        ESP32P4_EFUSE_BASE
#define ESP32_LP_TIMER_BASE                     ESP32P4_LP_TIMER_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32P4_RTC_TIMER_BASE
#define ESP32_LP_AON_BASE                       ESP32P4_LP_AON_BASE
#define ESP32_LP_WDT_BASE                       ESP32P4_LP_WDT_BASE
#define ESP32_RTC_WDT_BASE                      ESP32P4_RTC_WDT_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32P4_LP_IOMUX_BASE
#define ESP32_LP_GPIO_BASE                      ESP32P4_LP_GPIO_BASE
#define ESP32_LP_UART_BASE                      ESP32P4_LP_UART_BASE
#define ESP32_LP_I2C_BASE                       ESP32P4_LP_I2C_BASE
#define ESP32_LP_I2S_BASE                       ESP32P4_LP_I2S_BASE
#define ESP32_LPPERI_BASE                       ESP32P4_LPPERI_BASE
#define ESP32_INTPRI_BASE                       ESP32P4_INTPRI_BASE
#define ESP32_CLINT_M_BASE                      ESP32P4_CLINT_M_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32P4_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32P4_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32P4_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32P4_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32P4_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32P4_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32P4_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32P4_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32P4_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32P4_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32P4_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32P4_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32P4_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32P4_LEDC_COUNT
#define ESP32_PCNT_COUNT                        ESP32P4_PCNT_COUNT
#define ESP32_ETM_COUNT                         ESP32P4_ETM_COUNT
#define ESP32_MCPWM_COUNT                       ESP32P4_MCPWM_COUNT
#define ESP32_PARL_IO_COUNT                     ESP32P4_PARL_IO_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32P4_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32P4_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32P4_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32P4_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32P4_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32P4_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32P4_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32P4_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32P4_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32P4_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32P4_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32P4_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32P4_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32P4_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32P4_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32P4_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32P4_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32P4_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32P4_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32P4_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32P4_USB_SERIAL_JTAG_COUNT
#define ESP32_USB_OTG_COUNT                     ESP32P4_USB_OTG_COUNT
#define ESP32_AES_COUNT                         ESP32P4_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32P4_SHA_COUNT
#define ESP32_HMAC_COUNT                        ESP32P4_HMAC_COUNT
#define ESP32_ECC_COUNT                         ESP32P4_ECC_COUNT
#define ESP32_ECDSA_COUNT                       ESP32P4_ECDSA_COUNT
#define ESP32_KEYMNG_COUNT                      ESP32P4_KEYMNG_COUNT
#define ESP32_EFUSE_COUNT                       ESP32P4_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32P4_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32P4_INTPRI_COUNT

#endif // __ESP32P4_H__
