/**-------------------------------------------------------------------------
@file	esp32h4.h

@brief	ESP32-H4 chip-specific definition.

Dual-core 32-bit RISC-V (HP + LP), BLE 5 + 802.15.4 (Thread / Zigbee /
Matter), no Wi-Fi.  40 GPIOs, USB OTG full-speed.  Uses PCR for peripheral
clock-gating, dual INTMTX (INTMTX0/INTMTX1) for the two CPU cores, plus
INTPRI.

This chip has a DIFFERENT peripheral memory map from C5/C6/C61/H2: most
peripherals are clustered higher in the 0x60010000-0x600C0000 range
rather than starting at 0x60000000.

Defines the chip-specific ESP32H4_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32h4/include/soc/reg_base.h
   components/soc/esp32h4/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32H4_H__
#define __ESP32H4_H__

/*===========================================================================
 * Peripheral register base addresses
 *
 * Layout differs from earlier H/C chips: peripherals are spread between
 * 0x60000000 (debug/trace), 0x60010000-0x60030000 (HP peripherals), and
 * 0x60080000-0x600B6000 (system / crypto / LP).
 *==========================================================================*/
#define ESP32H4_TRACE0_BASE                 0x60000000UL    //!< Core0 RISC-V trace
#define ESP32H4_TRACE1_BASE                 0x60001000UL    //!< Core1 RISC-V trace
#define ESP32H4_TRACE_BASE                  ESP32H4_TRACE0_BASE
#define ESP32H4_BUS_MONITOR_BASE            0x60002000UL
#define ESP32H4_INTPRI_BASE                 0x60005000UL
#define ESP32H4_CACHE_BASE                  0x60008000UL

#define ESP32H4_GPSPI2_BASE                 0x60010000UL    //!< GP-SPI2
#define ESP32H4_GP_SPI2_BASE                ESP32H4_GPSPI2_BASE
#define ESP32H4_SPI2_BASE                   ESP32H4_GPSPI2_BASE
#define ESP32H4_GPSPI3_BASE                 0x60011000UL    //!< GP-SPI3
#define ESP32H4_GP_SPI3_BASE                ESP32H4_GPSPI3_BASE
#define ESP32H4_SPI3_BASE                   ESP32H4_GPSPI3_BASE
#define ESP32H4_UART0_BASE                  0x60012000UL
#define ESP32H4_UART1_BASE                  0x60013000UL
#define ESP32H4_UHCI_BASE                   0x60014000UL
#define ESP32H4_I2C0_BASE                   0x60015000UL
#define ESP32H4_I2C_BASE                    ESP32H4_I2C0_BASE
#define ESP32H4_I2C1_BASE                   0x60016000UL
#define ESP32H4_I2S0_BASE                   0x60017000UL
#define ESP32H4_I2S_BASE                    ESP32H4_I2S0_BASE
#define ESP32H4_PARL_IO_BASE                0x60018000UL
#define ESP32H4_MCPWM0_BASE                 0x60019000UL
#define ESP32H4_MCPWM_BASE                  ESP32H4_MCPWM0_BASE
#define ESP32H4_MCPWM1_BASE                 0x6001A000UL
#define ESP32H4_LEDC_BASE                   0x6001B000UL
#define ESP32H4_TWAIFD_BASE                 0x6001C000UL    //!< TWAI-FD controller
#define ESP32H4_TWAI_BASE                   ESP32H4_TWAIFD_BASE
#define ESP32H4_USB_SERIAL_JTAG_BASE        0x6001D000UL
#define ESP32H4_RMT_BASE                    0x6001E000UL
#define ESP32H4_AHB_DMA_BASE                0x6001F000UL
#define ESP32H4_GDMA_BASE                   ESP32H4_AHB_DMA_BASE
#define ESP32H4_PAU_BASE                    0x60020000UL
#define ESP32H4_SOC_ETM_BASE                0x60021000UL
#define ESP32H4_APB_SARADC_BASE             0x60022000UL
#define ESP32H4_SYSTIMER_BASE               0x60023000UL
#define ESP32H4_MEM_MONITOR_BASE            0x60025000UL
#define ESP32H4_PVT_BASE                    0x60026000UL
#define ESP32H4_PCNT_BASE                   0x60027000UL
#define ESP32H4_SAMPLE_RATE_CONVERTER_BASE  0x60028000UL
#define ESP32H4_ZERO_DET_BASE               0x60029000UL

/* USB OTG full-speed (USB 2.0 FS) core. */
#define ESP32H4_USB_OTG_FS_CORE0_BASE       0x60040000UL
#define ESP32H4_USB_OTG_FS_CORE1_BASE       0x6007F000UL
#define ESP32H4_USB_OTG_BASE                ESP32H4_USB_OTG_FS_CORE0_BASE
#define ESP32H4_USB_WRAP_BASE               0x60080000UL

/* Timer groups, GPIO/IOMUX, PCR are clustered here on H4. */
#define ESP32H4_TIMG0_BASE                  0x60090000UL
#define ESP32H4_TIMG1_BASE                  0x60091000UL
#define ESP32H4_IOMUX_BASE                  0x60092000UL
#define ESP32H4_GPIO_BASE                   0x60093000UL
#define ESP32H4_GPIO_EXT_BASE               0x60093E00UL
#define ESP32H4_PCR_BASE                    0x60094000UL
#define ESP32H4_SPIMEM0_BASE                0x60098000UL    //!< MSPI0
#define ESP32H4_SPI0_BASE                   ESP32H4_SPIMEM0_BASE
#define ESP32H4_SPIMEM1_BASE                0x60099000UL    //!< MSPI1
#define ESP32H4_SPI1_BASE                   ESP32H4_SPIMEM1_BASE
#define ESP32H4_INTMTX0_BASE                0x6009A000UL    //!< Core0 INTMTX
#define ESP32H4_INTMTX_BASE                 ESP32H4_INTMTX0_BASE
#define ESP32H4_INTMTX1_BASE                0x6009B000UL    //!< Core1 INTMTX
#define ESP32H4_HP_SYSREG_BASE              0x6009C000UL
#define ESP32H4_HP_APM_BASE                 0x6009D000UL
#define ESP32H4_CPU_APM_BASE                0x6009E000UL
#define ESP32H4_TEE_BASE                    0x6009F000UL

/* Crypto block. */
#define ESP32H4_KEYMNG_BASE                 0x600A5000UL
#define ESP32H4_AES_BASE                    0x600A6000UL
#define ESP32H4_SHA_BASE                    0x600A7000UL
#define ESP32H4_ECC_BASE                    0x600A8000UL
#define ESP32H4_HMAC_BASE                   0x600A9000UL
#define ESP32H4_ECDSA_BASE                  0x600AA000UL

/* LP / RTC / PMU domain. */
#define ESP32H4_HUK_BASE                    0x600B1000UL
#define ESP32H4_LP_TEE_BASE                 0x600B1400UL
#define ESP32H4_EFUSE_BASE                  0x600B1800UL
#define ESP32H4_OTP_DEBUG_BASE              0x600B1C00UL
#define ESP32H4_TRNG_BASE                   0x600B2000UL
#define ESP32H4_PMU_BASE                    0x600B2400UL
#define ESP32H4_LP_AON_BASE                 0x600B2800UL
#define ESP32H4_LP_ANA_PERI_BASE            0x600B2C00UL
#define ESP32H4_LP_CLKRST_BASE              0x600B3000UL
#define ESP32H4_LPPERI_BASE                 0x600B3400UL
#define ESP32H4_LP_IOMUX_BASE               0x600B3800UL
#define ESP32H4_LP_GPIO_BASE                0x600B3C00UL
#define ESP32H4_LP_TIMER_BASE               0x600B5000UL
#define ESP32H4_RTC_TIMER_BASE              ESP32H4_LP_TIMER_BASE
#define ESP32H4_LP_WDT_BASE                 0x600B5400UL
#define ESP32H4_RTC_WDT_BASE                ESP32H4_LP_WDT_BASE
#define ESP32H4_TOUCH_SENS_BASE             0x600B5800UL
#define ESP32H4_TOUCH_AON_BASE              0x600B5C00UL

#define ESP32H4_CLINT_M_BASE                0x20000000UL

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32H4_CPU_CORE_COUNT              2U      //!< 2 HP RISC-V cores
#define ESP32H4_CPU_INTERRUPT_COUNT         32U
#define ESP32H4_UART_COUNT                  2U      //!< 2 HP UART, no LP
#define ESP32H4_HP_UART_COUNT               2U
#define ESP32H4_LP_UART_COUNT               0U
#define ESP32H4_SPI_MEM_COUNT               2U      //!< SPIMEM0/SPIMEM1
#define ESP32H4_GP_SPI_COUNT                2U      //!< SPI2 + SPI3
#define ESP32H4_I2C_COUNT                   2U
#define ESP32H4_HP_I2C_COUNT                2U
#define ESP32H4_LP_I2C_COUNT                0U
#define ESP32H4_I2S_COUNT                   1U
#define ESP32H4_TWAI_COUNT                  1U
#define ESP32H4_RMT_COUNT                   1U
#define ESP32H4_LEDC_COUNT                  1U
#define ESP32H4_PCNT_COUNT                  1U
#define ESP32H4_ETM_COUNT                   1U
#define ESP32H4_MCPWM_COUNT                 2U      //!< MCPWM0/MCPWM1
#define ESP32H4_PARL_IO_COUNT               1U
#define ESP32H4_TIMER_GROUP_COUNT           2U
#define ESP32H4_TIMER_PER_GROUP_COUNT       1U
#define ESP32H4_TIMER_COUNT                 2U
#define ESP32H4_SYSTIMER_COUNT              1U
#define ESP32H4_SYSTIMER_COUNTER_COUNT      2U
#define ESP32H4_SYSTIMER_ALARM_COUNT        3U
#define ESP32H4_GDMA_COUNT                  1U
#define ESP32H4_GDMA_PAIR_COUNT             3U
#define ESP32H4_GDMA_TX_CHANNEL_COUNT       3U
#define ESP32H4_GDMA_RX_CHANNEL_COUNT       3U
#define ESP32H4_GPIO_PORT_COUNT             1U
#define ESP32H4_GPIO_PIN_COUNT              40U
#define ESP32H4_GPIO_PIN_MAX                39U
#define ESP32H4_GPIO_PIN_REG_COUNT          40U
#define ESP32H4_GPIO_FUNC_IN_COUNT          256U
#define ESP32H4_GPIO_FUNC_OUT_COUNT         40U
#define ESP32H4_GPIO_FUNC_OUT_REG_COUNT     40U
#define ESP32H4_ADC_COUNT                   1U
#define ESP32H4_ADC_DIGI_CONTROLLER_COUNT   1U
#define ESP32H4_UHCI_COUNT                  1U
#define ESP32H4_USB_SERIAL_JTAG_COUNT       1U
#define ESP32H4_USB_OTG_COUNT               1U
#define ESP32H4_AES_COUNT                   1U
#define ESP32H4_SHA_COUNT                   1U
#define ESP32H4_HMAC_COUNT                  1U
#define ESP32H4_ECC_COUNT                   1U
#define ESP32H4_ECDSA_COUNT                 1U
#define ESP32H4_KEYMNG_COUNT                1U
#define ESP32H4_HUK_COUNT                   1U
#define ESP32H4_EFUSE_COUNT                 1U
#define ESP32H4_INTMTX_COUNT                2U      //!< One per core
#define ESP32H4_INTPRI_COUNT                1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32H4_*
 *
 * Every ESP32H4_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_TRACE0_BASE                       ESP32H4_TRACE0_BASE
#define ESP32_TRACE1_BASE                       ESP32H4_TRACE1_BASE
#define ESP32_TRACE_BASE                        ESP32H4_TRACE_BASE
#define ESP32_BUS_MONITOR_BASE                  ESP32H4_BUS_MONITOR_BASE
#define ESP32_INTPRI_BASE                       ESP32H4_INTPRI_BASE
#define ESP32_CACHE_BASE                        ESP32H4_CACHE_BASE
#define ESP32_GPSPI2_BASE                       ESP32H4_GPSPI2_BASE
#define ESP32_GP_SPI2_BASE                      ESP32H4_GP_SPI2_BASE
#define ESP32_SPI2_BASE                         ESP32H4_SPI2_BASE
#define ESP32_GPSPI3_BASE                       ESP32H4_GPSPI3_BASE
#define ESP32_GP_SPI3_BASE                      ESP32H4_GP_SPI3_BASE
#define ESP32_SPI3_BASE                         ESP32H4_SPI3_BASE
#define ESP32_UART0_BASE                        ESP32H4_UART0_BASE
#define ESP32_UART1_BASE                        ESP32H4_UART1_BASE
#define ESP32_UHCI_BASE                         ESP32H4_UHCI_BASE
#define ESP32_I2C0_BASE                         ESP32H4_I2C0_BASE
#define ESP32_I2C_BASE                          ESP32H4_I2C_BASE
#define ESP32_I2C1_BASE                         ESP32H4_I2C1_BASE
#define ESP32_I2S0_BASE                         ESP32H4_I2S0_BASE
#define ESP32_I2S_BASE                          ESP32H4_I2S_BASE
#define ESP32_PARL_IO_BASE                      ESP32H4_PARL_IO_BASE
#define ESP32_MCPWM0_BASE                       ESP32H4_MCPWM0_BASE
#define ESP32_MCPWM_BASE                        ESP32H4_MCPWM_BASE
#define ESP32_MCPWM1_BASE                       ESP32H4_MCPWM1_BASE
#define ESP32_LEDC_BASE                         ESP32H4_LEDC_BASE
#define ESP32_TWAIFD_BASE                       ESP32H4_TWAIFD_BASE
#define ESP32_TWAI_BASE                         ESP32H4_TWAI_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32H4_USB_SERIAL_JTAG_BASE
#define ESP32_RMT_BASE                          ESP32H4_RMT_BASE
#define ESP32_AHB_DMA_BASE                      ESP32H4_AHB_DMA_BASE
#define ESP32_GDMA_BASE                         ESP32H4_GDMA_BASE
#define ESP32_PAU_BASE                          ESP32H4_PAU_BASE
#define ESP32_SOC_ETM_BASE                      ESP32H4_SOC_ETM_BASE
#define ESP32_APB_SARADC_BASE                   ESP32H4_APB_SARADC_BASE
#define ESP32_SYSTIMER_BASE                     ESP32H4_SYSTIMER_BASE
#define ESP32_MEM_MONITOR_BASE                  ESP32H4_MEM_MONITOR_BASE
#define ESP32_PVT_BASE                          ESP32H4_PVT_BASE
#define ESP32_PCNT_BASE                         ESP32H4_PCNT_BASE
#define ESP32_SAMPLE_RATE_CONVERTER_BASE        ESP32H4_SAMPLE_RATE_CONVERTER_BASE
#define ESP32_ZERO_DET_BASE                     ESP32H4_ZERO_DET_BASE
#define ESP32_USB_OTG_FS_CORE0_BASE             ESP32H4_USB_OTG_FS_CORE0_BASE
#define ESP32_USB_OTG_FS_CORE1_BASE             ESP32H4_USB_OTG_FS_CORE1_BASE
#define ESP32_USB_OTG_BASE                      ESP32H4_USB_OTG_BASE
#define ESP32_USB_WRAP_BASE                     ESP32H4_USB_WRAP_BASE
#define ESP32_TIMG0_BASE                        ESP32H4_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32H4_TIMG1_BASE
#define ESP32_IOMUX_BASE                        ESP32H4_IOMUX_BASE
#define ESP32_GPIO_BASE                         ESP32H4_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32H4_GPIO_EXT_BASE
#define ESP32_PCR_BASE                          ESP32H4_PCR_BASE
#define ESP32_SPIMEM0_BASE                      ESP32H4_SPIMEM0_BASE
#define ESP32_SPI0_BASE                         ESP32H4_SPI0_BASE
#define ESP32_SPIMEM1_BASE                      ESP32H4_SPIMEM1_BASE
#define ESP32_SPI1_BASE                         ESP32H4_SPI1_BASE
#define ESP32_INTMTX0_BASE                      ESP32H4_INTMTX0_BASE
#define ESP32_INTMTX_BASE                       ESP32H4_INTMTX_BASE
#define ESP32_INTMTX1_BASE                      ESP32H4_INTMTX1_BASE
#define ESP32_HP_SYSREG_BASE                    ESP32H4_HP_SYSREG_BASE
#define ESP32_HP_APM_BASE                       ESP32H4_HP_APM_BASE
#define ESP32_CPU_APM_BASE                      ESP32H4_CPU_APM_BASE
#define ESP32_TEE_BASE                          ESP32H4_TEE_BASE
#define ESP32_KEYMNG_BASE                       ESP32H4_KEYMNG_BASE
#define ESP32_AES_BASE                          ESP32H4_AES_BASE
#define ESP32_SHA_BASE                          ESP32H4_SHA_BASE
#define ESP32_ECC_BASE                          ESP32H4_ECC_BASE
#define ESP32_HMAC_BASE                         ESP32H4_HMAC_BASE
#define ESP32_ECDSA_BASE                        ESP32H4_ECDSA_BASE
#define ESP32_HUK_BASE                          ESP32H4_HUK_BASE
#define ESP32_LP_TEE_BASE                       ESP32H4_LP_TEE_BASE
#define ESP32_EFUSE_BASE                        ESP32H4_EFUSE_BASE
#define ESP32_OTP_DEBUG_BASE                    ESP32H4_OTP_DEBUG_BASE
#define ESP32_TRNG_BASE                         ESP32H4_TRNG_BASE
#define ESP32_PMU_BASE                          ESP32H4_PMU_BASE
#define ESP32_LP_AON_BASE                       ESP32H4_LP_AON_BASE
#define ESP32_LP_ANA_PERI_BASE                  ESP32H4_LP_ANA_PERI_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32H4_LP_CLKRST_BASE
#define ESP32_LPPERI_BASE                       ESP32H4_LPPERI_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32H4_LP_IOMUX_BASE
#define ESP32_LP_GPIO_BASE                      ESP32H4_LP_GPIO_BASE
#define ESP32_LP_TIMER_BASE                     ESP32H4_LP_TIMER_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32H4_RTC_TIMER_BASE
#define ESP32_LP_WDT_BASE                       ESP32H4_LP_WDT_BASE
#define ESP32_RTC_WDT_BASE                      ESP32H4_RTC_WDT_BASE
#define ESP32_TOUCH_SENS_BASE                   ESP32H4_TOUCH_SENS_BASE
#define ESP32_TOUCH_AON_BASE                    ESP32H4_TOUCH_AON_BASE
#define ESP32_CLINT_M_BASE                      ESP32H4_CLINT_M_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32H4_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32H4_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32H4_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32H4_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32H4_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32H4_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32H4_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32H4_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32H4_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32H4_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32H4_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32H4_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32H4_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32H4_LEDC_COUNT
#define ESP32_PCNT_COUNT                        ESP32H4_PCNT_COUNT
#define ESP32_ETM_COUNT                         ESP32H4_ETM_COUNT
#define ESP32_MCPWM_COUNT                       ESP32H4_MCPWM_COUNT
#define ESP32_PARL_IO_COUNT                     ESP32H4_PARL_IO_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32H4_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32H4_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32H4_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32H4_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32H4_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32H4_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32H4_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32H4_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32H4_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32H4_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32H4_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32H4_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32H4_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32H4_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32H4_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32H4_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32H4_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32H4_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32H4_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_UHCI_COUNT                        ESP32H4_UHCI_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32H4_USB_SERIAL_JTAG_COUNT
#define ESP32_USB_OTG_COUNT                     ESP32H4_USB_OTG_COUNT
#define ESP32_AES_COUNT                         ESP32H4_AES_COUNT
#define ESP32_SHA_COUNT                         ESP32H4_SHA_COUNT
#define ESP32_HMAC_COUNT                        ESP32H4_HMAC_COUNT
#define ESP32_ECC_COUNT                         ESP32H4_ECC_COUNT
#define ESP32_ECDSA_COUNT                       ESP32H4_ECDSA_COUNT
#define ESP32_KEYMNG_COUNT                      ESP32H4_KEYMNG_COUNT
#define ESP32_HUK_COUNT                         ESP32H4_HUK_COUNT
#define ESP32_EFUSE_COUNT                       ESP32H4_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32H4_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32H4_INTPRI_COUNT

#endif // __ESP32H4_H__
