/**-------------------------------------------------------------------------
@file	esp32c61.h

@brief	ESP32-C61 chip-specific definition.

Single-core 32-bit RISC-V at up to 160 MHz, Wi-Fi 6 (2.4 GHz) + BLE 5,
30 GPIOs, three HP UARTs (UART0/UART1/UART2), no 802.15.4 (Thread/Zigbee).
Budget-focused C6 derivative.  Uses PCR for peripheral clock-gating,
dedicated INTMTX + INTPRI.

Defines the chip-specific ESP32C61_* set; chip-agnostic ESP32_* aliases
are generated by esp32xx_aliases.h via the ESP32_VARIANT_PREFIX trick.

Source-of-truth: ESP-IDF master,
   components/soc/esp32c61/register/soc/reg_base.h
   components/soc/esp32c61/include/soc/soc_caps.h

@author	Nguyen Hoan Hoang
@date	May 12, 2026

@license

MIT License

Copyright (c) 2026 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/
#ifndef __ESP32C61_H__
#define __ESP32C61_H__

/*===========================================================================
 * Peripheral register base addresses
 *==========================================================================*/
#define ESP32C61_UART0_BASE                 0x60000000UL
#define ESP32C61_UART1_BASE                 0x60001000UL
#define ESP32C61_MSPI0_BASE                 0x60002000UL    //!< Main flash MSPI 0
#define ESP32C61_SPIMEM0_BASE               ESP32C61_MSPI0_BASE
#define ESP32C61_SPI0_BASE                  ESP32C61_MSPI0_BASE
#define ESP32C61_MSPI1_BASE                 0x60003000UL
#define ESP32C61_SPIMEM1_BASE               ESP32C61_MSPI1_BASE
#define ESP32C61_SPI1_BASE                  ESP32C61_MSPI1_BASE
#define ESP32C61_I2C_BASE                   0x60004000UL
#define ESP32C61_UART2_BASE                 0x60006000UL    //!< 3rd HP UART
#define ESP32C61_LEDC_BASE                  0x60007000UL
#define ESP32C61_TIMG0_BASE                 0x60008000UL
#define ESP32C61_TIMG1_BASE                 0x60009000UL
#define ESP32C61_SYSTIMER_BASE              0x6000A000UL
#define ESP32C61_I2S_BASE                   0x6000C000UL
#define ESP32C61_SAR_ADC_BASE               0x6000E000UL
#define ESP32C61_USB_SERIAL_JTAG_BASE       0x6000F000UL
#define ESP32C61_INTMTX_BASE                0x60010000UL
#define ESP32C61_SOC_ETM_BASE               0x60013000UL
#define ESP32C61_HINF_BASE                  0x60016000UL
#define ESP32C61_SLC_BASE                   0x60017000UL
#define ESP32C61_HOST_BASE                  0x60018000UL
#define ESP32C61_PVT_BASE                   0x60019000UL

#define ESP32C61_AHB_DMA_BASE               0x60080000UL
#define ESP32C61_GDMA_BASE                  ESP32C61_AHB_DMA_BASE
#define ESP32C61_SPI2_BASE                  0x60081000UL    //!< GP-SPI2
#define ESP32C61_GP_SPI2_BASE               ESP32C61_SPI2_BASE
#define ESP32C61_SHA_BASE                   0x60089000UL
#define ESP32C61_ECC_MULT_BASE              0x6008B000UL
#define ESP32C61_ECC_BASE                   ESP32C61_ECC_MULT_BASE
#define ESP32C61_ECDSA_BASE                 0x6008E000UL

#define ESP32C61_IOMUX_BASE                 0x60090000UL
#define ESP32C61_GPIO_BASE                  0x60091000UL
#define ESP32C61_GPIO_EXT_BASE              0x60091E00UL
#define ESP32C61_MEM_MONITOR_BASE           0x60092000UL
#define ESP32C61_PAU_BASE                   0x60093000UL
#define ESP32C61_HP_SYSREG_BASE             0x60095000UL
#define ESP32C61_PCR_BASE                   0x60096000UL
#define ESP32C61_TEE_BASE                   0x60098000UL
#define ESP32C61_HP_APM_BASE                0x60099000UL
#define ESP32C61_CPU_APM_BASE               0x6009A000UL

#define ESP32C61_PMU_BASE                   0x600B0000UL
#define ESP32C61_LP_CLKRST_BASE             0x600B0400UL
#define ESP32C61_LP_TIMER_BASE              0x600B0C00UL
#define ESP32C61_RTC_TIMER_BASE             ESP32C61_LP_TIMER_BASE
#define ESP32C61_LP_AON_BASE                0x600B1000UL
#define ESP32C61_LP_WDT_BASE                0x600B1C00UL
#define ESP32C61_RTC_WDT_BASE               ESP32C61_LP_WDT_BASE
#define ESP32C61_LPPERI_BASE                0x600B2800UL
#define ESP32C61_LP_ANA_BASE                0x600B2C00UL
#define ESP32C61_LP_TEE_BASE                0x600B3400UL
#define ESP32C61_LP_APM_BASE                0x600B3800UL
#define ESP32C61_LP_IOMUX_BASE              0x600B4000UL
#define ESP32C61_LP_GPIO_BASE               0x600B4400UL
#define ESP32C61_EFUSE_BASE                 0x600B4800UL
#define ESP32C61_OTP_DEBUG_BASE             0x600B4C00UL

#define ESP32C61_TRACE_BASE                 0x600C0000UL
#define ESP32C61_BUS_MONITOR_BASE           0x600C2000UL
#define ESP32C61_INTPRI_BASE                0x600C5000UL
#define ESP32C61_CACHE_BASE                 0x600C8000UL

#define ESP32C61_CLINT_M_BASE               0x20000000UL    //!< RISC-V CLINT machine-mode

/*===========================================================================
 * Peripheral instance counts
 *==========================================================================*/
#define ESP32C61_CPU_CORE_COUNT             1U
#define ESP32C61_CPU_INTERRUPT_COUNT        32U
#define ESP32C61_UART_COUNT                 3U      //!< 3 HP UART, no LP UART
#define ESP32C61_HP_UART_COUNT              3U
#define ESP32C61_LP_UART_COUNT              0U
#define ESP32C61_SPI_MEM_COUNT              2U
#define ESP32C61_GP_SPI_COUNT               1U
#define ESP32C61_I2C_COUNT                  1U
#define ESP32C61_HP_I2C_COUNT               1U
#define ESP32C61_LP_I2C_COUNT               0U
#define ESP32C61_I2S_COUNT                  1U
#define ESP32C61_TWAI_COUNT                 0U      //!< No TWAI on C61
#define ESP32C61_RMT_COUNT                  0U      //!< No RMT on C61
#define ESP32C61_LEDC_COUNT                 1U
#define ESP32C61_ETM_COUNT                  1U
#define ESP32C61_TIMER_GROUP_COUNT          2U
#define ESP32C61_TIMER_PER_GROUP_COUNT      1U
#define ESP32C61_TIMER_COUNT                2U
#define ESP32C61_SYSTIMER_COUNT             1U
#define ESP32C61_SYSTIMER_COUNTER_COUNT     2U
#define ESP32C61_SYSTIMER_ALARM_COUNT       3U
#define ESP32C61_GDMA_COUNT                 1U
#define ESP32C61_GDMA_PAIR_COUNT            3U
#define ESP32C61_GDMA_TX_CHANNEL_COUNT      3U
#define ESP32C61_GDMA_RX_CHANNEL_COUNT      3U
#define ESP32C61_GPIO_PORT_COUNT            1U
#define ESP32C61_GPIO_PIN_COUNT             30U
#define ESP32C61_GPIO_PIN_MAX               29U
#define ESP32C61_GPIO_PIN_REG_COUNT         30U
#define ESP32C61_GPIO_FUNC_IN_COUNT         128U
#define ESP32C61_GPIO_FUNC_OUT_COUNT        30U
#define ESP32C61_GPIO_FUNC_OUT_REG_COUNT    30U
#define ESP32C61_ADC_COUNT                  1U
#define ESP32C61_ADC_DIGI_CONTROLLER_COUNT  1U
#define ESP32C61_USB_SERIAL_JTAG_COUNT      1U
#define ESP32C61_SHA_COUNT                  1U
#define ESP32C61_ECC_COUNT                  1U
#define ESP32C61_ECDSA_COUNT                1U
#define ESP32C61_EFUSE_COUNT                1U
#define ESP32C61_INTMTX_COUNT               1U
#define ESP32C61_INTPRI_COUNT               1U

/*===========================================================================
 * Cross-chip alias hook-up
 *==========================================================================*/

/*===========================================================================
 * ESP32_* aliases -> ESP32C61_*
 *
 * Every ESP32C61_xxx symbol above is aliased to the chip-agnostic ESP32_xxx
 * name on the line below.  Driver code references the ESP32_xxx form and
 * uses `#ifdef ESP32_xxx_BASE` to guard chip-specific paths.
 *
 * No token-paste indirection -- each line is a plain alias.
 *==========================================================================*/

#define ESP32_UART0_BASE                        ESP32C61_UART0_BASE
#define ESP32_UART1_BASE                        ESP32C61_UART1_BASE
#define ESP32_MSPI0_BASE                        ESP32C61_MSPI0_BASE
#define ESP32_SPIMEM0_BASE                      ESP32C61_SPIMEM0_BASE
#define ESP32_SPI0_BASE                         ESP32C61_SPI0_BASE
#define ESP32_MSPI1_BASE                        ESP32C61_MSPI1_BASE
#define ESP32_SPIMEM1_BASE                      ESP32C61_SPIMEM1_BASE
#define ESP32_SPI1_BASE                         ESP32C61_SPI1_BASE
#define ESP32_I2C_BASE                          ESP32C61_I2C_BASE
#define ESP32_UART2_BASE                        ESP32C61_UART2_BASE
#define ESP32_LEDC_BASE                         ESP32C61_LEDC_BASE
#define ESP32_TIMG0_BASE                        ESP32C61_TIMG0_BASE
#define ESP32_TIMG1_BASE                        ESP32C61_TIMG1_BASE
#define ESP32_SYSTIMER_BASE                     ESP32C61_SYSTIMER_BASE
#define ESP32_I2S_BASE                          ESP32C61_I2S_BASE
#define ESP32_SAR_ADC_BASE                      ESP32C61_SAR_ADC_BASE
#define ESP32_USB_SERIAL_JTAG_BASE              ESP32C61_USB_SERIAL_JTAG_BASE
#define ESP32_INTMTX_BASE                       ESP32C61_INTMTX_BASE
#define ESP32_SOC_ETM_BASE                      ESP32C61_SOC_ETM_BASE
#define ESP32_HINF_BASE                         ESP32C61_HINF_BASE
#define ESP32_SLC_BASE                          ESP32C61_SLC_BASE
#define ESP32_HOST_BASE                         ESP32C61_HOST_BASE
#define ESP32_PVT_BASE                          ESP32C61_PVT_BASE
#define ESP32_AHB_DMA_BASE                      ESP32C61_AHB_DMA_BASE
#define ESP32_GDMA_BASE                         ESP32C61_GDMA_BASE
#define ESP32_SPI2_BASE                         ESP32C61_SPI2_BASE
#define ESP32_GP_SPI2_BASE                      ESP32C61_GP_SPI2_BASE
#define ESP32_SHA_BASE                          ESP32C61_SHA_BASE
#define ESP32_ECC_MULT_BASE                     ESP32C61_ECC_MULT_BASE
#define ESP32_ECC_BASE                          ESP32C61_ECC_BASE
#define ESP32_ECDSA_BASE                        ESP32C61_ECDSA_BASE
#define ESP32_IOMUX_BASE                        ESP32C61_IOMUX_BASE
#define ESP32_GPIO_BASE                         ESP32C61_GPIO_BASE
#define ESP32_GPIO_EXT_BASE                     ESP32C61_GPIO_EXT_BASE
#define ESP32_MEM_MONITOR_BASE                  ESP32C61_MEM_MONITOR_BASE
#define ESP32_PAU_BASE                          ESP32C61_PAU_BASE
#define ESP32_HP_SYSREG_BASE                    ESP32C61_HP_SYSREG_BASE
#define ESP32_PCR_BASE                          ESP32C61_PCR_BASE
#define ESP32_TEE_BASE                          ESP32C61_TEE_BASE
#define ESP32_HP_APM_BASE                       ESP32C61_HP_APM_BASE
#define ESP32_CPU_APM_BASE                      ESP32C61_CPU_APM_BASE
#define ESP32_PMU_BASE                          ESP32C61_PMU_BASE
#define ESP32_LP_CLKRST_BASE                    ESP32C61_LP_CLKRST_BASE
#define ESP32_LP_TIMER_BASE                     ESP32C61_LP_TIMER_BASE
#define ESP32_RTC_TIMER_BASE                    ESP32C61_RTC_TIMER_BASE
#define ESP32_LP_AON_BASE                       ESP32C61_LP_AON_BASE
#define ESP32_LP_WDT_BASE                       ESP32C61_LP_WDT_BASE
#define ESP32_RTC_WDT_BASE                      ESP32C61_RTC_WDT_BASE
#define ESP32_LPPERI_BASE                       ESP32C61_LPPERI_BASE
#define ESP32_LP_ANA_BASE                       ESP32C61_LP_ANA_BASE
#define ESP32_LP_TEE_BASE                       ESP32C61_LP_TEE_BASE
#define ESP32_LP_APM_BASE                       ESP32C61_LP_APM_BASE
#define ESP32_LP_IOMUX_BASE                     ESP32C61_LP_IOMUX_BASE
#define ESP32_LP_GPIO_BASE                      ESP32C61_LP_GPIO_BASE
#define ESP32_EFUSE_BASE                        ESP32C61_EFUSE_BASE
#define ESP32_OTP_DEBUG_BASE                    ESP32C61_OTP_DEBUG_BASE
#define ESP32_TRACE_BASE                        ESP32C61_TRACE_BASE
#define ESP32_BUS_MONITOR_BASE                  ESP32C61_BUS_MONITOR_BASE
#define ESP32_INTPRI_BASE                       ESP32C61_INTPRI_BASE
#define ESP32_CACHE_BASE                        ESP32C61_CACHE_BASE
#define ESP32_CLINT_M_BASE                      ESP32C61_CLINT_M_BASE
#define ESP32_CPU_CORE_COUNT                    ESP32C61_CPU_CORE_COUNT
#define ESP32_CPU_INTERRUPT_COUNT               ESP32C61_CPU_INTERRUPT_COUNT
#define ESP32_UART_COUNT                        ESP32C61_UART_COUNT
#define ESP32_HP_UART_COUNT                     ESP32C61_HP_UART_COUNT
#define ESP32_LP_UART_COUNT                     ESP32C61_LP_UART_COUNT
#define ESP32_SPI_MEM_COUNT                     ESP32C61_SPI_MEM_COUNT
#define ESP32_GP_SPI_COUNT                      ESP32C61_GP_SPI_COUNT
#define ESP32_I2C_COUNT                         ESP32C61_I2C_COUNT
#define ESP32_HP_I2C_COUNT                      ESP32C61_HP_I2C_COUNT
#define ESP32_LP_I2C_COUNT                      ESP32C61_LP_I2C_COUNT
#define ESP32_I2S_COUNT                         ESP32C61_I2S_COUNT
#define ESP32_TWAI_COUNT                        ESP32C61_TWAI_COUNT
#define ESP32_RMT_COUNT                         ESP32C61_RMT_COUNT
#define ESP32_LEDC_COUNT                        ESP32C61_LEDC_COUNT
#define ESP32_ETM_COUNT                         ESP32C61_ETM_COUNT
#define ESP32_TIMER_GROUP_COUNT                 ESP32C61_TIMER_GROUP_COUNT
#define ESP32_TIMER_PER_GROUP_COUNT             ESP32C61_TIMER_PER_GROUP_COUNT
#define ESP32_TIMER_COUNT                       ESP32C61_TIMER_COUNT
#define ESP32_SYSTIMER_COUNT                    ESP32C61_SYSTIMER_COUNT
#define ESP32_SYSTIMER_COUNTER_COUNT            ESP32C61_SYSTIMER_COUNTER_COUNT
#define ESP32_SYSTIMER_ALARM_COUNT              ESP32C61_SYSTIMER_ALARM_COUNT
#define ESP32_GDMA_COUNT                        ESP32C61_GDMA_COUNT
#define ESP32_GDMA_PAIR_COUNT                   ESP32C61_GDMA_PAIR_COUNT
#define ESP32_GDMA_TX_CHANNEL_COUNT             ESP32C61_GDMA_TX_CHANNEL_COUNT
#define ESP32_GDMA_RX_CHANNEL_COUNT             ESP32C61_GDMA_RX_CHANNEL_COUNT
#define ESP32_GPIO_PORT_COUNT                   ESP32C61_GPIO_PORT_COUNT
#define ESP32_GPIO_PIN_COUNT                    ESP32C61_GPIO_PIN_COUNT
#define ESP32_GPIO_PIN_MAX                      ESP32C61_GPIO_PIN_MAX
#define ESP32_GPIO_PIN_REG_COUNT                ESP32C61_GPIO_PIN_REG_COUNT
#define ESP32_GPIO_FUNC_IN_COUNT                ESP32C61_GPIO_FUNC_IN_COUNT
#define ESP32_GPIO_FUNC_OUT_COUNT               ESP32C61_GPIO_FUNC_OUT_COUNT
#define ESP32_GPIO_FUNC_OUT_REG_COUNT           ESP32C61_GPIO_FUNC_OUT_REG_COUNT
#define ESP32_ADC_COUNT                         ESP32C61_ADC_COUNT
#define ESP32_ADC_DIGI_CONTROLLER_COUNT         ESP32C61_ADC_DIGI_CONTROLLER_COUNT
#define ESP32_USB_SERIAL_JTAG_COUNT             ESP32C61_USB_SERIAL_JTAG_COUNT
#define ESP32_SHA_COUNT                         ESP32C61_SHA_COUNT
#define ESP32_ECC_COUNT                         ESP32C61_ECC_COUNT
#define ESP32_ECDSA_COUNT                       ESP32C61_ECDSA_COUNT
#define ESP32_EFUSE_COUNT                       ESP32C61_EFUSE_COUNT
#define ESP32_INTMTX_COUNT                      ESP32C61_INTMTX_COUNT
#define ESP32_INTPRI_COUNT                      ESP32C61_INTPRI_COUNT

#endif // __ESP32C61_H__
