/**--------------------------------------------------------------------------
@file	blueio_board.h

@brief	Contains definitions for BlueIO series boards

@author	Hoang Nguyen Hoan
@date	Sep. 20, 2014

@license

MIT License

Copyright (c) 2014 I-SYST inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

----------------------------------------------------------------------------*/

#ifndef __BLUEIO_BOARD_H__
#define __BLUEIO_BOARD_H__

#ifndef BLUEIO_BOARD
#define BLUEIO_BOARD						1
#endif

// ***** Default pin map for BLUEIO Boards
// LEDs
#define BLUEIO_LED1_PORT					0
#define BLUEIO_LED1_PIN						30
#define BLUEIO_LED1_PINOP					0

#define BLUEIO_LED2_PORT					0
#define BLUEIO_LED2_PIN						29
#define BLUEIO_LED2_PINOP					0

#define BLUEIO_LED3_PORT					0
#define BLUEIO_LED3_PIN						28
#define BLUEIO_LED3_PINOP					0

#define BLUEIO_LED4_PORT					0
#define BLUEIO_LED4_PIN						27
#define BLUEIO_LED4_PINOP					0

// ***** BLUEIO832-MINI pins

// BLUEIO832-MINI LED pins
#define BLUEIO832_MINI_LEDR_PORT			0
#define BLUEIO832_MINI_LEDR_PIN				18
#define BLUEIO832_MINI_LEDR_PINOP			0

#define BLUEIO832_MINI_LEDG_PORT			0
#define BLUEIO832_MINI_LEDG_PIN				16
#define BLUEIO832_MINI_LEDG_PINOP			0

#define BLUEIO832_MINI_LEDB_PORT			0
#define BLUEIO832_MINI_LEDB_PIN				17
#define BLUEIO832_MINI_LEDB_PINOP			0

#define BLUEIO832_MINI_LED_PINS	{ \
	{BLUEIO832_MINI_LEDR_PORT, BLUEIO832_MINI_LEDR_PIN, BLUEIO832_MINI_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDG_PORT, BLUEIO832_MINI_LEDG_PIN, BLUEIO832_MINI_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO832_MINI_LEDB_PORT, BLUEIO832_MINI_LEDB_PIN, BLUEIO832_MINI_LEDB_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// *****

// ***** BLUEIO840 pins

// BLUEIO840 LED
#define BLUEIO840_LED1_PORT					1
#define BLUEIO840_LED1_PIN					7
#define BLUEIO840_LED1_PINOP				0

#define BLUEIO840_LED2R_PORT				1
#define BLUEIO840_LED2R_PIN					11
#define BLUEIO840_LED2R_PINOP				0

#define BLUEIO840_LED2G_PORT				1
#define BLUEIO840_LED2G_PIN					6
#define BLUEIO840_LED2G_PINOP				0

#define BLUEIO840_LED2B_PORT				1
#define BLUEIO840_LED2B_PIN					10
#define BLUEIO840_LED2B_PINOP				0

#define BLUEIO840_LED_PINS	{ \
	{BLUEIO840_LED1_PORT, BLUEIO840_LED1_PIN, BLUEIO840_LED1_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_LED2R_PORT, BLUEIO840_LED2R_PIN, BLUEIO840_LEDR_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_LED2G_PORT, BLUEIO840_LED2G_PIN, BLUEIO840_LEDG_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_LED2B_PORT, BLUEIO840_LED2B_PIN, BLUEIO840_LED2B_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
}

// BLUEIO840 buttons
#define BLUEIO840_BUT1_PORT					1
#define BLUEIO840_BUT1_PIN					3
#define BLUEIO840_BUT1_PINOP				0

#define BLUEIO840_BUT2_PORT					0
#define BLUEIO840_BUT2_PIN					13
#define BLUEIO840_BUT2_PINOP				0

#define BLUEIO840_BUT_PINS	{ \
	{BLUEIO840_BUT1_PORT, BLUEIO840_BUT1_PIN, BLUEIO840_BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BLUEIO840_BUT2_PORT, BLUEIO840_BUT2_PIN, BLUEIO840_BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// BLUEIO840 I2C Eeprom
#define BLUEIO840_I2C_SCL_PORT				1
#define BLUEIO840_I2C_SCL_PIN				5
#define BLUEIO840_I2C_SCL_PINOP				0
#define BLUEIO840_I2C_SDA_PORT				1
#define BLUEIO840_I2C_SDA_PIN				2
#define BLUEIO840_I2C_SDA_PINOP				0

#define BLUEIO840_I2C_PINS	{ \
	{BLUEIO840_I2C_SCL_PORT, BLUEIO840_I2C_SCL_PIN, BLUEIO840_I2C_SCL_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_OPENDRAIN}, \
	{BLUEIO840_I2C_SDA_PORT, BLUEIO840_I2C_SDA_PIN, BLUEIO840_I2C_SDA_PINOP, IOPINDIR_BI, IOPINRES_PULLUP, IOPINTYPE_OPENDRAIN}, \
}

// BLUEIO840 QSPI Flash
#define BLUEIO840_QSPI_CLK_PORT				0
#define BLUEIO840_QSPI_CLK_PIN				13
#define BLUEIO840_QSPI_CLK_PINOP			1
#define BLUEIO840_QSPI_SIO0_PORT			0
#define BLUEIO840_QSPI_SIO0_PIN				12
#define BLUEIO840_QSPI_SIO0_PINOP			1
#define BLUEIO840_QSPI_SIO1_PORT			1
#define BLUEIO840_QSPI_SIO1_PIN				9
#define BLUEIO840_QSPI_SIO1_PINOP			1
#define BLUEIO840_QSPI_SIO2_PORT			0
#define BLUEIO840_QSPI_SIO2_PIN				11
#define BLUEIO840_QSPI_SIO2_PINOP			1
#define BLUEIO840_QSPI_SIO3_PORT			0
#define BLUEIO840_QSPI_SIO3_PIN				14
#define BLUEIO840_QSPI_SIO3_PINOP			1

#define BLUEIO840_FLASH_CS_PORT				1
#define BLUEIO840_FLASH_CS_PIN				8
#define BLUEIO840_FLASH_CS_PINOP			0

#define BLUEIO840_QSPI_PINS	{\
	{BLUEIO840_QSPI_CLK_PORT, BLUEIO840_QSPI_CLK_PIN, BLUEIO840_QSPI_CLK_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_QSPI_SIO0_PORT, BLUEIO840_QSPI_SIO0_PIN, BLUEIO840_QSPI_SIO0_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_QSPI_SIO1_PORT, BLUEIO840_QSPI_SIO1_PIN, BLUEIO840_QSPI_SIO1_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_QSPI_SIO2_PORT, BLUEIO840_QSPI_SIO2_PIN, BLUEIO840_QSPI_SIO2_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_QSPI_SIO3_PORT, BLUEIO840_QSPI_SIO3_PIN, BLUEIO840_QSPI_SIO3_PINOP, IOPINDIR_BI, IOPINRES_NONE, IOPINTYPE_NORMAL}, \
	{BLUEIO840_FLASH_CS_PORT, BLUEIO840_FLASH_CS_PIN, BLUEIO840_FLASH_CS_PINOP, IOPINDIR_OUTPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}

// *****

// Buttons
#define BLUEIO_BUT1_PORT					0
#define BLUEIO_BUT1_PIN						2
#define BLUEIO_BUT1_PINOP					0
#define BLUEIO_BUT2_PORT					0
#define BLUEIO_BUT2_PIN						13
#define BLUEIO_BUT2_PINOP					0



// UART pins
#define BLUEIO_UART_RX_PORT					0
#define BLUEIO_UART_RX_PIN					8
#define BLUEIO_UART_RX_PINOP				0
#define BLUEIO_UART_TX_PORT					0
#define BLUEIO_UART_TX_PIN					7
#define BLUEIO_UART_TX_PINOP				0
#define BLUEIO_UART_CTS_PORT				0
#define BLUEIO_UART_CTS_PIN					12
#define BLUEIO_UART_CTS_PINOP				0
#define BLUEIO_UART_RTS_PORT				0
#define BLUEIO_UART_RTS_PIN					11
#define BLUEIO_UART_RTS_PINOP				0

// I2C0 MASTER
#define BLUEIO_I2C0_MASTER_DEVNO			0
#define BLUEIO_I2C0_MASTER_SCL_PORT			0
#define BLUEIO_I2C0_MASTER_SCL_PIN			11
#define BLUEIO_I2C0_MASTER_SCL_PINOP		1
#define BLUEIO_I2C0_MASTER_SDA_PORT			0
#define BLUEIO_I2C0_MASTER_SDA_PIN			12
#define BLUEIO_I2C0_MASTER_SDA_PINOP		1

// I2C0 SLAVE
#define BLUEIO_I2C0_SLAVE_DEVNO				1
#define BLUEIO_I2C0_SLAVE_SCL_PORT			0
#define BLUEIO_I2C0_SLAVE_SCL_PIN			16
#define BLUEIO_I2C0_SLAVE_SCL_PINOP			1
#define BLUEIO_I2C0_SLAVE_SDA_PORT			0
#define BLUEIO_I2C0_SLAVE_SDA_PIN			15
#define BLUEIO_I2C0_SLAVE_SDA_PINOP			1



// SPI1
#define BLUEIO_SPI1_DEVNO					1

#define BLUEIO_SPI1_SCK_PORT				0
#define BLUEIO_SPI1_SCK_PIN					23
#define BLUEIO_SPI1_SCK_PINOP				1
#define BLUEIO_SPI1_MOSI_PORT				0
#define BLUEIO_SPI1_MOSI_PIN				24
#define BLUEIO_SPI1_MOSI_PINOP				1
#define BLUEIO_SPI1_MISO_PORT				0
#define BLUEIO_SPI1_MISO_PIN				25
#define BLUEIO_SPI1_MISO_PINOP				1

// SPI2
#define BLUEIO_SPI2_DEVNO					2

#define BLUEIO_SPI2_SCK_PORT				0
#define BLUEIO_SPI2_SCK_PIN					17
#define BLUEIO_SPI2_SCK_PINOP				1
#define BLUEIO_SPI2_MOSI_PORT				0
#define BLUEIO_SPI2_MOSI_PIN				16
#define BLUEIO_SPI2_MOSI_PINOP				1
#define BLUEIO_SPI2_MISO_PORT				0
#define BLUEIO_SPI2_MISO_PIN				15
#define BLUEIO_SPI2_MISO_PINOP				1

// ***** Most IMM-NRF5x base boards use P0.30 for Bluetooth connection state LED
#define BLUEIO_CONNECT_LED_PORT				BLUEIO_LED1_PORT
#define BLUEIO_CONNECT_LED_PIN				BLUEIO_LED1_PIN

// ***** IBK-BLUEIO - Blue IO breakout board
#define BLUEIO_LED_BLUE_PORT				BLUEIO_LED1_PORT
#define BLUEIO_LED_BLUE_PIN					BLUEIO_LED1_PIN
#define BLUEIO_LED_BLUE_PINOP				BLUEIO_LED1_PINOP
#define BLUEIO_LED_GREEN_PORT				BLUEIO_LED2_PORT
#define BLUEIO_LED_GREEN_PIN				BLUEIO_LED2_PIN
#define BLUEIO_LED_GREEN_PINOP				BLUEIO_LED2_PINOP
#define BLUEIO_LED_RED_PORT					BLUEIO_LED3_PORT
#define BLUEIO_LED_RED_PIN					BLUEIO_LED3_PIN
#define BLUEIO_LED_RED_PINOP				BLUEIO_LED3_PINOP


// ***** BLUEIO-TAG-BME680 board
#define BLUEIO_TAG_BME680_LED1_PORT			BLUEIO_LED1_PORT
#define BLUEIO_TAG_BME680_LED1_PIN			BLUEIO_LED1_PIN
#define BLUEIO_TAG_BME680_LED1_PINOP		BLUEIO_LED1_PINOP

#define BLUEIO_TAG_BME680_LED2_RED_PORT		0
#define BLUEIO_TAG_BME680_LED2_RED_PIN		18
#define BLUEIO_TAG_BME680_LED2_RED_PINOP	0

#define BLUEIO_TAG_BME680_LED2_GREEN_PORT	0
#define BLUEIO_TAG_BME680_LED2_GREEN_PIN	20
#define BLUEIO_TAG_BME680_LED2_GREEN_PINOP	0

#define BLUEIO_TAG_BME680_LED2_BLUE_PORT	0
#define BLUEIO_TAG_BME680_LED2_BLUE_PIN		19
#define BLUEIO_TAG_BME680_LED2_BLUE_PINOP	0

#define BLUEIO_TAG_BME680_I2C_SDA_PORT		0
#define BLUEIO_TAG_BME680_I2C_SDA_PIN		28
#define BLUEIO_TAG_BME680_I2C_SDA_PINOP		1

#define BLUEIO_TAG_BME680_I2C_SCL_PORT		0
#define BLUEIO_TAG_BME680_I2C_SCL_PIN		29
#define BLUEIO_TAG_BME680_I2C_SCL_PINOP		1

#define BLUEIO_TAG_BME680_SPI_SCK_PORT		0
#define BLUEIO_TAG_BME680_SPI_SCK_PIN		17
#define BLUEIO_TAG_BME680_SPI_SCK_PINOP		1

#define BLUEIO_TAG_BME680_SPI_MOSI_PORT		0
#define BLUEIO_TAG_BME680_SPI_MOSI_PIN		16
#define BLUEIO_TAG_BME680_SPI_MOSI_PINOP	1

#define BLUEIO_TAG_BME680_SPI_MISO_PORT		0
#define BLUEIO_TAG_BME680_SPI_MISO_PIN		15
#define BLUEIO_TAG_BME680_SPI_MISO_PINOP	1

#define BLUEIO_TAG_BME680_IMU_CS_PORT		0
#define BLUEIO_TAG_BME680_IMU_CS_PIN		5
#define BLUEIO_TAG_BME680_IMU_CS_PINOP		0

#define BLUEIO_TAG_BME680_IMU_INT_PORT		0
#define BLUEIO_TAG_BME680_IMU_INT_PIN		6
#define BLUEIO_TAG_BME680_IMU_INT_PINOP		0

// ***** BLUEIO-TAG-BME280 board
#define BLUEIO_TAG_BME280_LED1_PORT			BLUEIO_LED1_PORT
#define BLUEIO_TAG_BME280_LED1_PIN			BLUEIO_LED1_PIN
#define BLUEIO_TAG_BME280_LED1_PINOP		BLUEIO_LED1_PINOP

#define BLUEIO_TAG_BME280_LED2_PORT			0
#define BLUEIO_TAG_BME280_LED2_PIN			17
#define BLUEIO_TAG_BME280_LED2_PINOP		0

// BLUEIO-TAG-BMEx80 buttons

#define BLUEIO_TAG_BME280_BUT2_PORT			BLUEIO_BUT2_PORT
#define BLUEIO_TAG_BME280_BUT2_PIN			BLUEIO_BUT2_PIN
#define BLUEIO_TAG_BME280_BUT2_PINOP		BLUEIO_BUT2_PINOP

#define BLUEIO_TAG_BME280_I2C_SDA_PORT		0
#define BLUEIO_TAG_BME280_I2C_SDA_PIN		24
#define BLUEIO_TAG_BME280_I2C_SDA_PINOP		0

#define BLUEIO_TAG_BME280_I2C_SCL_PORT		0
#define BLUEIO_TAG_BME280_I2C_SCL_PIN		25
#define BLUEIO_TAG_BME280_I2C_SCL_PINOP		0

// ***** BLUEIO-TAG-EVIM board

#define BLUEIO_TAG_EVIM_LED2_RED_PORT		BLUEIO_TAG_BME680_LED2_RED_PORT
#define BLUEIO_TAG_EVIM_LED2_RED_PIN		BLUEIO_TAG_BME680_LED2_RED_PIN
#define BLUEIO_TAG_EVIM_LED2_RED_PINOP		BLUEIO_TAG_BME680_LED2_RED_PINOP

#define BLUEIO_TAG_EVIM_LED2_GREEN_PORT		BLUEIO_TAG_BME680_LED2_GREEN_PORT
#define BLUEIO_TAG_EVIM_LED2_GREEN_PIN		BLUEIO_TAG_BME680_LED2_GREEN_PIN
#define BLUEIO_TAG_EVIM_LED2_GREEN_PINOP	BLUEIO_TAG_BME680_LED2_GREEN_PINOP

#define BLUEIO_TAG_EVIM_LED2_BLUE_PORT		BLUEIO_TAG_BME680_LED2_BLUE_PORT
#define BLUEIO_TAG_EVIM_LED2_BLUE_PIN		BLUEIO_TAG_BME680_LED2_BLUE_PIN
#define BLUEIO_TAG_EVIM_LED2_BLUE_PINOP		BLUEIO_TAG_BME680_LED2_BLUE_PINOP

#define BLUEIO_TAG_EVIM_I2C0_DEVNO			0

#define BLUEIO_TAG_EVIM_I2C0_SCL_PORT		0
#define BLUEIO_TAG_EVIM_I2C0_SCL_PIN		29
#define BLUEIO_TAG_EVIM_I2C0_SCL_PINOP		1
#define BLUEIO_TAG_EVIM_I2C0_SDA_PORT		0
#define BLUEIO_TAG_EVIM_I2C0_SDA_PIN		28
#define BLUEIO_TAG_EVIM_I2C0_SDA_PINOP		1

#define BLUEIO_TAG_EVIM_SPI2_SCK_PORT		BLUEIO_SPI2_SCK_PORT
#define BLUEIO_TAG_EVIM_SPI2_SCK_PIN		BLUEIO_SPI2_SCK_PIN
#define BLUEIO_TAG_EVIM_SPI2_SCK_PINOP		BLUEIO_SPI2_SCK_PINOP
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PORT		BLUEIO_SPI2_MOSI_PORT
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PIN		BLUEIO_SPI2_MOSI_PIN
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PINOP		BLUEIO_SPI2_MOSI_PINOP
#define BLUEIO_TAG_EVIM_SPI2_MISO_PORT		BLUEIO_SPI2_MISO_PORT
#define BLUEIO_TAG_EVIM_SPI2_MISO_PIN		BLUEIO_SPI2_MISO_PIN
#define BLUEIO_TAG_EVIM_SPI2_MISO_PINOP		BLUEIO_SPI2_MISO_PINOP

#define BLUEIO_TAG_EVIM_IMU_CS_PORT			0
#define BLUEIO_TAG_EVIM_IMU_CS_PIN			5
#define BLUEIO_TAG_EVIM_IMU_CS_PINOP		0

#define BLUEIO_TAG_EVIM_IMU_INT_PORT		0
#define BLUEIO_TAG_EVIM_IMU_INT_PIN			6
#define BLUEIO_TAG_EVIM_IMU_INT_PINOP		0

#define BLUEIO_TAG_EVIM_EEP_WP_PORT			0
#define BLUEIO_TAG_EVIM_EEP_WP_PIN			27
#define BLUEIO_TAG_EVIM_EEP_WP_PINOP		0

#define BLUEIO_TAG_EVIM_BUZZ_PORT			0
#define BLUEIO_TAG_EVIM_BUZZ_PIN			14
#define BLUEIO_TAG_EVIM_BUZZ_PINOP			0

#define BLUEIO_TAG_EVIM_FLASH_CS_PORT		0
#define BLUEIO_TAG_EVIM_FLASH_CS_PIN		26
#define BLUEIO_TAG_EVIM_FLASH_CS_PINOP		0

// ***** BLUEIO-ADXL-WCHRG

#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PORT		BLUEIO_SPI2_SCK_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PIN		BLUEIO_SPI2_SCK_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PINOP		BLUEIO_SPI2_SCK_PINOP
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PORT		BLUEIO_SPI2_MOSI_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PIN		BLUEIO_SPI2_MOSI_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PINOP	BLUEIO_SPI2_MOSI_PINOP
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PORT		BLUEIO_SPI2_MISO_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PIN		BLUEIO_SPI2_MISO_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PINOP	BLUEIO_SPI2_MISO_PINOP

#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PIN		5
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PPINOP		0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PORT		BLUEIO_I2C0_SCL_PORT
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PIN		BLUEIO_I2C0_SCL_PIN
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PINOP		BLUEIO_I2C0_SCL_PINOP
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PORT		BLUEIO_I2C0_SDA_PORT
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PIN		BLUEIO_I2C0_SDA_PIN
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PINOP		BLUEIO_I2C0_SDA_PINOP

#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PIN		20
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0

#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PORT		BLUEIO_SPI1_SCK_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PIN			BLUEIO_SPI1_SCK_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PINOP		BLUEIO_SPI1_SCK_PINOP
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PORT		BLUEIO_SPI1_MOSI_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PIN		BLUEIO_SPI1_MOSI_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PINOP		BLUEIO_SPI1_MOSI_PINOP
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PORT		BLUEIO_SPI1_MISO_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PIN		BLUEIO_SPI1_MISO_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PINOP		BLUEIO_SPI1_MISO_PINOP

#define BLUEIO_ADXL_WCHRG_FLASH_CS_PORT			0
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PIN			26
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PINOP		0

// ***** BLUEIO832-MINI

// LED P0.17
#define BLUEIO832_MINI_LED_PORT					0
#define BLUEIO832_MINI_LED_PIN					17
#define BLUEIO832_MINI_LED_PINOP				0

// Analog input
#define BLUEIO832_MINI_A1						1	// P0.03
#define BLUEIO832_MINI_A2						2	// P0.04

// Digital I/O
#define BLUEIO832_MINI_D1_PORT					0
#define BLUEIO832_MINI_D1_PIN					12
#define BLUEIO832_MINI_D1_PINOP					0
#define BLUEIO832_MINI_D2_PORT					0
#define BLUEIO832_MINI_D2_PIN					11
#define BLUEIO832_MINI_D2_PINOP					0
#define BLUEIO832_MINI_D3_PORT					0
#define BLUEIO832_MINI_D3_PIN					8
#define BLUEIO832_MINI_D3_PINOP					0
#define BLUEIO832_MINI_D4_PORT					0
#define BLUEIO832_MINI_D4_PIN					7
#define BLUEIO832_MINI_D4_PINOP					0

// UART map
#define BLUEIO832_MINI_UART_RX_PORT				BLUEIO832_MINI_D3_PORT
#define BLUEIO832_MINI_UART_RX_PIN				BLUEIO832_MINI_D3_PIN
#define BLUEIO832_MINI_UART_RX_PINOP			1

#define BLUEIO832_MINI_UART_TX_PORT				BLUEIO832_MINI_D4_PORT
#define BLUEIO832_MINI_UART_TX_PIN				BLUEIO832_MINI_D4_PIN
#define BLUEIO832_MINI_UART_TX_PINOP			1

#define BLUEIO832_MINI_UART_CTS_PORT			BLUEIO832_MINI_D2_PORT
#define BLUEIO832_MINI_UART_CTS_PIN				BLUEIO832_MINI_D2_PIN
#define BLUEIO832_MINI_UART_CTS_PINOP			1

#define BLUEIO832_MINI_UART_RTS_PORT			BLUEIO832_MINI_D1_PORT
#define BLUEIO832_MINI_UART_RTS_PIN				BLUEIO832_MINI_D1_PIN
#define BLUEIO832_MINI_UART_RTS_PINOP			1



#endif // __BLUEIO_BOARD_H__
